html/huntlist.js
I have no idea what I'm doing, but this seems appropriate.
=> new zones first

html/huntlist.js
Barring capitalization and punctuation issues, hopefully this completes the elite marks name / rank / location data set.
=> Adding elite marks from 2.0 zones.

ui/jobs/jobs.css, ui/jobs/jobs.js, user/jobs-example.js
=> Fix new Opacity option

util/make_timeline.py
Script to create timelines from a Network_###.log file, from #37
=> Timeline creation script

ui/raidboss/data/timelines/o7s.txt
Adjusted the flight windows to all match the right timing windows, and adjusted all the other lines afterward to maintain the same differences. Should resolve #44
=> O7S Timeline fix

ui/raidboss/data/triggers/unending_coil_ultimate.js
Following your update, I added the very last 2 remaining French translations, and fixed NW cardinal with NO.
=> Added the last 2 remaining French translations

ui/raidboss/data/manifest.txt, ui/raidboss/data/timelines/ridorana_lighthouse.txt, ui/raidboss/data/triggers/ridorana_lighthouse.js
Hello again! Happy patch time!
I've added Ridorana Lighthouse timelines for all bosses. I ran it about 4x and refined it each time, and this is what I arrived at.
As a side note, getting pulled into Construct 7's add zone drops combat, not unlike the O5 ghost car issue from before. It fixes once Annihilation Mode casts though, by syncing from the stopped state.
I haven't added a timeline since all the localization stuff, if there's something I could do to them to make them more easily localizable let me know and I'm happy to accomodate.
=> Ridorana Lighthouse

ui/raidboss/data/triggers/tsukuyomi-ex.js
I tested the logic via /echo commands, just not in the actual fight yet. It should work though.
=> Added 4-stack warnings for debuffs

ui/raidboss/data/triggers/tsukuyomi-ex.js
@quisquous did you add the additional condition statements? 
I setup a test scenario using echo and it would not work with 2 condition statements in each trigger, so I separated them and it works fine this way.
=> Fixes for debuff triggers

ui/raidboss/data/triggers/byakko-ex.js, ui/raidboss/data/triggers/drowned_city_of_skalla.js, ui/raidboss/data/triggers/eureka_anemos.js, ui/raidboss/data/triggers/fractal_continuum_hard.js, ui/raidboss/data/triggers/general.js, ui/raidboss/data/triggers/lakshmi-ex.js, ui/raidboss/data/triggers/o5n.js, ui/raidboss/data/triggers/o5s.js, ui/raidboss/data/triggers/o6n.js, ui/raidboss/data/triggers/o6s.js, ui/raidboss/data/triggers/o7n.js, ui/raidboss/data/triggers/o7s.js, ui/raidboss/data/triggers/o8n.js, ui/raidboss/data/triggers/o8s.js, ui/raidboss/data/triggers/shinryu-ex.js, ui/raidboss/data/triggers/sohm_al.js, ui/raidboss/data/triggers/susano-ex.js, ui/raidboss/data/triggers/temple_of_the_fist.js, ui/raidboss/data/triggers/tsukuyomi-ex.js
Phew. That was nice, with the new Atom plugin :D 
Everything went smoothly and it didn't take as long as expected. Look at this patch after you've finished my other pull request :) 
- I've changed a few TTS for better pronounciation
- I've added all the missing translations I've found
What's left?:
- o1s-o4s translations
- rabanastre translation
If you find any issues, I'm happy to fix them :3
=> German completion patch

ui/eureka/eureka.js, ui/raidboss/data/timelines/tsukuyomi-ex.txt, ui/raidboss/data/triggers/byakko-ex.js, ui/raidboss/data/triggers/drowned_city_of_skalla.js, ui/raidboss/data/triggers/eureka_anemos.js, ui/raidboss/data/triggers/fractal_continuum_hard.js, ui/raidboss/data/triggers/lakshmi-ex.js, ui/raidboss/data/triggers/o1s.js, ui/raidboss/data/triggers/o2s.js, ui/raidboss/data/triggers/o3s.js, ui/raidboss/data/triggers/o4s.js, ui/raidboss/data/triggers/o5n.js, ui/raidboss/data/triggers/o6n.js, ui/raidboss/data/triggers/o7n.js, ui/raidboss/data/triggers/o7s.js, ui/raidboss/data/triggers/o8n.js, ui/raidboss/data/triggers/o8s.js, ui/raidboss/data/triggers/royal_city_of_rabanastre.js, ui/raidboss/data/triggers/shatter.js, ui/raidboss/data/triggers/shinryu-ex.js, ui/raidboss/data/triggers/sohm_al.js, ui/raidboss/data/triggers/susano-ex.js, ui/raidboss/data/triggers/temple_of_the_fist.js, ui/raidboss/data/triggers/tsukuyomi-ex.js, ui/raidboss/data/triggers/unending_coil_ultimate.js
Did Rabanastre and o1s-o3s. I've also corrected a little mistake in o8s. 
For some reason there are conflicts and I looked into them, but my changes are alright.
Got a question about a certain case through. If you look at rabanastre line 186:
if (data.maskValue)
return {
en: 'Move',
de: 'Bewegen',
};
return {
en: 'Stop',
de: 'Stopp',
};
I'm not sure how to place the curly braces there since those are two different cases. The original was:
if (data.maskValue)
return  'Move',;
return 'Stop';
},
And those two returns seem to be separate depending on something else, or am I mistaken there?
=> Only o4s missing now

ui/raidboss/data/triggers/test.js, ui/raidboss/data/triggers/tsukuyomi-ex.js
Hello,
I've corrected and added the missing translation.
I tested it, all is functionnal when game is set on French & Options.Language = 'fr' is present in user/raidboss.js.
This is the first time ever I'm using GitHub so if I made a mistake, just tell me.
=> FR Translation & Correction for Tsukuyomi-ex

ui/raidboss/data/triggers/tsukuyomi-ex.js
=> FR Improvement from @G0li4th

ui/raidboss/data/timelines/o9s.txt
Cobbled this together from a few different pulls on FFLogs, even though it's a bit tricky without encounter support yet. I won't be able to test it myself until next week as I cleared the fight before ACT worked, unfortunately. It should at least work as a baseline. Let me know if anything sticks out!
=> raidboss: Initial O9S timeline draft

util/test_timeline.py
Small change. It assumed integer timings before, this changes it to support float timings.
=> util: Fixing test_timeline

ui/raidboss/data/triggers/o9n.js, ui/raidboss/data/triggers/o9s.js, util/translate_fight.py
o9n : Missing translation,
o9s : Capitals missing,
translate_fight.py : typo.
=> FR Translation Fix (o9s/o9n) :

ui/raidboss/data/triggers/o10n.js, ui/raidboss/data/triggers/o10s.js, ui/raidboss/data/triggers/o11n.js, ui/raidboss/data/triggers/o11s.js, ui/raidboss/data/triggers/o12n.js, ui/raidboss/data/triggers/o12s.js, ui/raidboss/data/triggers/o9n.js, ui/raidboss/data/triggers/o9s.js, ui/raidboss/data/triggers/rathalos-ex.js, ui/raidboss/data/triggers/suzaku-ex.js
There is only 1 line where I didn't know what to do with it
=> What do we have here?

README.md, ui/raidboss/data/triggers/o10n.js, ui/raidboss/data/triggers/o11n.js, ui/raidboss/data/triggers/o11s.js, ui/raidboss/data/triggers/o12n.js
o11n : missed one Starboard sentence
o12n : Added FR triggers & capitals fixes
=> FR Translations

ui/raidboss/data/triggers/o12n.js
Capitals again, sorry I should have checked before.
=> FR Translation (o12n)

ui/raidboss/data/triggers/o9s.js
You might want to double check this. I hope google did a good job on translating the french localization. 
Man, this was a pain! Hope it works out for you too!
=> rewrote big parts

ui/eureka/eureka.js, ui/raidboss/data/triggers/o12s.js, ui/raidboss/data/triggers/o9s.js
Updated Pagos Mob Names (didn't see they were there in the first place), did some wording-tweaks in a few triggers and updated what was there to update :>
=> German Update

ui/raidboss/data/triggers/o9s.js
Fixes for new O9s trigger file
=> Fixes for FR Translation O9s

.travis.yml
Adding a syntax check to the Python code on pull request submit via Travis CI.
=> general: Adding Python Syntax Checking to Travis CI

ui/oopsyraidsy/oopsyraidsy.js, ui/raidboss/popup-text.js
Upon changing job to Pugilist (`PGL`):
```code
BrowserConsole: Unknown job role (Source: https://quisquous.github.io/cactbot/ui/raidboss/popup-text.js, Line: 164)
```
```code
BrowserConsole: Unknown job role (Source: https://quisquous.github.io/cactbot/ui/oopsyraidsy/oopsyraidsy.js, Line: 968)
```
Code changes can likewise be tested at my fork's GitHub page before merge: https://panicstevenson.github.io/cactbot/ui/raidboss/raidboss.html
=> raidboss: Fixing Pugilist Acronym

ui/eureka/eureka.js, ui/raidboss/data/triggers/eureka_pyros.js
By the way, I fixed a mob name, because I spelled it lowercase at the beginning and it only works if it starts with a capital (tested) :)
=> German Eureka Translations

ui/raidboss/data/triggers/o9s.js
this should resolve quisquous/cactbot#334
=> O9S: fix stack marker regex and entropy bug

ui/raidboss/data/triggers/orbonne_monastery.js
=> Orbonne Monastery: Fixing french regexes

ui/raidboss/data/triggers/general.js, ui/raidboss/data/triggers/o10s.js, ui/raidboss/data/triggers/o11s.js, ui/raidboss/data/triggers/o12s.js, ui/raidboss/data/triggers/o9s.js
Hi.
I localized some part of raidboss triggers.
Can I contribute to the project?
Thanks.
=> ja localize

ui/eureka/eureka.js
Betterment ideas / TODO:
- Add support for other languages
- Play some sound effect when one gets found
- Mark these in their own fancy way on the map, also reuse
SetStyleFromEntity instead of hackily duplicating it
WIP for #109
=> eureka: mark fairies (really lazily)

ui/raidboss/data/manifest.txt, ui/raidboss/data/triggers/innocence-ex.js, ui/raidboss/data/triggers/titania-ex.js
I've started to work on triggers for titania-ex but since I'm new to the ffxiv act combat log I'm trying to stay close to other trigger files.
=> Triggers for Titania and Innocence Extreme

ui/dps/rdmty/dps.css
colors match what fflogs went with for the new jobs
=> update rdmty bar color for gunbreaker and dancer

ui/raidboss/data/triggers/e3s.js
Not perfect, nor nearly up to @quisquous' quality, but an initial pass that worked fairly well in raid just to help out if it's wanted.
Otherwise, we can feel free to close this 😄 
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
=> raidboss: Initial E3S Triggers

ui/dps/rdmty/dps.html
Hi, I've done this simple change to allow to have user config on the rdmty dps module
=> adding user config for rdmty

ui/raidboss/data/timelines/e4s.txt
Adding a "--targetable--" to the first transition for Titan.
=> raidboss: add targetable to e4s first transition

user/raidboss-example.js
=> Updated raidboss-example.js in user directory

ui/oopsyraidsy/data/innocence-ex.js, ui/raidboss/data/triggers/e2s.js
Small german additions for e2s + adding missing triggers element for innocence-ex.js (to avoid error)
=> Small german e2s additions + adding missing element for oopsy

ui/jobs/jobs.js, user/jobs-example.js
A simple addition of BlmLowMPThreshold based on a question brought up on the ACT Discord.
=> Add BlmLowMPThreshold

docs/LogGuide.md
Alright, I believe this is all the markers that are currently referenced in Cactbot. I'm not 100% sure on the truth of column 4, as I didn't verify each one individually, but I'm reasonably confident on most of them. Now that I've gone through and done this, I'm less sure on the value to future contributors, but oh well, we have the data now. I know there are a few markers present in game that are missing from Cactbot and the guide, but I'll probably add that to the list of things I'm planning to revisit.
=> Log line table goodness

CactbotOverlay/FFXIVProcess.cs, CactbotOverlay/JSEvents.cs
Proposed implementation for #576
=> Add shield value to entities

CactbotOverlay/CactbotOverlayConfigPanel.Designer.cs, CactbotOverlay/CactbotOverlayConfigPanel.cs, CactbotOverlay/CactbotOverlayConfigPanel.resx
I got really tired of always being in need to reload the overlay manually.
Give me your thoughts on this!
I'm impressed how many changes Visual Studio does to the files when adding a checkbox...
=> cactbot.dll: automatic overlay reload on file change

resources/lang.js, ui/jobs/jobs.js
Fix incorrect spelling of stratagem.
=> jobs: Fix Chain Stratagem Typo

resources/lang/de.js, resources/lang/en.js, resources/lang/fr.js, resources/lang/ja.js, resources/lang/ko.js
Add string resources for each language for the card buffs recently added to the jobs buff tracker. Translations taken from XIVAPI and updated to match the values from Advanced Combat Tracker.
Action identifier comments updated to match the new Shadowbringers statuses.
=> jobs: Add Card Language String Resources

package.json, test/test_timelines.py, test/test_triggers.py
Fix encoding issues and incorrect WindowsPath issues.
=> test: Update Tests to Work With Windows

resources/lang/de.js, resources/lang/en.js, resources/lang/fr.js, resources/lang/ja.js, resources/lang/ko.js, ui/oopsyraidsy/data/05-shb/dungeon/dohn_mheg.js, ui/oopsyraidsy/data/05-shb/dungeon/qitana_ravel.js, ui/oopsyraidsy/data/manifest.txt
This should finish out #569. Qitana has entirely too many elements to everything, particularly Confession of Faith, but I think these are all correct.
Viper Poison 1 requires a full trigger, as the attack does damage to its primary target regardless of whether things are handled correctly. The puddle dropped by the attack is the same as the other puddles though.
=> Oopsy--Added remaining shb dungeons

test/test_triggers.py, test/trigger/test_trigger.js, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.js, ui/raidboss/data/04-sb/raid/o2s.js, ui/raidboss/data/05-shb/dungeon/holminster_switch.js
Adding individual trigger tests to the testing suite. I know it's bad form to have obnoxious `TODO`'s in a new commit, but there are a lot of changes that would be necessary to capture the output of the tests; it might be best to deliver these in a separate update.
=> test: Add Trigger Tests to Test Suite

ui/raidboss/data/05-shb/dungeon/holminster_switch.js
Not really a big deal, but it was an easy fix, so I figured I might as well toss it in while I was thinking on it.
=> Tiny Holminster fix

ui/raidboss/data/05-shb/raid/e2s.js
Capitals and some missing replaceText values
=> e2s small fixes for FR

ui/raidboss/data/05-shb/raid/e4s.js
Per #628. I checked over the other Savage encounters and didn't find any further occurrences.
=> Fixed incorrect localization labels

ui/oopsyraidsy/data/03-hw/dungeon/fractal_continuum.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/03-hw/dungeon/fractal_continuum.js, ui/raidboss/data/manifest.txt
We finished raid early tonight, so I put this together with the extra time. I have the data needed for timelines, but I'm still working through that.
I thought about adding uncleansed bombs on boss 3, but I wasn't sure whether that sort of mistake is something you wanted. (It would probably also need to track whether Paean is on cooldown or not, and that's a little more advanced than I wanted to go for something like this.)
I'm not 100% happy with the mines trigger, but I have only the one log and I didn't record the kill, so I'm not entirely sure what the actual cast is. (The adds can spawn them as well if they're left alone.) There's about 60s between primary spawns anyway, so it will function, but a 30s suppression feels messy. I'll clean that up when I do further testing runs.
=> Fractal Normal Raidboss/Oopsy

ui/raidboss/data/00-misc/general.js, ui/raidboss/data/00-misc/test.js, ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.js, ui/raidboss/data/05-shb/dungeon/amaurot.js, ui/raidboss/data/05-shb/dungeon/dohn_mheg.js, ui/raidboss/data/05-shb/dungeon/holminster_switch.js, ui/raidboss/data/05-shb/dungeon/malikahs_well.js, ui/raidboss/data/05-shb/dungeon/mt_gulg.js, ui/raidboss/data/05-shb/dungeon/qitana_ravel.js, ui/raidboss/data/05-shb/dungeon/twinning.js, ui/raidboss/data/05-shb/raid/e1n.js, ui/raidboss/data/05-shb/raid/e1s.js, ui/raidboss/data/05-shb/raid/e2n.js, ui/raidboss/data/05-shb/raid/e2s.js, ui/raidboss/data/05-shb/raid/e3n.js, ui/raidboss/data/05-shb/raid/e3s.js, ui/raidboss/data/05-shb/raid/e4n.js, ui/raidboss/data/05-shb/raid/e4s.js, ui/raidboss/data/05-shb/trial/hades.js, ui/raidboss/data/05-shb/trial/innocence-ex.js, ui/raidboss/data/05-shb/trial/innocence.js, ui/raidboss/data/05-shb/trial/titania-ex.js, ui/raidboss/data/05-shb/trial/titania.js
another round of german translations for all missing shb content up t…o patch 5.08 + german translation for test.js
=> german translations - another round

docs/LogGuide.md
Per #573 I've *finally* made the time to sit down and add these lines to the guide. I've marked this as a draft because it's not as clean as I would like. The information in here is correct as far I can tell, but it seems minimal.
=> Added lines 24-27 to log guide

resources/timerbar.js, ui/raidboss/popup-text.js, ui/raidboss/timeline.js
#385
Could probably be better, tell me what do you think
Example :
```
timelineStyles: [
{
regex: /Angry Dummy/,
style: {
color: 'red',
'font-family': 'Impact', // If the CSS property has '-' in it, you must use quotation marks
},
},
],
```
Add this is any `.js` file from the `data` folder
=> raidboss: change color/font of text

ui/raidboss/data/00-misc/general.js, ui/raidboss/data/03-hw/alliance/dun_scaith.js, ui/raidboss/data/03-hw/dungeon/sohm_al.js, ui/raidboss/data/04-sb/raid/o3s.js, ui/raidboss/data/04-sb/raid/o4n.js, ui/raidboss/data/05-shb/dungeon/mt_gulg.js
General fix for various syntax issues within Raidboss triggers.
=> raidboss: Fix Trigger Syntax Issues

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.js
This is the last instance of Unknown abilities in the Raidboss data set!
=> raidboss: Remove Unknown Ability Regex

ui/raidboss/data/04-sb/trial/seiryu-ex.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/data/05-shb/dungeon/holminster_switch.js, ui/raidboss/data/05-shb/raid/e1n.js, ui/raidboss/data/05-shb/raid/e2n.js, ui/raidboss/data/05-shb/raid/e3n.js, ui/raidboss/data/05-shb/raid/e4n.js, ui/raidboss/data/05-shb/trial/innocence-ex.js, ui/raidboss/data/05-shb/trial/innocence.js, ui/raidboss/data/05-shb/trial/titania-ex.js
Update the regex keys for various triggers to be in ascending order.
=> raidboss: List Regex Keys in Ascending Order

ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
Fixes https://github.com/quisquous/cactbot/issues/673
=> raidboss: Fix 'gains effect' UCoB Triggers

package.json, resources/lang.js, ui/eureka/eureka.js, ui/raidboss/popup-text.js, ui/raidboss/raidemulator.js, ui/raidboss/timeline.js
=> general: Remove Unnecessary Semicolons

ui/raidboss/data/04-sb/raid/o9s.js, ui/raidboss/data/05-shb/dungeon/mt_gulg.js
Fix incorrect regex spacing for various Chinese regular expression strings in O9S, and a French regular expression within Mt. Gulg.
=> raidboss: Fix Incorrect Regex Spacing

ui/raidboss/data/05-shb/raid/e1s.js, util/get_fisher_data.py
Use `python3 get_fisher_data.py` to get fisher resources from both xivapi and [cn xivapi](https://github.com/thewakingsands/cafemaker/wiki).
=> util: update cn fisher script

package.json, resources/timericon.js, ui/raidboss/data/04-sb/trial/shinryu-ex.js, ui/raidboss/raidemulator.js
Add the ESLint "recommended" preset which includes a few nice checks, most notably the checking of multiple spaces within a regular expression, which was updated in #677. Additional checking for JavaScript logic and syntax is included as well.
Compresses, reorders, and updates the package.json rules section to now exclude duplicate rules and to explicitly say "error" and "off", over 2 and 0, respectively.
=> lint: Add ESLint Recommended Preset

test/trigger/test_trigger.js
=> test: Add Test for Invalid Trigger Keys

ui/raidboss/data/04-sb/raid/o9s.js
Remove unknown ability within regular expressions for raidboss triggers.
=> raidboss: Remove Unknown Abilities

ui/oopsyraidsy/data/00-misc/general.js
With 5.1, it is no longer possible to miss Trick Attack; the vulnerability will be applied from any position.
=> oopsyraidsy: 5.1 Trick Attack Changes

ui/raidboss/data/05-shb/trial/hades-ex.js
Finishing out the fight for Hades Ex.
=> raidboss: More Hades Ex Triggers

ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.js
Why do people have to burn the furniture?
=> raidboss: Add Tether Instructions for Grand Cosmos

ui/oopsyraidsy/data/05-shb/dungeon/the_grand_cosmos.js
Add entry for failing to meet the distance requirement for Lugus' tether
mechanic.
=> oopsyraidsy: Add Entry for Lugus' Tether Mechanic

ui/raidboss/data/05-shb/alliance/the_copied_factory.js, ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.js
There's a lot of names and action that contains ':', I hope it do not break everything.
=> Copied factory FR translations

ui/raidboss/data/05-shb/alliance/the_copied_factory.js
i forgot to include it to my last PR as it wasn't done when i started working on it... <.<
=> add trigger translation for copied factory

resources/lang/cn.js, resources/lang/de.js, resources/lang/en.js, resources/lang/fr.js, resources/lang/ja.js, resources/lang/ko.js
Add status effect for Paralysis.
=> resources: Add Paralysis

ui/oopsyraidsy/data/04-sb/dungeon/temple_of_the_fist.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.js, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.txt, ui/raidboss/data/manifest.txt
Not much to say on this one, highly straightforward bosses.
=> Raidboss: Temple of the Fist initial timelines and triggers

README.md
=> docs: Update fisher with documentation on tug types

ui/jobs/jobs.js
Shadowbringers removed all of bard's MP skills.
=> jobs: Remove bard from jobs with MP

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.txt
Timing is 8 seconds after Fluid Swing.
=> Add the Cascade enrage spell to Living Liquid phase of TEA

test/trigger/test_trigger.js
Fix functionality where errors are printed, but the exit code for CI/CD
remains successful.
=> test: Non-Zero Exit Code on Testing Failures

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.txt
Based on times from https://www.fflogs.com/reports/WthzBwZTmMbGXP9g#fight=110
Living Liquid and Living Rage appear to be interchangeable in this phase.
=> Add timers up to Final Sentence for TEA

ui/raidboss/popup-text.js
TypeError: Cannot read property 'groups' of undefined
fixes #758 #756
=> fix popup-text.js - matches undefined

docs/LogGuide.md
I referred to @JLGarber's breakdown in #595. Thanks :)
=>  Add 0C: Player Stats to LogGuide.md

ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.txt
Apparently we skipped the entire intro...
=> raidboss: Update Lugus Fight Timeline

util/check_translation.py
=> util: fix #773

ui/raidboss/data/00-misc/general.js
You guess what, they renamed `Superbolide`!
=> raidboss: fix CN Superbolide

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
I have been using the throttle trigger here. Haven't yet tested the other triggers.
=> Throttle, Final Nisi Callouts, and few other triggers for TEA

util/encounter_tools.py, util/make_timeline.py, util/test_timeline.py
As I noted in #749 , there's some shuffling that should happen before I do further updates to `translate_fight`. The updates in here should be mostly self-explanatory. I'll gladly take criticism on naming or additional functionality that should be turned into helpers in addition to what I already moved.
=> Util: Function shuffling for timeline utilities.

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
=> raidboss: Minor Spacing Fix

CactbotOverlay/FFXIVProcess.cs, ui/test/test.js
Adds the missing base classes back to `FFXIVProcess.cs`; Arcanist, Thaumaturge, etc
=> plugin: add missing basic classes to FFXIVProcess.cs

CactbotOverlay/CactbotEventSource.cs, CactbotOverlay/CactbotOverlay.csproj, CactbotOverlay/FFXIVPlugin.cs, CactbotOverlay/FFXIVProcess.cs, CactbotOverlay/FFXIVProcessCn.cs, CactbotOverlay/FFXIVProcessIntl.cs, CactbotOverlay/VersionChecker.cs
Hiya,
As requested in #821 I've added support for the CN client, using memory offsets from the 0.11.2 release targetting FFXIV ver 5.01.
This also includes the changes from #824
=> plugin: Add dynamic support for CN version of FFXIV

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
Small cleanup to unused parameters and variables.
=> raidboss: Minor TEA Cleanup

resources/responses.js
fixed some DE responses and added missing onces.
=> german responses in responses.js

ui/eureka/eureka.js
=> eureka: fix log error `Uncaught TypeError: Cannot read property 'primaryWeather' of undefined`

README.md
=> docs: fix fisher troubleshooting url in readme.md

user/jobs-example.js
Tiny change, adds the new option in the jobs module added in 6a0c7a4b to the jobs example file.
see #550
=> Add BigBuffShowCooldownSeconds to jobs-example.js

ui/raidboss/data/03-hw/raid/a6s.js
These could always be improved upon; they were taken from a combination
of triggers from guides, a solo run of A6S that I couldn't complete
alone, existing triggers, and video footage.
=> raidboss: Initial A6S Triggers

CactbotOverlay/CactbotEventSource.cs, CactbotOverlay/CactbotOverlay.csproj, CactbotOverlay/FFXIVProcessKo.cs
Hiya, 
Quick addition of an extra `FFXIVProcessKo` to support the recent Korean release. It's untested as I don't have access to a Korean build but I'm hoping the offsets are unchanged.
=> plugin: add support for korean ffxiv v5.01

CactbotOverlay/CactbotEventSource.cs, CactbotOverlay/FFXIVPlugin.cs, CactbotOverlay/VersionChecker.cs
As per #879 I've added compatibility with the new FFXIV_Plugin_Korean.dll released by Ravahn.
=> plugin: Add new FFXIV_Plugin_Korean.dll support

ui/raidboss/data/02-arr/raid/t1.js, ui/raidboss/data/02-arr/raid/t2.js, ui/raidboss/data/02-arr/raid/t4.js, ui/raidboss/data/02-arr/raid/t5.js
Update Binding Coil of Bahamut trigger files to utilize the new Regexes
and Responses format.
Additional changes were made to logic if it seemed incorrect.
=> raidboss: Update Binding Coil Triggers

CactbotOverlay/FFXIVProcessCn.cs, CactbotOverlay/FFXIVProcessIntl.cs, CactbotOverlay/FFXIVProcessKo.cs
When I added the other missing classes I missed rogue..
=> plugin: add rogue to GetJobSpecificData

util/README.md
If this README.md file should be placed somewhere else, please tell me.
preview: https://github.com/Jaehyuk-Lee/cactbot/blob/master/util/README.md
=> add a readme about using python util

ui/jobs/jobs.css, ui/jobs/jobs.js
Added a css transform animation to the xeno timer when the proc
is about to get overwritten, closes #571
=> xeno timer pulse effect

util/coinach.py, util/gen_hunt_data.py
added ability to specify saintcoinach.cmd and ffxiv path for reader and cacbot path for writer to avoid common user error
=> Updated gen_hunt_data to avoid common issues

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
Seems like some spaces were either forgotten or reverted from the previous commit.
=> TEA RegEx in French fix

ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.js, ui/raidboss/data/05-shb/dungeon/amaurot.js, ui/raidboss/data/05-shb/dungeon/dohn_mheg.js, ui/raidboss/data/05-shb/dungeon/holminster_switch.js, ui/raidboss/data/05-shb/dungeon/malikahs_well.js, ui/raidboss/data/05-shb/dungeon/mt_gulg.js, ui/raidboss/data/05-shb/dungeon/qitana_ravel.js, ui/raidboss/data/05-shb/dungeon/twinning.js, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
Target instances
- Holminster Switch
- Dohn Mheg
- Qitana Ravel
- Mallakahs Well
- Mt Gulg
- Akademia Anyder
- Twinning
- TEA
=> Add Korean desc for shb instances and TEA

.travis.yml, test/test_manifests.py, test/test_timelines.py, util/check_translation.py, util/coinach.py, util/encounter_tools.py, util/fetch_deps.py, util/fflogs.py, util/gen_fisher_data.py, util/gen_hunt_data.py, util/gen_territory_type.py, util/gen_weather_rate.py, util/make_timeline.py, util/test_timeline.py, util/timeline_adjust.py, util/translate_fight.py
Add Python formatting check to Travis CI integration. The Python
formatter of choice is black, since it is unwaivering. For now, to make
pull request readability a thing, string normalization is skipped.
=> ci: Add Python Formatting Check to CI

.travis.yml, test/definitions.py, test/run_tests.py, test/test_manifests.py, test/test_timelines.py, test/test_triggers.py, test/unittests.py, util/DEPS.py, util/check_translation.py, util/coinach.py, util/encounter_tools.py, util/fetch_deps.py, util/fflogs.py, util/gen_fisher_data.py, util/gen_hunt_data.py, util/gen_territory_type.py, util/gen_weather_rate.py, util/make_timeline.py, util/test_timeline.py, util/timeline_adjust.py, util/timeline_aggregator.py, util/translate_fight.py
Enable Black's string normalization feature.
=> Enable String Normalization for Python Formatting

ui/raidboss/popup-text.js
=> change to regex

ui/oopsyraidsy/data/02-arr/trial/ifrit_nm.js, ui/oopsyraidsy/data/02-arr/trial/titan_ex.js, ui/oopsyraidsy/data/03-hw/dungeon/aetherochemical_research_facility.js, ui/oopsyraidsy/data/03-hw/dungeon/fractal_continuum.js, ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.js, ui/oopsyraidsy/data/04-sb/dungeon/ala_mhigo.js, ui/oopsyraidsy/data/04-sb/dungeon/temple_of_the_fist.js, ui/oopsyraidsy/data/04-sb/raid/o4s.js, ui/oopsyraidsy/data/04-sb/raid/o5s.js, ui/oopsyraidsy/data/04-sb/raid/o6s.js, ui/oopsyraidsy/data/04-sb/raid/o7s.js, ui/oopsyraidsy/data/04-sb/raid/o8s.js, ui/oopsyraidsy/data/04-sb/trial/byakko-ex.js, ui/oopsyraidsy/data/04-sb/trial/susano-ex.js, ui/oopsyraidsy/data/04-sb/ultimate/ultima_weapon_ultimate.js, ui/oopsyraidsy/data/04-sb/ultimate/unending_coil_ultimate.js
every time I write oopsyraidsy wrong
=> oopsyraidsy for KR

resources/timerbar.js
=> better visibility for Korean

ui/raidboss/data/05-shb/raid/e6s.txt
Based on pulls from https://www.fflogs.com/reports/2T4dYyzxjFab9Aw fight 1 and 14.
=> E6S Timeline (Preliminary)

resources/responses.js, ui/raidboss/data/02-arr/raid/t1.js, ui/raidboss/data/02-arr/raid/t2.js, ui/raidboss/data/03-hw/raid/a6s.js
Added responses based on #1044
=> New responses based on #1044

ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt
I tested this and worked fine.
=> Anyder timeline sync

ui/raidboss/data/05-shb/raid/e6s.txt
- #1068, there were lines that were leftover from merging two timelines
- Resync timeline to https://www.fflogs.com/reports/RkPv8yn1WJK9TX4V/#fight=2.
- Commented a few additional syncs
=> Fix for #1068 and Resync

ui/raidboss/data/05-shb/raid/e5s.js
Fix timing of e5s triggers based on the notes in #1069 
I haven't validated that these are correct yet but I will tonight when I run e5s.
@Jaehyuk-Lee pinging you in since this is an addition to your work on e5s triggers (thank you!)
=> Fix e5s crippling blow and stepped leader timing

ui/raidboss/data/05-shb/dungeon/anamnesis_anyder.js
Taken from my earlier run with what I remember from the mechanics; not
promising perfection, but also it's just a dungeon.
=> raidboss: Initial Anamnesis Anyder Triggers

ui/raidboss/data/05-shb/raid/e7s.js
A lot more in the way of color callouts can be added, but this is a
decent starting point hopefully.
=> raidboss: Initial E7S Triggers

ui/raidboss/data/05-shb/raid/e8s.js
An initial set of triggers; not complete, and not enough information to
go off of without video reference.
=> raidboss: Initial E8S Triggers

ui/raidboss/data/05-shb/raid/e6s.js
Adding some triggers; probably not overly helpful without video
reference to decipher things like Ifrit locations or Ferostorm
positioning.
=> raidboss: Initial E6S Triggers

ui/oopsyraidsy/data/05-shb/alliance/the_copied_factory.js, ui/oopsyraidsy/data/05-shb/dungeon/the_grand_cosmos.js, ui/raidboss/data/05-shb/alliance/the_copied_factory.js, ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.js
testing translations with real situation.
=> V5.1 korean update

ui/raidboss/data/05-shb/raid/e6s.js, ui/raidboss/data/05-shb/raid/e7s.js, ui/raidboss/data/05-shb/trial/ruby-weapon-ex.js
Minor fixes found during reclears.
=> raidboss: Minor Trigger Fixes

ui/raidboss/data/05-shb/raid/e8s.js
Some small additions for anyone progging.
=> raidboss: Minor E8S Additions

util/encounter_tools.py
This should resolve #1061. We may have to add more `21` lines to `is_instance_restarted`, but from the More Than One logs I tested this on, it seems to be happy regardless.
=> Util: Make_timeline fix for when ACT wasn't open at start of instance

ui/raidboss/data/05-shb/raid/e5s.js
1. show "enrage soon" not "grab an orb" on last cast of Fury's Fourteen.
2. undefined returns false, so I fixed it to work fine.
=> e5s trigger fixes

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
=> raidboss: fix Protean Wave for CN TEA

ui/raidboss/data/05-shb/raid/e5s.js, ui/raidboss/data/05-shb/raid/e6s.js
Sorry forgot to put a FIXME flag on this ...
=> FIXME in E5S

resources/responses.js, ui/raidboss/data/02-arr/raid/t1.js, ui/raidboss/data/02-arr/raid/t2.js, ui/raidboss/data/03-hw/raid/a6s.js, ui/raidboss/data/05-shb/raid/e7s.js
- Fixup E7S interrupt callout during adds phase
- Fix typo in canned interrupt response
=> raidboss: Fixup E7S Interrupt Callout

ui/raidboss/data/05-shb/trial/ruby-weapon-ex.js
Add missing matches parameter for multiple functions within Ruby Weapon
Extreme triggers.
Fixes #1128
=> raidboss: Add Missing Matches Parameter

ui/jobs/jobs.js
This commit will apply #1056 changes also into jobs module.
(better legibility for Korean)
=> jobs: add language info in pull-bar container

ui/raidboss/data/05-shb/raid/e8s.js
=> raidboss: Fix Icelit Dragonsong Callout

ui/raidboss/data/03-hw/dungeon/the_vault.js
This should resolve #1167. It's a *bit* of a hack, but oh well.
=> Raidboss: The Vault--knights should no longer trigger pre-battle

resources/lang/de.js, resources/lang/fr.js, resources/lang/ja.js, ui/oopsyraidsy/data/05-shb/raid/e5n.js
Nowhere near as many mistakes  exist as I had expected. I'm not 100% sure on the setup for Stormclouds that I used, but I'm (I hope understandably) reluctant to test that one deliberately in the duty finder, and I haven't seen that mistake today.
Known deficiencies:
1. Standing in the center for the Deadly Discharge knockback from Will of Ramuh. I don't know what the ability that goes off here is called when it hits a player.
2. I'm not sure whether we had figured out the "fell off platform" detection yet. If so, it would be possible to improve the knockback mechanics with triggers to check whether a player was pushed off.
=> Oopsy: E5N initial

ui/radar/radar_config.js, ui/raidboss/data/05-shb/raid/e5s.js, ui/raidboss/data/05-shb/raid/e6n.js, ui/raidboss/data/05-shb/raid/e6s.js, ui/raidboss/data/05-shb/raid/e7s.js, ui/raidboss/data/05-shb/raid/e8n.js, ui/raidboss/data/05-shb/trial/ruby-weapon-ex.js, ui/raidboss/data/05-shb/trial/ruby-weapon.js
Thanks for make cactbot and sry for REHI..
This pull request is trivial things, too.
=> misc ko translate

ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt, ui/raidboss/data/03-hw/dungeon/fractal_continuum.txt, ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt, ui/raidboss/data/03-hw/dungeon/the_vault.txt
This is a minor update that's going to be part of a larger overall project.  Looking over my older work, I wasn't at all as complete with sync windows as I should have been, and especially on more recent content I've been noticing how important good sync windows are. I'm hoping to go back over the next week or two and update older timelines to modern standards in that regard.
(Note that these are untested. I don't have any recent logs to test against, but purely from eyeballing the timelines things look okay. I understand if it's preferable that I hold on this one until I can get logs, but it could be a while.)
=> Raidboss: HW dungeon timelines--Sync windows

ui/fisher/static-data.js
updating new fish, baits and locations in diadem (through gen_fisher_data.py)
=> fisher: static-data.js update for 5.21

ui/oopsyraidsy/data/05-shb/raid/e5n.js, ui/oopsyraidsy/data/05-shb/raid/e6n.js, ui/oopsyraidsy/data/05-shb/raid/e7n.js
I'm deeply sorry I didn't catch this before submitting. I had been getting console errors for Oopsy for a while, and I assumed that I had broken something with my install. But no, I had just reversed things.
=> Oopsyraidsy: Fixing E5n/E6N/E7N

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
This turned out to be significantly simpler than I expected after Quisquous pointed me in the right directions. Note that it is entirely untested as I wasn't able to get the raid emulator working over lunch. However, looking things over there's no reason it shouldn't work. 
Apologies for the ugly bits. I mostly wanted to get concepts set down so we could improve on them and get this out for people as quickly as possible.
(Should resolve #1199 )
=> Raidboss: TEA head marker fix

ui/raidboss/data/05-shb/trial/ruby-weapon-ex.js
=> Raidboss: Ruby Weapon EX

ui/raidboss/data/05-shb/trial/ruby-weapon.js
=> Raidboss: Ruby Weapon

ui/raidboss/data/05-shb/raid/e8s.js
=> Raidboss: E8S translation fr minor

ui/raidboss/data/05-shb/raid/e7s.js
spelling adjustment and correction
=> Raidboss: E7S translation fr minor

ui/eureka/eureka.js
Translation and adjustement correction fr
=> Eureka Translation fr

ui/eureka/eureka.js
Corrected name (de). Sorry, much thing to verified. Ty for your patience.
=> Eureka corrected

ui/raidboss/data/05-shb/raid/e1s.js
=> Raidboss: E1S

ui/raidboss/data/05-shb/raid/e8n.js
=> Raidboss: E8N

ui/raidboss/data/05-shb/trial/titania.js
=> Raidboss: Titania

ui/raidboss/data/05-shb/trial/innocence.js
=> Raidboss: Innocence

ui/raidboss/data/04-sb/trial/rathalos-ex.js
translation exact of skills name fr missing
=> Raidboss: Rathalos EX

ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.js
=> raidboss: fix akadaemia_anyder.js CN translation

ui/raidboss/data/02-arr/raid/t1.js
Translation fr missing ( exact name of skill)
=> Raidboss: T1

ui/raidboss/data/05-shb/trial/innocence-ex.js
translation fr missing and adjustement for winged
=> Raidboss: Innocence EX

ui/raidboss/data/05-shb/raid/e3s.js
=> Raidboss: E3S

ui/raidboss/data/05-shb/raid/e4n.js
=> Raidboss: E4N

ui/raidboss/data/05-shb/raid/e4s.js
adjustement and spelling correction fr
=> Raidboss: E5S

ui/raidboss/data/05-shb/raid/e7s.js
=> Raidboss: E7S

ui/raidboss/data/05-shb/trial/hades-ex.js
=> Raidboss: Hades Ex

ui/raidboss/data/02-arr/raid/t4.js
=> Raidboss: T4

ui/raidboss/data/02-arr/raid/t5.js
translation  exact  to names of skills fr
=> Raidboss: T5

ui/raidboss/data/02-arr/raid/t6.js
Translation exact to names of skills and spelling correction
=> Raidboss: T6

ui/raidboss/data/02-arr/raid/t7.js
Translation exact to names of skills and adjustement fr
=> Raidboss: T7

ui/raidboss/data/02-arr/raid/t8.js
=> Raidboss: T8

ui/raidboss/data/05-shb/raid/e6s.js
=> Raidboss: E6S Fr

ui/raidboss/data/02-arr/trial/titan_ex.js
correction for more harmonization.
=> Raidboss: Titan EX fr

ui/raidboss/data/02-arr/raid/t11.js
=> Raidboss: T11 Fr

ui/raidboss/data/02-arr/raid/t12.js
harmonization fr as close as possible to the English translation
=> Raidboss: T12 fr

ui/raidboss/data/02-arr/raid/t6.js
grammar correction.
I checked again and again, ARR is finished. I corrected and Harmonized. Everything is explained in comment on the request E6S. I'm done. Soon ShB again. Ty for your patience.
=> Raidboss: T6 Fr

ui/raidboss/data/02-arr/raid/t9.js
Link conversation.
when I read it again, I doubt. Should I put the real name or a better indication.
https://github.com/quisquous/cactbot/pull/1259#issuecomment-602537597
I await your answer. Ty for your help.
=> Raidboss: T9 Fr

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
Such an obvious thing looking at it now. Computers definitely do *exactly* what we tell them...
(Should resolve #1266.)
=> Raidboss: TEA headmarker 1 fix

resources/hunt.js, util/gen_hunt_data.py
Modified gen_hunt_data.py to also store the monsters id into hunt.js
Updated hunt.js included
=> Add monsters id to resources/hunt.js

resources/responses.js
Here is what I suggest, to be as close as possible to the translation. 
Does this document work for all extensions of FFXIV ?
**In English, does he suggest going behind a player, something or the boss?**
does this document work for all extensions of FFXIV
=> Responses FR

resources/lang/cn.js, resources/lang/de.js, resources/lang/en.js, resources/lang/fr.js, resources/lang/ja.js, resources/lang/ko.js, ui/oopsyraidsy/data/04-sb/raid/o4n.js, ui/oopsyraidsy/data/manifest.txt
Nothing special about this one. There aren't a lot of mistakes to make in this fight! It's still missing Pyretic, since as I note in-line that isn't currently possible without some excessive effort, but other than that it should be basically complete.
=> Raidboss: O4N Oopsy

README.md
in Dependances: Manual Method section
=> fix incorrect links for ACT and OverlayPlugin in Readme

docs/RaidbossGuide.md
First pass at documenting this. I think this is a reasonable balance of information about these elements while leaving most of the internals in the respective files. Please comment and improve!
=> Docs: Canned trigger element replacement info

ui/raidboss/common_replacement.js, ui/raidboss/data/03-hw/raid/a3s.js
- Common: Don't hesitate to tell me if the translations are wrong, I'm not sure with google for Asian languages
=> Raidboss: Added common all lang + A3S Fr

ui/raidboss/data/05-shb/trial/varis-ex.js, ui/raidboss/data/manifest.txt
Couldn't quite get down Loaded Gunshield since it has varying timers.
=> Initial Varis Triggers

ui/raidboss/data/05-shb/trial/varis-ex.js
I don't know this fight, so some translation might wrong a bit.
=> raidboss: Varis-ex Korean

ui/raidboss/data/05-shb/raid/e7s.js, ui/raidboss/data/05-shb/raid/e8s.js, ui/raidboss/data/05-shb/trial/varis-ex.js
When shiva starts using holy, trigger notice me .getOut(). But when holy divided, .getIn() doesn't work. I think this line makes problem.
=> update ko translation, e8s miner fix

ui/raidboss/data/05-shb/raid/e1n.js, ui/raidboss/data/05-shb/raid/e1s.js
=> e1 korean changes

ui/raidboss/data/05-shb/trial/varis-ex.js
Sorry, I forget to update them when I put the last pull request.
Please merge this commit.
=> raidboss: add minor ja/cn translate for varis-ex.js

ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
=> raidboss: UCU Korean minor tts fix

ui/raidboss/raidboss_config.js, ui/raidboss/timeline.js
This is probably what https://github.com/quisquous/cactbot/issues/1247 and https://github.com/quisquous/cactbot/issues/1364 want.
=> raidboss: add timeline language config

resources/responses.js, ui/raidboss/data/05-shb/raid/e8n.js, ui/raidboss/data/05-shb/raid/e8s.js
Add shorthand response helpers for getBackThenFront() and getFrontThenBack() callouts.
=> Add getBackThenFront() and getFrontThenBack() Responses helpers.

util/check_translation.py, util/find_missing_translations.py
- check_translation had some issues with cases on replacementText
- find_missing_translation: added ability to filter results (path and files) to make it easier to go through all translations step by step
=> small translation script update

ui/eureka/eureka.js
I think those code make volume not customizable.
=> eureka: remove unused code

ui/raidboss/raidboss.css
=> raidboss: default css - infoText color to white

ui/raidboss/raidboss_config.js
I believe Browser means web browser, in Korean including "web" is better.
[Korean translation concern]
cactbot 웜홀 공략 방식이 영구정지식이라고 들었습니다. 제가 절알렉을 안해서 모르는데 그렇다길래 내용을 추가하는게 좋아보여서 추가해봤습니다. 영구정지식이 맞는지 알려주시면 좋겠어요.
=> raidboss config Korean

ui/eureka/eureka.js
My original entry was my best effort with google translation, correct translation taken from https://github.com/quisquous/cactbot/pull/1398#issuecomment-622352277.
Thanks @maiko-tan-coding.
=> Eureka: better JP bunny FATE label

ui/eureka/eureka.js
Add missing lines, fix FR NM names based on eureka-tracker
=> added and correction Fr ui/eureka/eureka.js

resources/responses.js
I believe Dorito Stack means to stack with person who's having this marker. (image below)
(I don't know what Dorito means, but translator says it's something "marker")
If not, please tell me.
=> raidboss: fill Korean responses

ui/raidboss/common_replacement.js, ui/raidboss/data/04-sb/trial/seiryu-ex.js
-  (Rotate), this is a line on Seiryu, i think it can be in (common).
@Akurosia @JLGarber  @Jaehyuk-Lee  @maiko-tan-coding, can you help me fix missing translations, I'm afraid google translation is not appropriate or accurate. Sorry for the inconvenience. Thank You all.
- (d(?:e|u|es) $1 dans), I would like to add this because I think this is missing. Is usefull ? @quisquous
=> Added --rotate-- line raidboss/common_replacement.js

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
=> Raidboss: TEA Shared Sentence shortnamify

ui/raidboss/raidboss_config.js
revert some of this cf2720c92282b203ede1b479f61bc570a1990951
=> raidboss config: remove some text on Korean

ui/raidboss/data/04-sb/eureka/eureka_hydatos.js
If someone needs logs to add triggers, I can provide them, but they will be in French. I don't know if we can transform them into English with act.
// FIXME: on all these forms, most of the time they come with double mechanics,
// so probably need some "Then," text so folks don't leave the first mechanic early.
// FIXME: random shade mechanic mid ozma form comes with holy/acceleration bomb/knockback
// so call out something like "get off + holy" or "get knocked in".
// FIXME: need callouts for knockback, and maybe "holy soon"?
=> Added missing translations Fr raidboss/eureka/eureka_hydatos

resources/common.js, resources/lang.js, resources/lang/cn.js, resources/lang/de.js, resources/lang/en.js, resources/lang/fr.js, resources/lang/ja.js, resources/lang/ko.js, resources/netregexes.js, resources/regexes.js, ui/jobs/jobs.js
This PR:
1. Adds additional regex capturing of timestamps to Regexes helper class
2. Adds kPetNames to language files
3. Adds kLanguage property to parent CactbotLanguage class
4. Adds zone name and timestamp capturing to seal/unseal/countdown language regexes
=> Regex Capturing and Language additions

resources/lang/cn.js
=> fix: invalid capture group name

ui/raidboss/data/03-hw/trial/sophia-ex.js
It was pointed out to me that things break slightly if the setup Quasars gets skipped. (The first tilt thereafter is treated as the Quasar setup and is therefore not called.) I didn't notice this because this is one of the failings of running content solo for timeline/trigger work...
I moved the direction-finding logic into a separate function to reduce clutter within the triggers. Now, if we see a tilt and we don't have entities to check against, we activate `sadTethers` regardless of the actual number of tethers. Functionality should be basically the same as before, just with the capability to call anything from the cast-call trigger.
(It's probably not strictly necessary to put the `clonesActive` condition up anymore, but I'd rather leave it in place for now, since it's also not …
=> Raidboss: Sophia EX tilt fix

ui/raidboss/data/03-hw/raid/a2s.js
Adds suppression to the soldiers.
=> raidboss: Fixup A2S Triggers

ui/raidboss/popup-text.js
=> Raidboss: fix error when AlertText is number

ui/raidboss/data/02-arr/raid/t7.js
Change regex to netRegex for cursed and shriek voice.
=> Raidboss: t7 Change regex to netRegex 

ui/raidboss/data/00-misc/test.js, ui/raidboss/data/02-arr/raid/t9.js, ui/raidboss/data/03-hw/trial/sophia-ex.js, ui/raidboss/data/04-sb/raid/o12s.js, ui/raidboss/data/04-sb/raid/o8s.js, ui/raidboss/data/04-sb/trial/tsukuyomi-ex.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/data/05-shb/raid/e1s.js, ui/raidboss/data/05-shb/raid/e6s.js, ui/raidboss/data/05-shb/raid/e7s.js, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js, ui/raidboss/popup-text.js, ui/raidboss/raidemulator.js
=> raidboss: add data.parserLang and data.displayLang

ui/raidboss/data/04-sb/raid/o10n.js, ui/raidboss/data/04-sb/raid/o11n.js, ui/raidboss/data/04-sb/raid/o12n.js, ui/raidboss/data/04-sb/raid/o9n.js
=> raidboss: omega alpha Korean

ui/raidboss/data/02-arr/raid/t1.js, ui/raidboss/data/02-arr/raid/t13.js, ui/raidboss/data/02-arr/raid/t2.js, ui/raidboss/data/02-arr/raid/t4.js, ui/raidboss/data/02-arr/raid/t5.js, ui/raidboss/data/02-arr/raid/t7.js, ui/raidboss/data/02-arr/raid/t8.js, ui/raidboss/data/02-arr/raid/t9.js, ui/raidboss/data/02-arr/trial/titan_ex.js
I just noticed that I was not always looking at the right line on the logs. There are several, but I understood which one is taken into account. So I correct those that I missed or wrote poorly. 
My apologies.
=> Raidboss: Bahamut fr

ui/raidboss/data/05-shb/trial/hades-ex.js
Discussion with @mooondark 
Je remet comme ça ou tu as une autre proposition.
Sinon concernant (drop) je n'ai pas vu la question que j'avais mis peut être un bug. Du coup il est traduit différemment suivant certains fichiers. Il y a posez, déposez, placez, je crois avoir vu autre chose mais tans pis. Déposez me semble le plus proche, j'aimerais ton avis que je rectifie tous ça sur une même traduction. merci à toi.
=> Raidboss: Hades fr

.github/workflows/README.md, CONTRIBUTING.md
Update the documentation revolving around GitHub Actions and debugging workflow failures for contributors.
=> docs: Update GitHub Actions Documentation

ui/raidboss/common_replacement.js, ui/raidboss/data/03-hw/trial/sophia-ex.js, ui/raidboss/data/04-sb/trial/shinryu.js, ui/raidboss/data/05-shb/trial/varis-ex.js
added corrections and missing translations fr on varis-ex.
removed translations on varis-ex, sophia-ex, shinryu for added on common.js all language.
=> Raidboss: Varis ex-fr+ common.js all language

ui/oopsyraidsy/data/03-hw/dungeon/aetherochemical_research_facility.js, ui/oopsyraidsy/data/03-hw/dungeon/fractal_continuum.js, ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.js, ui/oopsyraidsy/data/04-sb/dungeon/ala_mhigo.js, ui/oopsyraidsy/data/04-sb/dungeon/temple_of_the_fist.js, ui/oopsyraidsy/data/04-sb/raid/o2n.js, ui/oopsyraidsy/data/04-sb/raid/o3n.js, ui/oopsyraidsy/data/04-sb/raid/o4n.js, ui/oopsyraidsy/data/04-sb/trial/shinryu.js, ui/oopsyraidsy/data/05-shb/alliance/the_copied_factory.js, ui/oopsyraidsy/data/05-shb/dungeon/holminster_switch.js, ui/oopsyraidsy/data/05-shb/dungeon/qitana_ravel.js, ui/oopsyraidsy/data/05-shb/dungeon/the_grand_cosmos.js, ui/oopsyraidsy/data/05-shb/raid/e2s.js, ui/oopsyraidsy/data/05-shb/raid/e5s.js, ui/oopsyraidsy/data/05-shb/raid/e6n.js, ui/oopsyraidsy/data/05-shb/raid/e6s.js, ui/oopsyraidsy/data/05-shb/trial/hades-ex.js, ui/oopsyraidsy/data/05-shb/trial/titania-ex.js, ui/oopsyraidsy/data/05-shb/trial/titania.js, ui/oopsyraidsy/data/05-shb/trial/varis-ex.js, ui/oopsyraidsy/data/05-shb/ultimate/the_epic_of_alexander.js, ui/oopsyraidsy/oopsyraidsy.js
=> oopsy: add shareWarn/shareFail helpers

resources/user_config.js
=> config: fix; parser language is set to English

util/find_missing_translations.py
Update directory path to work for both Windows and Unix.
=> util: Update Path to Work for Windows and Unix

.github/matchers/markdownlint.json, .github/matchers/pylint.json, .github/matchers/stylelint.json, .github/workflows/css-lint.yml, .github/workflows/javascript-lint.yml, .github/workflows/markdown-lint.yml, .github/workflows/python-lint.yml, .github/workflows/test.yml
- Update names for steps within individual workflow jobs.
- Add problem matchers for markdownlint, pylint, and stylelint.
This should hopefully make error marking in pull requests more visible
and help with troubleshooting any failed action runs.
=> ci: Update GitHub Workflows

util/make_timeline.py
=> Util: Update make_timeline to restore FFLogs functionality

ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.js
=> Raidboss: the_grand_cosmos fr

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
added corrections and missing translations fr
@mooondark, si tu pouvais vérifier, je sais qu'il y a beaucoup de lignes désolé.
=> Raidboss: the_epic_of_alexander

.github/workflows/css-lint.yml, .github/workflows/javascript-lint.yml, .github/workflows/markdown-lint.yml, .github/workflows/python-lint.yml, .github/workflows/test.yml
Run GitHub Action workflows when their corresponding workflow file is
edited.
=> ci: Run Workflows on Workflow File Edit

.github/workflows/python-lint.yml
Update pylint version installed and remove temporary isort dependency
pin.
=> ci: Update pylint Version

ui/raidboss/common_replacement.js, ui/raidboss/data/04-sb/trial/yojimbo.js, ui/raidboss/data/04-sb/trial/yojimbo.txt
common replacement change is in logmessages:2014
=> small fixes in raidboss

ui/oopsyraidsy/data/04-sb/trial/byakko-ex.js, ui/oopsyraidsy/data/04-sb/ultimate/unending_coil_ultimate.js, ui/oopsyraidsy/data/05-shb/raid/e2n.js, ui/oopsyraidsy/data/05-shb/raid/e2s.js, ui/oopsyraidsy/data/05-shb/raid/e4s.js, ui/oopsyraidsy/oopsyraidsy.js, ui/raidboss/raidboss_config.js
adds missing translations fr.
adds missing regex de and fr for e4s.
removed fixme lines.
The lines added in French which are not translated is because we use the English words (early pull, late pull, party wipe).
=> Adds Oospyraidsy + ui

ui/raidboss/raidboss_config.js
=> fix: add '(5.x)' to ShB translation in Japanese

ui/oopsyraidsy/data/00-misc/general.js
=> oopsy: warn when buffs don't hit the whole party

ui/oopsyraidsy/data/02-arr/trial/shiva-ex.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/02-arr/trial/shiva-ex.js, ui/raidboss/data/02-arr/trial/shiva-ex.txt, ui/raidboss/data/manifest.txt
This was the worst timeline I've ever tried to make.  OOF
=> Shiva Extreme oopsy and raidboss

ui/raidboss/data/05-shb/raid/e5s.js, ui/raidboss/data/05-shb/raid/e7s.js
=> update e5s e7s trans

plugin/CactbotEventSource/FFXIVProcessCn.cs
I just copy&paste from `FFXIVProcessIntl` and it works well.
Since the target info is from OverlayPlugin's Enmity stuff, I made https://github.com/ngld/OverlayPlugin/pull/141 to ngld's OverlayPlugin.
=> plugin: cn 5.2 memory & data structure

plugin/CactbotEventSource/FateWatcher.cs
Untested but from the looks of things it should match the intl version.
=> Update FateWatcher for CN 5.2 release

.github/workflows/update-gh-pages.yml
Add GitHub Actions workflow to update gh-pages with any commits added to
main.
=> ci: Add Workflow to Update gh-pages From main

ui/raidboss/data/04-sb/eureka/eureka_hydatos.js
removal missingTranslation useless de, fr
=> Raidboss: eureka_hydatos

ui/raidboss/data/04-sb/alliance/royal_city_of_rabanastre.js
Two translations had changed.
And sorry for create node at recent pull requests, i cant rebase my forked repo, so I pulled other way but It makes nodes.
Really sorry for other developers. :(
=> update rabanastre kor translation

ui/radar/radar.js
=> radar: use network logs to filter on npc id

ui/eureka/eureka.js
=> eureka: more exceptions for tracker links

ui/raidboss/data/05-shb/raid/e8s.js
add missing translation + removal missingTranslation fr
=> Raidboss: e8s fr

resources/timericon.js, ui/jobs/jobs.js
Oops sorry, the regex has a little bug so it not work as expected.
=> job: bug hotfix on #1645

ui/raidboss/data/03-hw/trial/sephirot-ex.js
add missing translations fr + removal missingTranslation.
=> raidboss: sephirot-ex fr

ui/raidboss/data/03-hw/trial/sophia-ex.js
=> raidboss: sophia-ex fr

resources/common.js
Repose became a healer role action in ShB.
=> Update sleep jobs

ui/raidboss/data/03-hw/raid/a4s.js, ui/raidboss/data/03-hw/raid/a5s.js
a4s: minor correction.
a5s: add missing translations fr + removal missingTranslation=true.
I'm not doing at big pack anymore, I have not time, maybe during the holidays.
@mooondark je viens de me rendre compte que sur 3 ou 4 fichier j'ai traduit Dash par Ruée. De souvenir c'est Rush qui est traduit par ruée, du coup je me dis qu'un Dash c'est plutôt une Charge, qu'en penses tu ? cela concerne ( la voute, a5s, ravana et sophia ex).
=> raidboss: a4s + a5s fr

ui/raidboss/data/05-shb/dungeon/heroes_gauntlet.js, ui/raidboss/data/05-shb/dungeon/heroes_gauntlet.txt, ui/raidboss/data/manifest.txt
Untested, but it should work. I'll run this with a trust later tonight depending on how things go for my static and work on timelines/oopsy separately. Most of this I'm confident on, but the zombie triggers could use work. There's got to be a better way to handle that mechanic, or at least to communicate it to players.
=> Raidboss: Heroes' Gauntlet initial timeline and triggers

ui/raidboss/data/03-hw/raid/a6s.js
adds missing translations fr + removal missingTranslation
=> raidboss: a6s fr

ui/raidboss/data/05-shb/trial/wol-ex.js, ui/raidboss/data/05-shb/trial/wol-ex.txt, ui/raidboss/data/manifest.txt
Initial triggers for WoL Ex; mostly tested -- my farm party couldn't get a clear.
Feel free to test: https://panicstevenson.github.io/cactbot/ui/raidboss/raidboss.html
=> raidboss: Add Initial Warrior Of Light Ex Triggers

ui/jobs/jobs.js
added inner release to kAbility,
changed tempest to add 30 seconds, max of 60, i think.
changed storm's eye to add 30 seconds, max of 60 or set to 30
added Inner release effect of adding 15 seconds
=> 5.3 WAR changes

ui/raidboss/data/05-shb/trial/wol-ex.js
as the timeline is not available now, the timeline replacements are still consideres as missingReplacements
=> first part of wol-ex translations

ui/raidboss/data/04-sb/trial/byakko-ex.js, ui/raidboss/data/04-sb/trial/lakshmi-ex.js, ui/raidboss/data/04-sb/trial/rathalos-ex.js, ui/raidboss/data/05-shb/raid/e1s.js
adds missing translations fr +removal misingTranslation => lakshmi-ex
minor missing translations fr => e1s
minor missing corections fr => byakko-ex
minor correction fr => rathalos-ex
=> raidboss: translations lakshmi-ex, minor corrections e1s, byakko-ex, rathalos-ex FR

ui/raidboss/data/04-sb/trial/seiryu-ex.js
=> raidboss: seiryu-ex fr

ui/raidboss/data/04-sb/trial/shinryu-ex.js, ui/raidboss/data/04-sb/trial/shinryu.js
adds missing translations fr + removal missingTranslation
=> raidboss: Shinryu + Shinryu-ex fr

ui/raidboss/data/05-shb/trial/wol-ex.js, ui/raidboss/data/05-shb/trial/wol.js
But what is "GTFO" in wol?
EDIT: Well, I got it from [Akurosia](https://github.com/quisquous/cactbot/pull/1690#issuecomment-674368275), so never mind...
=> raidboss: add wol nm/ex initial translations

ui/raidboss/data/04-sb/trial/suzaku-ex.js, ui/raidboss/data/04-sb/trial/tsukuyomi-ex.js, ui/raidboss/data/04-sb/trial/yojimbo.js
added missing translations and corrections fr => tsukuyomi-ex
minor corrections fr => suzaku-ex
added missing translations fr => yojimbo
=> raidboss: suzaku-ex, tuskuyomi-ex and yojimbo FR

ui/radar/radar.js, ui/radar/radar_config.js
along with all ranks enabled/disabled via user config
=> Added B rank enabled/disabled via UI config

ui/radar/radar_config.js
=> add missing translation ui/radar_config fr

ui/raidboss/data/05-shb/trial/wol-ex.js
Sometimes this cast originates from the Warrior Of Light, preventing the knockback callout from triggering.
=> raidboss: Add Instance Where WoL Casts Suiton

ui/radar/radar.js
Reverts quisquous/cactbot#1680
=> Revert "radar: temporarily disable npcNameId matching"

ui/raidboss/data/03-hw/dungeon/sohm_al_hard.js
added and corrections translations FR
=> raidboss: sohm_al_hard fr

ui/oopsyraidsy/data/00-misc/buffs.js, ui/oopsyraidsy/data/04-sb/ultimate/unending_coil_ultimate.js, ui/oopsyraidsy/data/05-shb/raid/e5s.js, ui/oopsyraidsy/data/05-shb/raid/e7n.js, ui/oopsyraidsy/data/05-shb/raid/e7s.js
At misc/buffs, old things make sense but something weird to read. (reason is too small to see ` : ` letter)
=> oopsy: add missing translate, update misc

ui/raidboss/data/05-shb/trial/shiva-un.js
So players can use anti-knockback skills
(save poor BLM `(*/ω＼*)` )
=> raidboss: add knockback notice in shiva unreal

ui/radar/radar_config.js, ui/raidboss/data/05-shb/alliance/the_puppets_bunker.js
I'm sorry to request you together.
=> raidboss : puppet bunker KO translate / rader: rader-config

ui/radar/radar.js, user/radar-example.js
As discussed in https://github.com/quisquous/cactbot/issues/1724.
=> radar: fix issue#1724

ui/raidboss/popup-text.js
Refactor PopupText to move calls to `addOverlayListener` to a function to avoid having to avoid calling the super constructor in new raid emulator (#1387).
Pass duration into `_addText` and call `_scheduleRemoveText` from `_addText` to avoid having to duplicate a bunch of code in new raid emulator.
=> Refactor PopupText per discussion in #1387

ui/raidboss/popup-text.js, ui/raidboss/timeline.js
@r4ha @Bluefissure Can you both double-check if I translate them into Japanese/Chinese correctly?
=> add ja/cn debug text translation

ui/raidboss/data/05-shb/raid/e6s.js, ui/raidboss/data/05-shb/raid/e8s.js
I forgot there were transliterated translations, fixed them to client data.
=> fix trigger translation (KR)

ui/raidboss/data/04-sb/dungeon/the_burn.js, ui/raidboss/data/05-shb/alliance/the_puppets_bunker.js, ui/raidboss/data/05-shb/raid/e1s.js, ui/raidboss/data/05-shb/raid/e6s.js, ui/raidboss/popup-text.js, ui/raidboss/timeline.js
pls note that i removed the touchdown trigger in the burn, as it was neither used in the JS or TXT file
=> Added missing translations (mostly DE and KO)

resources/responses.js
=> respons.js fr

ui/dps/rdmty/dps.html, ui/dps/xephero/xephero-cactbot.html, ui/eureka/eureka.html, ui/fisher/fisher.html, ui/jobs/jobs.html, ui/oopsyraidsy/oopsyraidsy.html, ui/radar/radar.html, ui/raidboss/raidboss.html, ui/raidboss/raidemulator.html, ui/test/test.html
So don't have to read long long URL.
=> Remote Cactbot: add title to every html files

ui/raidboss/timeline.js
=> raidboss: simplify /countdown Engage! suppression during wipes

resources/player_override.js, resources/user_config.js, ui/oopsyraidsy/oopsyraidsy.js, ui/raidboss/common_replacement.js, ui/raidboss/data/00-misc/test.js, ui/raidboss/raidboss_config.js
But I am not confident with français.
@VanSlanzar sorry for disturbing, do you have time to check it once?
(And there are some brand new configurations lacks fr translations.)
=> Various translations adding and fixing

ui/radar/radar.js
Makes hunt mapping a little easier.
=> Add monster location to radar log

resources/player_override.js, ui/raidboss/data/00-misc/test.js
Sorry @MaikoTan @quisquous , I am not very available at the moment, thank you for mentioning me. Here are some missing translations that have been requested.
=> Various Translations fr

ui/oopsyraidsy/oopsy_common.css, ui/oopsyraidsy/oopsyraidsy.js, ui/oopsyraidsy/oopsyraidsy_config.js
This fixes #1782.
I think it's better to be optional since this function overwrites previous copied thing.
=> Oopsy: add click to copy

resources/regexes.js, resources/timerbar.js, ui/config/config.js, ui/dps/dps_common.js, ui/eureka/eureka.js, ui/fisher/seabase.js, ui/jobs/jobs.js, ui/oopsyraidsy/data/00-misc/test.js, ui/oopsyraidsy/oopsyraidsy_config.js, ui/raidboss/data/04-sb/alliance/orbonne_monastery.js, ui/raidboss/data/04-sb/raid/o4s.js, ui/raidboss/data/04-sb/trial/seiryu-ex.js, ui/raidboss/data/04-sb/trial/shinryu-ex.js, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/data/05-shb/raid/e3s.js, ui/raidboss/emulator/data/PopupTextAnalysis.js, ui/raidboss/popup-text.js, ui/raidboss/raidboss_config.js, ui/raidboss/test/dragon_test.js
Update the general usage of `indexOf()` to instead use `includes()` where the check isn't looking for an actual index but instead checking if value exists within a collection.
=> general: Update IndexOf Usage to Includes Where Applicable

ui/oopsyraidsy/oopsyraidsy.js
If the trigger is enabled for early pulls then they SHOULD be logged.
=> OopsyRaidsy:Fix enable check for early pulls

ui/jobs/jobs.css, ui/jobs/jobs.js
- Lily Amount
- Next Lily Countdown
- BloodLily Stack
- DoT Tracker
- Assize Cooldown Tracker
- Lucid Cooldown Tracker
=> jobs: WHM UI

plugin/CactbotEventSource/FFXIVProcessCn.cs, plugin/CactbotEventSource/FFXIVProcessIntl.cs, plugin/CactbotEventSource/FFXIVProcessKo.cs, ui/test/test.js
Overlooked this way back, sorry!
=> plugin: Add missing fields to JobMemory for DNC,DRK,MNK,MCH,SAM

ui/jobs/jobs.css, ui/jobs/jobs.js
Impactful proc is deleted in patch 5.0.
Also adjust black mana color to make it more looks like in-game black mana.
=> jobs: remove impactful proc box for RDM

ui/raidboss/data/02-arr/raid/t4.js, ui/raidboss/data/02-arr/raid/t4.txt
The previous way did not solve the problem itself,
instead of writing complecated regex, it is better
to change the text itself.
=> fix(Raidboss): directions not fully translated

test/trigger/test_trigger.js
example)
`Diadem F` being as common prefix for these
`Diadem Falling Asleep`
`Diadem Found Gather Point`
`Diadem Flag Alert`
fixed to be `Diadem`
But `Eden\'s Gate` becomes `Eden\'s`, so do we have two word ids?
=> test: fix for prefix check

ui/jobs/jobs.js
As issue #1857 discussed.
Temporarily fix it by simple if condition.
Overrides will be underway since more patch difference is underway.
(Seems that MNK will change a lot in patch 5.4?)
=> jobs: WAR quick fix in CN/KO by if condition

ui/jobs/jobs.css
These changes make bars and stacks match the width of HP bar better.
=> jobs: Better width for bars and stacks

.github/workflows/python-lint.yml, .gitignore, requirements.txt
- Add `requirements.txt` for pip installing ( although there are only 4 items for now )
- Add virtual environment-related files into .gitignore
- Add pip cache in python-lint workflow ( theoretically would be a little faster? )
=> CI: Some Python related simplification

resources/user_config.js, ui/config/config.js, ui/dps/rdmty/dps.html, ui/dps/xephero/xephero.js, ui/eureka/eureka.js, ui/fisher/fisher.js, ui/fisher/seabase.js, ui/jobs/jobs.js, ui/oopsyraidsy/oopsyraidsy.js, ui/pullcounter/pullcounter.js, ui/radar/radar.js, ui/raidboss/emulator/data/AnalyzedEncounter.js, ui/raidboss/emulator/data/NetworkLogConverter.js, ui/raidboss/emulator/data/RaidEmulator.js, ui/raidboss/popup-text.js, ui/raidboss/raidboss.js, ui/raidboss/raidemulator.js, ui/raidboss/timeline.js
Pass options as a parameter to anything using Options from the global scope to instead be passed a reference.
=> general: Add Options Parameter for Dependent Classes

ui/raidboss/data/00-misc/general.js
=> raidboss: show invuln/provoke/shirk triggers to healers

test/timeline/test_timeline.js, ui/raidboss/data/05-shb/raid/e8s.js, ui/raidboss/timeline.js
This will also print log messages, so that if users edit timeline
files and break timeline triggers, there will be some warning.
This will help with #1896.
=> raidboss: validate that all timeline triggers match something

ui/config/config.css, ui/raidboss/popup-text.js, ui/raidboss/raidboss_config.js
=> raidboss: add config ui to override duration

ui/raidboss/data/05-shb/etc/the_diadem.js, ui/raidboss/raidboss_config.js
fixed missing translations in raidboss config and diadem
=> fixed missing translations

docs/RaidbossGuide.md, docs/zh-CN/RaidbossGuide.md
Co-authored-by: Echoring <2461286672@qq.com>
=> Doc: Add RaidbossGuide.md Chinese Translation

docs/zh-CN/CactbotCustomization.md
Co-authored-by: Echoring <2461286672@qq.com>
=> Better Chinese CactbotCustomization.md translation

ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.js, ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.txt, ui/raidboss/data/manifest.txt
Nothing major on this one. The timings on each encounter seem remarkably rigid compared to most other instances. (The Ultima Warrior's phases drifted by less than a second over a 6-minute encounter!)
I could definitely use some criticism on Ultima Warrior's timeline. Assembling the phase blocks was easy, but I really don't like how I ended up setting this up. The endless duplication of the phase "tails" seems excessive.
It's very possible the Sophia circle triggers are overthinking it. Given how many times people run away though, I feel like explicit calls on that might be best.
Overall I'm happy to get this one cleaned up. It's one of my favorite instances in Stormblood and desperately deserved to have full support. Oopsy will be forthcoming in 6 to 8 weeks (TM).
=> Raidboss: Fractal hard timeline and triggers.

ui/eureka/eureka.js, ui/eureka/eureka_config.js, ui/raidboss/data/05-shb/eureka/bozjan_southern_front.js
For translations i tried to stay with a maximum of 20 chars max.
Its hard for some, as many dont have a common abbreviation
=> bozja updates

ui/raidboss/data/04-sb/dungeon/hells_lid.js, ui/raidboss/data/04-sb/dungeon/hells_lid.txt, ui/raidboss/data/manifest.txt
It's so straightforward that I don't really have any comments on it. Yay for output strings!
=> Raidboss: Hell's Lid timelines and triggers

ui/eureka/eureka_config.js
I guess skirmishes, critical engagements, duels are v5.35 contents, I don't know what are these, I've keep English names.
=> UI: eureka UI Korean translation

ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
preRun runs before delaySeconds, so data.betaIndex is not set yet when
the instructions callout preRun happens.  This leaves data.betaIndex as
undefined, and deta.betaInstructions also undefined.
Fixes #1996, probably.
=> raidboss: fix tea beta instructions

README.md, docs/ko-KR/README.md
Overlay module detailed part is yet in English, but I think worth to add this file now.
See markdown [here](https://github.com/Jaehyuk-Lee/cactbot/blob/docs-ko-readme/docs/ko-KR/README.md)
=> docs: Korean Readme

ui/jobs/jobs.js, ui/jobs/jobs_config.js
I've added countdown alarm sound enable/disable option, or better to add sound volume?
=> jobs: add option for countdown sound

util/make_timeline.py
=> make_timeline support non EN languages

README.md, docs/ko-KR/README.md
removed sentences based on #2011
=> Readme cleanup

package.json, resources/regexes.js, resources/widgetlist.js, ui/config/config.js, ui/dps/dps_common.js, ui/dps/xephero/fake_dps.js, ui/dps/xephero/xephero.js, ui/eureka/eureka.js, ui/fisher/fisher-ui.js, ui/fisher/fisher.js, ui/jobs/jobs.js, ui/pullcounter/pullcounter.js, ui/radar/radar.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/raidboss.js, ui/raidboss/raidemulator.js, ui/raidboss/test/dragon_test.js, ui/raidboss/timeline.js, ui/test/test.js
Fixed automatically using `--fix`.
=> general: Enable prefer-arrow-callback ESLint Rule

ui/raidboss/data/03-hw/dungeon/xelphatol.js, ui/raidboss/data/03-hw/dungeon/xelphatol.txt, ui/raidboss/data/manifest.txt
I found this rattling around in my fork from September. I don't remember why I forgot about it, but I did do a couple of test runs and everything seemed okay. Nothing of real interest here, it was all straightforward apart from some fiddly bits on the first boss. (Dual intermissions seems excessive for a first boss, but oh well, Square will be Square.)
=> Raidboss: Xelphatol timeline and triggers

ui/raidboss/data/05-shb/trial/varis-ex.js
@Jaehyuk-Lee could you please double check if this is now correct (or explain why the name differs in KO) ?
=> Varis - fixed KO name from bladesblood (검기) to gunshield (건실드)

ui/raidboss/data/03-hw/dungeon/xelphatol.js, ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.js
Co-authored-by: MaikoTan <maiko.tan.coding@gmail.com>
=> Xelphatol & Ghimlyt_dark ja by MaikoTan

docs/zh-CN/CactbotCustomization.md
Co-authored-by: Echoring <2461286672@qq.com>
=> doc: update Customization Chinese translation

ui/jobs/jobs.css, ui/jobs/jobs.js
Once discussed in #2014 
Retain id for easier access when special needed.
=> Jobs: Use class selector instead of id

resources/defaults.css, resources/user_config.js
The default font family makes Japanese shows weird, so add pre-defined font-family css rules.
=> Fix: change font when display lang set to ja

ui/raidboss/data/05-shb/raid/e8s.js, ui/raidboss/data/05-shb/raid/e8s.txt
In fact this mirror color is red.
Other languages do not translate the color so not need to add.
=> Raidboss: Fix mirror color not matched

ui/jobs/jobs.js
- Sort list, func block, kability, combo, etc by jobs order
- Add comment to split kability by jobs
- Fix RageOfHalone upper case not matched
- closes #1944
By the way, I notice that there're a lot of unused kability/combo here. May I going to clean them up or just leave it be for probably later use?
=> jobs: Rearrange jobs.js

plugin/CactbotEventSource/CactbotEventSource.cs, plugin/CactbotEventSource/CactbotEventSourceConfig.cs, ui/config/general_config.js
This option is superseded by the webpack dev server, which autoreloads
when files change.
=> plugin: remove file watching

plugin/CactbotEventSource/FFXIVPlugin.cs
This was mentioned on discord a while back.
=> plugin: skip disabled plugins when searching for ffxiv plugin

docs/LogGuide.md
I saw that you referred to my docs on 'DirectorUpdate' as 'directory update', so I feel compelled to push in this PR that fixes that and adds some further explanation on DirectorUpdate data.
Definitely feel free to critique the data as you will (other than the `s/directory/director/` change, of course), and I'll adjust as needed.
=> Small documentation fixes / improvement

plugin/CactbotEventSource/CactbotEventSource.cs, ui/oopsyraidsy/oopsyraidsy.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/emulator/data/AnalyzedEncounter.js, ui/raidboss/emulator/overrides/RaidEmulatorPopupText.js, ui/raidboss/emulator/overrides/StubbedPopupText.js, ui/raidboss/popup-text.js, ui/raidboss/raidboss.js, ui/raidboss/raidemulator.js, ui/raidboss/timeline.js
These functions no longer need to exist because data files are known
statically.  Clean up these calls and pass values to constructors
instead.
=> Clean up SetDataFiles functions

ui/jobs/jobs.css, ui/jobs/jobs.js
- Heat Gauge
- Battery Gauge
- Drill/Bioblaster Cooldown Tracker
- Air Anchor Cooldown Tracker
- Wild Fire Cooldown&Duration Tracker
- when overheated, Heat Gauge will show remain time instead of heat.
- when robot is active, Battery Gauge will show remain time instead of battery.
- when Wild Fire is active, there will be a gauge to show how many GCD you have landed.
=> Jobs: MCH UI

ui/jobs/jobs.js
Remove the condition once used to deal with WAR before patch 5.3.
=> Jobs: WAR update for CN 5.3

ui/config/config.css, ui/raidboss/raidboss_config.js, ui/raidboss/timeline.js
=> config: add beforeSeconds to raidboss config ui

ui/raidboss/data/05-shb/trial/castrum-ex.js, ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js, ui/raidboss/data/manifest.txt
This is just bare-bones for those who wanna add on top of it, I did some of it real quick from a few youtube videos and a network log from my friends. Some of the abilities probably don't have to be output string.
=> Raidboss: Castrum Ex initial triggers

ui/raidboss/data/05-shb/raid/e9n.js
hi, i am back.
fr corrections.
@mooondark, j'ai été absent longtemps, gros prob irl. Je vais reprendre les traductions avec toi. J'apporte ces petites modif en cohérence de l'uniformité des traductions de ce qu'on a fais avant. Si tu as une remarque ou si cela n'est pas bon dis le moi, comme dab. Merci à toi.
=> raidboss: e9n fr corrections

ui/raidboss/data/05-shb/raid/e9s.js
Some improvements can be made and some TODOs remain to be done, but here's some initial triggers.
=> raidboss: Initial E9S Triggers

ui/raidboss/data/05-shb/raid/e10s.js
I don't know these machanics, I compared with e10s video.
There maybe a mis-translations.
=> raidboss: e10s Korean translation

ui/raidboss/data/02-arr/dungeon/brayfloxs_longstop.js, ui/raidboss/data/02-arr/dungeon/haukke_manor.js
add a missing line and corrections translations fr.
add missing punctuation.
=> raidboss: Dungeons arr fr

ui/raidboss/data/05-shb/raid/e11s.js, ui/raidboss/data/05-shb/raid/e9s.js, ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js
=> raidboss: Korean translation

ui/raidboss/data/03-hw/raid/a1s.js, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.js, ui/raidboss/data/04-sb/dungeon/the_burn.js, ui/raidboss/data/04-sb/raid/o8s.js, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js, ui/raidboss/data/05-shb/raid/e1s.js
@quisquous, here are some corrections after discussions with @mooondark.
@mooondark, j'ai corrigé avec orienté quand se sont des lasers à orientés, mais laissez attirer quand cela cible un joueur ou des joueurs au hasard peut importe la position et que la position de la mécanique est verrouiller juste après. Ou si c'est un boss.
=> raidboss: minors corrections translations fr

ui/raidboss/data/05-shb/raid/e9n.js, ui/raidboss/data/05-shb/raid/e9s.js
=> raidboss: Convert E9 Break Chain Triggers to Tethers

ui/oopsyraidsy/data/00-misc/test.js, ui/oopsyraidsy/data/03-hw/alliance/weeping_city.js, ui/oopsyraidsy/data/05-shb/raid/e7s.js, ui/oopsyraidsy/data/05-shb/raid/e8n.js, ui/oopsyraidsy/data/05-shb/trial/wol-ex.js
@mooondark, peux-tu check s'il te plais ?
Je ne suis pas sûre pour slid off et knocked off. 
Désolé.
=> oopsyraidsy: missing translations Fr

ui/raidboss/data/05-shb/raid/e11s.js
* add tethers for shifting/sundered sky
* add tethers for cycle of faith
* rename "group stacks" to "holy groups", sorry for extra translations
* fix bug with tether collection
* improved red/blue durations so it's up when needed
=> raidboss: e11s improvements

ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js
=> raidboss: emerald-weapon-Ex Fr

ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js, ui/raidboss/data/05-shb/trial/emerald_weapon-ex.txt
@g0shu wanted sword explosion callouts.
Should we used a better name than the mechanic's name?
=> raidboss: Emerald Weapon Ex Updates

ui/raidboss/data/02-arr/trial/titan-ex.js, ui/raidboss/data/05-shb/trial/titan-un.js
Update Rock Throw triggers to use tethers intead, giving an alert to
people with the jail tether, and a mild reminder for everyone else.
Closes #2172
=> raidboss: Update Titan Unreal Rock Throw

util/encounter_tools.py, util/make_timeline.py, util/test_timeline.py
(This should resolve #2177)
Sample output:
```
> python make_timeline.py -f log.log -lf
01. 16:42:41.954 | 16:51:54.176 | 09:12 | Eden's Promise: Anamorphosis
02. 17:25:45.648 | 17:31:31.184 | 05:45 | Castrum Marinum (Extreme)
03. 17:32:12.626 | 17:38:51.487 | 06:38 | Castrum Marinum (Extreme)
04. 17:39:44.714 | 17:42:17.109 | 02:32 | Castrum Marinum (Extreme)
05. 17:42:40.990 | 17:47:22.555 | 04:41 | Castrum Marinum (Extreme)
06. 17:47:52.560 | 17:53:42.855 | 05:50 | Castrum Marinum (Extreme)
07. 17:54:08.564 | 17:57:37.200 | 03:28 | Castrum Marinum (Extreme)
08. 17:58:02.904 | 18:03:58.094 | 05:55 | Castrum Marinum (Extreme)
09. 18:04:27.087 | 18:10:15.342 | 05:48 | Castrum Marinum (Extreme)
10. 18:10:38.033 | 18:16:58.492 | 06:20 | Castrum Marinum (Extreme)
11. 18:27:01.503 | …
```
=> Util: Encounter listing in make/test_timeline is now readable

ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js
=> Raidboss: emerald-ex Missing translation fr

util/make_timeline.py, util/test_timeline.py, util/translate_fight.py
https://www.fflogs.com/accounts/changeuser doesn't exist anymore.
=> util: Update API Key Help Text

ui/raidboss/data/05-shb/raid/e10s.js
=> Add some missing e10s CN translations

ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.js
4763 Scorching Left: https://www.garlandtools.org/db/#action/18275
4762 Scorching Right: https://www.garlandtools.org/db/#action/18274
Co-authored-by: ShadyWhite <44015352+ShadyWhite@users.noreply.github.com>
=> Fix(Raidboss): Left/Right Slash nofify wrong side

plugin/CactbotEventSource/CactbotEventSource.cs
Had to add new method to allow overlays with external URLs.
Hope that's okay.
=> Add method to register overlays with external URL. Add ZeffUI

plugin/CactbotEventSource/FateWatcher.cs
Sorry it's a bit late. 
Quick tests in Bozja show it working as expected on my client.
=> Eureka: Update CE Opcode for 5.4hotfix

ui/raidboss/data/05-shb/raid/e10s.js
=> refactor(Raidboss): Move directions to top in e10s

ui/raidboss/data/05-shb/dungeon/heroes_gauntlet.js, ui/raidboss/data/05-shb/dungeon/matoyas_relict.js
=> Raidboss: Dungeons shb fr

ui/raidboss/data/05-shb/eureka/bozjan_southern_front.js
=> Raidboss: bozjan_southern_front FR

ui/raidboss/data/05-shb/raid/e9n.js, ui/raidboss/data/05-shb/raid/e9n.txt
This wasn't too bad to put together, but it does look like there's more variance on this than I'm used to. Wide-Angle Phaser and Rejuvenating Balm just seem to drift slightly from pull to pull. None of it actually matters since the exact timing on those two mechanics isn't make-or-break for anyone, but it's annoying. My suspicion is that when she tethers the wall, there's a difference in animation time between "tethers front" and "tethers back". Everything else seems to be mostly fine.
=> Raidboss: E9N timeline

ui/oopsyraidsy/data/05-shb/trial/emerald_weapon-ex.js
=> oopsraidsy: emerald-ex adds missing translations fr

ui/oopsyraidsy/data/03-hw/alliance/weeping_city.js, ui/oopsyraidsy/data/03-hw/raid/a12n.js, ui/oopsyraidsy/data/04-sb/raid/o4n.js, ui/oopsyraidsy/data/04-sb/trial/shinryu.js, ui/oopsyraidsy/data/04-sb/ultimate/unending_coil_ultimate.js, ui/oopsyraidsy/data/05-shb/raid/e11n.js, ui/oopsyraidsy/data/05-shb/raid/e11s.js, ui/oopsyraidsy/data/05-shb/raid/e12s.js, ui/oopsyraidsy/data/05-shb/raid/e4s.js, ui/oopsyraidsy/data/05-shb/raid/e5n.js, ui/oopsyraidsy/data/05-shb/raid/e5s.js, ui/oopsyraidsy/data/05-shb/raid/e7s.js, ui/oopsyraidsy/data/05-shb/raid/e8n.js, ui/oopsyraidsy/data/05-shb/raid/e9s.js, ui/oopsyraidsy/data/05-shb/ultimate/the_epic_of_alexander.js
adds and corrections translations fr
=> oopsyraidsy all expansions Fr

resources/user_config.js
The UI doesn't allow this, and adding support for user directories
requires removing this.  See: #860.
=> resources: remove support for remote user directories

ui/raidboss/data/05-shb/raid/e11n.js, ui/raidboss/data/05-shb/raid/e11s.js
=> raidboss: e11n and e11s Fr

ui/raidboss/data/05-shb/raid/e12n.js
=> Raidboss: e12n Fr

CONTRIBUTING.md, README.md
=> docs: add references to nodejs and npm install

docs/CactbotCustomization.md, plugin/CactbotEventSource/CactbotEventSource.cs, resources/user_config.js, test/unittests/config_test.js, ui/raidboss/raidboss_config.js
=> Add support for user folders

ui/raidboss/data/05-shb/raid/e12s.js
=> Raidboss: e12s fr adds missing translations fr

ui/jobs/jobs.js
=> refactor: simplify crafting detection

ui/jobs/jobs.js
Due to the launch of patch 5.3 in Korean, this block is no longer needed.
=> Jobs: Remove condition about eyeBox for Korean v5.3

plugin/CactbotEventSource/FateWatcher.cs
Updated the CE opcode for patch 5.41.
=> Eureka: Update bozja opcode for 5.41

webpack/loaders/timeline-loader.cjs, webpack/webpack.config.cjs
A too-young-too-simple timeline loader who remove comments and blank lines only.
=> build: webpack timeline loader

plugin/CactbotEventSource/FFXIVProcessKo.cs, resources/translations.js
I guess this will work, didn't really tried it though since the parser is not out yet.
=> plugin, jobs: v5.3 Korean server update

ui/jobs/jobs.js
As I changed Monk's lightning in #2395 ,
but it still kept showing a red timer which is annoying.
So just remove them when play in intl version.
=> jobs: remove lightning timer in intl version

docs/OopsyraidsyGuide.md, ui/oopsyraidsy/data/00-misc/test.js, ui/oopsyraidsy/data/04-sb/ultimate/ultima_weapon_ultimate.js, ui/oopsyraidsy/data/05-shb/raid/e8s.js, ui/oopsyraidsy/data/05-shb/trial/varis-ex.js, ui/oopsyraidsy/data/05-shb/ultimate/the_epic_of_alexander.js, ui/oopsyraidsy/oopsyraidsy.js
=> oopsy: implement suppressSeconds

ui/raidboss/data/05-shb/alliance/the_copied_factory.js
Adds missing translations and corrections Fr
=> Raidboss: the_copied_factory Fr

ui/raidboss/data/05-shb/raid/e9s.js, util/coverage/coverage.js
adjustment Fr for request #2402
=> Corrections fr : Coverage+e9s

ui/raidboss/data/05-shb/raid/e12s.js
These will call out "Eye on you" similar to e2s, and then later call out look away from player 1 and player 2, or the other player (if there).
Not sure if we want to keep the older one as an option, but this one would work well for when there is a non-standard comp.
=> raidboss: e12s oracle basic relativity shadoweye target callouts

ui/raidboss/data/03-hw/dungeon/xelphatol.js, ui/raidboss/data/03-hw/trial/sophia-ex.js
=> Raidboss: sophia-ex + xelphatol fr

util/coverage/coverage.css
via adding a tricky sticky css rule.
=> feat(coverage): keep table header on top

ui/jobs/jobs.js
Nothing actually goes wrong for not supporting PVP, but error log may make someone confused.
=> Jobs: Fix error log when draw card in pvp area

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.js
```text
Network_20700_20210111.log:20|2021-01-11T23:00:30.8870000+08:00|4000703D|究极神兵|2B84|魔科学激光|4000703D|究极神兵|2.70||a0686d5917c4304683b3a7441e9bb5ac
Network_20700_20210111.log:21|2021-01-11T23:00:33.8740000+08:00|4000703D|究极神兵|2B84|魔科学激光|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||5644035|11910290|0|10000|0|1000|113.7|86.3|0|-0.7854581|00007FBA|61702fd90e36ddf8e750a724fb8a3265
Network_20700_20210111.log:20|2021-01-11T23:00:35.0320000+08:00|4000703D|究极神兵|2B84|魔科学激光|4000703D|究极神兵|2.70||aa3b1328dd01abee524dc129638673dc
Network_20700_20210111.log:21|2021-01-11T23:00:38.0230000+08:00|4000703D|究极神兵|2B84|魔科学激光|E0000000||0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|||||||||||5644035|11910290|0|10000|0|1000|113.7|86.3|0|-0.7854581|00007FD1|fea987cbf46df1f9fa5425bce57e2a2d …
```
=> Raidboss: UWU add Aetherochemical Laser position triggers

ui/oopsyraidsy/data/05-shb/raid/e12s.js
=> oopsy: add e12s chiseled sculpture lasers

ui/raidboss/data/05-shb/raid/e12s.js
=> raidboss: add long/short ice/fire callouts to e12s

ui/eureka/eureka.js
Not a big deal but unicode is easy to read.
=> Eureka: use unicode \ue0bb instead

plugin/CactbotEventSource/FateWatcher.cs
Untested, will check when patch goes live as I'll be doing the new content!
=> plugin: update Bozja CE Opcode for global 5.45

ui/fisher/static-data.js, ui/oopsyraidsy/data/05-shb/raid/e12s.js, ui/raidboss/data/04-sb/raid/o2s.js, ui/raidboss/data/05-shb/raid/e12s.js
=> Ordered on wish

ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.js, ui/raidboss/data/03-hw/dungeon/gubal_library_hard.js, ui/raidboss/data/03-hw/raid/a9s.js, ui/raidboss/data/04-sb/dungeon/bardams_mettle.js, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.js, ui/raidboss/data/04-sb/eureka/eureka_hydatos.js, ui/raidboss/data/05-shb/raid/e8n.js
replacement of the verb `Tenez-vous` by another more pleasant and less sustained `placez-vous`
=> Stand In: Translation modification fr

ui/raidboss/data/04-sb/dungeon/swallows_compass.js, ui/raidboss/data/04-sb/dungeon/swallows_compass.txt, ui/raidboss/data/manifest.txt
Slightly late for BLU users, but here it is. All the special stuff is in the in-line comments.
=> Raidboss: Swallow's Compass timeline and triggers

ui/jobs/jobs.js
I think this change would help when refactoring jobs later.
cc @Echoring 
Also fix a bug might come from #1616 while invoking functions with an undefined "name".
=> Refactor(jobs): melt brd specific code into others

docs/ko-KR/README.md, ui/raidboss/data/04-sb/dungeon/swallows_compass.js, ui/raidboss/data/05-shb/eureka/delubrum_reginae.js, ui/raidboss/data/05-shb/raid/e12s.js
I don't know anything about delubrum reginae, so some translations are not done yet.
=> raidboss: Korean translation (swallows compass, delubrum reginae)

package.json, webpack/webpack.config.cjs
This helps when we are debugging with modules,
In chrome or CEF (in OverlayPlugin), we can directly set breakpoints in source code files provides by `webpack-dev-server`,
and then make changes in-game, to catch variables changes in code.
=> build: generate source map when in development

ui/oopsyraidsy/data/04-sb/dungeon/st_mocianne_hard.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/04-sb/dungeon/st_mocianne_hard.js, ui/raidboss/data/04-sb/dungeon/st_mocianne_hard.txt, ui/raidboss/data/manifest.txt
Nothing special really. The only thing of note is that we have no way of syncing the timeline sooner on boss 2 for the path splits. The user *can* tell which it will be, since the golems will be in a line if it's the Earthquake pattern and will be in a box if it's the Earth Shaker pattern. However, the timeline has no good way of determining this.
=> Raidboss + oopsyraidsy: St Mocianne's Arboretum (hard)

ui/oopsyraidsy/data/04-sb/dungeon/kugane_castle.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/04-sb/dungeon/kugane_castle.js, ui/raidboss/data/04-sb/dungeon/kugane_castle.txt, ui/raidboss/data/manifest.txt
I'm not sure why I never bothered with this one before, it was remarkably painless. Nothing special here.
=> Raidboss + oopsy: Kugane Castle

package.json, test/definitions.py
Revert changes from #2462 due to issues listed in #2479.
=> build: revert ts changes for running tests

docs/CactbotCustomization.md, resources/user_config.js
=> resources: add more and document user file imports

test/helper/test_timeline.js
Rather than storing string property names which require
re-parsing into regexes, store regex objects as keys in a Map.
This speeds up timeline tests by 2-3x.  <_<
Mentioned in #2483.
=> test: speed up timeline tests by storing parsed regexes

test/helper/test_timeline.js
The pre-replacement collision tests that two regexes that apply to the
same text can be applied in either order without causing issues.  In
these cases, we only need to consider the regexes that apply to
a particular item, and not every single regex.
This is about a 20% speedup.  Unfortunately, there's no way to make
the post-collision test any better.
Mentioned in #2483.
=> test: speed up timeline by reducing n in O(n^2) op

ui/jobs/components/smn.js
since #2467
onUseAbility works via assignment, not appending.
=> Fix(jobs): Summoner's Miasma proc box broken

resources/util.ts
Also remove a bunch of implicit return values that aren't needed
after making this change.
=> resources: mark Util export as const

ui/raidboss/data/04-sb/dungeon/the_burn.js
=> dungeon: the_burn fr

ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
=> raidboss: deluburm_reginae fr

ui/oopsyraidsy/data/05-shb/eureka/delubrum_reginae.js, ui/oopsyraidsy/data/05-shb/eureka/delubrum_reginae_savage.js, ui/oopsyraidsy/data/manifest.txt, ui/raidboss/data/05-shb/eureka/delubrum_reginae.js, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt, ui/raidboss/data/manifest.txt
=> [wip] delubrum savage

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
Log: https://www.fflogs.com/reports/LZPRYhkt3NBXW4aF#fight=13&view=events&type=casts&hostility=1&eventstart=14734598
=> raidboss: DRS Trinity Seeker Add Missing "Phantom Edge?" casts

ui/raidboss/data/04-sb/raid/o4s.js
Changed comments from `Decisive Battle` to `Dualcast`
=> Dualcast fix o4s.js

ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
so it matches the timeline and ingame appearance
=> DR - change sword to arrow 

ui/dps/rdmty/dps.js
format this file with `eslint --fix`
at least we should remove trailing whitespaces
=> format ui/dps/rdmty/dps.js

docs/CactbotCustomization.md, docs/RaidbossGuide.md, docs/zh-CN/RaidbossGuide.md
Since files structure changed a lot...
=> docs: update custom document

ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.txt
While collecting data for a forthcoming oopsy addition, I came across a few things with the timeline that need fixing. On Ultima Warrior, I had missed an Aetheroplasm cast at 1042.0. I don't know how I missed this before, but it was there on three separate attempts. Other than that, I widened/added sync windows in various places to better prevent visible desyncing.
=> Raidboss: Fractal Hard timeline improvements

ui/raidboss/timeline.js
@Akurosia @Jaehyuk-Lee May you have time to check if this localization correct?
=> i18n: localize 'Active:' text in timeline

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
Some issues that I found during testing that I could resolve and test live.
=> raidboss: DRS Fix Fateful words not calling out; Change duration => castTime

ui/jobs/components/war.js
This makes StormsEye more accurate, even if some log lines are missing (like in Bozjan).
=> Jobs: WAR improvement: Better way to handle StormsEye duration

ui/raidboss/data/05-shb/raid/e12s.js
We were running a bunch of e12s and so I had time to test this out
and iron it out.
I personally found that having a trigger on:
* initial number
* left right
* laser bait
* other three lasers
* knockback location
...was just incredibly noisy.
I have cut this back from #2443 to say:
* initial number (inner outer)
* left/right OR left/right + bait #1
* bait #n laser (no other lasers called out)
* knockback location
Inner/Outer seems to work with the changes that I made here to collect
the sculptures separately from the tether.
(@valarnin, sorry to implement a patch that you were in the middle
of, but I wanted to get this in before I didn't have a chance to
test it anymore.)
Closes #2443.
=> raidboss: e12s chiseled sculpture triggers (alternative)

README.md, docs/zh-CN/README.md, ui/jobs/components/drk.js, ui/jobs/constants.js, ui/jobs/jobs.css
- Blood Weapon Duration&Cooldown
- Delirium Duration&Cooldown
- Living Shadow Duration&Cooldown
=> Jobs: DRK improvement

resources/resourcebar.ts
just as others do, for consistency
=> fix: change resourcesbar export as default

resources/resourcebar.ts
just like https://github.com/quisquous/cactbot/pull/2532 of Trim21
=> Fix(resourcebar): getter and setter accept string

resources/resourcebar.ts
Reverts quisquous/cactbot#2628
Sorry, reverting this so that I can revert #2623 cleanly.
=> Revert "Fix: typo 'full' in resourcebar"

ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
=> Raidboss: delubrum reginae Fr

ui/raidboss/data/00-misc/general.js
=> Raidboss: misc general 

ui/raidboss/data/05-shb/eureka/delubrum_reginae.js
Added missing translations and corrections preposition fr
=> Raidboss: DR-nm fr

ui/raidboss/data/05-shb/raid/e12s.js, ui/raidboss/data/05-shb/raid/e4s.js
Improvement for better understanding.
=> raidboss: e12s and e4s fr minor corrections

ui/raidboss/data/05-shb/eureka/delubrum_reginae.js, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
Minors corrections and added missing translations fr.
=> raidboss: Delubrum-nm and savage fr

ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.js, ui/raidboss/data/05-shb/trial/innocence-ex.js, ui/raidboss/data/05-shb/trial/innocence.js
correction fr for a better understanding for rotate.
=> raidboss: Corrections fr for rotate.

ui/raidboss/data/03-hw/raid/a8n.js
=> raidboss a8n fr 

ui/raidboss/data/03-hw/raid/a12s.js, ui/raidboss/data/03-hw/raid/a2s.js, ui/raidboss/data/03-hw/raid/a5s.js, ui/raidboss/data/03-hw/raid/a9s.js
=> raidboss: alex fr

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
=> raidboss: delubrum reginae savage fr

ui/raidboss/data/03-hw/alliance/dun_scaith.js
=> raidboss: dun_scaith fr

ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.js, ui/raidboss/data/05-shb/eureka/bozjan_southern_front.js, ui/raidboss/data/05-shb/raid/e8s.js, ui/raidboss/data/05-shb/trial/ruby_weapon-ex.js
Issues found from converting triggers to TypeScript manually and
running tsc.
Ignoring issues around unused variables or type assertion, or anything
that applies to TypeScript exclusively.
=> raidboss: Logic Error Fixes from TypeScript Compiler

ui/raidboss/data/03-hw/alliance/weeping_city.js
=> raidboss: weeping_city fr

resources/timerbox.ts, ui/jobs/jobs.js
Closes #2614.
This is the same as #2614, except with an additional commit to rename `styleFill` to `stylefill`.
The attribute changed callback only appears to work with lowercase attribute names.
=> Refactor: TypeScript-ize timerbox.js

plugin/CactbotEventSource/FateWatcher.cs
=> Eureka: Update Bozja CE Opcode for v5.5

plugin/CactbotEventSource/FFXIVProcessCn.cs, plugin/CactbotEventSource/FFXIVProcessIntl.cs, plugin/CactbotEventSource/FFXIVProcessKo.cs, ui/jobs/components/ast.js
**BREAKING CHANGES**
This commit should be merged at a patch update,
in order to reduce unavailability.
Fixes #2549
=> Refactor: return steps(DNC), arcanums(AST) as list

ui/raidboss/data/05-shb/trial/diamond_weapon-ex.js, ui/raidboss/data/05-shb/trial/diamond_weapon-ex.txt, ui/raidboss/data/manifest.txt
This PR has an initial timeline for Diamond Weapon Extreme.
I've only done limited testing for this but the fight is fairly static.
As mentioned in Discord, there's a bug in raidemulator which prevents the timeline from syncing. I'll try to track that down and get a PR in for it soon.
=> raidboss: Diamond Weapon Extreme timeline

ui/raidboss/data/05-shb/dungeon/paglthan.js
=> raidboss: palgthan fr

ui/raidboss/data/05-shb/trial/diamond_weapon-ex.js
This is a WIP PR for initial triggers for Diamond Weapon Ex. Upstream branch is in PR #2736 so I'm not sure how exactly that'll work out if this ends up merged first. I can always rebase or close/reopen if merging breaks somewhere.
There are a number of TODOs still that I'm not sure exactly how to handle, and I'm looking for feedback. Also missing translations etc.
=> raidboss: Diamond Weapon Ex triggers

resources/resourcebar.ts, ui/jobs/jobs.js
to be the same as my others PRs doing
=> fix: change getter/setter in resourcebar

ui/raidboss/data/05-shb/trial/diamond_weapon-ex.js
=> raidboss: diamond_weapon-ex FR

ui/raidboss/data/05-shb/dungeon/paglthan.js
=> raidboss: paglthan fr

resources/widget_list.ts, ui/jobs/jobs.js
again
It looks like the element is not removed correctly. So the `_sorted` is getting bigger and bigger. so `_sorted.sort()` will cause leg(in `layout()`).
=> refactor(resources): migrate WidgetList to TypeScript 

ui/raidboss/data/05-shb/trial/diamond_weapon-ex.js
Adding headmarkers for LC/Flood Ray mechanic.
Haven't had a chance to test in-zone but raidemulator testing shows that they're correct over three days of pulls/clears.
=> raidboss: Diamond Ex headmarkers

test/helper/test_timeline.js, test/helper/test_trigger.js, util/translate_timeline.js
Partially reverts https://github.com/quisquous/cactbot/pull/2760
=> test: Remove Posix Relative Path

ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.js
Because the CN server has not been patch 5.5 so I didn't translate the name off Adds, which should be translated when the Chinese players got official translations.
@ShadyWhite review this PR pls, again.
=> Raidboss: add ja/cn translation in the tower

resources/outputs.ts, ui/raidboss/data/02-arr/raid/t11.js, ui/raidboss/data/04-sb/dungeon/ala_mhigo.js, ui/raidboss/data/05-shb/trial/wol.js
Replacement of the common noun by a conjugated verb which gives an order of execution for a better understanding.
=> Out Of: Better translations fr

ui/raidboss/data/04-sb/dungeon/kugane_castle.js, ui/raidboss/data/04-sb/dungeon/st_mocianne_hard.js
=> raidboss: dungeons SB Fr

plugin/CactbotEventSource/FateWatcher.cs
Untested, can verify later once servers are up.
=> plugin: Update Global CE Opcode for 5.5hotfix

resources/weather.ts
Fixes #2806.
This is a fix for #2785.  OOPS.
=> resources: fix getWeather not returning any weather

ui/raidboss/browser_tts_engine.ts
Fixes https://github.com/quisquous/cactbot/issues/2809
=> raidboss: Remove instanceof Check for Browser TTS

ui/raidboss/data/05-shb/raid/e12s.js
Missed a few `matches.effectId.toUpperCase()`
=> raidboss: Fix E12S Basic Relativity Debuffs

ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.js, ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt
=> raidboss: the_tower_at_pardigm_breach fr

resources/user_config.ts, types/data.d.ts, types/event.d.ts
This implements a few things from config that will probably need
to be moved there.
=> resources: convert user_config.js to TypeScript

ui/raidboss/common_replacement.ts
=> raidboss: support netregexes seal lines in common translations

.eslintrc.cjs, .mocharc.cjs
Also, eslint throws an error about dot files being changed but being
ignored, so add an un-ignore to the ignore section.
=> mocha: use less noisy progress reporter

ui/raidboss/timeline.js
Part of the TypeScript conversion for timelines; trying to separate
breaking logic changes.
=> raidboss: Add Strict Undefined Checks for Timeline

ui/jobs/components/drk.js, ui/jobs/constants.ts
So I try to separate the jobs module TypeScript-izing progress.
=> Refactor: TypeScript-ize jobs/constants.ts

ui/jobs/buff_tracker.ts, ui/jobs/types.d.ts
add common types in jobs module
=> Refactor: TypeScript-ize jobs/buff_tracker.ts

ui/jobs/jobs.js, ui/jobs/utils.js
Per comment https://github.com/quisquous/cactbot/pull/2834#discussion_r625482611
and change a little bit in the array initialization, to improve a little bit readability.
=> Refactor: Construct regex with player name

ui/radar/radar.js
Also switch to using exec and some stricter conditionals while here.
=> radar: construct regexes once, and not once per log line

ui/jobs/jobs.js
Like #2778 , this PR change String#match to RegExp#exec, also String#search to RegExp#test.
=> Refactor(jobs): String#match -> RegExp#exec, String#search -> RegExp#test

ui/raidboss/timeline.js
Small subset of refactoring changes for overall TypeScript conversion,
mostly template literals.
=> raidboss: Miscellaneous Timeline Refactoring

plugin/CactbotEventSource/FateWatcher.cs
=> Plugin: Update cedirector_cn for CN 5.41

ui/raidboss/timeline.ts
Refactor Timeline types for brevity.
=> raidboss: Refactor Timeline Types

ui/jobs/components/brd.js, ui/jobs/components/mnk.js, ui/jobs/jobs.js
- Fix bug about BRD repertoireTimer goes empty
- Delete MNK lightningTimer for cn/ko5.4
- <del>Job-specific UI will be reset upon party wipe now. </del>
=> Jobs: Fix BRD, MNK(cn/ko5.4)

ui/jobs/components/ast.js, ui/jobs/components/blm.js, ui/jobs/components/blu.js, ui/jobs/components/brd.js, ui/jobs/components/dnc.js, ui/jobs/components/drg.js, ui/jobs/components/drk.js, ui/jobs/components/gnb.js, ui/jobs/components/index.js, ui/jobs/components/mch.js, ui/jobs/components/mnk.js, ui/jobs/components/nin.js, ui/jobs/components/pld.js, ui/jobs/components/rdm.js, ui/jobs/components/sam.js, ui/jobs/components/sch.js, ui/jobs/components/smn.js, ui/jobs/components/war.js, ui/jobs/components/whm.js, ui/jobs/jobs.js
As discussed in #2871 ,a `reset` function is built to solve this issue.
=> Jobs: Reset job-specific UI

ui/raidboss/data/00-misc/general.js, ui/raidboss/data/00-misc/test.js
Converted via:
find ui/raidboss/data/00-misc/ -type f | xargs -i sed -i 's/function(\(.*\)) {/(\1) => {/' {}
=> raidboss: Apply ESLint prefer-arrow/prefer-arrow-functions to 00-misc

ui/raidboss/data/03-hw/alliance/dun_scaith.js, ui/raidboss/data/03-hw/alliance/weeping_city.js, ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.js, ui/raidboss/data/03-hw/dungeon/fractal_continuum.js, ui/raidboss/data/03-hw/dungeon/gubal_library_hard.js, ui/raidboss/data/03-hw/dungeon/sohm_al_hard.js, ui/raidboss/data/03-hw/dungeon/the_vault.js, ui/raidboss/data/03-hw/raid/a10s.js, ui/raidboss/data/03-hw/raid/a11s.js, ui/raidboss/data/03-hw/raid/a12n.js, ui/raidboss/data/03-hw/raid/a12s.js, ui/raidboss/data/03-hw/raid/a1s.js, ui/raidboss/data/03-hw/raid/a2s.js, ui/raidboss/data/03-hw/raid/a3s.js, ui/raidboss/data/03-hw/raid/a4s.js, ui/raidboss/data/03-hw/raid/a5s.js, ui/raidboss/data/03-hw/raid/a6s.js, ui/raidboss/data/03-hw/raid/a7s.js, ui/raidboss/data/03-hw/raid/a8n.js, ui/raidboss/data/03-hw/raid/a8s.js, ui/raidboss/data/03-hw/raid/a9s.js, ui/raidboss/data/03-hw/trial/sophia-ex.js
Converted via:
find ui/raidboss/data/03-hw/ -type f | xargs -i sed -i 's/function((.*)) {/(\1) => {/' {}
=> raidboss: Apply ESLint prefer-arrow/prefer-arrow-functions to HW
