quisquous/cactbot

plugin/CactbotEventSource/FateWatcher.cs
I'll likely start on adding Zadnor support to the eureka overlay soon. I took a quick look at the network data already.
I also still plan on reworking opcodes so it can be read from a file, removing the need for a re-release every time it changes, it's on my todo list, sorry.
=> plugin: Update intl CE Opcode for 5.55

ui/raidboss/data/04-sb/dungeon/bardams_mettle.js
Had these double-up during my run.
=> raidboss: Suppress Bardam's Mettle Bardam Alerts

ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
Fix #2932
@Trim21 I can't test this right now to make sure it fixes the exact issue you described, but it should. Can you test and verify? Otherwise I can test in about 4 or 5 hours.
=> raidemulator: Fix missing properties on getCombatants response

ui/eureka/eureka.css, ui/eureka/eureka.js
* config option for duels now plays only on CEs before duels
* different coloring for duel CEs
* cooldown timer for duels (and Castrum/Dalraida) shown on map
This should help some for folks chasing duels.
=> eureka: improve duel support

.github/scripts/auto-label.cjs, .github/workflows/labels.yaml, package-lock.json, package.json
=> ci: auto label PR

plugin/CactbotEventSource/FateWatcher.cs
Tested working.
I still plan on changing how these are loaded so you don't need to re-release every time. I apologise for any hassle regarding it.
=> plugin: update CE opcode for 5.55 hotfix

resources/timerbox.ts
Fix an issue that proc-tracking boxes do not go small when no proc.
=> Jobs: Fix bigatzero=false doesn't work

ui/raidboss/data/05-shb/eureka/zadnor.js
* second phase phenex / time eruption
* fix double spread call on pyrocrisis
=> raidboss: small Zadnor Sartauvoir improvements

docs/CactbotCustomization.md, docs/OopsyraidsyGuide.md, docs/RaidbossGuide.md, docs/ko-KR/CactbotCustomization.md, docs/zh-CN/CactbotCustomization.md, docs/zh-CN/RaidbossGuide.md, docs/zh-TW/CactbotCustomization.md
Since these files are already TypeScript
=> doc: update name/link to *.ts

docs/zh-CN/README.md
Co-authored-by: ShadyWhite <44015352+ShadyWhite@users.noreply.github.com>
=> doc: update zh-CN/README.md

.eslintrc.cjs, resources/netregexes.ts, util/find_missing_translations.js
Mentioned this in a comment in #3007
=> lint: Enable prefer-regex-literals

ui/raidboss/emulator/data/CombatantTracker.js, ui/raidboss/emulator/data/Encounter.js, ui/raidboss/emulator/data/Persistor.js, ui/raidboss/emulator/data/network_log_converter/LineEvent.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x17.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x1B.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x22.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x25.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x27.ts
Second PR requested from #2936
=> raidemulator: Refactor LineEvent properties to be normalized/consistent

ui/raidboss/popup-text.js, ui/raidboss/raidboss_options.ts
=> Add option to transform TTS output.

.eslintrc.cjs, resources/overlay_plugin_api.ts, resources/party.ts, resources/player_override.ts, ui/raidboss/emulator/EventBus.ts
=> lint: add @typescript-eslint/object-curly-spacing

.eslintrc.cjs, resources/responses.ts, types/trigger.d.ts, ui/raidboss/data/02-arr/raid/t1.ts, ui/raidboss/data/02-arr/trial/titan-ex.ts, ui/raidboss/data/raidboss_manifest.txt, ui/raidboss/timeline.ts, util/process_triggers_folder.ts
This is mostly just trying to put together some thoughts of what this might look like.  Feedback super welcome.
=> raidboss: Add TriggerSet types; convert some initial triggers

ui/raidboss/data/03-hw/alliance/dun_scaith.js
=> raidboss: Fix issue with Dun Scaith Ferdiad Hollow trigger

plugin/CactbotEventSource/FateWatcher.cs
=> Plugin: Update cedirector_cn for CN 5.45

resources/player_override.ts, tsconfig.base.json, ui/raidboss/browser_tts_engine.ts, ui/raidboss/common_replacement.ts, ui/raidboss/emulator/EmulatorCommon.ts, ui/raidboss/emulator/data/CombatantTracker.ts, ui/raidboss/raidboss_options.ts, ui/raidboss/timeline.ts, util/translate_timeline.ts
In regards to #3039.
Probably someone should review to make sure this fully forces relative paths, and should test it in an overlay to make sure it still works as expected.
=> Remove baseUrl definition from tsconfig

ui/raidboss/data/05-shb/raid/e11s.js
TTS is too long to remember or hear
I think just telling which elemental of cycle is good.
* I don't know Chinese and don't have client data, so I just left Chinese the same as before.
=> raidboss: add e11s cycle of faith TTS

ui/raidboss/data/05-shb/raid/e10s.js, ui/raidboss/data/05-shb/raid/e8s.js
As mentioned in https://github.com/quisquous/cactbot/pull/3064#discussion_r650472109
=> raidboss: Fix some trigger properties returning string when they should return float

ui/eureka/eureka.js
tested and ©works on my machine
=> French translation for Zadnor NMs

ui/raidboss/popup-text.ts, ui/raidboss/timeline.ts
Fixes #3075.
I didn't see anything to test with in existing timelines, but this doesn't impact normal raidboss use.
=> raidboss: Refactor PopupTextGenerator to pass timeline time

ui/jobs/components/drk.ts, webpack/webpack.config.cjs
Fixes #3087 
In fact, the bug likely occurred before #3001 though
=> fix(jobs): darkside proc box not working

ui/raidboss/popup-text.ts
=> fix config outputString

ui/raidboss/popup-text.ts
=> raidboss: Fix timeline triggers getting added to triggers and netTriggers

docs/RaidbossGuide.md, types/trigger.d.ts, ui/raidboss/data/02-arr/raid/t1.ts, ui/raidboss/popup-text.ts
Closes #3071 as long as this implementation is what you're looking for.
I can track down a trigger set that would benefit from this and convert as part of this PR as well, if that's something you'd want?
=> raidboss: Add option for trigger sets to initialize data object

types/trigger.d.ts
=> raidboss: extend OutputStrings to allow for string entries

ui/raidboss/popup-text.ts
User trigger may pass anything as parameters    
So type `
params` as `{ [key: string]: unknown }`
=> popup-text replacement should be `unknown`

ui/raidboss/emulator/data/AnalyzedEncounter.js, ui/raidboss/emulator/data/PopupTextAnalysis.ts
This fixes timeline triggers in raidemulator, which were broken in #3084.
As pointed out in #3126
=> raidemulator: Fix timeline triggers

ui/raidboss/popup-text.ts
=> raidboss: Fix tts issues re: #3136

ui/raidboss/raidemulator.js
This removes a bunch of `let`s, an IIFE, and turns a `.then` into an `await`.
=> raidemulator: refactor raidemulator.js initialization

ui/jobs/jobs_config.ts
I think more people want this than not, and those that don't can turn it
off in the options.
=> jobs: turn on notifications by default

ui/jobs/jobs_config.ts
Translation of cn&ja for new feature recently added to Jobs module.
=> i18n(Jobs): New option translation for cn&ja

util/csv_util.ts
which can be used by other gen_* files.
=> refactor(util): extract csvReader as a new func

plugin/CactbotEventSource/FateWatcher.cs
Tested and verified working in-game.
Work on loading opcodes from a remote .json is currently in progress!
=> plugin: update CE opcode for 5.57

ui/raidboss/raidboss_config.js
=> i18n: add new config ja/cn/ko translation

ui/eureka/eureka.js, ui/eureka/eureka_config.ts, ui/jobs/jobs_config.ts
This PR fixes something that is almost a bug.
=> i18n(eureka, jobs): Fix multi-language support on eureka, small translation for jobs Korean

ui/config/config.js, ui/eureka/eureka.js, ui/eureka/eureka_config.ts
- Category `Eureka` has been renamed to `Adventuring Forays` in Party Finder.
- Add Translation new feature about field note and short name.
- Fix some translation mistakes.
=> i18n(eureka): Translation for new feature

util/coverage/coverage.css, util/coverage/coverage.html, util/coverage/coverage.js
=> coverage: add description about release and latest version differencences

ui/config/config.js, util/coverage/coverage.js
=> coverage: fix description text

ui/raidboss/emulator/data/AnalyzedEncounter.ts, ui/raidboss/emulator/data/PopupTextAnalysis.ts, ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
=> raidemulator: Bug fixes

ui/raidboss/data/02-arr/raid/t8.ts
Cleaning up unnecessary code with recent changes.
=> raidboss: Minor T10 TypeScript Revisions

util/find_missing_translations.js
This should fix #3192, can you confirm @MaikoTan?
=> util: Fix linux paths in find_missing_translations.js tool

types/trigger.d.ts
close: #3188
tsc is happy with the example in that PR and my user conf files.
@panicstevenson can you test it with your TS trigger?
I have test it with this example: https://gist.github.com/Trim21/8ed357968b6d8be416b3f2a197dba2fe
hope this contains all condition
(and indent and formatting problems are driving me crazy, why some part of this file is indented with 4 spaces? we should just add prettier with typescript......)
=> fix: trigger `response` type

ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/raidboss_manifest.txt
There was for some strange reason a local version of `ShortName` here which I also cleaned up since it seemed kind of pointless?
=> raidboss: Convert test triggerset to typescript

.github/scripts/auto-label.cjs
See:
https://github.com/quisquous/cactbot/runs/2923687004?check_suite_focus=true
=> ci: fix auto-label on pure renames

ui/jobs/jobs.js
=> jobs: prevent notifications if only buffs are shown

ui/jobs/jobs.js, ui/jobs/utils.ts
Also fix a bug that skill/spell speed obtain failed.
=> refactor(jobs): convert regex using to netregex

resources/user_config.ts
=> fix(config): display English when display language set to default

resources/overlay_plugin_api.ts, resources/timerbox.ts, ui/fisher/fisher-ui.js, ui/jobs/buff_tracker.ts, ui/jobs/components/dnc.js, ui/jobs/components/drg.js, ui/jobs/components/drk.ts, ui/jobs/components/gnb.ts, ui/jobs/components/mch.js, ui/jobs/components/nin.js, ui/jobs/jobs.js, ui/oopsyraidsy/oopsy_live_list.ts
For
1) get the correct return type
2) this should be run in browser
3) differentiate with user-defined functions (although there isn't corrently)
=> refactor: prefix setTimeout with window global

04-sb/dungeon/drowned_city_of_skalla.js
Reverts quisquous/cactbot#3273
=> Revert "Update drowned_city_of_skalla.js"

ui/oopsyraidsy/damage_tracker.js, ui/oopsyraidsy/oopsyraidsy.js
This is a breaking change to user triggers.
=> oopsy: remove all non-netRegex trigger types

plugin/CactbotEventSource/CactbotEventSource.cs, plugin/CactbotEventSource/CactbotEventSource.csproj, plugin/CactbotEventSource/loc/Strings.zh.resx, plugin/CactbotOverlay/CactbotOverlay.csproj, plugin/CactbotOverlay/loc/Strings.zh.resx
=> i18n(plugin): add Chinese translations

package-lock.json, package.json, webpack/webpack.config.ts
by adding fork-ts-checker-webpack-plugin
Before:
real    1m28.067s
user    1m9.672s
sys     0m8.042s
After:
real    0m47.489s
user    1m7.175s
sys     0m6.496s
-------
EDIT: Found that remove progress plugin make it faster
real    0m8.470s
user    0m5.978s
sys     0m0.987s
=> build: accelarate typescript build

.eslintrc.cjs, webpack/loaders/manifest-loader.ts, webpack/loaders/timeline-loader.ts, webpack/webpack.config.ts
@Trim21 Miss Auto-Label didn't tag it as `build`?
=> build: convert custom loader to TS

resources/timerbox.ts
=> fix(resources): hideafter typo in timerbox.ts

plugin/CactbotEventSource/FFXIVProcessCn.cs, plugin/CactbotEventSource/FFXIVProcessIntl.cs, plugin/CactbotEventSource/FFXIVProcessKo.cs, types/event.d.ts, ui/jobs/components/mnk.js, ui/jobs/jobs.css, ui/test/test.ts
Mentioned in #3311 
Because there is no code using greased lightning stack except `ui/test/test.html` which would report `undefined`, so I think it is ok to merge right now.
Looks like the offset of `chakra` comes to `0x00`, I have tested in `test.html` and it worked.
=> refactor: remove all PGL/MNK lightning related code

ui/raidboss/data/05-shb/eureka/bozjan_southern_front.ts
=> raidboss: fix Adrammelech single orb bug

ui/jobs/jobs.js, ui/jobs/jobs_options.ts
This is a partial refactoring of #3293
=> jobs: extract options to new file

.github/scripts/lint-pr-title.cjs, .github/workflows/lint-pr-title.yaml
Mentioned in #3122 and inspired by #2967
=> ci: add PR title linting

.github/scripts/lint-pr-title.cjs
Also, rename "non-scope" to "prefix" for clarity in English.
Also also, add debugging logic so it's easier to tell from the github
workflow what went wrong.
=> ci: fix regex bugs in PR title workflow

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.ts
Fixes #3339.
Also broken in #3282, sorry!
=> raidboss: fix DRS sword brand direction

ui/raidboss/data/04-sb/raid/o3n.txt, ui/raidboss/data/04-sb/raid/o4n.txt, ui/raidboss/data/04-sb/raid/o9n.txt
Figured I might as well complete the set.
=> raidboss: Add targetability lines to Omega normal

ui/raidboss/popup-text.ts
Fixes #3399
This was caused by #3081
=> raidboss: Fix issue with initial timeline load + user config

ui/raidboss/raidboss_alerts_only.html, ui/raidboss/raidboss_timeline_only.html
=> raidboss: Fix *_only.html pages to also include OVERLAY_WS

docs/TimelineGuide.md, docs/zh-CN/TimelineGuide.md
@ShadyWhite @Echoring 同じく check してください
=> docs: add cn translate of timrline guide

plugin/CactbotEventSource/FateWatcher.cs, ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts, ui/raidboss/data/05-shb/dungeon/paglthan.ts, ui/raidboss/data/05-shb/trial/diamond_weapon-ex.ts, ui/raidboss/data/05-shb/trial/diamond_weapon.ts
and... I didn't solved the python error, please someone run it please. 😅
=> i18n: update 5.5 KR translations + CE opcode

resources/translations.ts, ui/jobs/jobs.js, ui/jobs/utils.ts
Also convert massive "if-else" to "switch-case" for readability.
This PR should improve the performance a bit?
=> jobs: reduce regex matching via logDefinition

ui/oopsyraidsy/oopsyraidsy_config.js
Hello, I haven't disappeared, but my life has been complicated for a while.
=> oopsy/config: add translation fr

ui/oopsyraidsy/oopsyraidsy_config.js
Co-Authored-By: 迷子 (Maiko Tan) <19927330+MaikoTan@users.noreply.github.com>
=> oopsy: config cn/ja

ui/raidboss/emulator/translations.ts
Per #3506 
And ShadyWhite said the current Chinese translation is okay.
=> i18n: fix ja translations of "Collectors"

ui/raidboss/data/04-sb/trial/shinryu-ex.ts, ui/raidboss/data/04-sb/trial/shinryu-ex.txt
=> raidboss: improve shinryu extreme timeline

resources/party.ts, resources/player_override.ts, resources/user_config.ts, resources/util.ts, test/unittests/util_test.js, ui/dps/dps_common.js, ui/jobs/jobs.ts, ui/jobs/utils.ts, ui/oopsyraidsy/damage_tracker.ts, ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/02-arr/raid/t11.ts, ui/raidboss/data/02-arr/raid/t5.ts, ui/raidboss/data/02-arr/raid/t6.ts, ui/raidboss/data/02-arr/raid/t7.ts, ui/raidboss/data/02-arr/raid/t9.ts, ui/raidboss/data/02-arr/trial/levi-ex.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts, ui/raidboss/data/05-shb/raid/e10s.ts, ui/raidboss/data/05-shb/trial/levi-un.ts, ui/raidboss/emulator/data/AnalyzedEncounter.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts, ui/raidboss/emulator/ui/EmulatedPartyInfo.ts, ui/raidboss/popup-text.ts
But change to export an object expression
instead of a const global variable
=> resources: revert resources/util.ts default export

resources/party.ts, resources/player_override.ts, resources/user_config.ts, resources/util.ts, test/unittests/util_test.js, ui/dps/dps_common.js, ui/jobs/jobs.ts, ui/jobs/utils.ts, ui/oopsyraidsy/damage_tracker.ts, ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/02-arr/raid/t11.ts, ui/raidboss/data/02-arr/raid/t5.ts, ui/raidboss/data/02-arr/raid/t6.ts, ui/raidboss/data/02-arr/raid/t7.ts, ui/raidboss/data/02-arr/raid/t9.ts, ui/raidboss/data/02-arr/trial/levi-ex.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts, ui/raidboss/data/05-shb/raid/e10s.ts, ui/raidboss/data/05-shb/trial/levi-un.ts, ui/raidboss/emulator/data/AnalyzedEncounter.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts, ui/raidboss/emulator/ui/EmulatedPartyInfo.ts, ui/raidboss/popup-text.ts
Reverts quisquous/cactbot#3593
raidboss_config.js wasn't updated and so webpack no longer starts.  I'm going to do a clean revert of the previous patch.
=> Revert "resources: revert resources/util.ts default export"

resources/party.ts, resources/player_override.ts, resources/user_config.ts, resources/util.ts, test/unittests/util_test.js, ui/dps/dps_common.js, ui/jobs/jobs.ts, ui/jobs/utils.ts, ui/oopsyraidsy/damage_tracker.ts, ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/02-arr/raid/t11.ts, ui/raidboss/data/02-arr/raid/t5.ts, ui/raidboss/data/02-arr/raid/t6.ts, ui/raidboss/data/02-arr/raid/t7.ts, ui/raidboss/data/02-arr/raid/t9.ts, ui/raidboss/data/02-arr/trial/levi-ex.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts, ui/raidboss/data/05-shb/raid/e10s.ts, ui/raidboss/data/05-shb/trial/levi-un.ts, ui/raidboss/emulator/data/AnalyzedEncounter.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts, ui/raidboss/emulator/ui/EmulatedPartyInfo.ts, ui/raidboss/popup-text.ts, ui/raidboss/raidboss_config.js
This reverts commit b3a89f5e6ff6b3f22fa4eebed717596eae29305e.
=> resources: Revert #3465 change export type util.ts

test/helper/test_timeline.js, types/trigger.d.ts, ui/raidboss/emulator/overrides/RaidEmulatorAnalysisTimelineUI.ts, ui/raidboss/emulator/overrides/RaidEmulatorTimeline.ts, ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.ts, ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.ts, ui/raidboss/popup-text.ts, ui/raidboss/timeline.ts, ui/raidboss/timeline_parser.ts, util/find_missing_timeline_translations.js, util/translate_timeline.ts
=> raidboss: separate timeline parser

ui/fisher/fisher.js
Fixes #3598.
PR #3542 changed fisher to using net log lines.  The previously existing
snag and chum log lines did not appear to exist at all and so that PR
switched to gains effect lines, but didn't limit them to the current
player (oops).  This caused fisher to blank out if anybody nearby used
chum.
=> fisher: only handle your own snag/chum messages

ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts
=> raidboss: fix ucob nael dive callouts

ui/oopsyraidsy/oopsyraidsy_config.js
=> i18n: fix oopsy config kr translation

.vscode/settings.json, types/event.d.ts, types/manifest.d.ts, types/net_matches.d.ts, types/net_trigger.d.ts, types/oopsy.d.ts, types/trigger.d.ts, ui/raidboss/emulator/data/PopupTextAnalysis.ts, ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts, ui/raidboss/emulator/overrides/StubbedPopupText.ts, ui/raidboss/popup-text.ts, ui/raidboss/timeline.ts
Reverts quisquous/cactbot#3613
Breaks `npm run process-triggers` and the triggers branch.
=> build: Revert fix skipLibCheck type errors

ui/raidboss/data/05-shb/raid/e8n.ts
Just a drive-by addition based on getting it in duty roulette and noticing this was missing.
=> raidboss: E8n--add Diamond Frost AoE warning

resources/outputs.ts
One string missing and several fixes
=> resources: FR fixes

ui/config/config.js, ui/oopsyraidsy/oopsyraidsy_config.js, ui/raidboss/raidboss_config.js
This will make it easier to add the right types and make the
parameters required.
=> config: change param types of getOption/setOption

tsconfig-for-webpack.json
There is an un-printable `\u200b` at the end of line.
make this file unable to parse as json.
=> build: remove a un-printable charactor

ui/raidboss/data/03-hw/alliance/dun_scaith.txt, ui/raidboss/data/03-hw/alliance/weeping_city.txt, ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt, ui/raidboss/data/03-hw/dungeon/baelsars_wall.txt, ui/raidboss/data/03-hw/dungeon/fractal_continuum.txt, ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt, ui/raidboss/data/03-hw/dungeon/sohm_al.txt, ui/raidboss/data/03-hw/dungeon/sohm_al_hard.txt, ui/raidboss/data/03-hw/dungeon/the_vault.txt, ui/raidboss/data/03-hw/dungeon/xelphatol.txt, ui/raidboss/data/03-hw/raid/a10s.txt, ui/raidboss/data/03-hw/raid/a11s.txt, ui/raidboss/data/03-hw/raid/a12n.txt, ui/raidboss/data/03-hw/raid/a12s.txt, ui/raidboss/data/03-hw/raid/a1s.txt, ui/raidboss/data/03-hw/raid/a2s.txt, ui/raidboss/data/03-hw/raid/a3s.txt, ui/raidboss/data/03-hw/raid/a4s.txt, ui/raidboss/data/03-hw/raid/a5s.txt, ui/raidboss/data/03-hw/raid/a6n.txt, ui/raidboss/data/03-hw/raid/a6s.txt, ui/raidboss/data/03-hw/raid/a7s.txt, ui/raidboss/data/03-hw/raid/a8n.txt, ui/raidboss/data/03-hw/raid/a8s.txt, ui/raidboss/data/03-hw/raid/a9s.txt, ui/raidboss/data/03-hw/trial/ravana-ex.txt, ui/raidboss/data/03-hw/trial/sephirot-ex.txt, ui/raidboss/data/03-hw/trial/sophia-ex.txt
(Re-doing this one since I initially checked out `main` instead of `alpha_plugin`, and fixing it "correctly" is rather too much effort for now.)
As with the other timeline conversion PRs, we'll have to update the tests before landing this.
Manual fixes to be added:
```
gubal_library_hard
a11s
a3s
a7s
{
gubal_library_hard: [
'1100.0 "--sync--" sync /00:....:The liquid flame gains the effect of Chirom
orph/ window 100,250',
'1200.0 "--sync--" sync /00:....:The liquid flame gains the effect of Anemom
orph/ window 200,0',
'1300.0 "--sync--" sync /00:....:The liquid flame gains the effect of Anthro
pomorph/ window 300,10'
],
a11s: [
'45.8 "E.D.D. Add" sync / 03:........:Added new combatant E\\.D\\.D\\./ wind
ow 50,5',
'458.7 "E.D.D. Add" sync / 03:........:Added new combatant E\\.D\\.D\\./', …
```
=> raidboss: Automated alpha conversion of HW timelines

resources/defaults.css
=> i18n: remove CN remote font

ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts
Reverts quisquous/cactbot#3605
=> raidboss: revert: add trigger for Bloody Sweep

ui/raidboss/data/02-arr/raid/t7.txt, ui/raidboss/data/02-arr/raid/t9.txt, ui/raidboss/data/02-arr/trial/titan-nm.txt, ui/raidboss/data/03-hw/raid/a11s.txt, ui/raidboss/data/03-hw/raid/a3s.txt, ui/raidboss/data/03-hw/raid/a7s.txt, ui/raidboss/data/04-sb/alliance/ridorana_lighthouse.txt, ui/raidboss/data/04-sb/dungeon/swallows_compass.txt, ui/raidboss/data/04-sb/raid/o11n.txt, ui/raidboss/data/04-sb/raid/o12n.ts, ui/raidboss/data/04-sb/raid/o12n.txt, ui/raidboss/data/04-sb/raid/o5s.txt, ui/raidboss/data/04-sb/raid/o7n.txt, ui/raidboss/data/04-sb/raid/o7s.txt, ui/raidboss/data/04-sb/raid/o8s.txt, ui/raidboss/data/04-sb/raid/o9n.txt, ui/raidboss/data/04-sb/trial/seiryu-ex.txt, ui/raidboss/data/04-sb/trial/tsukuyomi-ex.txt, ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt, ui/raidboss/data/05-shb/trial/hades.txt, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.txt
Currently the following items are outstanding:
```
gubal_library_hard: [
'1100.0 "--sync--" sync /00:....:The liquid flame gains the effect of Chirom
orph/ window 100,250',
'1200.0 "--sync--" sync /00:....:The liquid flame gains the effect of Anemom
orph/ window 200,0',
'1300.0 "--sync--" sync /00:....:The liquid flame gains the effect of Anthro
pomorph/ window 300,10'
],
eureka_hydatos: [
'0 "--Reset--" sync /04:........:Removing combatant Proto Ozma\\.  Max HP: \
\d{8}\\./ window 10000 jump 0',
'1002.5 "--sync--" sync / 15:........:Art:3956:[^:]*:........:[^:]/ window 1
500,0',
'2002.5 "--sync--" sync / 15:........:Owain:3957:[^:]*:........:[^:]/ window
2500,0',
'3154.9 "--sync--" sync / 17:........:Raiden:3878:/ window 40,0',
'3341.7 "--sync--" sync / 17:........:Raiden:3878:/ window …
```
=> raidboss: alpha 6.0 manual timeline fixes

resources/util.ts, types/job.d.ts, ui/jobs/components/index.ts, ui/jobs/components/rpr.ts, ui/jobs/components/sge.ts
I don't know what the actual enum values are, but I just wanted to see what was needed typescript-wise to add a new job.
=> resources/jobs: add new EW job enums

plugin/CactbotEventSource/FFXIVProcess.cs, plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/test/test.ts
I am not very sure if it is correct because I don't know C# and memory things, but it works well on my side.
=> plugin: add sage job detail

ui/raidboss/data/06-ew/dungeon/the_tower_of_zot.ts, ui/raidboss/data/raidboss_manifest.txt
Haven't tested, WIP, etc etc. Just putting it out there to make sure directory structure lines up with what's expected.
=> raidboss: Add some basic Tower of Zot triggers

plugin/CactbotEventSource/FateWatcher.cs
Thanks to @ngld for most of these fixes.
Sorry for the headaches, let me know if there's any way to improve this.
=> plugin: support for type rename in FFXIV_ACT_Plugin 2.6.2.0

plugin/CactbotEventSource/FateWatcher.cs
Quick test shows it's working in-game.
=> plugin: Update CE Opcode for v6.0

ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.ts, ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.txt, ui/raidboss/data/raidboss_manifest.txt
Untested in game, successfully survived More Than One pass through `test_timeline`.
=> raidboss: Tower of Babil initial timeline

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/jobs/components/index.ts, ui/jobs/components/smn.ts, ui/jobs/constants.ts, ui/test/test.ts
Still no idea what is 0x04-0x05 is.
But seems like that we need is already here?
=> plugin: renew 6.0 summoner job detail

ui/raidboss/data/06-ew/dungeon/ktisis_hyperboreia.ts, ui/raidboss/data/06-ew/dungeon/ktisis_hyperboreia.txt, ui/raidboss/data/raidboss_manifest.txt
Complete so far as we know, survives `test_timeline` with More Than One log, but untested in-game etc.
=> raidboss: Ktisis Hyperboreia initial timeline

ui/raidboss/data/06-ew/dungeon/the_tower_of_zot.ts
=> raidboss: the_tower_of_zot Fr

docs/LogGuide.md, resources/regexes.ts, util/gen_log_guide.ts
* tether regexes were using network6d (thanks, Aho!)
* tether heading had wrong hex id
* capitalize hex ids in parsed Regexes
Fixes #3743.
=> docs: fix several log guide issues

ui/raidboss/data/06-ew/dungeon/vanaspati.ts
=> i18n: ew-vanaspati Fr

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/test/test.ts
learnt the new method from the Dalamud project.
Didn't test 'cause in hotfixes maintainance, I'll test it tonight.
=> plugin: update RDM/BRD job details

ui/raidboss/data/06-ew/trial/zodiark.ts
=> i18n: ew zodiark-Fr

ui/raidboss/data/06-ew/dungeon/vanaspati.ts
=> raidboss: fix Vanaspati Last Gasp trigger

ui/raidboss/data/06-ew/trial/endsinger.ts, ui/raidboss/data/06-ew/trial/endsinger.txt, ui/raidboss/data/raidboss_manifest.txt
Triggers need more testing by someone other than me. There's probably issues with the `Doomed Stars` and `Epigonoi` triggers still.
Timeline is really basic and the loops for add phase and final phase aren't working, I'm probably doing something wrong there.
=> raidboss: Initial triggers and timeline for EW final trial

ui/raidboss/data/06-ew/dungeon/the_tower_of_zot.ts
=> i18n:  ew the_tower_of_zot Fr

ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.ts, ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.txt
Tested in-game with complete success. The remaining TODOs shouldn't be *that* hard, but I can't math this weekend.
=> raidboss: Tower of Babil triggers

plugin/CactbotEventSource/FFXIVProcessCn.cs, plugin/CactbotEventSource/FFXIVProcessIntl.cs, plugin/CactbotEventSource/FFXIVProcessKo.cs, types/event.d.ts, ui/jobs/components/blm.ts, ui/test/test.ts
Changed `foulCount` to `polyglot` for more accurate name.
=> jobs: add blm paradox in job detail

ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
=> raidboss: fix crystallize+aureole in 2nd EW extreme

ui/jobs/components/war.ts
#3774 forgot those regions still in ShB.
=> jobs: WAR: Re-support ShB

ui/jobs/components/gnb.ts
After level 88 max cartridges is raised to 3
Also change code order to makes box order same as before #3818
=> jobs: GNB: update cartridges guage

ui/jobs/components/mnk.ts
Twin Snakes has been made a new effect.
=> jobs: MNK: support Disciplined Fist

ui/jobs/components/nin.ts
Seems they have been broken for a long time for the change of #3545
=> jobs: NIN: Fix huton and ninjutsu

ui/jobs/components/brd.ts, ui/jobs/constants.ts
Fixes #3827 , DoT time 45s now
Straight Shot Proc time 30s now
Fix broken song box due to change of #3545
Refactor repertoire timer, for in EW it no longer rely on DoT.
Also change code order to makes box order same as before #3818
=> jobs: BRD: EW changes

ui/jobs/combo_tracker.ts, ui/jobs/components/base.ts, ui/jobs/components/dnc.ts, ui/jobs/components/drk.ts, ui/jobs/components/gnb.ts, ui/jobs/components/mch.ts, ui/jobs/components/nin.ts, ui/jobs/components/sam.ts, ui/jobs/components/war.ts, ui/jobs/constants.ts, ui/jobs/player.ts
Also fix a bug that combo timer would just stop after 15 seconds, because there is a `setTimeout` called with the old 15000ms.
=> jobs: refactor combo tracker as an event emitter

ui/jobs/components/blm.ts
Several Thunder DoT duration has been adjusted.
Also change code order to makes box order same as before #3818
=> jobs: BLM: update thunder dot duration

ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
=> raidboss: fix 2nd EW extreme Crystallize->Beacon->Aureole

ui/jobs/jobs.css
=> jobs: fix only buff option not hide procs

ui/raidboss/data/06-ew/dungeon/stigma_dreamscape.ts
Don't cross-pollinate Oopsy data while working on triggers!
=> raidboss: Correct Dreamscape second boss buster ID

ui/jobs/components/dnc.ts
#3741 forgot those still in 5.x and those below level 86.
Re-support ShB DNC, and better support EW DNC below lv86.
=> jobs: Flourish timer fix and re-support ShB

ui/raidboss/data/06-ew/trial/endsinger.ts
=> i18n: endsinger Fr

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update CE opcode for 6.01

ui/raidboss/data/06-ew/raid/p1n.ts, ui/raidboss/data/raidboss_manifest.txt
This adds triggers for the new pandæmonium raid's first boss.
=> raidboss: Add p1n triggers

resources/effect_id.ts, ui/jobs/components/sge.ts, util/gen_effect_id.ts
Fixes #3905
untested for SGE level not enough, but I think it will work.
=> jobs: SGE: Fix Eukrasian Dosis III

ui/raidboss/data/06-ew/raid/p2n.ts, ui/raidboss/data/raidboss_manifest.txt
Adds triggers for the second pandæmonium normal boss.
=> raidboss: p2n trigger

ui/raidboss/data/06-ew/raid/p3n.ts, ui/raidboss/data/raidboss_manifest.txt
Adds triggers for p3n.
These are tested and correct as far as I'm concerned.
=> raidboss: p3n trigger

ui/raidboss/data/06-ew/raid/p4n.ts, ui/raidboss/data/raidboss_manifest.txt
Adds triggers for pandämonium's 4th boss.
The overwhelming part was done by @xziino this time I'm basically just submitting this because we worked on my repo and because of a little git illiteracy.
As usual we stand ready to fix stuff o7
=> raidboss: p4n trigger

ui/jobs/components/ast.ts, ui/jobs/components/blm.ts, ui/jobs/components/blu.ts, ui/jobs/components/brd.ts, ui/jobs/components/dnc.ts, ui/jobs/components/drg.ts, ui/jobs/components/drk.ts, ui/jobs/components/gnb.ts, ui/jobs/components/mch.ts, ui/jobs/components/mnk.ts, ui/jobs/components/nin.ts, ui/jobs/components/pld.ts, ui/jobs/components/rdm.ts, ui/jobs/components/sam.ts, ui/jobs/components/sch.ts, ui/jobs/components/sge.ts, ui/jobs/components/smn.ts, ui/jobs/components/war.ts, ui/jobs/components/whm.ts
According to @Echoring , components should reset when it is initialized.
Otherwise, some variable is not valid value.
=> jobs: fix component should reset on init

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/test/test.ts
Fix error `nextSummoned` due to wrong condition.
Also fix a type error in `activePrimal`.
=> plugin: fix SMN job detail

ui/raidboss/data/06-ew/hunts/elpis.ts, ui/raidboss/data/06-ew/hunts/garlemald.ts, ui/raidboss/data/06-ew/hunts/labyrinthos.ts, ui/raidboss/data/06-ew/hunts/mare_lamentorum.ts, ui/raidboss/data/06-ew/hunts/thavnair.ts, ui/raidboss/data/06-ew/hunts/ultima_thule.ts, ui/raidboss/data/raidboss_manifest.txt
I was doing enough hunt trains for materia that I wrote these while waiting for congestion.
=> raidboss: add A rank EW hunt triggers

plugin/CactbotEventSource/FFXIVProcessIntl.cs, ui/test/test.ts
Fix error `activePrimal` due to wrong condition.
Also remove an unnecessary [] in test module.
=> plugin: fix more SMN job detail

ui/jobs/components/smn.ts, ui/jobs/constants.ts, ui/jobs/jobs.css
based on #3935
- Summon Guage
Show summon time/attunement time if there is. Color refers to next/now demi-summon or actived primal.
- Aetherflow Guage
- Arcanum and Attunement Guage
Show usable Arcanum and availble Attunement(include those stored in Arcanum).
- Energy Drain Timer
- Summon Timer
Color varies with next demi-summon. Threshold varies with usable Arcanum number(When this box goes big, you should use a wasty way pouring out your Arcanum to avoid delay of the coming demi-summon).
- Lucid Dream Timer
=> jobs: SMN: EW UI

ui/jobs/components/smn.ts, ui/jobs/constants.ts
Support Aethercharge and Dreadwyrm Trance for leveling.
=> jobs: SMN: Support low level

ui/oopsyraidsy/data/06-ew/raid/p1n.ts, ui/oopsyraidsy/data/06-ew/raid/p4n.ts, ui/raidboss/data/06-ew/raid/p2n.ts
=> i18n: update EW KR translations

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/test/test.ts
@Echoring might do the UI part.
Oh, and 🎉 HAPPY NEW YEAR!! 🎉
=> plugin: add reaper job details

plugin/CactbotEventSource/CactbotEventSource.cs, plugin/CactbotEventSource/FFXIVPlugin.cs, plugin/CactbotEventSource/FFXIVProcess.cs, plugin/CactbotEventSource/loc/Strings.Designer.cs, plugin/CactbotEventSource/loc/Strings.resx, util/DEPS.json5
=> plugin: use process id from FFXIV ACT Plugin

ui/dps/rdmty/dps.css
Added the colors for SGE and RPR from those used by FFLogs.
Resolves #3959
=> dps: update rdmty bar color for SGE and RPR from FFLogs

ui/raidboss/data/06-ew/hunts/elpis.ts, ui/raidboss/data/06-ew/hunts/garlemald.ts, ui/raidboss/data/06-ew/hunts/labyrinthos.ts, ui/raidboss/data/06-ew/hunts/mare_lamentorum.ts, ui/raidboss/data/06-ew/hunts/thavnair.ts, ui/raidboss/data/06-ew/hunts/ultima_thule.ts
@mooondark sur le fichier thavnair, je ne sais pas comment traduire. Je veux bien un coup de main. Merci à toi.
=> i18n: Ew hunt francais

ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.txt
When I generated this timeline, every single one of the 15+ attempts I did had Scrapline first. Naturally it was only this week that I saw the other possibility. (Quisquous had sent me an example a while ago, but I forgot about it when I was finishing stuff up.)
Tested against More Than One log, but not in-game due to maintenance.
=> raidboss: Tower of Babil--Add Barnabas timeline fork

ui/raidboss/data/06-ew/raid/p4n.ts
Fix : Change FR from "Take your role tower" to "Take another role tower".
=> i18n: fix p4n wrong FR meaning

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update intl bozja CE opcode for 6.05

ui/raidboss/data/06-ew/raid/p1s.ts
Add callouts for Fourfold Shackles and Shackles of Time.
=> raidboss: P1S Add Shackle Callouts

ui/raidboss/data/06-ew/raid/p4s.ts, ui/raidboss/data/06-ew/raid/p4s.txt, ui/raidboss/data/raidboss_manifest.txt
This is the timeline portion from #3997.
Co-authored-by: Legends0 <nac10fsu@gmail.com>
=> raidboss: add p4s timeline

ui/jobs/components/mch.ts, ui/jobs/constants.ts, ui/jobs/jobs.css
based on and closes #4019
haven't tested for I don't have a lv90 MCH
Co-Authored-By: Christian <christian.delta@gmx.net>
=> jobs: MCH: add Chain Saw

ui/raidboss/data/06-ew/raid/p3s.ts, ui/raidboss/data/06-ew/raid/p4s.ts, ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
@Akurosia
Hi, can you find the translations `Nearsight` and `Farsight` on p4s for all language ? i have just find `Nearsight` in french, i can not find the others. I have finding `Demigod Double` in french, but not in others language.
=> i18n: P3s-p4s and hydaelyn ex fr

ui/raidboss/raidemulator.ts
at raidemulator.ts 123, 128 line
=> raidemulator: make typescript promise explicit

ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.ts, ui/raidboss/data/02-arr/trial/titan-nm.ts, ui/raidboss/data/03-hw/dungeon/baelsars_wall.ts, ui/raidboss/data/03-hw/dungeon/xelphatol.ts, ui/raidboss/data/03-hw/raid/a6n.ts, ui/raidboss/data/03-hw/raid/a8s.ts
corrections, simplification and add missing translations fr
=> i18n: add missing translations fr HW

ui/raidboss/data/06-ew/raid/p4s.ts
```
-0.3 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6EB8:/
0.0 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
1.5 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
2.8 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
4.1 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
5.4 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
6.8 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
8.1 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
9.5 "Fleeting Impulse" sync / 1[56]:[^:]*:Hesperos:6A1C:/
19.2 "Wreath of Thorns" sync / 1[56]:[^:]*:Hesperos:6A35:/
22.3 "Hemitheos's Thunder III" sync / 1[56]:[^:]*:Hesperos:6A0E:/
23.5 "Hemitheos's Thunder III" sync / 1[56]:[^:]*:Hesperos:6A0E:/
24.7 "Hemitheos's Thunder III" sync / 1[56]:[^:]*:Hesperos:6A0E:/
25.9 …
```
=> raidboss: keep p4s thorn count on screen

plugin/CactbotEventSource/FateWatcher.cs
Thanks for @Loskh, the opcode was found by his tips : D
=> plugin: update CE opcode for cn 5.58

ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.ts, ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt
The name of the second boss has changed (see attached log and image)
[en_Network_26309_20220122.log](https://github.com/quisquous/cactbot/files/7918376/en_Network_26309_20220122.log)
=> i18n: Akadaemia Anyder - fix english name for morbol boss

ui/raidboss/data/05-shb/dungeon/matoyas_relict.ts, ui/raidboss/data/05-shb/raid/e10n.ts, ui/raidboss/data/05-shb/raid/e10s.ts, ui/raidboss/data/05-shb/trial/hades-ex.ts, ui/raidboss/data/05-shb/trial/ruby_weapon-ex.ts
add missing translation fr.
Much fix replaceSync fr
=> i18n: Much fix replaceSync fr shb

ui/raidboss/data/05-shb/eureka/bozjan_southern_front.ts
Here is the error there was. I noticed that in German there was a change. That's the only way I pass the test. Say me, if you have other solution.
=> i18n: fix line regex FR on bozjan_southern_front

plugin/CactbotEventSource/FateWatcher.cs
quick test in Zadnor suggests it's working.
=> plugin: update bozja intl opcode for 6.08

ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts
add missing translation and corrections fr
=> i18n: the_tower_at_paradigms_breach corrections Fr

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.txt
For `Grand Whirlwind`, i couldn't find this skill. Is this something you created for the timeline or that it was an error when creating the timeline? Otherwise, i made this correction, because i found this skill `Great Whirlwind`. Tell me if this is wrong and I will correct my modification.
**This image is from the FFLOGS on UWU.**
=> i18n: Ultima_weapon_ultimate fr

ui/raidboss/data/06-ew/raid/p2s.ts
* say that you have avarice instead of "away from group" immediately
* add delayed call to move for goldfish brain
* show who is marked to help anybody raid calling
=> raidboss: improve P2S predatory avarice calls

plugin/CactbotEventSource/FFXIVPlugin.cs, plugin/CactbotEventSource/FFXIVProcess.cs
[1/30/2022 10:27:06 AM] Info: PIDDEBUG: RegisterProcessChangedHander
[1/30/2022 10:27:07 AM] Info: PIDDEBUG: OnProcessChanged: process_: (null)
[1/30/2022 10:27:07 AM] Info: PIDDEBUG: OnProcessChanged: changed_existence: True, changed_pid: False
[1/30/2022 10:27:07 AM] Info: PIDDEBUG: OnProcessChanged: set: 18904
Diagnostics for #4046.
=> plugin: add logging for debugging process issues

plugin/CactbotEventSource/CactbotEventSource.cs, plugin/CactbotEventSource/FFXIVPlugin.cs, plugin/CactbotEventSource/loc/Strings.Designer.cs, plugin/CactbotEventSource/loc/Strings.resx
=> plugin: initialize with current ffxiv process to avoid race

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/jobs/components/drg.ts, ui/jobs/components/index.ts, ui/jobs/jobs.css, ui/test/test.ts
- Split EW DRG from ShB.
- Adjust Sonic Thrust applied Power Surge time.
- Fix and merge blood and eyes box
- Add Firstminds' Focus Box
=> jobs: DRG: EW Gauges

ui/jobs/components/ast.ts, ui/jobs/constants.ts, ui/jobs/jobs.css
- Add Minor Arcana Timer.
- Fix a format bug
=> jobs: AST: Add Minor Arcana Timer

ui/jobs/components/sge.ts, ui/jobs/constants.ts, ui/jobs/jobs.css, ui/jobs/jobs_options.ts
- Change adderTimer from bar to number box, and add exceed alert color.
Things of healing resource need more accurate gauge.
- Hide Adder Gauge below lv 45
Due to unknown reason, if you sync to below lv45, addersgall is not availble but memory still says you have 3 addersgall.
- Add HP and MP number display
- Add Phlegma Timer
- Fix missing threholds and reset
=> jobs: SGE: Improvement

ui/oopsyraidsy/oopsy_live_list.ts, ui/raidboss/data/00-misc/test.ts
@quisquous or @Akurosia
For these 3 regex, I'm not sure. Is there a way to check them?
```
netRegexFr: NetRegexes.echo({ line: 'cactbot langue.*?', capture: false }),
netRegexFr: NetRegexes.echo({ line: 'cactbot test de réponse.*?', capture: false }),
netRegexFr: NetRegexes.echo({ line: 'cactbot montre d\'essai.*?', capture: false }),
```
=> i18n: add missing transaltions - Misc test fr

ui/jobs/components/dnc.ts, ui/jobs/components/rpr.ts, ui/jobs/components/sge.ts
As discussed in #4092, use `matches.targetIndex` instead.
=> jobs: Improve multi-call preventer

ui/jobs/components/whm.ts, ui/jobs/jobs.css
This may improve intuitiveness for lily gauge and unity with SGE gauge, also more beautiful.
Also improve code tidiness I written long time ago when I'm just a beginner `_(:3rz)_`
=> jobs: improve lily gauge

ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
Something I quickly wrote up. ~~I am not sure if suppresSeconds is necessary, alternative could be to remove the condition/preRun and have a two minute or so suppressSeconds to cover the adds enrage period.~~
=> raidboss: second ex trial add phase directions

plugin/CactbotEventSource/FFXIVProcessIntl.cs, types/event.d.ts, ui/jobs/components/mnk.ts, ui/jobs/jobs.css, ui/test/test.ts
- Add master's gauge support, also update plugin memory and test module about master's gauge.
- FormlessFist can also trigger formTimer now.
=> jobs: MNK master's gauge

ui/raidboss/data/02-arr/trial/titan-hm.txt
=> raidboss: fix Tumult syncs in Titan Hard

ui/raidboss/common_replacement.ts
Addresses some of the issues in #4102.
=> raidboss: fix French timeline translations

ui/raidboss/data/05-shb/trial/emerald_weapon-ex.ts
During Emerald Ex phase 2, the boss will use an attack called Tertius
Terminus Est. This attack spawns several swords which perform cross or
plus aoes in sequence. Players need to predict which spots will explode
last and move near them and away from the first explosions in order to
safely avoid the AOEs.
The current implementation does not prompt players anything until all
6 swords have dropped. This gives players little time to figure out
what is safe and where to move after the first aoe.
It is seven seconds, but this can still leave players rushing and
mis-reading the queue.
We know that swords will always spawn in all 4 corners (along with two
in the middle). We can predict the last two sword spots by intersecting
the first 4 with the expected full set. This allows us to give the …
=> raidboss: predict last 2 EmEx swords to give more time

ui/raidboss/data/06-ew/raid/p4s.ts
@Legends0 FYI
#4031 added some code that collected the first headmarkers and then sorted them.  I went through all of my pulls with the following script, and it looks like the four orange tethers are always first, so far as I can tell.  This simplifies a lot of the logic.  This also makes it simpler to do the act 2 callouts on the tethers (which always come after the headmarkers), handle the purple tank (who doesn't get a headmarker), and also call out your tether partner (which can be important for some roles/strats).
```
grep "\(^20.*Act 2\|^20.*Act 3\|^35.*|00AC|\|^27\)" /d/ffxivlogs/log/Network*2022*.log | grep "Act 2" -A 14 > t.txt
```
```typescript
import fs from 'fs';
import readline from 'readline';
import NetRegexes from './resources/netregexes';
const filename = process.argv[2]; …
```
=> raidboss: improve act 2 tether callouts

ui/raidboss/data/06-ew/raid/p1s.ts, ui/raidboss/data/06-ew/raid/p1s.txt
* adds Intemperate Torment
* adds English simplifications
* fixes Gaoler's Flail syncs which would sync backwards -2s
* cleans up number of syncs for simultaneous abilities
=> raidboss: small fixes to P1S timeline

plugin/CactbotEventSource/FFXIVPlugin.cs, plugin/CactbotEventSource/FFXIVProcess.cs
This was added in #4079 and appears to have been fixed by #4093.
=> plugin: remove PIDDEBUG logging

ui/jobs/components/rpr.ts, ui/jobs/jobs.css
- Add Death Gauge
- Fix Bloodsown Circle trace
=> jobs: RPR: enshroud support and fixing

ui/eureka/zone_bozja_southern.ts, ui/eureka/zone_zadnor.ts
there are 1 or 2 places where I restored the short and long names which were reversed.
=> i18n: adds missing translations Fr Bozja/zadnor

ui/oopsyraidsy/death_report.ts, ui/raidboss/data/04-sb/trial/byakko-ex.ts
- Again problem regex. I hope my fix is correct. If no, help me plz.
=> i18n: add missing translations Fr death_report

plugin/CactbotEventSource/FFXIVProcessIntl.cs
=> plugin: don't title case entity names

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update bozja intl opcode for 6.08h

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update cedirector_cn

ui/jobs/jobs.ts
FFXIV CN version launch 6.0 today.
=> jobs: Remove CN is5x

ui/oopsyraidsy/data/06-ew/raid/p4s.ts
There is one TODO for #4161 that can be updated when that lands.
=> oopsy: add p4s final

ui/jobs/components/war.ts
Seems broken for a long time since #3316, but no one mention it...
=> jobs: WAR: Fix eyesbox threshold

resources/effect_id.ts, ui/jobs/components/pld.ts, ui/jobs/constants.ts, ui/jobs/jobs.css, ui/jobs/jobs_options.ts, util/gen_effect_id.ts
- Add Requiescat stack gauge. (Hide when no stack)
- Add Fight or Flight TimerBox
- Add Expiacion TimerBox
- Adjust Pld Medium/Low MP Threshold to 6200/4400 (one/no spare MP to cast Clemency)
=> jobs: PLD: More function and MP Threshold adjust

ui/jobs/components/war.ts, ui/jobs/constants.ts, ui/jobs/jobs.css
- add Upheaval and Inner Release Timer.
- minor name change
Due to #3853 changes, those jobs with less than 3 box may appear weird like following so add some boxes.
=> jobs: WAR: more timer box

plugin/CactbotEventSource/FFXIVProcessCn.cs
=> plugin: Update FFXIVProcessCn for EW job detail

ui/raidboss/raidboss_config.ts
@mooondark pourrais-tu check ce que j'ai traduit, et aussi me dire celles que je n'ai pas traduites. j'ai crée les lignes, elles sont en attentes. Je ne suis pas sûr du sens à leur donner. Merci à toi.
=> i18n: adds missing translations fr on raidboss_config

ui/raidboss/data/04-sb/trial/susano.ts, ui/raidboss/data/06-ew/hunts/labyrinthos.ts
=> raidboss: fix susano CN translation and labyrinthos hunt

plugin/CactbotEventSource/FateWatcher.cs
plugin: update bozja China opcode for 6.01
=> plugin: update bozja cn opcode for 6.01

docs/CactbotCustomization.md
Not sure if there's a need for more verbiage around the description, or a more complete example maybe via switch/case matching some default TTS outputs?
=> docs: Add documentation for TransformTts customization

util/find_missing_translations.js
=> util: skip definition files for find translations

ui/raidboss/data/06-ew/trial/zodiark-ex.ts, ui/raidboss/data/06-ew/trial/zodiark-ex.txt
This is #3933, rebased, and with a few minor fixes from running it on top.
Closes #3933.
=> raidboss: zodiark ex

plugin/CactbotEventSource/FateWatcher.cs
Tested and working!
Had to manually spawn a CE reeee
=> plugin: update bozja intl opcode for 6.1

ui/raidboss/data/06-ew/trial/endsinger-ex.ts
This is based on my other PR for the timeline. Once that PR is merged I'll rebase this onto upstream/main again to remove the "extra" additions for the timeline etc.
Not 100% sure on the method I used to detect the star collisions here. Seemed consistent across 5-6 pulls but didn't have time to test further.
=> raidboss: Endsinger ex basic triggers

ui/oopsyraidsy/data/06-ew/trial/ultima-unreal.ts, ui/oopsyraidsy/data/oopsy_manifest.txt
Straight find/replace. The relative offsets of the different abilities match up from EX to Unreal, so I'm confident it's good enough.
=> oopsy: Add Ultima Unreal

ui/raidboss/data/06-ew/trial/endsinger-ex.ts
* minimize output string texts for triggers that don't use them all to make the UI cleaner
* make Mechanic typed so that it's harder to typo
=> raidboss: small endsinger typescript/outputstring fixes

plugin/CactbotEventSource/FFXIVProcessIntl.cs, ui/test/test.ts
Fixes #4265
AST jobmemory has been changed. 
3 arcanums merged in to one offset and cards moved.
Maybe its a prelude to 6.2 AST great changes.
=> plugin: Update AST jobmemory for 6.1

ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.ts, ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.txt
This should resolve #4292.
It looks like I screwed up the timeline lookahead for boss 1. Fortunately it was something that would fix itself without too much intervention, but it definitely looked bad.
On bosses 2/3 I think I resolved the multiple callouts. Gotta remember to *always* put the `targetIsYou` condition in for spread mechanics!
=> raidboss: Alzadaal updates

ui/raidboss/data/00-misc/general.ts
fixes ReadyCheck alert bug #4294
thank yimo for finding the such message channel code
Co-authored-by: yimo <53830825+yimo0908@users.noreply.github.com>
=> raidboss: prevent chat trigger ready check

ui/raidboss/data/06-ew/trial/endsinger-ex.ts
5head mechanic is the 5 IDs in a row 19/20 times. It's the 1/20 that gets ya.
=> raidboss: Fix Endsinger Ex 5head collector logic

ui/raidboss/data/06-ew/trial/zodiark-ex.ts
=> raidboss: improve zodiark ex styx text

util/find_missing_timeline_translations.js
=> util: fix multiple apostrophe issue in trigger ids

ui/raidboss/data/00-misc/general.ts
=> raidboss: fix ready check trigger

plugin/CactbotEventSource/CactbotEventSource.cs
https://github.com/quisquous/cactbot/pull/4313
=> plugin: use game version for memory locations

plugin/CactbotEventSource/CactbotEventSource.cs, resources/user_config.ts, types/data.d.ts, types/event.d.ts
=> plugin: pass version info to overlays

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update bozja intl opcode for 6.11

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Partially borrowed from #4343.
Tested in raid emulator.
=> raidboss: add some basic DSR triggers

ui/jobs/constants.ts
SpreadShot upgrade to Scattergun.
=> jobs: MCH: add missing combo breaker

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
- Calls out location Ser Adelphel moves to for charge.
- Calls out safe spots for Spiral Thrusts.
- Calls out location Thordan moves to after Spiral Thrusts.
- Calls out clock direction to move first for Sanctity.
=> raidboss: DSR Strength and Sanctity additional triggers

.vscode/settings.json
[file nesting](https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting) is a new feature of vscode that would merge related files into a logical "folder" that makes workspace apperance better.
Before:
After:
=> util: enable vscode file nesting feature

ui/raidboss/timeline_parser.ts
=> raidboss: Allow comments on timeline hideall lines

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
=> raidboss: temporarily disable Adele L/R call

util/process_triggers_folder.ts
=> build: Include timeline files in triggers branch

ui/raidboss/data/00-misc/test.ts
This eliminates some of the remaining issues from #1306.
=> i18n: add Japanese timelineReplace test translations

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
=> raidboss: add DSR Thordan1 meteor names to trigger

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Mechanic appears to be the same as in UCOB.
=> raidboss: DSR Twisting Dive

docs/TimelineGuide.md, docs/zh-CN/TimelineGuide.md, resources/netregexes.ts, resources/regexes.ts
=> docs: Update links to log guide line types

ui/raidboss/popup-text.ts
If a locale-specific netRegex exists (e.g. netRegexDe), then that will
take precedence over auto-translating netRegex.
The follow-up to this is to deprecate netRegexDe and friends and remove
it from all trigger files.
This is for #1306.
=> raidboss: auto-translate netRegex

ui/raidboss/popup-text.ts
Fixes https://github.com/quisquous/cactbot/pull/4449#issuecomment-1127046058
This seems like a bit of a code smell issue in general, and is probably something that tsc or a linter should catch?
=> raidboss: Fix issue with data init in PopupText

ui/raidboss/data/00-misc/general.ts, ui/raidboss/data/00-misc/test.ts
Part of #1306.
```shell
$ find ui/raidboss/data/00-misc/ -name "*.ts" | xargs -i sed -i "/netRegex..:/d" {}
```
=> i18n: remove locale netRegex from 00-misc

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
The callout may be rather lengthy.
Lef/Right, Near/Far from Hraesvelgr (Tankbusters)
=> raidboss: DSR Hallowed Wings and Plume

util/coinach.py
#4510 
```py
try:
output = raw_output.decode("utf8")
except UnicodeDecodeError:
output = str(raw_output).replace("\\r", "\r").replace("\\n", "\n")
```
to infer encoding from bytes, you need a package like [`chardet`](https://github.com/chardet/chardet). I did it this way because it's not important.
=> util: coinach.py detail error indication

plugin/CactbotEventSource/FateWatcher.cs
tested and working.
Sorry for forgetting about this! 😭
=> plugin: update bozja intl opcode for 6.11h

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
@kshman @pyeonch 
`dive`의 번역에 대해 절용시를 직접 해본 분들의 의견을 듣고싶습니다.
여기 다이브에는 니드호그 페이즈의 하이점프, 교묘한 점프, 척추강타, 용눈 페이즈의 환영 강타가 포함됩니다.
=> i18n: ko DSR update

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
=> raidboss: DSR P6 & P7 some triggers

ui/raidboss/data/02-arr/dungeon/pharos_sirius.ts, ui/raidboss/data/03-hw/trial/sephirot.ts, ui/raidboss/data/05-shb/trial/wol-ex.ts, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts, ui/raidboss/data/06-ew/trial/zodiark-ex.ts
- zodiark-ex
nobody in Korea goes northwest instead of northeast. 😢
=> i18n: ko translations update

ui/oopsyraidsy/data/03-hw/raid/a3n.ts, ui/oopsyraidsy/data/oopsy_manifest.txt, ui/raidboss/data/03-hw/raid/a3n.ts, ui/raidboss/data/03-hw/raid/a3n.txt, ui/raidboss/data/raidboss_manifest.txt
I've had this sitting around for a while and for some reason I never bothered to finish it up. Most of it is copypasta from A3s, but I made a few modifications to better fit normal mode.
=> raidboss/oopsy: Add A3n package

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
=> raidboss: DSR fix incorrect p6 cauterize call

ui/oopsyraidsy/player_state_tracker.ts
The party mapping was cleared after a wipe, which would cause
missed buffs to no longer show up and leave "couldn't find owner"
console error messages.
=> oopsy: fix missed buff party tracking

docs/zh-CN/README.md
Corrected some outdated/incorrect path/link.
Added the path/link for the rdmty and xephero overlay.
=> docs: Update zh-cn README.md

util/logtools/make_timeline.ts
I'm not terribly happy about this due to the need to run `filter` on each iteration of the `assembleTimelineStrings()` loop, but overall it didn't feel too slow. Given that we shouldn't have more than 2,000-3,000 entries to churn through, and there shouldn't be more than 100 or so unique enemy ability usages in any single encounter, the performance hit is probably worth it.
I'm perfectly fine making other changes here, this is mostly a proof-of-concept improvement over the naive stepping-stone I submitted last week.
```
109.7 "Homing Lasers" sync / 1[56]:[^:]*:The Ultima Weapon:6EF0:/
117.0 "Radiant Plume" sync / 1[56]:[^:]*:The Ultima Weapon:6F00:/
120.0 "Weight of the Land" sync / 1[56]:[^:]*:The Ultima Weapon:6F01:/
121.0 "Ceruleum Vent" sync / 1[56]:[^:]*:The Ultima Weapon:6EEF:/ …
```
=> util: Improve make_timeline sync auto-commenting 

plugin/CactbotEventSource/FateWatcher.cs
I got it all from [kshman/DutyContent](https://github.com/kshman/DutyContent)
=> plugin: update bozja ko opcode for 6.05

ui/raidboss/data/06-ew/raid/p4s.ts, ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
=> i18n: ko DSR update & small p4s fix

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update bozja intl opcode for 6.18

plugin/CactbotEventSource/FateWatcher.cs
from https://github.com/kshman/DutyContent/pull/106
=> plugin: update bozja ko opcode for 6.05h

ui/raidboss/data/05-shb/eureka/bozjan_southern_front.ts
mentioned in #4641 , thanks for pointing out
=> i18n: fix minor ja translation

util/logtools/make_timeline.ts
=> util: Fix phase timing error in make_timeline.ts

ui/jobs/buff_tracker.ts, ui/jobs/components/ast.ts, ui/jobs/components/dnc.ts, ui/jobs/components/drk.ts, ui/jobs/components/whm.ts, ui/jobs/constants.ts
I have been busying and left cactbot for a long time. I'm not sure all these changes are correct. Review needed.
=> jobs: CN 6.1 changes

plugin/CactbotEventSource/FateWatcher.cs
Tested working. Sorry for the delay, had to get it manually.
=> plugin: update bozja intl opcode for v6.2

ui/raidboss/data/06-ew/trial/barbariccia-ex.ts
add translation for existing triggers
=> i18n: barbariccia-ex chinese translation

ui/oopsyraidsy/data/06-ew/dungeon/the_fell_court_of_troia.ts, ui/raidboss/data/06-ew/dungeon/the_fell_court_of_troia.ts, ui/raidboss/data/06-ew/dungeon/the_fell_court_of_troia.txt
=> raidboss/oopsy: add The Fell court of Troia

docs/MemorySignatures.md
=> docs: Add Note About CE's Debugger Option

ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
"_rsv_11319_-1_4_C0_0BNpcName"→龙威骑神托尔丹
=> i18n: fix DSR P7 Thordan name

ui/raidboss/data/06-ew/raid/p5s.txt
From: https://www.fflogs.com/reports/RcB9gKFyYDmzp8Jn#fight=37
=> raidboss: p5s add hard enrage to timeline

ui/raidboss/data/06-ew/raid/p5s.ts
Adds callout for when to move for Tail to Claw and Claw to Tail
=> raidboss: p5s Raging Tail/Raging Claw Callout

ui/raidboss/data/06-ew/raid/p5s.ts
This could be improved with specifying the half of the room and quadrant (second time) that the two crystals are at.
=> raidboss: p5s callout for venom pool crystals

plugin/CactbotEventSource/FateWatcher.cs
I'm so sorry, I forgot about this until now! 😭 
Untested, but I will have time to test later tonight (~5-6 hours from now).
=> plugin: update bozja intl opcode for v6.2h

ui/raidboss/data/06-ew/raid/p6s.ts
This is a continuation of the previous headmarkers in PR #4757
=> raidboss: p6s Exchange of Agonies headmarkers

ui/raidboss/data/06-ew/raid/p6s.ts, ui/raidboss/data/06-ew/raid/p6s.txt
I built this based on a log from quisquous. This has received no live testing, and I haven't taken the time to match everything 1-1 with the video I was handed alongside, but it passed `test_timeline` against every encounter in that log.
Given that my group hasn't started on this yet, I don't know what timeline elements are superfluous. Unholy Darkness and Dark Dome in particular are probably in need of some cleanup. I also didn't distinguish any potential 100% split or shared Synergy busters.
=> raidboss: P6s initial timeline

ui/raidboss/data/06-ew/raid/p5s.ts
=> raidboss: Fix P5S Topaz Cluster Overrides

ui/raidboss/data/06-ew/raid/p6s.txt
Also adds a window for catching enrage start cast.
=> raidboss: p6s timeline pathogenic cells counts

ui/raidboss/data/06-ew/raid/p6s.txt
This timing is tied to 013E stackmarkers with Unholy Darkness 7892
=> raidboss: p6 fix Unholy Darkness spellid

ui/raidboss/data/06-ew/raid/p7s.ts
Quick early implementation for inviolate bonds and inviolate purgation. Seems to be working as intended - might need to test a bit more. The duration is set to match the last debuffs expiring - not sure if too long.
=> raidboss: p7s inviolate bonds, inviolate purgation

ui/raidboss/data/06-ew/raid/p7s.txt
Forbidden Fruit 4, Miniature Io is a Bull
=> raidboss: p7s timeline fix comment Birds => Bulls

docs/zh-CN/README.md
Update to #4809. Add Chinese translation. @quisquous
=> docs: update CN README for new OverlayPlugin

ui/raidboss/data/06-ew/trial/barbariccia.ts
I believe this is a shared tank buster.
=> raidboss: changed Barb's Void Aero III to shared tankbuster

ui/raidboss/data/06-ew/raid/p6s.ts
Corrected the Chinese translation of p6s `Synergy` mechanic.
=> i18n: Corrected one p6s machanic CN translation.

ui/raidboss/data/06-ew/raid/p7s.ts, ui/raidboss/data/06-ew/raid/p8s.ts
=> i18n: update ko p7s, p8s translate

ui/raidboss/data/06-ew/raid/p8s.ts
=> raidboss: p8s north/south bird fix attempt 2

ui/raidboss/data/06-ew/raid/p6s.ts
Added CN translations for p6s `predation`.
=> i18n: More p6s CN translations

ui/raidboss/data/06-ew/raid/p8s.ts
=> i18n: P8S more Japanese translations

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update bozja intl opcode for v6.21

ui/raidboss/data/06-ew/raid/p8s.ts
This is probably ok, but it's also like ~2s after the first visual so it feels late.
=> raidboss: p8s add End of Days first/second row

resources/timerbar.ts, ui/raidboss/raidboss_config.ts, ui/raidboss/skins/jwidea/jwidea.css
I use this with my material-ui and delvui. I wanna to have something similar to Lippe but closer to what I have, so maybe there are ppl want to have sth like this as well.
=> config: New skin for timeline and alert text

ui/raidboss/data/06-ew/raid/p8s.ts
Boss apparently can face -3.13727832 as well being North.
=> raidboss: p8s Quadrupedal Impact/Crush fix 2

plugin/CactbotEventSource/FFXIVProcessIntl.cs
ninja gauge data got shuffled around with 6.2
Fixes #4861
=> plugin: update ninja job gauge for 6.2

ui/raidboss/popup-text.ts
=> raidboss: fix Thavnair/Mare Lamentorium hunt triggers

.github/workflows/update-gh-pages.yml
=> ci: set force_orphan when publishing gh-pages

docs/LogGuide.md, resources/netlog_defs.ts
Mentioned by @valarnin:
https://github.com/quisquous/cactbot/pull/4905#discussion_r985769682
=> resources: rename field in MapEffect line

docs/LogGuide.md, resources/regexes.ts, util/gen_log_guide.ts
This is the parsed log line equivalent of #4851 and #4906.
=> docs: auto-generate regex for all lines

docs/LogGuide.md, util/gen_log_guide.ts
I think "ACT log lines" is kinda ambiguous, and most people seem to say "parsed" vs "network" these days.
=> docs: update log guide wording to say "parsed" log lines

plugin/CactbotEventSource/FateWatcher.cs, resources/outputs.ts, ui/raidboss/data/03-hw/trial/sephirot-ex.ts
Contains some cn translation fixes before 6.2, due to few changes, do not open PR separately.
=> plugin: CE opcode for cn 6.15

ui/raidboss/data/06-ew/hunts/elpis.ts
i18n: add missing CN translations.
=> i18n: add missing CN translations

plugin/CactbotEventSource/FateWatcher.cs
It's a bit late...
v6.11 will be released on the 25th.
=> plugin: update bozja ko opcode for 6.1

ui/raidboss/data/06-ew/raid/p6s.ts
is this right? It's confusing...
=> i18n: update ko p6s translations

plugin/CactbotEventSource/FateWatcher.cs
=> plugin: update bozja intl opcode for v6.25

resources/zone_info.ts
=> resources: ko 6.11 update

resources/netregexes.ts, ui/oopsyraidsy/damage_tracker.ts, ui/pullcounter/pullcounter.ts, ui/raidboss/common_replacement.ts, ui/raidboss/emulator/EmulatorCommon.ts, ui/raidboss/popup-text.ts, ui/raidboss/timeline.ts, util/logtools/encounter_tools.ts
This should work perfectly fine
=> resources: common net regex

resources/translations.ts, test/helper/test_trigger.ts
cherry-picked from https://github.com/quisquous/cactbot/pull/4970
=> raidboss: fix test in some edge case

resources/netregexes.ts
for https://github.com/quisquous/cactbot/pull/4970
=> resources: deprecate `NetRegexes.addedCombatantFull`

ui/raidboss/data/06-ew/raid/p8s.ts
Just removed these unnecessary brackets.
=> raidboss: p8s unnecessary brackets around 793E

.gitignore
if someone is using `eslint --cache`
=> lint: add `.eslintcache` to .gitignore

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
@Legends0 I'd appreciate you looking these over so we don't duplicate work
=> raidboss: additional triggers for ASS second boss

ui/raidboss/data/06-ew/hunts/ss_rank.ts
=> raidboss: fix Ker hunt trigger

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts, ui/raidboss/data/06-ew/hunts/ss_rank.ts
Attempt to fix ASS Silkie triggers for first and third Soaping Spree and third Slippery Soap.
Addresses #4992
cc: @Legends0
=> raidboss: fix ASS Silkie triggers

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.txt
The timings were not correct. These are them retimed.
=> raidboss: ASS fix gladiator timeline last bit

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
=> raidboss: fix ASS Soaping Spree with no suds

test/helper/regex_util.ts, test/helper/test_manifest.ts, test/helper/test_timeline.ts, test/helper/test_trigger.ts, test/unittests/config_test.ts, test/unittests/csv_util_test.ts, test/unittests/netregex_test.ts, test/unittests/regex_test.ts, test/unittests/resources_test.ts, test/unittests/responses_test.ts, test/unittests/util_test.ts
=> test: refactor `chai` import style

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.txt, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts, ui/raidboss/data/raidboss_manifest.txt
Simple find/replace on IDs.  Timeline will need extra attention.
=> raidboss: add Another Sil'dihn Subterrane (Savage)

util/DEPS.json5, util/fetch_deps.ts
same as https://github.com/OverlayPlugin/OverlayPlugin/pull/72
=> build: hash entire dep file and fix hash update

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
=> raidboss: make sure ASS(S) trigger ids are unique

ui/raidboss/data/02-arr/raid/t10.ts, ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts, ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
thanks for all triggers. very helpful in dsr.
=> i18n: update ko dsr, sildihn translations

resources/content_type.ts, util/gen_zone_id_and_info.py
=> util: add The Masked Carnivale to content_type.ts

ui/oopsyraidsy/data/06-ew/raid/p8s.ts
=> oopsy: fix p8s2 multi/supersplicer mistakes

util/test_timeline.ts
This keeps -s and -e support from manual args being passed, but makes -lf the default.
=> util: add support for `-lf` to test_timeline.ts

ui/raidboss/data/06-ew/hunts/ultima_thule.ts
Partial triggers for the Chi boss FATE.
=> raidboss: Chi boss FATE triggers

ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_general.ts, ui/raidboss/data/raidboss_manifest.txt
Adds general triggers for the Heaven-on-High deep dungeon.
Includes general triggers that are applicable to all HoH floor sets.
=> raidboss: initial triggers for Heaven-on-High

ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_121-130.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_131-140.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_141-150.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_151-160.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_161-170.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_171-180.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_181-190.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_191-200.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_general.ts, ui/raidboss/data/raidboss_manifest.txt
Triggers for The Palace of the Dead Floors 121-200.
=> raidboss: PotD 121-200

docs/LogGuide.md, ui/raidboss/emulator/EmulatorCommon.ts, util/logtools/encounter_tools.ts
=> docs/util: add variant/criterion clear code

ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_21-30.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_31-40.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_41-50.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_51-60.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_61-70.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_71-80.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_81-90.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_91-100.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_general.ts, ui/raidboss/data/raidboss_manifest.txt
Triggers for Heaven-on-High Floors 21-100.
=> raidboss: HoH 21-100

eslint/cactbot-output-strings.js, ui/raidboss/data/06-ew/trial/zodiark-ex.ts
fix https://github.com/quisquous/cactbot/issues/5057
=> lint: fix eslint output string spreading syntax

ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_181-190.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_81-90.ts
=> raidboss: reorder DD chimera callouts

resources/zone_info.ts
Co-Authored-By: Yarukon <61296195+Yarukon@users.noreply.github.com>
=> resources: cn 6.2 update

ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_171-180.ts, ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_floors_181-190.ts, ui/raidboss/data/04-sb/deepdungeon/heaven-on-high_floors_81-90.ts, ui/raidboss/data/04-sb/map/the_hidden_canals_of_uznair.ts, ui/raidboss/data/04-sb/map/the_shifting_altars_of_uznair.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, ui/raidboss/data/05-shb/map/the_dungeons_of_lyhe_ghiah.ts, ui/raidboss/data/05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
- ASS/S
All directions are taken from `p6s.ts` 
- treasure maps
`adds` are from `the_masked_carnivale.ts`
=> i18n: add ko translations

ui/oopsyraidsy/buff_map.ts
Adds RDM's Magick Barrier ability to oopsy.
Closes #5137.
=> oopsy: add RDM Magick Barrier

docs/LogGuide.md, resources/netlog_defs.ts, util/gen_log_guide.ts
Fixes https://github.com/OverlayPlugin/OverlayPlugin/issues/150
=> docs: add documentation for line 260

ui/oopsyraidsy/buff_map.ts
I think this covers everything that was missing for all current jobs.
This file could use some re-formatting so abilities are sorted by job for easier updating in the future.
=> oopsy: more missing buffs

resources/effect_id.ts, ui/jobs/components/mch.ts, ui/jobs/components/pld.ts, ui/jobs/components/sge.ts, ui/jobs/components/whm.ts, ui/jobs/constants.ts, ui/jobs/utils.ts, util/gen_effect_id.ts
WHM: 
- Assize cooldown 45s -> 40s
SGE: 
- Phlegma cooldown 45s -> 40s
MCH:
- Overheated box show buff stacks instead of duration
PLD: 
- Goring Blade change to show cooldown
- Fight or Flight duration 25s -> 20s
- Requiescat reduced to 4 stack
- Remove magic combo trace (Requiescat stacks can represent)
etc: 
- showDuration func to replace lengthy duration-cooldown structure, will replace other jobs module in later PR.
=> jobs: 6.3 changes

ui/raidboss/data/06-ew/raid/p8s.ts
=> raidboss: enhancement for p8s orogenic deformation

ui/oopsyraidsy/data/06-ew/trial/rubicante-ex.ts, ui/oopsyraidsy/data/oopsy_manifest.txt, ui/raidboss/data/06-ew/trial/rubicante-ex.ts, ui/raidboss/data/06-ew/trial/rubicante-ex.txt, ui/raidboss/data/raidboss_manifest.txt
Closes #5208 (because it incorporates most of it)
Co-Authored-By: ksh <kshman@msn.com>
Co-Authored-By: valarnin <valarnin@gmail.com>
=> raidboss/oopsy: add EX5 basics (no ordeals)

ui/raidboss/data/06-ew/map/the_shifting_gymnasion_agonon.ts, ui/raidboss/data/raidboss_manifest.txt
Initial pass, may have some mistakes.
=> raidboss: add The Shifting Gymnasion Agonon map dungeon

ui/oopsyraidsy/data/06-ew/dungeon/lapis_manalis.ts, ui/raidboss/data/06-ew/dungeon/lapis_manalis.ts
Some stuff I had that didn't make it in the earlier PR.
=> raidboss/oopsy: additional Lapis Manilis triggers

ui/raidboss/data/06-ew/dungeon/lapis_manalis.txt
This prevents needing to translate these chat lines.
=> raidboss: use map events for Lapis timeline syncs

ui/oopsyraidsy/data/06-ew/trial/rubicante.ts, ui/oopsyraidsy/data/oopsy_manifest.txt, ui/raidboss/data/06-ew/trial/rubicante.ts, ui/raidboss/data/06-ew/trial/rubicante.txt, ui/raidboss/data/raidboss_manifest.txt
Going to spend some time tomorrow working on the map effects stuff with Purgation, so marking this as draft for now.   However, the rest should be good to go.
=> [wip] raidboss/oopsy: timeline + triggers for Rubicante

ui/raidboss/data/06-ew/trial/rubicante.ts
"Rebased" 🙃.  Should be identical to the last commit in #5225.
=> raidboss: add Rubicante (normal) Ordeals

ui/raidboss/data/06-ew/dungeon/lapis_manalis.txt
=> raidboss: fix Lapis Albion timeline syncs

ui/raidboss/browser_tts_engine.ts
According to RadiantKakas#8501 on discord, the call in the constructor did not return voices, but would afterwards. So, try a few times to get voices when playing sounds.
=> raidboss: try to initialize tts multiple times

resources/netregexes.ts, resources/translations.ts, ui/jobs/buff_tracker.ts, ui/jobs/components/ast.ts, ui/jobs/components/dnc.ts, ui/jobs/components/drk.ts, ui/jobs/components/gnb.ts, ui/jobs/components/whm.ts, ui/jobs/constants.ts, ui/raidboss/common_replacement.ts
This is part of what is needed to fix #5270.
=> resources/jobs: KO 6.2 code update

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
run `ts-node util/sync_files.ts` after #5285
=> i18n: run sync_files for sildihn savage

ui/oopsyraidsy/data/06-ew/ultimate/the_omega_protocol.ts, ui/raidboss/data/03-hw/raid/a3n.ts, ui/raidboss/data/06-ew/raid/p7n.ts, ui/raidboss/data/06-ew/trial/barbariccia-ex.ts, ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> i18n: add & fix ko translations

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
This has more "phases" than fflogs, but it seems more useful to separate the p5 into multiple parts for different hello/near world behavior.
=> raidboss: TOP add phase tracking

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Have not really tested this one out yet, but ran it through one of my encounters in raidemulator to get the right output. ~~It also only needs the 4 directions, but I used an 8 direction function.~~ **EDIT:** Replaced with using eye relative.
=> raidboss: TOP p5 delta swivel cannon

ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_21-30.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_41-50.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_61-70.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_71-80.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_81-90.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_91-100.ts
Some additional mob/boss triggers.  Also removes some triggers that seemed too spammy upon further testing.
=> raidboss: more Eureka Orthos

ui/oopsyraidsy/data/06-ew/ultimate/the_omega_protocol.ts
This also fixes the pile pitch delta issue.
=> oopsy: TOP add more p5

test/helper/test_trigger.ts, ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> raidboss: TOP call out conga partner for p3 intermission 

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> raidboss: disable TOP Sigma Superliminal/Blizzard

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
This is #5334 but applied to #5330 as well.
=> raidboss: TOP adjustments and cleanup for omega pre-dodges

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Reverts quisquous/cactbot#5339
=> raidboss: revert TOP add left/right rotation to omega dodge

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> raidboss: TOP suppress useless bait tethers calls

ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Fixes #5217.
cc @Akurosia who added this in #4990
=> i18n: correct ASS(S) fr translation of Hateful Visage

ui/jobs/components/mch.ts, ui/jobs/components/pld.ts, ui/jobs/components/sge.ts, ui/jobs/components/whm.ts, ui/jobs/constants.ts
CN region updated to patch 6.3 two days ago (I almost forget it).
Also fix a bug that cast Goring Blade after Riot Blade will refresh combo time remained after 6.3.
And fix a bug that cast Atonement cannot reset combo timer.
=> jobs: apply 6.3 changes to CN region

ui/raidboss/data/04-sb/alliance/royal_city_of_rabanastre.ts
=> raidboss: fix Argath Fire IV id

ui/raidboss/data/06-ew/raid/p6n.txt
The first two are always opposite, but not a guaranteed order.
=> raidboss: update P6N timeline for randomness

ui/jobs/buff_tracker.ts, ui/jobs/combo_tracker.ts, ui/jobs/constants.ts, ui/jobs/jobs.ts
Atonement no longer interrupt combo.
=> jobs: 6.4 update

ui/raidboss/popup-text.ts
=> raidboss: allow disabled triggers without regex/netRegex

ui/oopsyraidsy/data/03-hw/trial/zurvan-ex.ts, ui/oopsyraidsy/data/oopsy_manifest.txt, ui/raidboss/data/03-hw/trial/zurvan-ex.ts, ui/raidboss/data/03-hw/trial/zurvan-ex.txt, ui/raidboss/data/raidboss_manifest.txt
I thought I would have more time to test things in-game and then Omega said no.
There's probably a better way to handle the Metal Cutter spam, but suppressing for 10 seconds seemed reasonably okay. Other than that, everything should be straightforward.
=> raidboss: Initial ZurvanEX package

plugin/CactbotEventSource/FFXIVProcessIntl.cs
ScholarJobMemory has been move left one.
=> plugin: ScholarJobMemory change

resources/user_config.ts, resources/util.ts
@quisquous Per our discussion on #5395 / discord, here's some direction-related helpers to be added to `util.ts`.
I opted to export all of the functions in a single `Directions` object, rather than to export each function individually.  Let me know if you'd prefer to have them live in `Util{}` or some other preference.
=> resources: Update util.ts to add direction-related helpers

ui/oopsyraidsy/buff_map.ts
=> oopsy: fix 6.4 buffs: tech step, veil, searing

ui/raidboss/data/06-ew/trial/golbez-ex.ts, ui/raidboss/data/06-ew/trial/golbez-ex.txt
Mostly untested, but should be correct.
I have notes all over the place still including stuff in parenthesis after ability names, until I get to trigger stuff.
=> raidboss: Initial ex6 timeline + basic triggers

ui/raidboss/emulator/data/AnalyzedEncounter.ts, ui/raidboss/emulator/data/Combatant.ts, ui/raidboss/emulator/data/CombatantTracker.ts, ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.ts, ui/raidboss/emulator/ui/EmulatedPartyInfo.ts
Plus some other minor cleanup related to combatant properties/functions
=> raidemulator: Remove significantStates

ui/oopsyraidsy/data/03-hw/trial/sophia-ex.ts, ui/oopsyraidsy/data/06-ew/trial/sophia-un.ts
Some day I will remember to close and save final changes in VSCode.
=> raidboss/oopsy: Sophia fixups

ui/raidboss/emulator/data/CombatantTracker.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x105.ts
~~Since this is in a weird state where it requires both current `main` code and the changes in #5379, the PR will show a lot of extra commits that are part of those branches. As such, please only consider commit c78e682 for review.~~
~~I will rebase to `main` again once #5379 is merged.~~
Rebased to `main`.
=> raidemulator: Support for combatant memory lines

ui/raidboss/data/06-ew/raid/p10s.ts, ui/raidboss/data/06-ew/raid/p10s.txt
As mentioned here: https://github.com/quisquous/cactbot/pull/5472
=> i18n: fix Daemoniac Bonds name

ui/raidboss/data/06-ew/raid/p9s.ts, ui/raidboss/data/06-ew/raid/p9s.txt
=> raidboss: P9S full timeline

ui/raidboss/data/06-ew/raid/p9n.ts, ui/raidboss/data/06-ew/raid/p9s.ts
=> i18n: p9s & p9n boss name fix for FR

docs/RaidbossGuide.md
=> docs: update RaidbossGuide re sequential trigger execution

ui/raidboss/data/06-ew/raid/p12s.ts, ui/raidboss/data/06-ew/raid/p12s.txt
WIP-ish timeline, not really sure of the procedure for these sorts of things. Doorboss has been extensively tested in-game and is working just fine, but Pallas is untested ingame, as it was created mainly from watching vods and ACT logs.
However, both Pallas and Doorboss are running just fine when tested against multiple FFLogs timelines using the test_timeline util.
=> raidboss: P12S Timeline

ui/raidboss/timeline_parser.ts
=> raidboss: ignore InCombat lines for missing translations

ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Modification: In CN, avoid using M or F to indicate gender.
Improvement: Ensure consistency and standardization of the text.
=> i18n: Update TOP CN translations

ui/raidboss/data/04-sb/hunts/yanxia.ts
=> raidboss: add Angada hunt triggers

ui/raidboss/data/06-ew/raid/p10s.ts
=> raidboss: add tether side/direction for p10s dividing wings

ui/raidboss/data/06-ew/raid/p11s.ts
* more "X => Y" then "Y" followups for goldfish brain
* longer durations for goldfish brain
* who the tank tether is on for Upheld (Over)ruling
* party stack calls for Upheld Ruling
* calls for towers during Letter of the Law
* add some TODOs to track remaining items
=> raidboss: add more p11s triggers

ui/raidboss/data/06-ew/raid/p10s.ts
add Chinese translate for Jade Passage
=> i18n: add Chinese for Jade Passage

ui/raidboss/data/06-ew/raid/p12s.ts
Sorry for the mistakes! Just run the lint check. seems no warnings.
=> i18n: add cn translate in p12s p1

ui/raidboss/data/06-ew/raid/p12s.ts
Not sure if I did something dumb while rebasing or Visual Studio did, but it was a messy unwind, and doing a new PR was POLR.  So I'm killing the old PR (#5580 ) and opening a new one.  This includes all revisions incorporating feedback from the initial code review.  Apologies for any added work.
=> raidboss: add support for P12S Engravements

ui/raidboss/data/03-hw/trial/zurvan-ex.ts, ui/raidboss/data/06-ew/trial/zurvan-un.ts
Implements #5600 @ish-edge
Closes #5600
=> raidboss: Zurvan JA translation

ui/raidboss/data/04-sb/dungeon/bardams_mettle.ts, util/logtools/make_timeline.ts
=> raidboss: update Bardam's Mettle for 6.4 changes

ui/raidboss/data/04-sb/dungeon/castrum_abania.ts, ui/raidboss/data/04-sb/dungeon/castrum_abania.txt, util/logtools/make_timeline.ts
First boss had minor timeline changes.  Second boss was completely revamped.
=> raidboss: update Castrum Abania for 6.4

ui/raidboss/data/04-sb/dungeon/ala_mhigo.txt, util/logtools/make_timeline.ts
Timeline changes, primarily to the second boss.
=> raidboss: update Ala Mhigo for 6.4

ui/raidboss/data/04-sb/dungeon/bardams_mettle63.ts
=> raidboss: convert one final NetRegexes.message to params

docs/RaidbossGuide.md, types/trigger.d.ts, ui/raidboss/data/04-sb/dungeon/bardams_mettle63.ts
=> raidboss: migrate to new NetParams trigger style

ui/raidboss/data/06-ew/raid/p12s.ts
This was added in #5597.
Sorry, I should have looked at this more closely.
These are the correct tower spots for this strategy.
=> raidboss: fix up p12s engravement clockwise strategy

ui/raidboss/data/06-ew/raid/p12s.ts
I made this PR for someone who can make more better triggers.
If this PR is not enough for purpose, please discard this.
Thank you.
Added:
* Palladian Grasp
* Gaiaochos
* The Classical Concepts
* Caloric Theory
=> raidboss: more P12S second phase

resources/outputs.ts, ui/raidboss/data/06-ew/raid/p12s.ts
* rewrote the Ultima Blow tethers to not depend on roles (since people can be dead and it can go weird)
* used ids in more places
* fixed headmarker id
* updated English text
* changed some alert severities (also by making some things responses)
* rewrote the classical 2 tracking which was wrong for the final player
=> raidboss: refactoring of P12S second phase #5620

ui/raidboss/data/06-ew/raid/p12s.ts
Nothing to see here.  Nothing at all. 👀
=> raidboss: p12s classical concepts bug fix

resources/util.ts, ui/raidboss/data/06-ew/trial/endsinger-ex.ts, ui/raidboss/data/06-ew/trial/endsinger-ex.txt
* handle head direction during star knockback
* combine Elenchos inside/outside with other mechanics
* Telomania call
* chains calls
* timeline numbering
=> raidboss: Endsinger Extreme improvements

ui/raidboss/data/06-ew/raid/p9s.ts
Closes #5642 .  I ran this against a reclear log from this morning in emulator and it looks fine, but could probably benefit from additional testing.
=> raidboss: p9s additional limit cut 1 info

ui/raidboss/data/06-ew/raid/p9s.ts
Addresses #5642 secondary request: https://github.com/quisquous/cactbot/issues/5642#issuecomment-1621824429
=> raidboss: add P9S - Beastly Fury callout

ui/raidboss/data/06-ew/raid/p12s.ts
=> raidboss: add p12s concepts ctxs (rainbow) option

ui/raidboss/emulator/data/CombatantTracker.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x105.ts, ui/raidboss/emulator/data/network_log_converter/ParseLine.ts
Fixes various issues found while writing some custom triggers.
=> raidemulator: Various fixes for CombatantMemory lines

ui/raidboss/data/06-ew/raid/p4s.ts
Updates P4S calls to be consistent with P12S, ref: https://github.com/quisquous/cactbot/pull/5692#discussion_r1264011379
=> raidboss: update p4s tank in/out + party out/in calls

ui/raidboss/data/03-hw/raid/a7s.ts, ui/raidboss/data/04-sb/dungeon/doma_castle.ts, ui/raidboss/data/06-ew/deepdungeon/eureka_orthos_floors_71-80.ts, ui/raidboss/data/06-ew/raid/p9s.ts, ui/raidboss/data/06-ew/trial/endsinger-ex.ts, ui/raidboss/raidboss_config.ts
p12s will come in a sepperate commit as it is a bigger update
=> i18n: add missing de translations

resources/party.ts
=> resources: remove unneeded type assertion

ui/raidboss/data/06-ew/raid/p12s.ts, ui/raidboss/data/06-ew/raid/p12s.txt
=> raidboss: add p12s2 tethers to timeline

ui/raidboss/data/06-ew/raid/p10s.ts
=> raidboss: add callout for tetradaemonic bonds targets

ui/raidboss/emulator/data/Persistor.ts
=> raidemulator: move encounter loading outside of Dexie zone

ui/raidboss/data/03-hw/pvp/shatter.ts
I accidentally queued for this today so thought I'd fix it.
Fixes #5430
=> raidboss: fix Shatter big ice triggers for new map

ui/oopsyraidsy/data/00-misc/general.ts
=> oopsy: fix food buff triggers

ui/raidboss/data/06-ew/raid/p12s.ts
=> raidboss: fix classical1 bug with noflip checkbox

ui/raidboss/data/06-ew/raid/p10s.ts
The dir of cn's outputs already includes the side field.
before:
now:
=> raidboss: update cn translation

resources/party.ts, resources/util.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.txt
* config options for custom jail order (by name or job)
* garuda sisters locations
* nail spawn locations
* ifrit charge directions (closes #3715)
* predation safe cardinal and rotation
* improved timeline
=> raidboss: uwu updates

webpack/webpack.config.ts
=> build: include images directory

ui/oopsyraidsy/damage_tracker.ts, ui/oopsyraidsy/data/05-shb/raid/e12s.ts, ui/oopsyraidsy/death_report.ts, ui/oopsyraidsy/oopsy_common.ts, ui/oopsyraidsy/oopsy_live_list.ts, ui/oopsyraidsy/oopsy_summary_list.ts, ui/oopsyraidsy/oopsyraidsy.ts, ui/oopsyraidsy/oopsyraidsy_config.ts, ui/oopsyraidsy/player_state_tracker.ts
=> lint: Handle nullable empty string checks in oopsy

ui/raidboss/browser_tts_engine.ts, ui/raidboss/emulator/data/CombatantTracker.ts, ui/raidboss/emulator/data/PopupTextAnalysis.ts, ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts, ui/raidboss/emulator/data/network_log_converter/ParseLine.ts, ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.ts, ui/raidboss/emulator/ui/EmulatedPartyInfo.ts, ui/raidboss/emulator/ui/EncounterTab.ts, ui/raidboss/html_timeline_ui.ts, ui/raidboss/popup-text.ts, ui/raidboss/raidboss.ts, ui/raidboss/raidboss_config.ts, ui/raidboss/raidemulator.ts, ui/raidboss/timeline.ts, ui/raidboss/timeline_parser.ts
=> lint: Handle nullable empty string checks in raidboss code

ui/raidboss/autoplay_helper.ts
created only once, rather than multiple times.
=> raidboss: prevent duplicate button creation

resources/outputs.ts, ui/oopsyraidsy/data/00-misc/general.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, util/coverage/coverage.ts, util/logtools/web_splitter.ts
small fix to be more clear (even if its not full propper german)
=> i18n: added new and missing translations,

ui/raidboss/data/06-ew/trial/golbez-ex.ts
=> raidboss: fix JA translation for golbez-ex

ui/oopsyraidsy/data/00-misc/general.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, ui/raidboss/data/06-ew/raid/p12s.ts, ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> i18n: update ko translations

ui/raidboss/data/06-ew/trial/zeromus-ex.ts
`Miasmic Blast` needs more testing, not sure it's 100% correct yet.
=> raidboss: Some initial ex7 triggers

resources/util.ts, ui/raidboss/data/06-ew/trial/zeromus-ex.ts
Adds safe spots for Miasmic Blast and a reminder for accel bombs.  I won't have time to get back to it until next week, so this is probably all I can PR for now.
=> raidboss: additional ex7 triggers

ui/raidboss/data/06-ew/trial/zeromus-ex.ts
=> raidboss: fix ex7 forked lightning

ui/raidboss/data/06-ew/trial/zeromus-ex.ts
=> raidboss: temporarily disable ex7 miasmic trigger

ui/raidboss/data/06-ew/trial/zeromus-ex.ts
=> raidboss: reenable ex7 miasmic trigger

ui/raidboss/data/06-ew/trial/zeromus-ex.ts, ui/raidboss/data/06-ew/trial/zeromus.ts
- add ex7 zeromus CN translate
- `ZeromusEx Abyssal Nox` only aleart Healers
=> i18n: add ex7 zeromus CN translate

ui/raidboss/data/06-ew/trial/zeromus.ts
Added Japanese output strings for:
* Abyssal Nox
* Abyssal Echoes
* Sable Thread
* Visceral Whirl
* Flare
* Akh Rhai
=> raidboss: Add JA translation for Zeromus

ui/raidboss/data/06-ew/alliance/thaleia.ts, ui/raidboss/data/06-ew/alliance/thaleia.txt
Sorry no timeline.
Sorry again for poor English output strings. 😭
=> raidboss: Simple Thaleia triggers

ui/oopsyraidsy/data/06-ew/dungeon/alzadaals_legacy.ts
=> oopsy: fix Alzadaal pulse laser ability id

plugin/CactbotEventSource/FFXIVProcessKo.cs
This is a copy of cn-6.4(#5800).
=> plugin: update FFXIVProcessKo.cs for ko 6.4

ui/oopsyraidsy/data/06-ew/raid/p12s.ts
Not tested but looks correct.
Closes #5770
=> oopsy: P12S - Add trigger for failing caloric due to stacks

ui/raidboss/data/06-ew/trial/golbez-ex.ts
=> i18n: fix ko golbez-ex

ui/raidboss/data/03-hw/alliance/dun_scaith.ts, ui/raidboss/data/03-hw/dungeon/sohm_al_hard.ts, ui/raidboss/data/03-hw/dungeon/the_lost_city_of_amdapor_hard.ts, ui/raidboss/data/03-hw/dungeon/the_vault.ts, ui/raidboss/data/03-hw/dungeon/the_vault61.ts, ui/raidboss/data/03-hw/raid/a10s.ts, ui/raidboss/data/03-hw/raid/a11s.ts, ui/raidboss/data/03-hw/raid/a12n.ts, ui/raidboss/data/03-hw/raid/a12s.ts, ui/raidboss/data/03-hw/raid/a1s.ts, ui/raidboss/data/03-hw/raid/a2s.ts, ui/raidboss/data/03-hw/raid/a3n.ts, ui/raidboss/data/03-hw/raid/a3s.ts, ui/raidboss/data/03-hw/raid/a5s.ts, ui/raidboss/data/03-hw/raid/a6n.ts, ui/raidboss/data/03-hw/raid/a6s.ts, ui/raidboss/data/03-hw/raid/a7s.ts, ui/raidboss/data/03-hw/raid/a8n.ts, ui/raidboss/data/03-hw/raid/a8s.ts, ui/raidboss/data/03-hw/trial/thordan-ex.ts, ui/raidboss/data/06-ew/trial/thordan-un.ts
=> raidboss: update hw to use player objects

ui/raidboss/data/03-hw/dungeon/baelsars_wall.ts, ui/raidboss/data/03-hw/dungeon/baelsars_wall62.ts, ui/raidboss/data/03-hw/raid/a4s.ts, ui/raidboss/data/03-hw/trial/sophia-ex.ts, ui/raidboss/data/03-hw/trial/zurvan-ex.ts, ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.ts, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.ts, ui/raidboss/data/04-sb/raid/o10s.ts, ui/raidboss/data/04-sb/raid/o12n.ts, ui/raidboss/data/04-sb/raid/o12s.ts, ui/raidboss/data/04-sb/raid/o2n.ts, ui/raidboss/data/04-sb/raid/o3s.ts, ui/raidboss/data/04-sb/raid/o7s.ts, ui/raidboss/data/04-sb/raid/o8s.ts, ui/raidboss/data/04-sb/trial/seiryu.ts, ui/raidboss/data/04-sb/trial/shinryu-ex.ts, ui/raidboss/data/04-sb/trial/shinryu.ts, ui/raidboss/data/04-sb/trial/susano-ex.ts, ui/raidboss/data/04-sb/trial/tsukuyomi-ex.ts, ui/raidboss/data/04-sb/trial/tsukuyomi.ts, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts, ui/raidboss/data/06-ew/trial/sophia-un.ts, ui/raidboss/data/06-ew/trial/zurvan-un.ts
=> raidboss: update sb to use player objects

ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts, ui/raidboss/data/05-shb/dungeon/heroes_gauntlet.ts, ui/raidboss/data/05-shb/dungeon/holminster_switch.ts, ui/raidboss/data/05-shb/eureka/delubrum_reginae.ts, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.ts, ui/raidboss/data/05-shb/eureka/zadnor.ts, ui/raidboss/data/05-shb/hunts/lakeland.ts, ui/raidboss/data/05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts, ui/raidboss/data/05-shb/raid/e10s.ts, ui/raidboss/data/05-shb/raid/e11n.ts, ui/raidboss/data/05-shb/raid/e11s.ts, ui/raidboss/data/05-shb/raid/e12n.ts, ui/raidboss/data/05-shb/raid/e12s.ts, ui/raidboss/data/05-shb/raid/e4s.ts, ui/raidboss/data/05-shb/raid/e6s.ts, ui/raidboss/data/05-shb/raid/e7s.ts, ui/raidboss/data/05-shb/raid/e8s.ts, ui/raidboss/data/05-shb/raid/e9s.ts, ui/raidboss/data/05-shb/trial/hades-ex.ts, ui/raidboss/data/05-shb/trial/hades.ts, ui/raidboss/data/05-shb/trial/shiva-un.ts, ui/raidboss/data/05-shb/trial/titania-ex.ts, ui/raidboss/data/05-shb/trial/varis-ex.ts, ui/raidboss/data/05-shb/trial/wol-ex.ts, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts
=> raidboss: update shb to use player objects

ui/raidboss/data/06-ew/alliance/aglaia.ts, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon-savage.ts, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts, ui/raidboss/data/06-ew/dungeon/lapis_manalis.ts, ui/raidboss/data/06-ew/dungeon/the_dead_ends.ts, ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.ts, ui/raidboss/data/06-ew/raid/p10s.ts, ui/raidboss/data/06-ew/raid/p11n.ts, ui/raidboss/data/06-ew/raid/p11s.ts, ui/raidboss/data/06-ew/raid/p12s.ts, ui/raidboss/data/06-ew/raid/p1s.ts, ui/raidboss/data/06-ew/raid/p2n.ts, ui/raidboss/data/06-ew/raid/p2s.ts, ui/raidboss/data/06-ew/raid/p3s.ts, ui/raidboss/data/06-ew/raid/p4s.ts, ui/raidboss/data/06-ew/raid/p5s.ts, ui/raidboss/data/06-ew/raid/p8s.ts, ui/raidboss/data/06-ew/raid/p9n.ts, ui/raidboss/data/06-ew/trial/golbez.ts, ui/raidboss/data/06-ew/trial/rubicante-ex.ts, ui/raidboss/data/06-ew/trial/zeromus-ex.ts, ui/raidboss/data/06-ew/trial/zeromus.ts, ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts, ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
=> raidboss: update ew to use player objects

docs/CactbotCustomization.md, docs/OopsyraidsyGuide.md, docs/RaidbossGuide.md, docs/ko-KR/CactbotCustomization.md, docs/zh-CN/CactbotCustomization.md, docs/zh-CN/RaidbossGuide.md, docs/zh-TW/CactbotCustomization.md, ui/raidboss/data/00-misc/general.ts
=> docs: update documentation to use player objects

ui/raidboss/popup-text.ts
=> raidboss: fix errors on delayed triggers being cancelled

ui/raidboss/data/05-shb/raid/e10n.ts
=> raidboss: improve e10n wording

ui/raidboss/data/04-sb/eureka/eureka_pyros.ts
=> raidboss: fix Skoll Howl in Eureka Pyros

ui/oopsyraidsy/oopsyraidsy_config.ts, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon-savage.ts, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon.ts, ui/raidboss/raidboss_config.ts
another mount rokkon + default player label config
=> i18n: update ko another mount rokkon

ui/raidboss/data/06-ew/dungeon/another_mount_rokkon-savage.ts, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon.ts
* improve Soldiers of Death blue add to say the quadrant
* prefer role stacks even if melee selected for Soldiers of Death
* make Double Iai-giri say melee/roles/partners instead of w/player
=> raidboss: minor Another Mount Rokkon improvements

util/logtools/make_timeline.ts
Follow-up to https://github.com/quisquous/cactbot/pull/5939
=> util: update make_timeline to emit netregex

package.json
Do this until a better solution for #5910 exists.
=> build: temporarily limit node version

README.md, docs/FAQ-Troubleshooting.md, docs/ko-KR/README.md, docs/zh-CN/README.md
- fix up badge
- remove outdated information
- change ancient "module" language to say "overlay"
=> docs: main README update

ui/raidboss/data/02-arr/raid/t10.txt, ui/raidboss/data/02-arr/raid/t11.txt, ui/raidboss/data/02-arr/raid/t12.txt, ui/raidboss/data/02-arr/raid/t13.txt, ui/raidboss/data/02-arr/raid/t6.txt, ui/raidboss/data/02-arr/raid/t8.txt, ui/raidboss/data/02-arr/trial/ifrit-nm.txt, ui/raidboss/data/02-arr/trial/shiva-ex.txt, ui/raidboss/data/02-arr/trial/titan-ex.txt, ui/raidboss/data/02-arr/trial/titan-hm.txt, ui/raidboss/data/02-arr/trial/titan-nm.txt, ui/raidboss/data/02-arr/trial/ultima-ex.txt
=> raidboss: timeline netregex for arr startsusing

ui/raidboss/data/03-hw/alliance/dun_scaith.txt, ui/raidboss/data/03-hw/alliance/weeping_city.txt, ui/raidboss/data/03-hw/dungeon/baelsars_wall.txt, ui/raidboss/data/03-hw/dungeon/sohm_al.txt, ui/raidboss/data/03-hw/dungeon/the_lost_city_of_amdapor_hard.txt, ui/raidboss/data/03-hw/dungeon/xelphatol.txt, ui/raidboss/data/03-hw/raid/a10n.txt, ui/raidboss/data/03-hw/raid/a11s.txt, ui/raidboss/data/03-hw/raid/a12s.txt, ui/raidboss/data/03-hw/raid/a1s.txt, ui/raidboss/data/03-hw/raid/a3s.txt, ui/raidboss/data/03-hw/raid/a4s.txt, ui/raidboss/data/03-hw/raid/a5s.txt, ui/raidboss/data/03-hw/raid/a7s.txt, ui/raidboss/data/03-hw/raid/a8s.txt, ui/raidboss/data/03-hw/raid/a9s.txt, ui/raidboss/data/03-hw/trial/ravana-ex.txt, ui/raidboss/data/03-hw/trial/thordan-ex.txt, ui/raidboss/data/03-hw/trial/zurvan-ex.txt, ui/raidboss/data/06-ew/trial/thordan-un.txt, ui/raidboss/data/06-ew/trial/zurvan-un.txt
A few backslash escapes were found which are listed in a PR comment below.
=> raidboss: timeline netregex for hw startsusing

ui/raidboss/data/05-shb/eureka/bozjan_southern_front.txt, ui/raidboss/data/05-shb/eureka/zadnor.txt
`/sync\s*\/ 21:\.{8}:(?<command>[^:]*):(?<data>[^:]*):\//`
=> raidboss: timeline netregex for actorControl

ui/raidboss/data/03-hw/dungeon/the_lost_city_of_amdapor_hard.txt, ui/raidboss/data/04-sb/eureka/eureka_hydatos.txt, ui/raidboss/data/05-shb/eureka/bozjan_southern_front.txt, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt, ui/raidboss/data/05-shb/eureka/zadnor.txt, ui/raidboss/data/06-ew/alliance/aglaia.txt, ui/raidboss/data/06-ew/alliance/euphrosyne.txt, ui/raidboss/data/06-ew/alliance/thaleia.txt, ui/raidboss/data/06-ew/dungeon/aetherfont.txt, ui/raidboss/data/06-ew/dungeon/aloalo_island.txt, ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.txt, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon-savage.txt, ui/raidboss/data/06-ew/dungeon/another_mount_rokkon.txt, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.txt, ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.txt, ui/raidboss/data/06-ew/dungeon/ktisis_hyperboreia.txt, ui/raidboss/data/06-ew/dungeon/lapis_manalis.txt, ui/raidboss/data/06-ew/dungeon/smileton.txt, ui/raidboss/data/06-ew/dungeon/stigma_dreamscape.txt, ui/raidboss/data/06-ew/dungeon/the_aitiascope.txt, ui/raidboss/data/06-ew/dungeon/the_dead_ends.txt, ui/raidboss/data/06-ew/dungeon/the_fell_court_of_troia.txt, ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.txt, ui/raidboss/data/06-ew/dungeon/the_sildihn_subterrane.txt, ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.txt, ui/raidboss/data/06-ew/dungeon/the_tower_of_zot.txt, ui/raidboss/data/06-ew/dungeon/vanaspati.txt
`/sync\s*\/ 29:\[\^:\]\*:(?<id>[^:]*):\//`
=> raidboss: timeline netregex for systemLogNoParam

ui/raidboss/data/03-hw/trial/thordan-ex.txt, ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.txt, ui/raidboss/data/06-ew/dungeon/aloalo_island.txt, ui/raidboss/data/06-ew/raid/p8n.txt, ui/raidboss/data/06-ew/trial/thordan-un.txt
`/sync\s*\/ 1\[56\]:\[\^:\]\*:\[\^:\]\*:(?<id>[^:]*):\//`
=> raidboss: timeline netregex for abilityNoSource

ui/raidboss/data/00-misc/test.txt, ui/raidboss/data/04-sb/alliance/orbonne_monastery.txt, ui/raidboss/data/04-sb/alliance/royal_city_of_rabanastre.txt, ui/raidboss/data/04-sb/raid/o12n.txt, ui/raidboss/data/04-sb/raid/o12s.txt, ui/raidboss/data/06-ew/trial/endsinger.txt
`/sync\s*\/ 00:(?<code>[^:]*):\[\^:\]\*:(?<line>[^:]*)\//`
=> raidboss: timeline netregex for gameLogNoName

ui/raidboss/data/04-sb/raid/o7n.txt, ui/raidboss/data/04-sb/raid/o7s.txt
`/sync\s*\/ 1A:(?<effectId>[^:]*):(?<effect>[^:]*):\[\^:\]\*:\[\^:\]\*:\[\^:\]\*:\[\^:\]\*:(?<target>[^:]*):\//`
=> raidboss: timeline netregex for gainsEffectWithTarget

ui/raidboss/data/06-ew/dungeon/lapis_manalis.txt
`/sync\s*\/ 257 101:\.{8}:(?<flags>[^:]*):\//`
=> raidboss: timeline netregex mapEffectNoInstanceNoLocation

ui/raidboss/data/03-hw/raid/a7s.txt
`/sync\s*\/ 1A:\[\^:\]\*:(?<effect>[^:]*):\//`
=> raidboss: timeline netregex for gainsEffectNameOnly

ui/raidboss/data/02-arr/raid/t9.txt
`/sync\s*\/ 1B:\.{8}:\[\^:\]\*:\.{4}:\.{4}:(?<id>[^:]*):\//`
=> raidboss: timeline netregex for headMarkerNoName

ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt
`/sync\s*\/ 00:\[\^:\]\*::(?<line>[^:]*)\//`
=> raidboss: timeline netregex for gameLogNoNameNoCode

ui/raidboss/data/03-hw/dungeon/fractal_continuum.txt
`/sync\s*\/ 1B:\.{8}:(?<name>[^:]*):\.{4}:\.{4}:(?<id>[^:]*):\//`
=> raidboss: timeline netregex for headMarkerName

ui/raidboss/data/04-sb/eureka/eureka_hydatos.txt, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.txt
`/sync\s*\/ 04:\.{8}:(?<name>[^:]*):\//`
=> raidboss: timeline netregex for removedCombatant

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
`/sync\s*\/ 19:\[\^:\]\*:(?<target>[^:]*):\//`
=> raidboss: timeline netregex for wasDefeated

ui/raidboss/data/02-arr/raid/t9.txt, ui/raidboss/data/03-hw/alliance/dun_scaith.txt, ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt, ui/raidboss/data/03-hw/raid/a10n.txt, ui/raidboss/data/03-hw/raid/a3s.txt, ui/raidboss/data/03-hw/trial/thordan-ex.txt, ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.txt, ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt, ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt, ui/raidboss/data/05-shb/eureka/delubrum_reginae.txt, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt, ui/raidboss/data/05-shb/trial/wol-ex.txt, ui/raidboss/data/06-ew/alliance/aglaia.txt, ui/raidboss/data/06-ew/raid/p7n.txt, ui/raidboss/data/06-ew/trial/endsinger-ex.txt, ui/raidboss/data/06-ew/trial/thordan-un.txt, ui/raidboss/data/06-ew/trial/zodiark.txt, ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt, ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
Oops #6039 used single quotes and not double.
They both work, but everything else is double quotes.
=> raidboss: timeline netregex quote fixup

test/helper/test_timeline.ts
Fixes #3547
Closes #5977
cc #5619
=> test: add test to verify all timeline syncs are netregex

resources/netlog_defs.ts
This is for: NetworkRaidMarker and NetworkTargetMarker
=> resources: improve anonymization for various line types

ui/raidboss/data/06-ew/trial/rubicante-ex.ts
Also improve some of the stack/spread calls to flow better
=> raidboss: add Rubi Ordeal of Purgation
