quisquous/cactbot

- ui/raidboss/data/timelines/o6s.txt
Haven't actually tested it in combat yet (going in tomorrow), but seems to work outside that.
As a style note, even though most public timelines don't sync every line, I prefer to because xiv has some amount of [drift in its combat timings](https://www.reddit.com/r/ffxiv/comments/6qk2mv/timestamps_for_all_deltascape_savage_encounters/dkxzuqt/?context=1). So the time in between adjacent abilities ends up being more important than the time from the beginning of a fight/phase to something several minutes into it, since it could be way off by that point. By syncing every ability, it can make minor 100ms corrections throughout the fight.
I plan on making timelines like this for the other fights too (it's fun!) if none exist by the time I get around to it.
> O6S Timeline

- CactbotOverlay/CactbotOverlay.cs
Fix allows the web.DownloadString to download the manifest.txt file when remotely hosting the overlay from github pages
> Fix SSL/TLS issue when attempting to read manifest file from github pages

- ui/raidboss/data/timelines/o5s.txt
More complete version of O5S, still untested until tomorrow's reset. From #37
> O5S Timeline syncs

- ui/raidboss/data/manifest.txt
- ui/raidboss/data/timelines/o5n.txt
- ui/raidboss/data/triggers/o5n.js
Added an O5N timeline since it's nice to have in general, but also it'll be *way* easier to test #33 without getting a static together.
> O5N Timeline

- ui/raidboss/data/timelines/o5n.txt
- ui/raidboss/data/timelines/o5s.txt
Diabolic Whistle (knockback) was too long and was appearing on top of the timer, making the time unreadable. This shortens that name to prevent that, and rewrites the others to keep the style consistent.
> Shortening O5 timeline names

- ui/raidboss/data/manifest.txt
- ui/raidboss/data/timelines/o6n.txt
- ui/raidboss/data/timelines/o7n.txt
- ui/raidboss/data/timelines/o8n.txt
- ui/raidboss/data/triggers/o6n.js
- ui/raidboss/data/triggers/o7n.js
- ui/raidboss/data/triggers/o8n.js
O6N:
Pretty standard. Just like savage, there's no real RNG, and a pretty early loop. One tricky part is that Demonic Wave is two casts; the boss has the long castbar, and then Portrayal of Water casts the real one 1 second after the cast bar finishes. Was always kind of confusing trying to pop out and in of melee range for it, and that explains why. No more, thanks to the timeline!
A nearly final version is here, the only thing I took out is the first (fake, boss castbar) Demonic Wave inside the loop: https://www.twitch.tv/videos/229684132
O7N:
There's no set order that I could detect. The only consistency is that a program will not be one of the last two loaded; that is, if the order goes Ultros -> Air Force, the next one will be either Dadaluma or Bibliotaph. If the third is Dadaluma, …
> Adding timelines for Sigmascape 6-8N

- ui/raidboss/data/timelines/o8s.txt
Cleaned up some of the intro kefka namings. They're (intentionally, probably) confusing, but for reference, this is a quick glossary I compiled while doing this and normal mode:
* Gravitational Wave is the west half arena hit, and Intemperate Will is the east half.
* Ave Maria is the question mark gaze looking at the statue, Indolent Will is the gaze looking away.
* Inexorable Will are the ordinary targeted ground aoes.
* Indomitable Will is the four stack markers during first graven.
* These aren't in the timeline, but Indulgent Will is the confuse application, Idyllic Will is the sleep.
I also split it out into Graven sections, combined Blizzard+Thunder to make the actual event happening more clear from the timeline, and added the untargetable line for the enrage.
> O8S (P1) naming cleanup

- ui/raidboss/data/timelines/o8s.txt
Adding some lines for the untargetable/targetable instances that make sense, since they aren't right when Graven Image goes off.
Video with these changes: https://www.twitch.tv/videos/232532546?t=1h24m40s
> O8S timeline tweaks

- util/make_timeline.py
Added a lot of functionality to this script.
- Added FFlogs support. This requires the requests library; if it's not present, the error on line 27 instructs the user how to install it. This also requires an API key, and also provides direction if it's missing. With those things active, it will pull all the cast events and make a timeline the same way it does for files.
- Added event filtering. Using the -ii argument, you can provide a list (like -ii 2ABC 2ABD 2ACE) to ignore ability IDs. This will also ignore them for the purposes of calculating time deltas between two lines, so, say, four players hitting their kefka heads won't throw off the rounding. You can also use -ic and -ia for combatant or ability names respectively.
- Added phase support. You can pass something like "-p …
> make_timeline.py improvements

- ui/raidboss/data/timelines/o7s.txt
Minor oversights. They were close enough to not lose syncing but still enough to be misleading.
> raidboss: O7S timeline fixes

- ui/raidboss/data/timelines/o8s.txt
The diff may not be super useful, so I'll summarize the changes (beyond simply adding syncs). My group got to 1389 on this, so up to that is script-generated, past that is hand-made from fflogs. Preserved your existing naming for the most part.
- Added the Thunder/Fire hits of Celestriad
- Fixed some slight +/- 1s timing issues
- Added all non-starstrafe Soaks (The Path of Light, renamed for clarity), since they were included, albeit inconsistently, later on in the fight. Having specific timing for them is useful for dodging into it.
- Added All Things Ending to Past/Future End during Starstrafe. The ATE cast on the normal ones is fast enough (3s) that it's not worth timing it, but there's a bigger gap in that one (8s).
- Also added Meteor hit (the stack) during Starstrafe
- Added some …
> Adding O8S timeline syncs

- ui/eureka/eureka.js
Hi, I've made it so that you can take the clipboard copy function from ffxiv-eureka.com
e.g. `/e ★ NMs on cooldown: Sabo (70m) > Emperor (82m) > Pazuzu (85m) > Caym (98m) > Amemet (110m)`
This will grab the times and update them on the cactbot tracker.
> eureka: add ability to import times from web tracker

- ui/raidboss/data/timelines/tsukuyomi-ex.txt
This timeline is as-of-yet untested. It was made with make_timeline.py and curated a bit from videos, logs, and guides as reference. I've cleared the fight, so I know what each mechanic does, but I did so before ACT was fixed and haven't been back in. This is mostly meant as a starting point.
In particular, the add phase is fairly empty right now and could use spawn times and syncs to Added combatant... lines.
> Tsukuyomi EX Timeline

- ui/raidboss/data/timelines/ridorana_lighthouse.txt
- ui/raidboss/data/timelines/tsukuyomi-ex.txt
Fixed some timing issues in Ridorana and added the add phase in Tsukuyomi. Weirdly, line 17 doesn't work even though I'm sure that line is present in the logs. Not sure what's up with that, probably a FFXIV plugin hiccup, but it only causes Concentrativity to show the wrong timing and it's pretty clearly visible. Might want to just hide that for now though.
Can see the Tsukuyomi timeline in action here: https://www.twitch.tv/videos/265667584?t=1h19m15s
I did learn from this low-dps learning party that the middle phase isn't actually a real loop, it will only run until the second Antitwilight/Perilune, so I might change that from a loop to the real sequence, but this is good enough to be useful as-is.
> Cleaning up timelines

- ui/raidboss/data/timelines/tsukuyomi-ex.txt
This should be the final revision. Just cleared with this version and can't see any further changes unless people discover more patterns in the fight than I'm currently aware of to remove the RNG. Sorry for the spamming of revision commits on this one!
> raidboss: Tsukuyomi timeline cleanup

- ui/raidboss/data/triggers/ridorana_lighthouse.js
I did a ridorana run and happened to have cactbot running, but I noticed some mistakes and some misleading TTS regarding some mechanics. Also the Regexes for the division mechanics of Construct 7 don't seem to work in German. I've searched my logs and there were no 14:2CCA:, 14:2CCC: and 14:2CCD: in the logs. Only the indivisible had 14:2CCE:, but the German ones for numbers weren't logged that way, so I adjusted the Regexes from what I found in the Logs.
> noticed some mistakes and some regexes didn't work in german

- util/test_timeline.py
Hello! I haven't done much in a while, but I had a spare weekend and decided to put it towards cactbot.
The goal for this is to have a system where we can point to a timeline, point to a log, and run that timeline against that log to see how it lines up. This will complement (possibly replace, but probably not completely) the old process of making a timeline, recording a vod of it, going over it later to see where it desynced, and so on. It's pretty basic right now, but it should get there eventually. Hopefully before 4.4.
Syntax is similar to make_timeline, with the added argument of a timeline filename. I ran the uwu timeline against the furthest pull i have (suppression gaol) like so:
```
test_timeline.py -f "%APPDATA%\Advanced Combat Tracker\FFXIVLogs\Network_20180727.log" -s …
```
> util: Adding starting work on automated timeline testing

- util/make_timeline.py
We'd mentioned this in prior PRs, but the timing on some of the O9S stuff was frustratingly half-second in enough places that I went ahead and made the change. As expected, it makes timelines that gradually increase that decimal place, but it should be a better reflection of what's actually happening, instead of the platonic ideal of how the game is coded. It's also going to mean a lot of variance between pulls, so some care should be taken when combining data from multiple pulls to line up a common starting point; a 100.5 in one pull might well be a 99.9 in another, and both will end up with the timer looking right in-game, but it would mess with it a bit if you then take an ability at 102.5 in the first pull and put it at 102.5 in the second pull, for example.
> util: Changing make_timeline to round to tenths of seconds

- util/test_timeline.py
This is a change that allows it to sync the Frost Breaths in O10S properly. Previously it would ignore multiple syncs to the same entry to avoid the issue of spamming one sync repeatedly, but an exception should be made for wide windows where that's potentially the intent.
> util: Fix test_timeline forward syncs

- ui/raidboss/data/timelines/o10s.txt
Technically, I believe these are the flip mechanics:
Coil - first spin, either orientation. 31AC is spin, 31AD is flip
Azure Wings - second spin, either orientation. 31AE is spin, 31B0 is flip
Collectively: Flip/Spin
Azure Wings - hits under the boss into max melee range, changed to In (31B2)
Stygian Maw - hits outside the boss's targetting circle changed to Out (31B4)
Collectively: In/Out
Crimson Wings - hits corners in an X, changed to Cardinals (31B3)
Bloodied Maw - hits a cross to the boss's front, rear, and sides, changed to Corners (31B5)
Collectively: Cardinals/Corners
All final actions together collectively (only shown in the cosmetic fake future parts): Positions
I'm normally very much in favor of leaving original mechanic names in whenever possible, since I believe a timeline …
> Adding O10S timeline

- ui/raidboss/data/manifest.txt
- ui/raidboss/data/timelines/suzaku-ex.txt
- ui/raidboss/data/triggers/suzaku-ex.js
Tested this on four runs and it worked well, added in the targetable/untargetable lines afterwards from logs and I don't imagine that will break anything.
32DD and 32DE are both called Phantom Flurry; the first is the rapid tank hits and the second is the half-arena hit. I've renamed the second one to Phantom Half for clarity. 322E is the boss jump to center, but I've opted to keep it as invisible --sync-- lines since she doesn't actually drop target in that time (bless). 
I've opted to show the 10 Scarlet Hymns (DDR) individually, since it's really the only thing going on, but there's a case to make them two separate durations, for the first 3 and last 7, which come in 1 second intervals with 5 seconds between the two groups. It's debatable. The Hotspots (simon says) are durations since …
> raidboss: Adding Suzaku EX timeline

- ui/raidboss/data/timelines/o10s.txt
- ui/raidboss/data/timelines/o9s.txt
- util/make_timeline.py
- util/test_timeline.py
I had an oversight when I changed make_timeline to use tenths of seconds and noticed inaccuracies when I would run test_timeline against the same exact timeline used to generate them. I sort of shrugged it off until now but I dug in and found the issue. I corrected the Suzaku one with manual adjustments, but 9 and 10 were still affected; these commits fix both the tools and the timelines. Besides the timings, I think the only change is adding un/targetable lines in 10, and some extra info around Protostar. Hopefully this will make the rest of the timelines a little smoother to produce; I'm going to work on 11 and 12 (which I haven't actually entered yet myself) tonight.
> Timeline fixes

- util/make_timeline.py
- util/test_timeline.py
A few small things, mostly just:
1. Fixing the case where casts are from the Environment combatant, which is where ACT couldn't resolve the name of the enemy doing it. These have shown up a bit in 10, but 12 was the first time it broke both make and test, so I added logic to catch those cases.
2. Not printing lines about missing syncs with a large window. Testing the very beginning of Omega+ or whatever we're calling that boss, I noticed it (correctly) indicated it missed syncs for the entirety of the M/F timeline. Having a window over 999 seconds probably means missing those syncs is something expected, so there's no reason to spam it.
> util: Fixing Environment combatant and large-window syncs

- ui/raidboss/data/timelines/o12s.txt
Not only untested in-game, I don't even really know the fight yet! This tests correctly against several fflogs reports along both branches, but in-game viability is a mystery. Will probably need some double-checking later for things that are important in the fight; I think the big eye moves around the outside and we'd probably want a timeline entry for that, for example, but I have no idea what cast it might be. There's quite a few empty-name casts in the fight (formerly Unknown_#### before the xivdb->xivapi changeover), so any one of those could end up being important. We'll see!
I also added just the first minute or so of the other O12S fight as a placeholder.
> raidboss: Adding Omega-M/F timeline

- user/oopsyraidsy-example.js
- user/raidboss-example.js
Small fixes to the user documentation within the example JavaScript for the raidboss and oopsyraidsy modules.
> raidboss: Fixing Typo in Example Documentation

- CactbotOverlay/FFXIVProcess.cs
- ui/jobs/jobs.js
- ui/oopsyraidsy/oopsyraidsy.js
- ui/raidboss/popup-text.js
Updating all references to `GLD` to `GLA` to match the in-game acronym.
Closes https://github.com/quisquous/cactbot/issues/289
> general: Fixing Gladiator Acronym

- README.md
Changes to the main README file to match recommendations from [markdownlint](https://github.com/markdownlint/markdownlint) with some fixes to indentation, etc. to preserve list counting.
Also adding gitter as a means for contributors to communicate outside of GitHub issues. If something else is preferred or gitter is not wanted, we can put something else or remove the badge entirely.
Preview available [here](https://github.com/panicstevenson/cactbot/blob/markdown-changes/README.md).
> style: README Markdown Changes

- ui/raidboss/data/triggers/o12s.js
This only shows the infoText if you do not have the Short Stack, or if it is only on the first DPS player (any future "short stacks" won't show up)
I made it as infoText, because it looked odd having 2 alertText running at once about the same mechanic. having the difference between info and alert made it look a lot cleaner in my opinion.
Not sure if there's a better of doing this, but if there is I'd be happy to change it.
Also, I don't know German, so the translation there is likely wrong - but I did my best.
> Add infoText to show Short Stack on DPS during Hello World

- ui/raidboss/data/timelines/seiryu-ex.txt
- ui/raidboss/data/triggers/seiryu-ex.js
Removed the => and <= as they were being called out with TTS when I tested (maybe was my settings?).
Idea is that cardinal is called where it starts, then it is assumed the player went to the cardinal and stood there and needs to move for the next hand.
Out of middle call is added, but may be removed. It's primary use is to clear up the tracking of the first hand, and second give increased emphasis on the middle circle where the deadly hand will land.
The last Fifth Element is an 18 second cast according to my logs.
> Enrage sync and Handprint Move Callouts

- ui/dps/rdmty/dps.js
Currently, on the "rdmty" overlay the HPS numbers that are shown display the amount of healing that is being done, but does not take the % overheal into account.
This means, that by purely spamming Cure 2 or any other heal on a full hp target, the number would keep growing - even though the effective HPS isn't truly changing.
This change should help reflect better on that, by making it so you see the effective HPS of each encounter.
There's probably a better way to do this, but this has been working flawlessly for the past few months of me using it, so I thought I may as well submit a pull request.
This could break if `combatant['OverHealPct']` somehow doesn't have a formatted number showing "100%" etc, but that hasn't happened yet, in all of my testings.
If you have a suggestion of how I …
> Fix the way HPS is displayed on 'rdmty' overlay

- ui/eureka/eureka.js
fixes the "Uncaught TypeError: Cannot read property 'replace' of undefined" and "Uncaught TypeError: Cannot read property 'style' of undefined" on non-English clients by making sure nm.spawnTrigger[this.options.Language] is only accessed if it's defined
> fix errors in Hydatos on non-English client

- ui/dps/rdmty/dps.js
Healing hps value currently always shows NaN because the healing variable contains a string in parseHealing.
I've added a parseFloat just like formatNumber right below does it.
> dps: Fix rdmty healing meter hps value

- ui/fisher/fisher.js
This should fix #363. Tested with Hedgemole Cricket and it recorded catches after the change, when it was erroring before. The issue ended up being that it was setting `this.fishing` to `false` when the bite happened, and when the fish was actually retrieved. The OnPlayerChange event (which includes bait updates) is set to only change the bait when not currently fishing. Apparently in that time while the reel animation plays, the bait given in memory is some kind of invalid data, and the overlay was respecting that. Now, the bait is locked in, by keeping `this.fishing = true`, until the catch is complete (in `handleCatch` and `handleNoCatch`), which more closely reflects the actual relationship between bait and catch.
> Fixing issue with bait resetting during mooch catch

- util/check_translation.py
- util/fflogs.py
- util/translate_fight.py
- add cn language to fflogs & check_translations & translate_fight
- sort replace text from long to short to solve prefix problem
- remove translate_fight reformatting
What's more:
- as for the replace text with space or hyphen in it, I don't think it will be compatible without changing the runtime `timeline.js` to become case-insensitive. I've tried to add case insensitive to `check_translations.py` and add them to triggers but timeline is translated in the runtime script.
What about adding something like ` text = text.replace(Regexes.Parse('/'+keys[j]+'/i'), r[replaceKey][keys[j]]);` to [timeline.js](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/timeline.js#L55)?
- as for the order of the keys, I managed them in the python script instead of runtime script, python3.6+ will …
> util: add support of cn

- CactbotOverlay/FFXIVProcess.cs
- CactbotOverlay/JSEvents.cs
Updated MachinistJobData in FFXIVProcess.cs (lines 958 - 995)
Updated MachinistDetail in JSEvents.cs (lines 215 - 221)
Fixes support for heat/battery gauge and timers for overheated/rook/queen summons.
> Fixed/Update MCH Job Support

- CactbotOverlay/CactbotOverlay.cs
- CactbotOverlay/CactbotOverlay.csproj
My updated OverlayPlugin doesn't use CefGlue so trying to load Cactbot with that fails right now.
Cactbot either needs to use CefSharp (which I'm using) or drop all references to Xilium.CefGlue.
Switching to CefSharp would break compatibility with the old OverlayPlugin so I'd rather avoid that.
This change should be compatible with both versions. I've tested this change with my updated version but not with the old one. If it breaks, the most likely cause is that trying to execute JavaScript before the page is loaded is silently ignored. In that case I'll have to think of a better solution to the issue.
> Drop all references to Xilium.CefGlue

- ui/raidboss/data/timelines/e2n.txt
Adding additional windows in case there's enough DPS to skip tankbusters. https://github.com/quisquous/cactbot/issues/482
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
> raidboss: Additional Voidwalker Normal Phase Windows

- ui/raidboss/data/triggers/e4s.js
Updates to the Eden's Gate: Sepulture Savage triggers. These triggers are currently untested.
Should have every head indicator, mechanic trigger, fist pattern, and fracture pattern. These are not gospel -- use best judgement; I used the fflogs replay feature to ground assumptions.
Wish List:
Tank swapback
Geocrush position
Bomb explosion order
2x Evil Earth positions for safe corners
Indicate Force needs two stacks for the 8x Force mechanics
> raidboss: initial e4s triggers

- ui/raidboss/data/triggers/e3s.js
Typo fix stolen from @quisquous' stream to properly indicate the tank cone mechanics during the second Tsunami.
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
> raidboss: fixing sweeping waters typo

- ui/raidboss/popup-text.js
Surprisingly, the default TTS I have with Windows 10 can pronounce `inout` and `eastwest` just fine; there's probably a very minor subset of words that this would have been an issue with, but just to save ourselves the future code change.
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
> raidboss: minor tts replacement fix

- ui/raidboss/data/timelines/e1s.txt
The update no one wanted:
* updating the initial Eden's Gravity sync window
* smoothing timeline data aggregated across multiple runs
* adding an additional Mana Slice if warranted during add phase
* updating the final phase and enrage
Timelines aggregated with multiple 10 minute+ kills and wipes, and tested against several of the current fastest clearing reports available.
> raidboss: e1s timeline updates

- ui/raidboss/data/manifest.txt
- ui/raidboss/data/triggers/dun_scaith.js
- ui/raidboss/popup-text.js
This is the result of a week's worth of running and testing. There's still some stuff that could be added, and there are currently no timelines available, but this should cover most of the major stuff. Note that I haven't tested the tank/healer-specific triggers. Apart from an incorrect notification on Flare Star and a similar one on Noctoshield this should be ready for public release.
~~Known Issues
1. Detection on the correct Atomos targets during Ferdiad is not functional. I've isolated the mechanics for how the game works the sphere vs donut, but I'm clearly overlooking something obvious on the detection regex. (This goes for a few of these issues, actually.)
2. Detection on Flameflow. Same issue as 1. There's no way to determine which element is correct apart from checking the 1A log …
> Added Dun Scaith triggers

- util/make_timeline.py
- util/timeline_aggregator.py
Adding functionality to the make_timeline.py util to allow for timeline aggregation/event timestamp averaging.
Updates to make_timeline.py:
* Adding import statement for timeline_aggregator
* Updating print statements to return an array
* Main function call will return expected results to stdout
* Reports can handle a comma-separated list of values to parse multiple fflogs reports at the same time, `-r report1,report2` or `-r "report1,report2"` if you're easily scared without quotes
* Adding argparse option `-at` for the averaging threshold, not required and only used when supplying multiple reports
timeline_aggregator.py:
* Could have a better/more accurate name
* Takes N fflogs reports, uses make_timeline to create the timeline, and returns a new timeline with the event timestamps …
> util: adding timeline aggregator

- .travis.yml
- test/manifest_integrity.py
Add tests for validating the integrity of a manifest.txt file:
Errors:
- An entry in the manifest must exist within the data directory
- A file within the data directory must have a corresponding
manifest entry
Add test to automation via Travis CI.
> Add Manifest Integrity Checker

- resources/timerbar.js
- ui/jobs/jobs.css
- ui/jobs/jobs.js
BLM is a job that relies heavily on exact MP tick timings, since getting
a lucky MP tick early on in the umbral ice phase allows BLMs to skip
needing a second filler spell for mana.
This commit adds support for tracking the MP tick timer. To detect MP
tick events, we hard-code the known constants for MP tick numbers (these
were known even before SHB, which is why I'm hard-coding them as a
percentage of max MP rather than using exact values, even though max MP
is now fixed at 10000).
To continue tracking the MP tick even when mana ticks are disabled (such
as in astral fire) or mana is high enough that excess mana from ticks is
cut off, we extend the timer-bar class to support seamlessly looping the
timer.
The user is able to control the display of this MP ticker as well as
hide it when out …
> jobs: add MP tick timer for BLM

- ui/oopsyraidsy/data/malikahs_well.js
- ui/oopsyraidsy/data/manifest.txt
This one wasn't hard at all. No failure/death conditions in this dungeon, it's remarkably easy overall.
One thing I considered is adding a line comment indicating briefly what the mechanic is. This would look like:
```  
'Malikah Falling Rock': '3CEA', // Boss 1 boulder drops
'Malikah Wellbore': '3CED', // Boss 2 get-out circle
```
etc. I feel like this might be helpful to players who want to disable specific triggers, as they might be able to identify them more easily. (*"Are the ground circles on boss 2 Swift Spill or Geyser Eruption? Hmm..."*) I left that out because that's not really in the spirit of this particular request, but if you think it's okay I'll do a separate request to update the dungeon oopsies with that as a batch next week.
One other thing I also didn't do was to …
> Oopsyraidsy Malikah

- CactbotOverlay/VersionChecker.cs
Fix the regular expression for revision versions within the upstream version checker.
Closes https://github.com/quisquous/cactbot/issues/606
> plugin: Fix Version Checker RegEx for Revisions

- CactbotOverlay/VersionChecker.cs
Update the remote version checker to use the GitHub API endpoint for releases instead of parsing the release page HTML.
Fixes: #609
> plugin: Use GitHub Release API for Version Checks

- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
Took me longer to realize this was the issue I was chasing, but here it is nonetheless.  The regex match for the JP client was missing one of the floats and wouldn't match properly which threw off calculating dragon positions.
> Fixed UCoB regex filter for JP clients.

- test/trigger/test_trigger.js
- ui/raidboss/data/04-sb/raid/o4s.js
Fix incorrect regex string builder string and update tests to be more aggressive in their search criteria.
Update any trigger files found to no longer be in compliance.
> test: Fix Trigger Test Regexes

- .travis.yml
Pin the version for both pylint and requests Python packages to ensure no unwanted changes slip in.
> test: Pin Travis CI Python Dependencies

- ui/raidboss/data/02-arr/raid/t13.js
Fix unreachable code block for Flatten target in Turn 13.
I came across this while adding additional tests. Also makes me wonder if BLU should be included into the healer role (or all roles? kind of gross) since this would be applicable to any fight in which BLU can participate.
> raidboss: Fix Unreachable Code

- test/trigger/test_trigger.js
- ui/raidboss/data/03-hw/alliance/dun_scaith.js
- ui/raidboss/data/04-sb/eureka/eureka_anemos.js
- ui/raidboss/data/04-sb/raid/o12s.js
- ui/raidboss/data/04-sb/raid/o1s.js
- ui/raidboss/data/04-sb/raid/o2s.js
- ui/raidboss/data/04-sb/raid/o4s.js
- ui/raidboss/data/05-shb/dungeon/twinning.js
Make the regex matching for previous tests stricter. Ensure there are no invalid combinations of '.' operators within the trigger regexes. Inform the user when there are instances of matching a single character via the use of groups instead of picking a character from a set.
Note: The former isn't that smart, and can't tell if you've used something like `(?:ABC1|ABC2)`; only if you're using `ABC(?:1|2)`.
> test: Add Additional Tests for Regex Cleanliness

- ui/raidboss/data/03-hw/dungeon/fractal_continuum.js
- ui/raidboss/data/03-hw/dungeon/fractal_continuum.txt
- ui/raidboss/data/manifest.txt
I had thought Fractal Continuum would be an easy introduction to timeline creation, but it very definitely was not. Phantom Ray was the only straightforward part.
Minotaur's timeline is messy due to several interlocking possibilities. The basic Swipe > Swing > Groan > Slash > Swipe rotation is simple enough. The intended flow after this is that he starts a long 1111-Tonze Swing cast, which is then interrupted by opening a cage. This starts a long Feast cast, which leads back into the primary rotation. However, if the cage is not used, Minotaur jumps to the basic rotation immediately after using 1111-Tonze Swing. It's fiddly to get this to work, but it's functional in this release.
There is currently an issue with Minotaur in that it's possible to use a cage early. This will send him to …
> Fractal timeline additions

- ui/raidboss/data/03-hw/dungeon/the_vault.js
- ui/raidboss/data/03-hw/dungeon/the_vault.txt
- ui/raidboss/data/manifest.txt
After the pain that was Fractal Continuum, this was amazingly simple. Everything matches up nicely and I had no issues putting this together.
The inconsistent timings on tank busters vs AoE are to avoid unfortunate overlaps on mechanics. If everything were set to 5 seconds, it could be easy for users to assume that one popup was meant for a different mechanic, if they just go by sounds. The timings are adjusted to account for this as much as possible.
The one thing that could be added would be a popup to tell the user to try to overlap Hyperdimensional Slashes on Grinnaux. I couldn't think of a concise enough way to put it, and it would be spammy because he doesn't target these at a player. Perhaps later on when I feel like doing the math to determine his facing relative to player …
> The Vault--Added triggers and timelines

- ui/jobs/jobs.js
PLD section was incorrectly referring to `blood` in if/else flow, change to oath instead.
> Replace incorrect PLD reference to `blood` with `oath`

- ui/raidboss/data/03-hw/alliance/dun_scaith.js
- ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.js
This was cleaned up in https://github.com/quisquous/cactbot/pull/652, but there were a couple of lingering instances of network ability regexes not ending with a colon.
> raidboss: Ensure Network Ability Regex Ends With Colon

- docs/LogGuide.md
Except Memory parsing stuff, this should include most of the changes since FFXIV 4.58/ FFXIV_ACT_PLUGIN 1.7.2.13
Also as a sidenote (and as i am not 100% sure if/where i should include this)
I spoke with Ravahn on how to finde out if a cast is magic or not and he gave me following information (for loglines 15/16). These information were gathered by the guys of the Sapphire-Project:
For the flags e.g. 710003 (#ability-flags) the first digit decides the type like this:
`damage_type = {
"-1": "WeaponOverride",
"0": "None",
"1": "Slashing",
"2": "Piercing",
"3": "Blunt",
"4": "None",
"5": "Magical",
"6": "Darkness",
"7": "None",
"8": "LimitBreak"
} ` 
while the second digit desiced the element: 
`element_type = {
"0": "None",
"1": "Fire",
"2": "Ice",
"3": "Wind",
"4": "Stone",
"5": …
> Updated LogGuide

- ui/raidboss/popup-text.js
- ui/raidboss/raidboss.js
If we attach the overlay listeners before gPopupText has been set, we risk triggering a "Cannot read property '...' of undefined" error. If we attach them in the constructor instead, we can be sure that the object exists.
Since only one instance of PopupText is ever created, we don't have to worry about detaching the overlay listeners.
This should fix the issue reported in https://github.com/quisquous/cactbot/issues/660#issuecomment-542819459.
I've also eliminated a duplicated call to `cactbotReadDataFiles` which was part of the modified code.
> raidboss: Eliminiate a race condition during raidboss initialization.

- ui/raidboss/data/05-shb/dungeon/mt_gulg.js
Noticed that these triggers were a bit spammy when I ran this the other day, so I went back to add a `suppressSeconds` to the function, but noticed it was already there.
> raidboss: Fix Suppress Trigger Function Spelling

- .travis.yml
There was an issue in #684 with the Node version installed on the Travis CI node being too low. Bump the Node version to instead use the preinstalled version.
> ci: Use Preinstalled Node Version

- ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.js
- ui/oopsyraidsy/data/manifest.txt
- ui/raidboss/data/03-hw/dungeon/gubal_library_hard.js
- ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt
- ui/raidboss/data/manifest.txt
Taking a break  from the (very) slow progress on `make_timeline`, this dungeon ended up being relatively simple.
I'm not terribly happy about the `00` game log lines for the phase changes on Liquid Flame, but as I noted in the timeline file, whichever phase comes second inevitably has multiple `gainsEffect` lines. I couldn't think of a way to clean that up with ACT log lines since the defining abilities (Sun/Moon seal, Magnetism, and Slosh) inside each phase are much too far in to be usable. (Maybe something could be done with `26`? But I didn't really have the time to untangle that one.)
Strix's ability names are too long. I cut "On The" from each to make things fit better, but if there's a better solution I'm much happier to do that. (Especially since this doesn't help at all for the FR …
> Initial Gubal (Hard) triggers and timelines

- ui/jobs/jobs.js
From the 5.1 patch notes:
- Peculiar Light duration has been increased from 10 to 15 seconds.
- Trick Attack duration has been increased from 10 to 15 seconds.
> jobs: 5.1 Buff Duration Changes

- ui/raidboss/data/05-shb/trial/hades-ex.js
Make the callouts for knockbacks happen earlier/not necessarily based off role. Add a 'Move' trigger so people don't eat the 2nd Protean.
> raidboss: Additional Hades Ex Trigger Updates

- ui/oopsyraidsy/data/04-sb/dungeon/ala_mhigo.js
- ui/oopsyraidsy/data/manifest.txt
- ui/raidboss/data/04-sb/dungeon/ala_mhigo.js
- ui/raidboss/data/04-sb/dungeon/ala_mhigo.txt
- ui/raidboss/data/manifest.txt
This one was easy enough. I ended up doing some of the testing for the `make_timeline` changes on this. Magitek Scorpion is boring and a terrible boss.
Aulus Mal Asina is sort of interesting, in that the party members are cloned during the intermission, and everything then happens to the clones. It's fascinating how Square handles these things.
Zenos is just a well-designed battle overall. Each of the phases flows naturally into the next, and it's all put together so cleanly that I never noticed the divisions before deliberately looking for them. The action list within each block is also long enough to disguise the rotation once he is brought under 65% HP, especially combined with the randomizing of Storm and Swell. Square really outdid themselves with this one, and I wish I had …
> Raidboss: Ala Mhigo oopsy, timeline, and triggers

- ui/raidboss/data/05-shb/dungeon/the_grand_cosmos.txt
Apparently if you push Lugus, you can skip the first tankbuster. Also, it appears that if you fail the tether mechanic then you get hit with a different move, 475F, instead of 4760, which can mess up synchronization.
Also, you can skip a Sorching Left/Right if his HP is too low.
> raidboss: Lugus Timeline Updates

- util/make_timeline.py
It's here! Sort of.
(This is in response to #646)
Before we go into details, there's a great deal of room for improvement on this one. It's truly a draft and will need much more input before it's ready to go live. Most of the choices I made on handling various aspects of this had to do with "This was an obvious tool to use from the standard library" or "I just want this to work, we can always clean it up later". I haven't used Python for anything besides personal education before, so this was a bit of an adventure.
Now then. The changes I made involve the addition of an argument, `search_fights` (aliased to `-lf` currently,) which is (intended to be) mutually exclusive with `-start` + `-end` or `-report`. All other arguments should be compatible. 
`-search_fights` takes zero or one …
> Util: make_timeline automation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Add GitHub issue templates to help guide users between their various concerns when opening issues.
An example of what this feature looks like can be seen when creating an issue off of my fork: https://github.com/panicstevenson/cactbot/issues/new/choose
Read more: [GitHub Documentation](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates)
> docs: Add Issue Templates

- util/encounter_finder.py
- util/make_timeline.py
- util/test_timeline.py
Per #719, we have a new file containing most of the additional functionality that was introduced for the `make_timeline` updates. It's a fairly naive implementation as I'm not that familiar with Python's modularization potential, so I just went with what I could easily understand. I kept this solely as a function library rather than making it standalone, since there's *probably* not much reason to just list encounters in a file, and if the user actually does want that, the overhead from using that functionality within `make` or `test` is low enough to be negligible.
It's entirely possible we could move the fiddly bits hunting for the start/end timestamps into a helper function in `finder`, but that gets a little more complicated and would require passing state in as well.
> Util: Move common timeline functions into separate file

- ui/oopsyraidsy/data/03-hw/dungeon/fractal_continuum.js
- ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.js
- ui/oopsyraidsy/data/04-sb/dungeon/ala_mhigo.js
- ui/oopsyraidsy/data/05-shb/dungeon/dohn_mheg.js
- ui/oopsyraidsy/data/05-shb/dungeon/holminster_switch.js
- ui/oopsyraidsy/data/05-shb/dungeon/qitana_ravel.js
Or maybe that should be "extremely urgent". Who knows? Don't even look at Gubal Hard. It's awful. Just push the button on that one.
(More seriously, `console.log` might be worth adding to the test suite as a warning, even as blatantly obvious as it should be.)
I happened to be looking through the Oopsy folder for something else and noticed a couple of points where I had unthinkingly used `role == 'tank'` as a condition. As long as I was going to fix that, I went through all my Oopsy contributions and removed the unused `data` parameter from the triggers.
> Oopsy: Minor fixes

- ui/oopsyraidsy/data/README.md
* Add linting results from running README documentation through
Markdownlint.
* Fix minor spelling mistake.
All changes are minor and do not alter the documentation in a major way.
> lint: Oopsy Raidsy README Documentation

- AdvancedCactbot.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/LogGuide.md
- docs/MemorySignatures.md
- docs/TimelineGuide.md
- ui/raidboss/data/README.md
Update various Markdown files in accordance with Markdownlint's
suggestions. Changes related to spacing were added via Markdownlint's
--fix option, while other changes were mostly implemented manually. As
for the code block language distinctions, I picked what seemed
reasonable for each type, opting for `bash` as the option for the
timeline output, seeing as that gives it _some_ color, but nothing too
distracting.
Spelling changes were done manually.
Markdownlint can be added to automation eventually, but there are still
some decisions that need to be made before that happens, namely:
* Unordered list convention is not consistent.
* Markdownlint picks whichever is the first used unordered list
character, and assumes that should be used everywhere. Some files
begin with dashes, and others …
> lint: Initial Markdownlint Changes

- .travis.yml
- AdvancedCactbot.md
- package.json
- resources/lang.js
- resources/regexes.js
- test/run_tests.py
- test/test_triggers.py
- test/trigger/test_trigger.js
- test/unittests.py
- test/unittests/regex_test.js
- ui/raidboss/data/04-sb/raid/o5n.js
- ui/raidboss/popup-text.js
Adds a number of regex helper functions that all take a dictionary of optional fields.  Fields can be filled in optionally with strings/regular expressions/arrays of multiple values.  If field values are unspecified, it will match anything.
Each dictionary of fields can also specify `capture` as a boolean variable.  If not specified, capture is true.  If capture is true, then everything in the regex will be captured as a named group (with the same name as the field that would have specified it).
Examples:
* `Regexes.losesEffect({effect: '(?:Doom|Forked Lightning)'})`
* `Regexes.startsUsing({id: ['1C7F', '1C90'], name: 'Deathgaze Hollow', ability: 'Void Death'})`
* `Regexes.ability({name: 'Caduceus', id: '4B8', ability: 'Hood Swing'})`
Fixes #543.
> Add canned regex helpers

- ui/oopsyraidsy/data/03-hw/dungeon/aetherochemical_research_facility.js
- ui/oopsyraidsy/data/manifest.txt
- ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.js
- ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt
- ui/raidboss/data/manifest.txt
This one's not quite as good as I would like, but I'm not sure what the best way to resolve that is. No issues with Oopsy or triggers, but unfortunately the Ascian Twins timeline is messy. Because it's a two-enemy boss, and the bosses are on separate + unequal timer loops, each phase will desync the longer it goes. Apologies for the wall of text (this is from Lahabrea, HP < 75%, but it's representative of both bosses' HP < 75% phases:)
```
2354.113: Matched entry: 2354.0 Dark Fire II (-0.113s)
2359.195: Matched entry: 2359.1 Dark Fire II (-0.095s)
2364.269: Matched entry: 2364.2 Dark Fire II (-0.069s)
2373.388: Matched entry: 2373.4 Dark Fire II (+0.012s)
2374.601: Matched entry: 2374.6 End Of Days (-0.001s)
2382.512: Matched entry: 2382.5 Shadow Flare (-0.012s)
2388.077: Matched entry: …
```
> Raidboss: ARF initial dungeon package

- ui/raidboss/data/02-arr/raid/t9.js
- ui/raidboss/data/04-sb/alliance/ridorana_lighthouse.js
- ui/raidboss/data/04-sb/raid/o4s.js
- ui/raidboss/data/04-sb/raid/o9s.js
- ui/raidboss/data/05-shb/raid/e3s.js
Fix instances where the number of capturing groups don't match up with
the number of times matches is called. Most instances are pretty
inconsequential, especially since every practically every regular
expression going forward will have more groups captured than used.
> raidboss: Fix Mismatched Capturing Groups

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.txt
Added x6 to Splash to mirror Tumults in e4s, I propose to make this a duration timer as well.
Adjusted some of the later timers for the Cruise Chaser transition with new logs.
Comments for phases and transition titles.
Based on these logs:
https://www.fflogs.com/reports/rGj4dhJZv2nQmBFP#fight=23
https://www.fflogs.com/reports/kWpGy7gKPNJ3jrYH#fight=18
Edit:
Twitch VoD for the first set of logs - https://www.twitch.tv/videos/508191550?t=07h22m50s could be useful for trigger development.
> Add remaining timers for TEA

- ui/raidboss/data/05-shb/raid/e3s.js
The regexes are missing a `'for '`. It was brought up on the discord by Shira#9825.
> raidboss: Fix e3s Smothering Waters regexes

- ui/fisher/fisher.js
Hiya, following a discussion on the ACT discord, the current fisher overlay doesn't handle undiscovered fishing holes very well.
I'm not very confident with the chinese regexes I've added, but I was able to test the en/fr/de/ja entries.
@xephero If you would like to look this over I'm open to any comments you may have.
Thanks!
> fisher: Add support for undiscovered fishing holes

- resources/lang/cn.js
- resources/lang/de.js
- resources/lang/en.js
- resources/lang/fr.js
- resources/lang/ja.js
- resources/lang/ko.js
- resources/regexes.js
- test/unittests/regex_test.js
- ui/jobs/jobs.js
Hiya,
I've added 0xC log line support for the jobs overlay as requested in #595. It runs the setupJob() functions with a default 2.5s gcd, then as soon as we see `0C: Player stats:` (usually instantly, unless you reload the overlay manually) it updates the relevant variables. It has support for every status affecting GCDs; I added bare bones support for BRD, NIN, WHM and SAM purely for feature completion.
I'm not really confident that the statChangeRegex in `regexes.js` matches the surrounding functions' style, and I'm open to feedback on that especially.
> jobs: use 0xC player stats log line to determine gcd 

- user/jobs-example.js
Forgot to remove these earlier, sorry.
> jobs-example.js - Remove GCD vars from Options

- CactbotOverlay/VersionChecker.cs
Replaces the regex matching with a call to
```C#
System.Diagnostics.FileVersionInfo.GetVersionInfo(plugin.pluginFile.FullName).FileVersion
```
Thanks!
> plugin: VersionChecker - replace regex matching with GetVersionInfo call

- CactbotOverlay/FFXIVProcessCn.cs
- CactbotOverlay/FFXIVProcessIntl.cs
Hiya,
Another bug introduced during #750. 😭 
Level should be an 8-bit int, not 16. Was causing undefined errors in jobs, and probably a lot more..
> plugin: level fix

- ui/raidboss/data/03-hw/dungeon/gubal_library_hard.js
- ui/raidboss/data/04-sb/raid/o4n.js
Per #838, this fixes the diametrically wrong Ferrofluid trigger. Also threw in a change for Exdeath normal, as I happened to run that tonight and saw that the tank buster doesn't work as I thought it did. (Instead of "Exdeath casts buster on tank", it's "Exdeath casts buster on Exdeath, and at the end of that cast, instantly uses buster on tank". Because of this, there's no way to reliably extract the correct target. I'll probably revisit this when I get around to doing a timeline for this one, use the new party data to figure out which tank has threat, and adjust the callouts from there.)
> Raidboss: Gubal Hard and O4N fixes

- ui/radar/radar.js
"forgiven pedantry" doesn't have a cn name so take en for default.
> radar: add default monster name

- resources/lang/ko.js
- ui/raidboss/data/00-misc/general.js
- ui/raidboss/data/00-misc/test.js
Thanks for updating cactbot supports Korean. I have tested test.js and it worked well except playing tts and sound file.
and may I ask a question?
Dose it need in translating raidboss triggers to match exactly '~effectNames' with in-game data like 'Physical Vulnerability Up'? I saw translated titania and innocence triggers and find some difference.
> add Korean supports to resources/lang, raidboss\data\00-misc

- CactbotOverlay/CactbotEventSourceConfig.cs
- resources/user_config.js
C# `Dictionary`s throw an exception if a missing key is accessed. I used `TryGetValue` to avoid that.
The `JToken` objects behave as expected (a missing key just returns `null`).
Finally, I had to change `user_config.js` because it tried to access a property on a `null` value when `cactbotLoadData` returns `null`.
> Fix the new user config for users who haven't used it, yet.

- resources/common.js
Minor changes:
- GNB listed as a job that can silence twice
- CNJ incorrectly listed as a job with Addle
- ARC missing from the list of ranged DPS jobs
> plugin: Update Common Job Lists

- CactbotOverlay/CactbotEventSource.cs
- CactbotOverlay/VersionChecker.cs
Following the submission of #908 and #906, it's common that the Korean FFXIV_ACT_Plugin dll is being renamed. 
Using the FFXIV_ACT_Plugin's game language setting is also a reliable check, as although it isn't a true check of the region, the international client doesn't have Korean language support and so should only be set as such on a Korean client.
> plugin: Revert korean region check and just use FFXIV_ACT_Plugin's language setting

- resources/hunt.js
I know it says not to edit this file directly, but the data gathered directly from the gamefiles includes placeholders for german grammar.
So for now this fixes the incorrect names so they are detected. 
However the underlying problem needs to be fixed in the python script parsing the game files, but I am not sure how to do it as there is no fixed grammar rules for each placeholder as they are determined by gender and other things regarding it's target.
> Fixed incorrect german names for hunt targets

- ui/raidboss/raidemulator.html
Pretty self explanatory.
This fixes errors like this one:
```
BrowserConsole: Uncaught TypeError: Cannot read property 'E1S Initial' of undefined (Source: file:///.../ui/raidboss/popup-text.js, Line: 330)
```
> Add missing raidboss_config.js to raidemulator.html

- ui/raidboss/data/05-shb/raid/e3s.txt
I tried to parse cactbot's timeline files for a little tool of mine but found that naive parsing of spells from the timeline failed because of some formatting errors.
I guess these are unwanted and just happened to be there and not upset cactbot's parsing so I suggest to unify them.
> WIP: raidboss: Fix formatting in e1/e3 timelines

- ui/radar/radar.js
Quick change to update monster position when (re-)detected, mainly for B ranks but works for all monsters.
This fixes the situation where (example):
1. You're scouting and gets in range of a B rank.
2. Radar detects B rank and adds it to the list.
3. You fly out of range as you continue scouting.
4. B rank gets killed while you're out of range, causing it to respawn somewhere else.
5. You get in range of said monster's new position.
6. Radar doesn't update the position because the old one is "still alive".
This small change makes it so the radar update the B rank's position in example above. Updating the position in realtime would be suitable but I don't know enough to code it. This should however be enough as hunts don't move too far anyway.
> Update monster position

- ui/radar/radar.js
Adds a missing dom update when the monster is pulled.
Allows for the puller name to appear immediately without needing to nudge a bit to see it.
> radar: Add missing dom update on pull

- ui/radar/radar.js
I spotted options wasn't being passed to PlaySound after the cleanup was reverted, this commit re-adds it.
Reason the cleanup broke PlaySound is because of lines 116-119, which creates a local version of the variable options, which is then used for PlaySound.
> radar: pass options to PlaySound

- test/unittests.py
- util/check_translation.py
- util/encounter_tools.py
- util/gen_fisher_data.py
- util/gen_territory_type.py
- util/gen_weather_rate.py
- util/make_timeline.py
- util/test_timeline.py
- util/timeline_aggregator.py
- util/translate_fight.py
Initial pass at using [black](https://github.com/psf/black) to format the Python code in the repository; there is a lot left out, because this was done without the single to double quote conversion or taking line-length into account in order to reduce noise and catch any possible issues or other ways to clean up code without resorting to line breaks, and to increase individual pull request readability.
> lint: Initial Python Formatting

- CONTRIBUTING.md
Update the issues link to point to the templatized version of the issues
page to hopefully encourage using issues that automatically label
themselves.
> docs: Update Issues Link

- util/check_translation.py
This will prevent the `json.decoder.JSONDecodeError` if the last element of a timeline replacement ends with ` // FIXME`
> fix issue when //FIXME is the last element

- ui/raidboss/data/03-hw/alliance/dun_scaith.js
This fixes a small issue with the `alertText` functions in two Dun Scaith triggers. During the regex overhaul the conditions were changed to check the wrong match groups.
After this change the alerts show up in the emulator again. Haven't done any further tests.
I'll see if the other two recently reported trigger issues are caused by similar mistakes.
> Fix alertTexts for Dun Scaith

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
This should fix the Nisi and Inception formation RegEx that had ":" without a space beforehand. I've also added some extra translations!
> TEA Nisi & Inception French trigger fix + translations

- plugin/CactbotOverlay/Properties/AssemblyInfo.cs
CactbotOverlay wasn't bumped in the 0.15.3.0 release and still shows as 0.15.2.0.
> Bump CactbotOverlay to 0.15.3.0.

- plugin/CactbotEventSource/FFXIVPlugin.cs
There is no need to find FFXIV_ACT_Plugin_Korean.dll anymore.
> FFXIV_ACT_Plugin_Korean.dll is not needed

- ui/raidboss/popup-text.js
Korean TTS reads wrong with '1번째'. Force it to read it right.
it's now reading it as '한번째' but it should read as '첫번째'
> Korean TTS 1번째

- test/test_timelines.py
- test/timeline/test_timeline.js
Adding this as a proposal to make timeline text replacement easier to understand.  Right now, timeline translations apply in key order, and keys are regexes.  This is definitely confusing, and @Akurosia resorted a lot of them in #986 and #987, which creates some risk that translations that used to work no longer work (if they ever did?)
This pull request adds the stipulation that if you have two translations of the same text and both of them match the text, then they must be able to be applied in either order and get the same result.
For example, it's ok to have the text "Magnetism/Repel" and then have a translation for "Magnetism" and "Repel", because you can apply those in either order.  It's not ok to have text "Savage Wave Cannon" and then have a translation for "Savage Wave Cannon" …
> Add timeline tests for text replacement uniqueness

- ui/raidboss/common_replacement.js
- ui/raidboss/raidboss.html
- ui/raidboss/raidemulator.html
- ui/raidboss/timeline.js
I've done some code with common replacement.
`ui/raidboss/timeline.js` part can be improved much, but I don't know how this code exactly works. I've just added new function, but it's having error.
Suggestions to this code is needed.
```
TypeError: Cannot read property 'Language' of undefined
at Timeline.GetReplacedCommon (/home/travis/build/Jaehyuk-Lee/cactbot/ui/raidboss/timeline.js:61:31)
at Timeline.GetReplacedText (/home/travis/build/Jaehyuk-Lee/cactbot/ui/raidboss/timeline.js:71:17)
at Timeline.LoadFile (/home/travis/build/Jaehyuk-Lee/cactbot/ui/raidboss/timeline.js:166:20)
at new Timeline (/home/travis/build/Jaehyuk-Lee/cactbot/ui/raidboss/timeline.js:37:10)
at Object.<anonymous> (/home/travis/build/Jaehyuk-Lee/cactbot/test/timeline/test_timeline.js:22:16)
at Module._compile …
```
> add common replacement

- plugin/CactbotEventSource/FFXIVProcessKo.cs
I think @quisquous changed signature in `FFXIVProcessKo.cs` to match with v5.2 patch mistakenly.
> KR v5.0 fix

- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
- ui/raidboss/popup-text.js
I think those replaces needs "global".
`In => Out => Spread`
`↖ Front left / Back right ↘`
these things don't need exceptional tts after this change.
Also, I've removed tts in UCU those doesn't need to be.
(Those are the same as text or ttsText replacer changes well.)
> add global to tts replace regexes

- ui/raidboss/data/05-shb/raid/e5s.js
`E5S Stratospear Summons` can be changed to timelineTrigger, but there's no timeline now, so I added there. (Only the first *Stratospear Summons* (4BA5) is needed.)
There's something needed to be fixed. `E5S Stepped Leader` has problem, it only alerts `data.leaderCount %2 == 0` (ready spread). I believe this logic should do both. Strangely, `E5S Stepped Leader Spread` is working well. only when `data.leaderCount %2 == 0`, it says to Spread.
I don't know why this happens..
Other things are all working fine. I've tested so many times with melee DPS. (So, I didn't actually tested `E5S Crippling Blow` but, it should be fine.)
> e5s triggers

- util/test_timeline.py
Per #1062 this should resolve the error if the user attempts to test against a fight without a timeline selected. I'm not 100% sure it's correct to order the errors like this, but I think it's clearer this way.
> Util: Added missing parser error to test_timeline

- ui/raidboss/data/05-shb/raid/e7s.js
Work in progress. I think there's an error in the XIV files when it comes to adds name in French, which I expect to be fixed in a future patch. Blashemy and Idolatry currently have the same name in-game: https://i.imgur.com/fnkXoNP.jpg
> FR RegEx for E7S

- util/check_translation.py
Otherwise, it'll read `Fate Projection α` as `Fate Projection 伪`, which is confusing when I try to translate lol.
> util: fix file encoding

- ui/fisher/fisher.js
The fishing spot/place during ocean fishing changes while fishing. Set it on every cast regardless of whether it has already been set to handle this.
This should also fix #1075 as the ocean fish data has already been added.
Only tested in one voyage but it worked, and regular fishing looks like it still works.
> ocean fishing fix

- ui/raidboss/data/05-shb/raid/e6n.txt
No triggers alongside this yet, I'll probably have those soon enough. Minimal testing went into this etc.
Ferostorm is not synced because there are multiple different ability IDs to go with it. (I believe each cardinal direction can be one, in much the same way Double Sever in Fractal Continuum, or Port/Star and Fore/Aft in Temple of the Fist have separate IDs for each direction.) Rather than try to find all the correct IDs for both Garuda and Raktapaksa, I figured it was better just not to sync at all. [(The syncs are commented out rather than deleted so that if we do translation work based on timelines in the future, we still have those ability IDs available.](https://github.com/quisquous/cactbot/issues/749#issuecomment-557830256))
> Raidboss: Initial e6n timeline

- ui/raidboss/data/05-shb/raid/e5s.js
Raise infoText level alerts for getting an orb to alertText if you don't
already have one.
> raidboss: Increase Alerts for Getting Orbs in E5S

- util/timeline_adjust.py
It's the tiniest of tiny nits, but every time I go to adjust a timeline I forget that the arguments aren't aliased. No more forgetting!
> Util: QoL adjustment for timeline_adjust

- ui/raidboss/data/05-shb/raid/e6s.js
- ui/raidboss/data/05-shb/raid/e8s.js
Update matches.target and matches.source trigger notifications to use
the short name as opposed to using players' full names.
> raidbosss: Update Matches Names to Use Short Name

- resources/responses.js
I did a few searches and couldn't find any other uses in the repository, so I think we're safe to change this. E6n will most likely be a near-future use once I get the triggers working for that.
> Resources: Spelling fix for responses.js

- ui/raidboss/data/05-shb/raid/e6n.js
- ui/raidboss/data/05-shb/raid/e6n.txt
As with E5n, most of this is shamelessly stolen from elsewhere in the repository. I think I caught all the changes necessary, but I can't test the tank/healer triggers due to not being comfortable in this content with those roles. Everything that I was able to test functions as expected. Timing on targetable/untargetable lines may need slight adjustments.
To do:
1. Math out Ifrit's jump after Strike Spark, so we can tell the user the direction instead of just a simple warning.
2. Warn the user of the surprise Eruptions alongside Enumeration + Hands of Hell. (It's going to be just complex enough to call that I'm leaving it out for now, but it's one of the MAJOR sources of deaths in pickup runs. I'm actually a little surprised Square included it in a normal-difficulty encounter.)
> Raidboss: Initial E6n triggers and updated timeline

- ui/raidboss/data/05-shb/raid/e7n.js
- ui/raidboss/data/05-shb/raid/e7n.txt
As it turns out, counting is hard. The color triggers will no longer fail to warn the user on the third application of darkness/light. The color tracking will also clean up after itself now. (I deliberately added the ability name to the cleanup trigger so it was clear what ability was being used without doing a lookup.) Also a small but significant correction to re-targeting time after the intermission.
> Raidboss: E7n minor updates

- resources/party.js
- ui/raidboss/autoplay_helper.js
- ui/raidboss/browser_tts_engine.js
- ui/raidboss/popup-text.js
- ui/raidboss/raidboss.css
- ui/raidboss/raidboss.html
- ui/raidboss/raidboss.js
- ui/raidboss/raidboss_config.js
- ui/raidboss/raidemulator.html
Allow overriding player name and playing TTS through browser when using raidboss overlay with websocket. Example query string:
`&player=Some%20Person`
If that person is in your party, raidboss will display the same timeline as normal, but give callouts for that person and their job instead of the person hosting the ACT/Overlay/WS/Cactbot instance.
Text to Speech is done via google services as that was the simplest to implement. Audio should only be fetched once per TTS string per page load.
Initial tests for this functionality are good but haven't had a chance to do extensive testing yet.
> Raidboss player name override features

- ui/raidboss/data/05-shb/raid/e6n.js
Thanks to @mooondark for catching the error. This should resolve the Normal side of #1155. Going forward I will *always* copy/paste into regex placeholders!
> Raidboss: E6n Ferostorm fix

- ui/raidboss/data/05-shb/raid/e7s.js
The condition only runs if you're the target, leaving the tether list to
be undefined at Betwixt Worlds Stack markers.
Fixes https://github.com/quisquous/cactbot/issues/1161
> raidboss: Fix E7S Betwixt Worlds Tether Condition

- ui/raidboss/data/05-shb/raid/e8s.js
- ui/raidboss/raidboss_config.js
- Players can dodge both knockbacks if action is used during boss' turn to attack target.
Example: https://clips.twitch.tv/CreativeDreamyAsparagusKlappa
Log with earliest: https://www.fflogs.com/reports/rYgBcTKLkNqHdPmF#fight=9
Log with latest: https://www.fflogs.com/reports/rYgBcTKLkNqHdPmF#fight=7
In this situation, tanks have to adjust for mirrors everyone else can stay put. There could be callouts for the tanks to adjust to mirror, but the timing for all this is very quick.
I suspect the latest possible reaction time is 1.4s, but the best log I have is a 1.337s.
> raidboss: e8s mirror 4 uptime knockback callout

- ui/oopsyraidsy/data/05-shb/raid/e6n.js
Standard stuff for the most part.
Known deficiencies:
1. Storm of Fury tethers. It's going to be a bit of work to figure out overlap tracking for this one, since checking for double-taps won't work. (It's not a mistake for multiple people to be hit by an individual cone.) Currently I'm thinking of something like pre-collecting the tether targets, then collecting all cone targets, seeing whether there are duplicates, and THEN seeing whether the tether targets are *also* in that list of duplicates. A lot of code for one thing, and there's gotta be a better way.
2. No handling for Hands of Hell. I'm not really sure what we want to do with it, so I left it alone for now.
3. Ferostorm IDs might be incomplete? I'm not sure. I'm wondering whether the actual cones have only one ID, and then the …
> Oopsy: E6N initial

- resources/responses.js
- test/trigger/test_trigger.js
- ui/raidboss/data/00-misc/test.js
- ui/raidboss/data/README.md
- ui/raidboss/popup-text.js
This PR adds support for async triggers. A trigger can define a `promise` property which should be a function which returns a `Promise`. This is in response to @quisquous comment here: <https://github.com/ngld/OverlayPlugin/pull/116#issuecomment-593735692>
An example trigger might look like this:
```javascript
{
id: 'Test Trigger',
regex: Regexes.ability({ id: '1234' }),
condition: function(data, matches) {
return true;
},
promise: function() {
let p = new Promise((res) => {
window.setTimeout(() => {
res({
name: "Testing",
});
}, 1000);
});
},
infoText: function(data, matches) {
let name = matches.name;
return {
en: 'Test Trigger: ' + name,
};
},
},
```
With the `window.setTimeout` being replaced by some other async function as needed.
> - Add async support for triggers

- resources/lang/cn.js
- resources/lang/de.js
- resources/lang/en.js
- resources/lang/fr.js
- resources/lang/ja.js
- resources/lang/ko.js
- ui/oopsyraidsy/data/05-shb/raid/e7n.js
- ui/oopsyraidsy/oopsyraidsy.js
There aren't a lot of mistakes to be made in this encounter either. (Or, more properly, there are only a LOT of variations of a few categories.)
I'm really not happy with the handling for Dark's/Light's Course. There's gotta be a better way than spending five(!) triggers on two mechanics. However, I'm hesitant to move any of that functionality in-line since we tend to keep things separated elsewhere in the repository. Improvements to this mess would be welcome. (Also, anything we do here "should" be a suitable drop-in for Savage once the ability IDs are switched out.)
Another thing that could use improvement, as I mentioned in-line, is that I don't like the regex soup I used to check for damage events on Course casts. Should I have used the `regex: Regexes.ability()` construction here …
> Oopsy: E7N Initial

- ui/raidboss/popup-text.js
This PR is to fix a bug found with the new async trigger functionality while testing my e6s football trigger. The bug only happens if a trigger has a `promise` function.
> Fix issue with async trigger promise call not referencing this

- ui/raidboss/data/05-shb/raid/e8n.js
Also included is a fix to ensure that the Scythe Kick trigger will fire whether or not mirrors are active.
> Raidboss: E8N mirrors are now correctly suppressed.

- resources/responses.js
add Japanese translation for response.js, and fix some wrong translation.
But I am not sure what I thought about [`Dorito stack`](https://github.com/quisquous/cactbot/blob/8f0d54547fa91151639b42d944006a94b8b71443/resources/responses.js#L324), the Chinese translation is not clear so I cannot confirm.
Was it meaning that a gimmick shown reversed triangle mark on several members and the marked member should be stacked together, or they would die?
> add japanese translation for response.js

- ui/raidboss/data/05-shb/raid/e7n.txt
I've noticed this one seems to be *very* inconsistent on whether or not it starts. I think it's because I initially put down slightly narrower starting windows than I should have. After the changes, it seems much happier. (The post-intermission rotation block is already fairly well covered for syncs, and I've never noticed any issues there.)
> Raidboss: E7N additional timeline syncs

- docs/TimelineGuide.md
This update contains three independent elements:
1. Changed the information on sync windows to reflect current usage.
2. A throwaway capitalization change if the word "cactbot" appears as the first word of a sentence. (It doesn't really matter, but I was editing the file, so in it went.)
3. Information on `-lf`. Best to have that documented in this file.
(Maybe we should expand the command line arguments information into its own section, since it cuts across both of the timeline utilities in the guide?)
> Docs: Updates to timeline guide

- ui/raidboss/data/04-sb/raid/o4n.js
Nothing major here, just some necessary cleanup. The Thunder 3 cleave warning is returning "avoid tank cleave" even for tanks, which is kind of weird. I haven't been able to figure out exactly why though, looking through `responses.js`, it *looks* like tanks are explicitly special-cased to just warn about cleaves.
> Raidboss: O4N trigger updates

- resources/responses.js
Per [some previous discussion](https://github.com/quisquous/cactbot/pull/1281#issuecomment-604507116), this should remove any ambiguity in how the `tankCleave()` response works. Do we need to explicitly check that `target` is defined? I feel like no, but there might be something I'm not thinking of.
> Resources: Minor fix to Responses.tankCleave()

- test/trigger/test_trigger.js
- ui/raidboss/data/00-misc/test.js
- ui/raidboss/data/README.md
- ui/raidboss/popup-text.js
In particular, delaySeconds runs, and the promise trigger field itself is not evaluated until after the delaySeconds.
Requested in #1269.
> raidboss: have delaySeconds in triggers run before promise

- docs/RaidbossGuide.md
I'm so sorry, that bit about handling the `response` element didn't actually make it in, I was assuming it was still in question. This actually adds it, as well as localizing the `tts` element.
> Docs: Small addition to Raidboss readme

- ui/oopsyraidsy/data/05-shb/raid/e7n.js
I'm not sure how this happened, but I'm guessing it was a copy/paste error when we redid the oopsy triggers to use regex replacements.
> Oopsy: E7N Light's Course fix

- resources/responses.js
- Several friends who speak good English have told me about my mistakes. So we are meeting to discuss this.
After a very long debate on the mechanics and announcements to be made, we decided to make these changes.
- Some words like (spread) or (stack), they complicated, because there are different lines with these words. In order to keep the same word for each line using it, some have been conjugate and others have been transformed.
- (package, packez) have been deleted because the definition is not correct. (package) Only concerns objects or files, but I could accept it.
- the rest has been simplified while remaining logical.
- I think that a party of French players who raid put FFXIV in English, and I would like those who put it in French to benefit from the calls in French. If (spread, …
> Respons.js correction Fr

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
This should resolve #1346 . The fix introduced for the 5.2 scrambling of the TEA markers had a ridiculously subtle bug. As the comment notes, any time the initial head marker is `004F`, the offset is zero. Since zero is falsy, this collides with the naive check for "did we find the offset yet?" This wasn't a problem in 5.2 content, since the odds of hitting That One Instance where the offset was actually 0 are extremely low. No surprise it wasn't noticed until people had to do this on 5.1! 
Many thanks to quisquous for taking the time to look through this and point me in the right direction. Thanks Jaehyuk-Lee for the bug report!
> Raidboss: Fix for broken TEA headmarker fix

- plugin/CactbotEventSource/CactbotEventSource.cs
- plugin/CactbotEventSource/FateWatcher.cs
Add the missing OPCodes for KR/CN regions.
I've confirmed the KR opcode with @Jaehyuk-Lee, I'm assuming the CN opcode is the same until 5.2.
This should fix #1359.
> plugin: Add cn/kr FATE opcodes

- ui/raidboss/data/03-hw/trial/sephirot-ex.txt
Per #1328, this is the first of some updates that will be needed before that can go through.
Shasta and DnT did great work at the time, but the Heavensward timelines they graciously put together are extremely outdated. With some help from quisquous, we now have a modernized Sephirot EX timeline.
(Note that there are two abilities, `Gevurah Chesed|1578` and `Chesed Gevurah|1579`. I'm not 100% sure of the difference, but I'm relatively sure it has to do with who gets what color debuffs. Regardless, because having multiple different variants of "Chesed" in the translation object is painful, I opted to have all instances of either be displayed as "Chesed Gevurah". If someone who knows Hebrew has improvements I would gladly integrate that.)
Potential deficiencies:
1. Zero live testing. I've …
> Raidboss: Sephirot EX timeline update

- ui/eureka/eureka.js
remove these characters on map ![ffxiv_20200423_211302_148](https://user-images.githubusercontent.com/4695371/80098090-4280ee80-85a7-11ea-9026-b4906d5b6225.png)
party member's \<flag\> chat -> those party member's number also printed on map
one better Korean label name.
> eureka: remove character name on map

- docs/RaidbossGuide.md
- ui/raidboss/popup-text.js
This PR refactors the `PopupText` class's `OnTriggerInternal` function to move functionality to subfunctions. This results in cleaner code and allows the raid emulator redesign that I've been working on to override the time-sensitive portions of the functionality with its own logic for pause/seek support.
> Refactor PopupText class for new raidemulator support

- util/find_missing_translations.py
this prevents following error: `TypeError: 'in <string>' requires string as left operand, not NoneType`
> fix filter on find_missing_translation if no filter argument is provided

- ui/eureka/eureka.js
Flauros was requested in #1393, while Goldemar was spotted during review of all fates.
> Eureka: Add missing FATE reqs to Flauros/Goldemar

- ui/oopsyraidsy/data/00-misc/general.js
I added this line (Ja) which did not exist, and I have just seen another translation in newly created lines. I therefore correct for more consistency.
If the translator (ja) wants to comment, it's welcome. Picture taken in (ui / eureka / eureka.js)
> Correction Jap general.js

- ui/raidboss/popup-text.js
Part of the code review for #1366 was to invert the logic of the _onTriggerInternalCondition method to return false if the condition check fails. This PR changes the logic of the _onTriggerInternalCheckSuppressed method to return true if the trigger is suppressed, which more closely matches the expectation of the method name.
> raidboss PopupText class suppressed check logic

- util/make_timeline.py
I've forgotten the `Engage!` sync on way too many timelines already. Rather than improve my memory, I'm instead opting to be constructively selfish here.
> Util: Tiny QoL fix for make_timeline

- util/make_timeline.py
This permits the user to generate timelines with precisely-timed  `targetable/untargetable` entries baked in. It's rather a pain to hunt through the log and manually add these, so based on an idle suggestion from quisquous the other day I went and added it.
I played with it a little, but I don't like working with `argparse` much, so for now `include_targetable` is only an explicit allow list. (Passing as a bare flag has no effect, and honestly unless Square comes up with something *really* out there, I don't think it's necessary to just display all nameplate changes.) Suggestions welcome, since I mostly slapped these changes together over lunch earlier today.
Sample output from Sophia's intermission:
```
102.4 "Cloudy Heavens" sync /:Sophia:19BE:/
103.6 "--untargetable--"
112.7 "Vertical …
```
> Util: Basic support for 34 network log lines in make_timeline

- resources/regexes.js
Missed `job` and `level` capturing groups for Regexes.addedCombatantFull.
I'm still working through converting the regexes for #1387 to use `Regexes` functions.
> Fix job and level capture missing from Regexes.addedCombatantFull

- docs/RaidbossGuide.md
(This will resolve #1460.)
Per panicstevenson's [comment](https://github.com/quisquous/cactbot/pull/1458#discussion_r429465012) and #1460, I've added a short paragraph indicating that context is now recommended for triggers included in the cactbot repository.
I added this alongside the id field information, since that's usually where *I* put it, but if we think it should be moved elsewhere, we could put it after the description of the regex fields.
Wording advice/changes welcome!
(I'll probably do something similar for Oopsy, but given that only 2-3 people seem to be actively working with those files right now, it's less of a priority.)
> Docs: Added recommendation for contextual trigger names in Raidboss

- util/encounter_tools.py
- util/test_timeline.py
I originally combined these two functions in #755, but after some work in November on translation stuff, it became clear that this probably wasn't ideal. In preparation (I *hope*) for some actual progress on translation utilities this summer, I'm just tossing this change in now.
> Util: De-combine the clean and split timeline functions in encounter_tools

- ui/raidboss/data/03-hw/raid/a3s.txt
Remove timeline entries because the timeline currently shows double Hydromorph while leaving adds phase.
> raidboss: Remove Duplicate Timeline Entries

- ui/raidboss/data/05-shb/trial/titania-ex.js
- ui/raidboss/data/05-shb/trial/titania.js
Added corrections all language.
Added missing translations fr.
Added missing sync fr, ja, cn,  on titania normal.
Added missing sync fr, ja, cn,ko,   on titania ex.
Removed double lines and `missingtranslation=true` useless.
> Raidboss: Titania normal and ex

- .travis.yml
- test/test_timelines.py
- util/encounter_tools.py
- util/gen_hunt_data.py
- util/make_timeline.py
- util/test_timeline.py
- util/timeline_adjust.py
Past pull requests to enable linting (https://github.com/quisquous/cactbot/pull/978) did not properly enable failing on lint failure within CI systems; update existing code base to conform to [black](https://black.readthedocs.io/en/stable/)'s standards of pythonic beauty and enable failing within CI on unformatted Python code to prevent further drift.
> ci: Update Python Linting

- README.md
Update Travis CI build status badge to instead point to GitHub Actions' Test workflow off master. Add badge noting the latest semver release, redirecting to the Releases page.
> docs: Update GitHub Badges

- util/encounter_tools.py
This should resolve #1498. It's unlikely Square will implement many more two-part encounters, and since most players deliberately wipe after checkpoints for a clean reset, this will work for 99% of content. For the other 1%, we still have the old start/end flags available for manual usage.
(There's other "minor" cleanup I need to do on this file, but I'd prefer to do that as a separate request to keep things organized.)
> Util: Remove limit resets from encounter_tools' automated encounter detection

- README.md
- util/fetch_deps.py
Update the language around the dependency fetching documentation, fixing the path to the dependency fetching script.
Add a shebang to the script and change the execution permissions to allow calling the script in a matter matching the documentation.
> docs: Update Dependency Fetching Documentation

- package.json
This was an (un)interesting issue. The original command:
```
node_modules/.bin/markdownlint **/*.md --ignore node_modules --ignore publish --ignore CactbotOverlay/ThirdParty
```
when run through the command line directly would not pick up root level changes to Markdown files. However, running the npm wrapper command:
```
npm run markdownlint
```
would pick it up.
However, neither the original command nor the npm wrapper command would work on my MacOS command line when attempting to find issues to files in the root directory. This updated command should work for all variations, Unix/Windows, command line directly, and npm wrapper command.
> ci: Update Markdownlint Command to Work Universally

- util/encounter_tools.py
This should resolve #1499. Nothing much to say about it, It Works On My Machine. Cleaner implementation suggestions welcome, I mostly tossed this together.
(It is technically not necessary to handle the case of full-line comments, since for any situation where comments would appear, they would have been ignored before reaching `clean_line`. But of course it doesn't hurt to Just Make Sure.)
```
1251.082: Matched entry: 1251.1 Morn Afah #1 (+0.018s)
1257.462: Matched entry: 1257.5 Akh Morn #1 (+0.038s)
1269.843: Matched entry: 1270.0 Exaflare #1 (+0.157s)
1289.231: Matched entry: 1289.3 Akh Morn #2 (+0.069s)
1306.903: Matched entry: 1306.9 Morn Afah #2 (-0.003s)
1319.180: Matched entry: 1319.2 Exaflare #2 (+0.020s)
1340.391: Matched entry: 1340.5 Morn Afah #3 (+0.109s)
1352.693: Matched …
```
> Util: Update encounter_tools to permit "#" in timeline text

- util/check_translation.py
- util/coinach.py
- util/find_missing_translations.py
- util/gen_fisher_data.py
- util/gen_hunt_data.py
- util/gen_territory_type.py
- util/gen_weather_rate.py
- util/make_timeline.py
- util/publish.sh
- util/test_timeline.py
- util/timeline_adjust.py
- util/translate_fight.py
Add shebangs to standalone scripts and change the executable flag so they can be invoked shorthand.
> util: Update Standalone Scripts as Executables

- package.json
Update Husky to run hooks more frequently, but to take a significantly smaller amount of time by only running on staged code changes.
> npm: Update Hooks to Only Affect Code Changes

- README.md
Indent the image within the numbered list to prevent the list from
restarting its count.
> docs: Fix Adding Overlay Modules Numbered Lists

- util/make_timeline.py
Targetable/untargetable lines don't have "ability_name" or
"ability_id" on their entry, and so it's a key error to check for them.
e.g. `{'line_type': '34', 'time': datetime.datetime(2020, 6, 28, 18, 34, 10, 608000), 'combatant': 'Titan', 'targetable': '--untargetable--'}`
> util: fix make_timeline errors with -it

- .github/workflows/python-lint.yml
Pin CI system isort dependency until pylint is upgraded to a version where the dependency is properly capped. Addresses the dependency issues found in #1541.
> ci: Pin isort Dependency

- .github/workflows/python-lint.yml
PyYAML and requests dependencies aren't ever directly executed and are
only pulled within CI systems to avoid import errors in pylint. Keeping
pinned dependencies for Python packages executed directly to avoid
randomly picking up breaking changes.
> ci: Unpin Unexecuted Dependencies

- ui/raidboss/data/04-sb/eureka/eureka_hydatos.js
adds regex fr, questions sorry, i have this:
**in act log** 
**in my network log**
Vertu relative bénéficie de l'effet  Bras de Lumière.
I don't know if the one I added is well written or it should just be
`regexFr: Regexes.gameLog({ line: 'Vertu relative bénéficie de l\'effet Bras de Lumière.*?', capture: false }),`
> Raidboss: eureka_hydatos fr

- ui/oopsyraidsy/oopsyraidsy.js
In line with #1504 , this adds support for `gainsEffect` mistakes without requiring dedicated triggers in a given instance's oopsy file. This is support only, with no changes to existing instance oopsy files.
Note that this helper uses the `matches` parameter rather than `event` in the returned `mistake` object. This is primarily because I don't have a firm enough grasp of `event` to have it work correctly with `netRegex` in the trigger body. This works, and is what we want to move toward in future anyway, so I feel that it's relatively acceptable here even if it doesn't exactly match the surrounding helpers.
I'm rather unhappy with 
```
this.AddSimpleTriggers('warn', set.damageWarn);
this.AddSimpleTriggers('fail', set.damageFail);
this.AddGainsEffectTriggers('warn', set.gainsEffectWarn); …
```
> oopsy: Added gainsEffect helper

- CONTRIBUTING.md
- package.json
Changes `lint-staged` to run via `npx` rather than being invoked
directly. This change sets up the PATH for various programs like VSCode
or GitHub Desktop that might be running into issues where `lint-staged`
is attempting to be directly executed, outside of Node.
> npm: Update Lint-Staged Command to Run Via npx

- docs/LogGuide.md
Ravahn happened to give us some information on the `25` log line that was more accurate than what was currently noted in the guide. I cleaned it up and spliced it in as best I could.
The [] brackets indicate changes in the quote, much as you would expect to see in a news story. You can compare it with Ravahn's [original exact quote](https://discordapp.com/channels/551474815727304704/551476873717088279/733336512443187231):
>line 37 is effectively a 'sync' packet where the server tells the client that the previous action should now be rendered on the ui / chatlog.
or something along those lines, thats how i think about it.  others may have a better understanding.
example - if I cast a spell, i will get an effectresult packet (line type 21/22) showing the damage amount, but the target isnt …
> Docs: More accurate description for type 25 log lines

- CONTRIBUTING.md
- package.json
Create `lint-staged` npm script to match how other third-party npm modules are executed. Updates the `husky` command from running `npx` to instead invoking `lint-staged` via an npm script.
Changing from `npx` to invoking `lint-staged` via `npm run lint-staged` should decrease the delta in execution time between developers while still allowing contributors to utilize third-party desktop applications to create and edit git commits.
Testing between the various alternatives:
- Direct invocation:
```
time lint-staged
ℹ No staged files found.
lint-staged  0.17s user 0.06s system 109% cpu 0.204 total
```
- npm script:
```
time npm run lint-staged
> cactbot@ lint-staged /c/cactbot
> lint-staged
ℹ No staged files found.
npm run lint-staged  0.37s user 0.10s system 96% cpu 0.492 total
```
- …
> npm: Add lint-staged Script

- ui/raidboss/data/05-shb/raid/e5n.js
I thought the infoText was done by someone else so I missed them in e5n.
> raidboss: fix e5n missing cn infoText

- .github/workflows/build-artifact.yml
- .github/workflows/css-lint.yml
- .github/workflows/javascript-lint.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/python-lint.yml
- .github/workflows/test.yml
Revert actions/checkout to V1 from V2, as there are existing bugs within
checkout@V2 causing it to possibly checkout the wrong commit SHA.
See:
- https://github.com/actions/checkout/issues/299
- https://github.com/quisquous/cactbot/pull/1600
> ci: Revert Checkout Action to V1

- CONTRIBUTING.md
Add documentation on how to leverage your personal fork for testing
changes made to individual cactbot modules with GitHub Pages.
> docs: Document Personal GitHub Pages from Fork

- ui/oopsyraidsy/data/00-misc/general.js
- ui/oopsyraidsy/data/03-hw/dungeon/aetherochemical_research_facility.js
- ui/oopsyraidsy/data/03-hw/dungeon/gubal_library_hard.js
- ui/oopsyraidsy/data/04-sb/dungeon/ala_mhigo.js
- ui/oopsyraidsy/data/04-sb/raid/o2n.js
- ui/oopsyraidsy/data/04-sb/raid/o4n.js
- ui/oopsyraidsy/data/04-sb/raid/o4s.js
- ui/oopsyraidsy/data/04-sb/trial/shinryu.js
- ui/oopsyraidsy/data/04-sb/ultimate/ultima_weapon_ultimate.js
- ui/oopsyraidsy/data/04-sb/ultimate/unending_coil_ultimate.js
- ui/oopsyraidsy/data/05-shb/dungeon/dohn_mheg.js
- ui/oopsyraidsy/data/05-shb/raid/e2s.js
- ui/oopsyraidsy/data/05-shb/raid/e5n.js
- ui/oopsyraidsy/data/05-shb/raid/e5s.js
- ui/oopsyraidsy/data/05-shb/raid/e7n.js
- ui/oopsyraidsy/data/05-shb/raid/e7s.js
- ui/oopsyraidsy/data/05-shb/raid/e8n.js
- ui/oopsyraidsy/data/05-shb/raid/e8s.js
- ui/oopsyraidsy/data/05-shb/trial/hades-ex.js
- ui/oopsyraidsy/data/05-shb/ultimate/the_epic_of_alexander.js
This is a very indirect patch which is getting rid of non-jobs usages of
gLang.kEffect, so I can use netRegex for effects in jobs, remove
gLang.kEffect entirely, in order to track atonement stacks for #725.
This also contributes to several other ongoing nebulous efforts like
using NetRegexes for oopsy instead of events (#1487) and also cleaning
up the unfortunate gLang data structures (#1221).
> oopsy: use netRegex for all effects

- ui/dps/dps_common.js
- ui/dps/xephero/dps_phase_tracker.js
- ui/dps/xephero/xephero.js
- ui/fisher/fisher.js
- ui/jobs/jobs.js
- ui/oopsyraidsy/oopsyraidsy.js
- ui/pullcounter/pullcounter.js
- ui/radar/radar.js
- ui/raidboss/popup-text.js
- ui/test/test.js
This is the "switch to the new event type" part of #1037, where
followups can start using the zone id more.
> Replace onZoneChangedEvent with ChangeZone

- ui/eureka/eureka.js
- ui/raidboss/data/03-hw/alliance/weeping_city.js
- ui/raidboss/data/03-hw/alliance/weeping_city.txt
- ui/raidboss/data/manifest.txt
A primary difficulty in building packages for older alliance raids is that ACT has been significantly improved since 2016. It's tough to get logs with all the necessary information in them, so the work represented here is a combination of generation from 4 years's worth of different logs in addition to trawling FFLogs for the longest possible encounters I could find. ([Arachne Eve](https://www.fflogs.com/reports/MC7HrDWkTPabLKYg#fight=3), [Forgall](https://www.fflogs.com/reports/YpchN4C21yTVa67v#fight=45), [Ozma](https://www.fflogs.com/reports/kWKBtdr8jYJfyTap#fight=1), [Calofisteri](https://www.fflogs.com/reports/R831VACkL2tNMndX#fight=last), for anyone who wants to have a look themselves.)
The timelines are reasonably accurate, but there's probably a good bit of improvement that could …
> Raidboss: Weeping City of Mhach timeline/triggers

- util/test_timeline.py
When working with zoneseal messages where casing is not guaranteed, `test_timeline` can break if there are no close-by syncs:
`0 "--sync--" sync /00:0839:The Main Deck will be sealed off/`
This fails if the combat log has `the main deck` instead. Current practice is to title case the "name" portion of the zone seal message. Square's localization team is *very* good, but they seem to have real trouble with casing things, and that collides here.
Probably this logic should be moved to `encounter_tools`, but for now if nothing else this will *work*.
> Util: Force case insensitivity in zone seal regex

- ui/raidboss/common_replacement.js
- ui/raidboss/data/02-arr/trial/shiva-ex.js
- ui/raidboss/data/02-arr/trial/shiva-hm.js
- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
- adds missing translations fr.
- removal lines `adds targetable` on shiva-ex/hm + epic_alex for add common. there was a misunderstanding between appear and targetable on the German translation that I corrected.  anvisierbar=targetable and erscheinen=appear
> Raidboss: Shiva hm/ex + common

- ui/jobs/jobs.css
- ui/jobs/jobs.js
- **CardBox**
Show on which kind of jobs your card plays better by color. Blue on melee, purple on ranged, and grey when no card.
Also show whether you already have the seal of this card by O/X. O means it's OK to play this card, and X means don't play this card directly if time permits.
- **SealBox**
Show how many kind of seals you already have. Turn green when you have all 3 kinds of seal.
- **Combust DoT Tracker**
Support all combusts that AST have.
- **Draw Cooldown Tracker**
A good AST never forgets draw on time.
- **LucidDreaming Cooldown Tracker**
AST's mana is very poor, cast LucidDreaming on time to ensure your mana.
- **AspectedBeneficBox and AspectedHeliosBox**
These boxes only work for Diurnal AST, and they use these spells rarely. 
Besides, in these days Nocturnal AST is more …
> jobs: AST part Remake

- ui/jobs/jobs.js
These icon can hold only 2 CN/Kor charactors. 3 will escape out of box.
(If I'm not misunderstand, this line is for CN/KR player, because only these name can be `length != 2`)
> job: small fix about raidbufftracker's player name in CN

- ui/raidboss/data/03-hw/alliance/dun_scaith.js
- ui/raidboss/data/03-hw/alliance/dun_scaith.txt
It's all bad. Dun Scaith has by far been the most difficult timeline work I've done. Let's just get that out of the way at the start. Modern runs through here *usually* don't go anywhere near long enough to see boss rotations, and ACT logs from prior to 2019 or so don't have everything because any attacks that didn't strike a target simply weren't recorded. This meant a much longer reconstruction process than should have been necessary. (It doesn't help that FFLogs doesn't have this instance easily searchable, so we can't just construct stuff from there as we did Weeping City.)
I've thrown a number of logs at this with `test_timeline`, and it's mostly accurate. Because of the lack of consistently available data, I mostly left things alone as long as the matches weren't off by more than …
> Raidboss: Dun Scaith timelines

- ui/raidboss/data/03-hw/alliance/dun_scaith.js
(This should resolve #549.)
This probably isn't as self-explanatory as some others, unfortunately. NetRegexes have made most of this possible.
To begin with, anytime there's a trigger that uses a choice of abilities, we now use the `['ID1', 'ID2']` construction, rather than `'ID[12]'`. It's so nice not to use bare regexes anymore!
Certain triggers on Proto-Ultima have been removed. All of them have prominent AoE indicators alongside, so there's really no good reason to keep them. (It was good practice for me at the time though!)
All `addedCombatant` lines have been replaced with `addedCombatantFull` in order to be completely language-agnostic without the need for language-specific regexes. (It's technically not necessary for all of them, but since the Atomos triggers *do* require it, it …
> Raidboss: Dun scaith trigger cleanup

- ui/radar/radar.js
Once https://github.com/ravahn/FFXIV_ACT_Plugin/issues/256 has been
fixed then this should be reverted.
> radar: temporarily disable npcNameId matching

- plugin/CactbotEventSource/FateWatcher.cs
FIxes #1688 
Category should always have been a ushort but it seems with 5.3 there can now be garbage bytes resulting in erroneous values.
> plugin: Fix FateWatcher casting ActorControl143 Category as int instead of ushort

- ui/raidboss/data/04-sb/trial/susano-ex.js
added missing translations fr + removal missingTranslations
`Pointe d'éclair` is an incorrect name, so I corrected it.
I'm putting the link and a capture to you, because I know I bothered you a lot with unnecessary capital letters in `replaceSync` (I was misled due to the different ways written, in-game, logs, fflogs, saintcoinach, garlandtools, as well as the display bug that you fixed in the check timeline) and I apologize and thank you for your patience.
https://xivapi.com/BNpcName/6223?pretty=true
> raidboss: susano-ex fr

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
@r4ha Sorry for disturbing.
https://github.com/quisquous/cactbot/blob/c5a6c24c8690fc7ab1c31d6134dd31d28b3c9806/ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js#L2240-L2247
I think the text in here should be "逃亡禁止" instead of "接触禁止". Is it my misunderstanding or just your typo here?
Waiting for your reply.
> raidboss: fix text typo in alex ultimate

- ui/jobs/jobs.css
- ui/jobs/jobs.js
- **Aetherflow Box**
Show how many Aetherflow Stack you have.
Turn red when you still have 2 stack and Energy Drain is about to ready in 8s(for finish current cast, then cast a Fester).
- **Demi-Summoning Box**
When not in Demi-Summoning/Trancing, show what you can summon next turn by color.
While Summoning/Trancing, show time remains.
Turn red when Demi-Summon time remains less than 7s, to alarm player cast the second Enkindle, and don't cast a spell which has cast time. 
Also turn red when Trance time remain less than 2s for Deathflare.
- **Miasma & Bio DoT Tracker**
To track 2 DoT, Tracker part looks a little crowded.
- **Energy Drain Cooldown Tracker**
Both Energy Drain and Energy Siphon is supported.
- **Trance Cooldown Tracker**
Infact, Trance's Cooldown is 55s, but wait till 60s is …
> Job: new SMN UI

- ui/raidboss/raidboss.html
- ui/raidboss/timeline.js
This PR fixes #1453 by tracking the countdown/wipe state for the timeline and preventing the `Engage!` event from starting the timeline if there was a wipe during countdown.
> - Fix #1453

- ui/pullcounter/pullcounter.html
Adding missing `<meta>` tag in pullcounter.html
I've checked other html files and they do have meta charset tags already (except `ui/dps/xephero/manual_dps_test.html` which is a test file).
> pullcounter: add meta charset to html

- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
If people die, it calls it twice.
```
[17:14:58.730] 16:40004588:Twintania:26B2:Twisting Dive:106F8A6D:Baddie One:730003:58454401:20:80000:1B:26B28000:0:0:0:0:0:0:0:0:0:0:42735:42735:3745:10000:0:1000:7.374826:7.486454:-0.0005370203:0.9083784:1:5533785:10000:10000:0:1000:-8.4853:22.6273:0:2.356182:0000781D
[17:14:58.730] 16:40004588:Twintania:26B2:Twisting Dive:106BF6B7:Baddie Two:F1730006:38C14401:20:80000:1B:26B28000:0:0:0:0:0:0:0:0:0:0:42719:42719:5400:10000:0:1000:17.22228:-3.507673:-0.001305427:1.968111:1:5533785:10000:10000:0:1000:-8.4853:22.6273:0:2.356182:0000781D
```
> raidboss: Suppress Twister Dive

- resources/responses.js
- ui/raidboss/data/03-hw/raid/a8s.js
- ui/raidboss/data/04-sb/raid/o12s.js
- ui/raidboss/data/04-sb/trial/suzaku-ex.js
- ui/raidboss/data/04-sb/trial/tsukuyomi-ex.js
- ui/raidboss/data/05-shb/raid/e4s.js
- ui/raidboss/data/05-shb/trial/hades.js
- ui/raidboss/data/05-shb/trial/innocence-ex.js
- ui/raidboss/data/05-shb/trial/varis-ex.js
- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
https://github.com/quisquous/cactbot/blob/3cdb806d2b0b9cb8325e3e4fc8bdd81eb51a7170/ui/raidboss/popup-text.js#L774-L787
There are some translators translate `Tankbuster on someone` as `死刑 => someone`, but the code above would replace every arrow in the middle as `然后(then)`, so TTS would call out like `死刑然后someone (Tankbuster then someone)`.
(I think the correct TTS info should be like `Tankbuster on someone (死刑 点 someone)`.)
It confused players and should be fixed.
EDIT:
It seems there other languages have the same problem. For now I have only modified Chinese translations, because I don't know whether the other languages should be fixed or not.
> Fix(raidboss): arrows at wrong place in trigger info text

- ui/raidboss/data/05-shb/raid/e6n.js
- ui/raidboss/data/05-shb/raid/e6s.js
Instant Incineration is physical damage.
See [here](https://fflogs.com/reports/hXYR6ZV8fTb9Djnp#fight=5&type=casts&hostility=1&source=19). (blue is magical, orange is physical)
> raidboss: Eden Furor Incineration Trigger fix

- ui/oopsyraidsy/data/04-sb/dungeon/the_burn.js
- ui/oopsyraidsy/data/manifest.txt
Nothing special about this one. I did notice that Falling Rock was displaying for trash that got caught in it, so we'll have to look into a fix for that separately. (Probably really simple to add a check to the `damageWarn` helper for whether the target is a player.)
> Oopsyraidsy: Initial Burn package

- resources/translations.js
This should fix unintended UI hiding bug.
I wonder if `(?<recipe>.*)` returns string with "x3" thing (multiple craft output)
I added `×[2-9]` in regex, but I'm not sure this is right.
This fixes #1772.
Successfully tested that this code does not make UI hide with other player's craft done.
> Jobs: fix bug for Korean server

- ui/raidboss/browser_tts_engine.js
I don't think we need `encodeURIComponent` to `lang` parameter, so I didn't make it.
This fixes "non-English TTS problem" part of #1773.
> Remote cactbot: Google TTS language fix

- resources/common.js
- test/unittests/common_test.js
- ui/jobs/jobs.js
Updates the job to role mapping to instead use the user-defined lists as
a reference when determining job role.
Additionally shortening the function logic for most function calls to
directly check if the user-defined list includes the job.
Adds a quick exit within WSServer code if location is undefined,
primarily for local usecases (such as running tests).
Lastly, adding tests for the logic around job util functions and
creating the jobToRoleMap.
> resources: Update Common Job Util Functions

- resources/translations.js
They use full-size (2-bytes) bracket in CN.
So the previous regex would not work.
> fix(jobs): full-size bracket in countdownStartRegex

- ui/jobs/jobs.js
UI resource timer using Math.floor(millisecond) is not equal to in-game guage timer.
Change to Math.ceil(millisecond) to match in-game guage to avoid confusing.
(And a little readable change)
> jobs: change Math.floor to Math.ceil

- resources/common.js
- resources/party.js
- test/unittests/common_test.js
- ui/dps/dps_common.js
Hide data lists for Util, only exposing the functions as defined in the object returned.
Any remaining reliance on the actual lists themselves being exposed has been updated to be a function instead.
> resources: Hide Job Data Lists

- ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.js
- ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt
(Multiple commits for ease of viewing changes.)
Mostly self-explanatory. The timeline changes on Regula are because it is juuuust possible to have an overlap if the group kills the first turret set super-fast and Regula goes into the second set immediately. The removed lines at the end are because they would never show up in the overlay.
Casing on Height Of Chaos normally wouldn't matter, but it did here. Oops! (I fiexed the casing on End Of Days while I was in there.)
> Raidboss: ARF minor fixes

- ui/jobs/jobs.css
I errorly add a whm hp bar style in whm UI #1806   because of my personal change.
Remove it here.
> jobs: Remove spare css in WHM UI #1806

- ui/jobs/jobs.html
- ui/jobs/jobs.js
As once discussed in issue #1672 also closes #1672  
Early return from `UpdateJob()` meet some error on zone change, so just hide them.
Seems calling `UpdateJob()` in `OnChangeZone(e)` will cause something wrong.
> jobs: Hide UI except hp/mp bar in pvp zone

- ui/jobs/jobs.js
Dragoon skill combos share some of the same skills, such as
some having Wheeling Thrust -> Fang and Claw and others having
Fang and Claw -> Wheeling Thrust at the end.
The current combo tracker has a global map of all skills by id,
and so both of these abilities get marked as the "final" ability
in the chain, which is incorrect some of the time.
Refactor the combo tracker to have a tree of nodes instead, so that
there is context about the chain of abilities to get there.
This will let #1804 not have to track specific abilities with timers
and will let it use the combo tracker more naturally.
> jobs: refactor combo tracker to be a tree, not a map

- ui/raidboss/data/04-sb/raid/o12s.txt
With modern unsynced DPS output, it's possible to enter the duo phase well before the developers intended us to. These windows ensure that the raidboss timeline will always be at the correct place.
(Strictly speaking only the Firewall sync is necessary, but it's nice to have the non-targetable intermission displayed too.)
> Raidboss: O12S minor timeline fix

- .github/workflows/create-tag.yml
- .github/workflows/release.yml
Add GitHub workflows to create a tag off version updates and create a
draft release off of a tag being created.
> ci: Add GitHub Workflows to Release Artifacts

- ui/jobs/jobs.js
Pull #1825 forgot an early return if an id was handled in the state
transition.  It meant that valid ids that were both part of a combo and
treated as combo breakers (e.g. Maim) would get handled twice, causing
Maim to end the combo.
The other issue is that AbortCombo reuses StateTransition, and so
the callback should not be called in these cases.
Fixes #1845.  This is an alternative approach to #1848.
> jobs: fix combo tracker calling callback unexpectedly

- resources/player_override.js
- ui/dps/dps_common.js
Add exports for functions that are used elsewhere, updating function
declarations as necessary.
In the case of Options being exported for dps_common, the downstream
modules, rdmty and xephero, don't declare their own options.
> general: Update Function Declarations and Exports

- CONTRIBUTING.md
cactbot-highlight is now available on Visual Studio Market,
so update the URL
> doc: update cactbot-highlight url

- ui/oopsyraidsy/oopsyraidsy.js
- ui/raidboss/data/05-shb/etc/the_diadem.js
- ui/raidboss/data/manifest.txt
- ui/raidboss/popup-text.js
- util/gen_zone_id_and_info.py
I added gatherer diadem thing in raidboss, it's not actually raid thing though.
`Diadem Falling Asleep` same as eureka's one, but this is 7 minutes alert, not 5 minute. I think 7 minute is better for eureka, too.
`Diadem Found Gather Point` I don't know expression for English. I tried to alert rare gather points founds.
`Diadem Flag Alert`, show infoText, when \<flag\> on diadem was on chat.
I guess this error is thinking that `Diadem F` is prefix, but it's not.
I don't know what's the problem.
`netRegex` is needed, so I just added `I don\'t know in English` there. I need English expression for that. I don't know how to say this in English, you can see these gather points in [garland bell](https://garlandtools.org/bell/) (No Diadem points though.)
> raidboss: add gatherer diadem support + multiple zoneId

- ui/jobs/jobs.css
- ui/jobs/jobs.js
Healer's HP is as important as Tank's.
Many times I saw healers are busy at restoring other's HP, 
but ignore their own HP is not enough and got killed in AoE, causing party wipe.
Also healer who makes barrier sometimes want to know how much damage can it nullify.
So I think it's necessary to show HP number in Healer.
> Jobs: Show HP number in Healer

- ui/jobs/jobs.js
Since all lucidBox except this one use `this.gcdSpell() + 1`, and you can cast lucid at almost anytime, 4*gcd is unnecessary and may cause additional disturbtion.
> Jobs: Shorten lucidBox.threshold for BLU

- ui/fisher/seabase.js
Switch functions to instead use arrow functions to preserve `this` without
having to create subsequent variables inside of individual functions.
Fixes #1880
> fisher: Fix Lexical Scoping

- ui/jobs/jobs.css
- ui/jobs/jobs.js
RDM's MP cost is very high compare to other magical DPS.
Add lucidBox to avoid MP insufficient when you want to cast verraise.
> Jobs: Add lucidBox for RDM

- docs/RaidbossGuide.md
- ui/raidboss/popup-text.js
Rather than adding an explicit `override` property on triggers,
this change implicitly makes all triggers with the same id override any
previously processed triggers.  For cactbot internal triggers, this
shouldn't be an issue, as all triggers must be unique.  User triggers
will be processed after internal triggers for obvious reasons.
There is a potential present hazard here that users have triggers with
ids that match existing ids, but are not meant to override that trigger,
and will be defaulted into to unexpected behavior.
There is also a future hazard, if ids ever conflict.  Cactbot internal
triggers have a unique prefix per file that will prevent this from
happening internally, but this is still a potential hazard for future
triggers (new cactbot triggers colliding with old user …
> raidboss: add implicit trigger overrides

- plugin/CactbotEventSource/CactbotEventSource.cs
- plugin/CactbotEventSource/CactbotEventSourceConfig.cs
This is to work towards #1767, by setting the user folder directly
from any implicit values.
> plugin: set config dir explicitly if found implicitly

- docs/CactbotCustomization.md
- docs/RaidbossGuide.md
- plugin/CactbotEventSource/CactbotEventSource.cs
- resources/user_config.js
- ui/raidboss/popup-text.js
- ui/raidboss/raidboss_config.js
- user/raidboss-example.js
- user/test-override.txt
* Change the plugin to also load text files.
* Change user_config.js to allow a custom user file processor.
* Add a custom user file processor to raidboss_config.js.
* In this processor, convert timeline filenames into timeline contents,
as user-specified timeline files are not part of the data files and so
can't be loaded by name later.
* Add a new overrideTimelineFile flag that clears previously loaded
timeline information.
* Add documentation for all of this.
> raidboss: allow for timeline overriding

- test/timeline/test_timeline.js
- ui/config/config.js
- ui/dps/xephero/dps_phase_tracker.js
- ui/jobs/jobs.js
- ui/oopsyraidsy/oopsyraidsy.js
- ui/pullcounter/pullcounter.js
- ui/radar/radar.js
- ui/raidboss/data/03-hw/raid/a4s.js
- ui/raidboss/timeline.js
- util/find_missing_timeline_translations.js
Replace all string.match with regExp.test where applicable, also precompile regex in timeline.js `LoadFile()` since they're used in a loop which is a big performance penalty.  
Fixed a4s missing Hydrothermal Missile regex which caused the tests to fail (`!!event.name.match(undefined) === true`)
`string.match` vs `regExp.test` bench http://jsbench.github.io/#edf82fee9c75a58c7f48889ff0449453
> refactor(perf): change string.match to regExp.test

- util/make_timeline.py
Making timelines for Critical engangements can be confusing with action from random mobs.
With this option you can specify the enemy you want to make a timeline around (mostly usefull in eureka and bozja)
> added only-combatant option to make timeline

- ui/raidboss/data/04-sb/raid/o8s.js
At some point during one of the many regex conversions we've done in the last three years, the ID for Futures Numbered got corrupted. Futures Numbered follows the awful "Cast one thing on self, then instantly use another thing on targets/AoEs". (Using ACT lines here since I still happen to have it open, but the network log is the same.)
```
[00:57:00.655] 14:28EE:Kefka starts using Futures Numbered on Kefka.
[00:57:05.549] 15:4001A7BF:Kefka:28EE:Futures Numbered:4001A7BF:Kefka:3C:0:1B:
[00:57:05.861] 15:4001A7BF:Kefka:28EF:Futures Numbered:E0000000::0:35374003:1B:
```
> Raidboss: O8s Futures Numbered works again

- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
@panicstevenson wdyt
I'm hoping I can maybe wrangle a script to auto-convert anything that has `infoText: { object literal }`, so these are the harder ones.
I also removed tts (in a separate commit) that I felt like was not useful to have broken out (although I left a bunch that I felt was usefully shorter and less cluttered).  I also changed to arrow functions and eqeqeq (not in a separate commit???), but mostly because it was super painful to not update it.  Feel free to complain at me about this and I can do it differently.
> raidboss: convert ucob to output strings

- ui/raidboss/data/02-arr/dungeon/brayfloxs_longstop.js
- ui/raidboss/data/02-arr/dungeon/haukke_manor.js
- ui/raidboss/data/02-arr/raid/t1.js
- ui/raidboss/data/02-arr/raid/t2.js
- ui/raidboss/data/02-arr/raid/t7.js
- ui/raidboss/data/02-arr/raid/t9.js
- ui/raidboss/data/02-arr/trial/titan-ex.js
- ui/raidboss/data/02-arr/trial/titan-hm.js
Update conditions for ARR triggers to use canned responses where
available, and/or use arrow functions where it makes sense.
Addresses all utility functions from common (CanCleanse, CanStun,
etc.) and all conditions from Conditions that aren't targetIsYou /
targetIsNotYou.
> raidboss: Update ARR Triggers Conditions

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
- ui/raidboss/raidboss_config.js
I think adding `sec` to duration is better
https://github.com/quisquous/cactbot/blob/6809fe44899ee01b7bf98e7280b3203b411a7f4a/ui/raidboss/raidboss_config.js#L123-L127
`duration` -> `duration (sec)`
> raidboss: Korean translate

- ui/raidboss/data/02-arr/dungeon/brayfloxs_longstop.js
- ui/raidboss/data/02-arr/raid/t1.js
- ui/raidboss/data/02-arr/raid/t10.js
- ui/raidboss/data/02-arr/raid/t11.js
- ui/raidboss/data/02-arr/raid/t12.js
- ui/raidboss/data/02-arr/raid/t13.js
- ui/raidboss/data/02-arr/raid/t2.js
- ui/raidboss/data/02-arr/raid/t5.js
- ui/raidboss/data/02-arr/raid/t6.js
- ui/raidboss/data/02-arr/raid/t7.js
- ui/raidboss/data/02-arr/raid/t8.js
- ui/raidboss/data/02-arr/raid/t9.js
- ui/raidboss/data/02-arr/trial/shiva-ex.js
- ui/raidboss/data/02-arr/trial/shiva-hm.js
- ui/raidboss/data/02-arr/trial/titan-ex.js
- ui/raidboss/data/02-arr/trial/titan-hm.js
- ui/raidboss/data/02-arr/trial/titan-nm.js
Enable additional core ESLint rules for triggers:
- https://eslint.org/docs/rules/arrow-body-style
- https://eslint.org/docs/rules/eqeqeq
- https://eslint.org/docs/rules/no-unused-vars (with `_` as an exception)
- https://eslint.org/docs/rules/prefer-arrow-callback
- https://eslint.org/docs/rules/prefer-const
Additionally, running the following rule locally:
- https://www.npmjs.com/package/eslint-plugin-prefer-arrow
> raidboss: Additional ESLint Rules for ARR Triggers

- ui/raidboss/emulator/ui/Tooltip.js
- ui/raidboss/raidemulator.html
Small hack to speed up the rendering steps for trigger-heavy encounters within
the raid emulator.
Before:
After:
This adds a bit to the `Recalculate Style` step, but the performance hit there
is outweighed by the speed increase in selecting the DOM element.
I saw roughly a ~50% reduction in total time to load a trigger-heavy
encounter (TEA). With a ~70% reduction in total drawing time after the
log events had been loaded.
> raid emulator: Add Element Ids for Tooltip Templates

- ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.js
- ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.txt
- ui/raidboss/data/manifest.txt
The direction the Colossus spins for Magitek Slash is indicated by a head marker, but I couldn't think of a concise way to convey that to the player usefully. Slash itself seems to have a slightly variable timing, up to about 0.5 seconds in either direction, so I just called it good and left it, since everything else seemed to line up okay.
On Prometheus, Needle Gun/Oil Shower are the cast-time telegraphed 90-degree frontal and 270-degree rear cleaves. When running solo, Needle Gun is used twice, while on all my test runs with party members it was invariably Needle Gun followed by Oil Shower. I'm *relatively* sure it's determined by whether there's a target within the affected radius at the time the cast starts, but I figured it was safe to just account for both possibilities.
I didn't …
> Raidboss: The Ghimlyt Dark timelines and triggers

- test/trigger/test_trigger.js
- ui/raidboss/data/00-misc/test.js
- ui/raidboss/data/02-arr/trial/shiva-ex.js
- ui/raidboss/data/03-hw/raid/a10s.js
- ui/raidboss/data/03-hw/raid/a5s.js
- ui/raidboss/data/05-shb/alliance/the_puppets_bunker.js
- ui/raidboss/data/05-shb/raid/e7s.js
- ui/raidboss/data/05-shb/raid/e8s.js
- ui/raidboss/data/05-shb/trial/shiva-un.js
- ui/raidboss/data/05-shb/trial/varis-ex.js
- ui/raidboss/data/05-shb/trial/wol.js
Fix up tests to catch this case.  Also, support output strings that are
string values and not just translatable objects in tests.
It's no longer useful to call Responses dynamically from inside a
`response` object, because we can't dynamically know the output strings
that it will need.  This adds some duplication here, unfortunately.
The long term plan is:
https://github.com/quisquous/cactbot/issues/1307#issuecomment-723486775
> raidboss: convert remaining responses to output strings

- .github/workflows/build-artifact.yml
- .github/workflows/create-tag.yml
- .github/workflows/release.yml
Apparently there is a [security vulnerability](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) in using `set-env`. Updating all `set-env` invocations to use the `$GITHUB_ENV` file, as described in [the updated workflow documentation.](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
> ci: Fix GitHub Actions Using set-env

- .github/workflows/build-artifact.yml
According to https://github.blog/changelog/2020-10-08-github-actions-ability-to-change-retention-days-for-artifacts-and-logs/ ,
we can set retention days as 30,
so don't need to keep massive artifact storage within default 90 days.
> ci: set retention of artifacts as 30 days

- ui/jobs/jobs.css
- ui/jobs/jobs.js
These jobs have a lot of insertable skills that do not break combo(like FC*5), but easy to let combo timeout.
Besides, combotimers share a same color across jobs, so merge them.
> Jobs: Add combo timer for WAR, DRK, MCH

- ui/jobs/jobs.js
- Royal Authority combo is not used(Atonement use effect id to work).
- SAM has at most 2 Iaijutsu to insert, comboTimer is not needed.
- Seems RDM UI no longer care about combo(and combo breaks at start casting, not cast out).
> Jobs: Delete unused combo

- plugin/CactbotEventSource/CactbotEventSource.cs
Code that wants data files should import the manifest directly
to get the same result that this handler would have returned.
Part of #1767.  Depends on #2044.
> plugin: remove cactbotReadDataFiles handler

- ui/jobs/jobs.css
Due to #2043 , there is a mistake that an unnecessary bar appear in the stack guage.
Other bars define there height there own, but delete this line seems result in a default height, so change it to 0.
> Jobs: Fix bar in stack guage

- resources/defaults.css
As mentioned in #2042 , this PR changed the default font for Chinese.
For 黑体(SimHei) font, I used @DieMoe233 's mirror, which has better display readability, larger charset, and wide accessibility in mainland China.
For those players who are not in mainland China, or just failed in downloading the font, their default font would fallback to just SimHei, which included in Windows Chinese language pack.
> style: add default Chinese font.

- util/make_timeline.py
This is another one of those little annoying things that bugged me enough to fix. This will automagically fill in the zone name, title-cased, if the start event is a zone seal.
I'm really not happy with the setup I used to do this, but the approach suffers from some circular problems. `is_zone_seal` depends on being fed pre-split log lines, but during each iteration of the loop, we don't split until after we might already have rejected a zone-seal message. I'd rather not split every log line for performance reasons. I guess maybe we could instead rewrite the "set `started` to true" block to be more like this?
```
if not started:
started = True
last_ability_time = e_tools.parse_event_time(line)
if e_tools.is_zone_seal(line.split("|")):
entry = make_entry(
{
"line_type": "zone_seal", …
```
> Util: Automate zone seal messages in make_timeline

- README.md
> Doc: remove description of tp bar

- .editorconfig
- .gitattributes
- .vscode/extensions.json
- .vscode/settings.json
- resources/conditions.js
- resources/regexes.js
- util/make_timeline.py
Initial VSCode extension recommendations (basically just ESLint and @MaikoTan's highlighting extension from https://github.com/quisquous/cactbot/issues/1846), as well as some simple settings.
File associations won't be upset if the cactbot-highlight extension isn't installed. I don't know if there's any reason to have the `.git` folder appear in VSCode (potentially maybe node_modules can be here too?). Likewise, I don't think there's much point in search results showing dist or node_modules.
Perhaps these can be extended to include third-party files, such as lodash.min.js, etc. but I figured it might be best to ground something small first.
> Add VSCode Recommendations and Basic Settings

- ui/radar/radar.js
Sometimes a hunt can spawn in the middle of the night when someone's AFKing in the zone - they'll see it go up on the logs, but not down, meaning there's no precise timer. This gives them a time of death.
> radar: Log death of monsters

- docs/RaidbossGuide.md
- docs/zh-CN/RaidbossGuide.md
- resources/responses.js
- test/trigger/test_trigger.js
- ui/raidboss/data/00-misc/test.js
- ui/raidboss/emulator/data/PopupTextAnalysis.js
- ui/raidboss/popup-text.js
This was originally going to be some way to have tts for discord
purposes, but I think the overlayplugin shared tab does this better.
Additionally, cactbot triggers are designed for individuals and it
seems pretty clear that nobody has time to edit a million triggers
to behave properly in this group tts mode.
> raidboss: remove group tts

- resources/defaults.css
- ui/jobs/jobs.css
- Add a line-height to solve that numbers appear not in the middle of the box in CN, due to new font. 
Co-authored-by: Maiko Tan <maiko.tan.coding@gmail.com>
- Add missing MCH UI right side icon position.
> Jobs: Fix some position

- .github/workflows/build-artifact.yml
so user can trigger the workflow manually by clicky.
> ci: add workflow_dispatch in build-artifact

- resources/defaults.css
- ui/jobs/jobs.css
Seems that this font problem(#2091 ) only affect jobs module, leave it in default may cause some other problem, so move it to only affect jobs module.
> Jobs: move line-height of boxtext to jobs.css

- package-lock.json
- package.json
- ui/test/test.js
I want to use the programmatic ESLint interface to format generated files, but that's not available until 7.0.0.
Bump to the latest while we're here.
Also, fix a complaint the updated version had about unreachable code.  (Yay linting?)
> npm: Update eslint to 7.14.0

- ui/raidboss/data/05-shb/trial/emerald_weapon-ex.js
These are reliable as is, but the removingCombatant triggers will fire
on the transition between phases, which adds an awkward 'out' when
there's nothing to do.
> raidboss: Move Emerald Weapon Ex Combatant Triggers to Timeline Triggers

- ui/raidboss/data/05-shb/raid/e12n.js
- ui/raidboss/data/05-shb/raid/e12n.txt
*None of this has had live testing, I haven't had time to do that today and won't until much later tonight. `test_timeline` is mostly happy with it, the only timing variability I've seen is when Stock is cast leading into the second and subsequent primal blocks. Other than that, timing seems consistent across all logs I checked.*
This is a middling-complexity timeline. Not overly difficult, but not a nice straightforward one either. I think the in-line comments mostly cover what's needed. Shiva or Titan can be used first after the intermission, but the coda block that follows Shiva/Titan is fixed. (Odd coda blocks are Maleficium, even coda blocks are Formless Judgment.)
From everything I've seen, the opening block and its primal skills are fixed. It's possible Eden may open with …
> Raidboss: E12N timeline and basic triggers

- ui/raidboss/data/05-shb/raid/e11n.js
- ui/raidboss/data/05-shb/raid/e11n.txt
(@quisquous next time we add placeholders, we can probably include all imports rather than just `ZoneID`, unless that would cause linting problems.)
Nothing really special on this one. The opening block, introducing the basic mechanics, can be Fire or Lightning in a random order. The block following the Serpent intermission is Holy 100%. After Prismatic Deception, any Burnt Strike can be any element, with the exception that two in succession will not be the same. No matter what element Burnt Strike is, anywhere, it will not affect the timing on subsequent mechanics other than Blastburn/Burnout/Shining Blade.
Triggers are largely stolen from quisquous's work on E11S. I double-checked all IDs and verified that all non-healer/tank-specific callouts are functioning.
I haven't done Bound of …
> Raidboss: E11N timeline and intial triggers

- ui/raidboss/data/05-shb/dungeon/matoyas_relict.js
Per #2207, things are *really* noisy during Barbeque. I've added a suppression for Sucked In, and moved Barbeque down to Alert, since it's not quite so urgent at that point.
> Raidboss: Reduce alarm annoyance in Matoya's Relict

- ui/raidboss/data/05-shb/raid/e11s.js
- ui/raidboss/data/05-shb/raid/e11s.txt
I had a look through some of quisquous's enrage logs from this week and made some changes. The biggest addition is of course the cycle blocks and enrage at the end. Those ones I'm 100% confident on.
A *lot* of the Bound of Faith stuff seems a bit inscrutable. It got to the point where I felt like I was just throwing random extra IDs in to make things work. As it stands, this version passed every iteration of `test_timeline` I threw at it, which was about 10 different pulls. A couple of them had 0.5-1s drift on the "move to center" timing during the cycles, and the exact timing on Sinsight/Sinsmite/Sinmoke seems to just vary no matter where it is. Other than that, the timings seemed reasonably rigid.
Suggestions welcome. I'm not at this encounter yet, so everything I've done here is from …
> E11S: Timeline updates

- ui/raidboss/data/05-shb/raid/e10s.js
e10s Shadow Servant mechanic has a debuff with separate IDs for each shadow direction. This PR adds north/south/east/west callouts for targeted players.
This is my first time working with the cactbot code since the webpack transition and the outputStrings customization, so please let me know if there's something that should be adjusted there.
> Add callouts for e10s giga slash drops

- ui/raidboss/data/05-shb/dungeon/matoyas_relict.txt
Currently the timeline start parsing is not smart enough to figure out that `The` is sometimes elided. This change should restore functionality to the timeline. `Test_timeline` correctly started for every encounter I tried it on.
> Raidboss: Matoya's Relict timelines should now function correctly

- ui/raidboss/data/05-shb/raid/e11s.txt
Some buddies were running E11S last night and noted that they had some small issues with the Cycle portion of the timeline. The general feeling was that there was just too much information in the timeline, and that not all of it was useful.
1. (Temporary only, to be properly fixed when there's time.) I commented out the Solemn Charge syncs at 471. Unfortunately, the possibilities for each overlap here, causing bad timeline jumpiness. This should be resolved by figuring out the actual IDs for each ability and then doing a full match instead of the compact format used here. (That is, `sync /:Fatebreaker:(5659|5960):/` as opposed to `sync /:Fatebreaker:56(59|60):/`, and similarly for other possible collision points.)
2.  Holy Cycle closing jumps. This is a *bad* mistake and I'm not sure how …
> Raidboss: E11S timeline fixes and QoL

- ui/raidboss/data/05-shb/raid/e10n.js
- ui/raidboss/data/05-shb/raid/e10n.txt
Nothing much to say on the encounter itself. It's very straightforward for both timeline and triggers. Much appreciation to @quisquous for finishing up E10s so I could borrow!
I noted it in-line in the timeline file, but the two phase change abilities are not translated: `英雄の影が受けた攻撃：影の遠吠え`, "Attack on the Shadow of the Hero: Howling Shadow", and `英雄の影が受けた攻撃：ヴォイドパルセーション`, "Attack on the Shadow of the Hero: Void Pulsation". I translated or `"--sync--"`d both. (This is also 100% necessary because both the plugin and `test_timeline` complain about having "unknown characters" if the untranslated names are even in timeline comments. It's easily solvable in `test_timeline` by ensuring the timeline is opened as UTF-8, but I'm not 100% sure of the solution for the timeline controller.) Thanks …
> Raidboss: E10n timeline and triggers

- ui/raidboss/data/05-shb/raid/e12n.js
Thanks to @valarnin for chasing down instances where this happened. It looks like the coordinate system Square uses is just awful all round. (If it weren't completely impossible given what we know of Square, I would have speculated that the coordinates were randomized on each entry.)
> Raidboss: Fix diametrically wrong E12N N/S callouts

- util/encounter_tools.py
- util/test_timeline.py
(This is currently a proof-of-concept only! It needs lots of refinement.)
It occurred to me that it would be nice to color-code certain lines in `test_timeline` that drift by more than a second. The technique I used here is obviously not what will make it into the final version, but at least we have a baseline for what we want. Note that this currently works on my (Windows 10) machine in Powershell, but after some brief testing from @panicstevenson it looks like it does *not* work in Git Bash.
Todo:
1. Make the conditions/string formatting not-ugly. We have plenty of room for improvement there.
2. Make the thresholds configurable at the command line. This should be relatively trivial.
3.
> Util: Test_timeline terminal color-coding

- ui/raidboss/data/05-shb/raid/e9s.js
There was a message on Discord about this potentially not working in some instances; I don't know if this is _the_ fix, but this seems unnecessary to be included.
> raidboss: Remove Unnecessary Headmarker Regex

- .eslintrc.json
- .vscode/settings.json
- eslint/cactbot-locale-order.js
- eslint/package.json
- package.json
Last month I planed to add [this new feature](https://github.com/MaikoTan/cactbot-highlight/pull/5) in my VSCode extension cactbot-highlight,
but I found it is hard to implement the fixture from VSCode extension because I don't know how to fetch and parse code blocks around.
So I abandoned that approach, and try to implement this feature via eslint's existing ecosystem.
This also allows contributors using different editors or IDEs, not only VSCode supports it, even Github Actions would report warnings.
So, this PR planning to implement just like the previous PR that I mentioned:
> ci: add eslint custom rules for locale order

- package-lock.json
- package.json
- webpack/webpack.config.cjs
Requires upgrading to webpack 5.0.0+ to support the `dependsOn` field / more complex `entry` field types.  Upgraded to latest because why not.
> webpack: share raidboss/oopsy data across entries

- .vscode/settings.json
For consistency.
Use `Black` as formator, `pylint` as linter.
> other: add python-related settings of vscode

- ui/jobs/jobs.css
The #right-side-icons are being pulled back behind the resource box as BLM is being treated as having 0 boxes on the right side.
Before: 
After:
> jobs: make space for BLM's Xeno counter resource box

- README.md
- docs/FAQ-Troubleshooting.md
- docs/ko-KR/README.md
Translating to Korean is on progress, I have some concerns with old contents with readme.
1. `utils` directory is changed to `util`
1. "curse" is changed to "curseforge", changed link for BigWigs Bossmods.
1. timeline and trigger uses same directory, so I've put them together.
After [v0.20.0](https://github.com/quisquous/cactbot/releases/tag/v0.20.0), building step is added.
Need to run `npm run build` for building `dist` folder. Prior to this, we need `node.js` install and `npm install`.
So, we should separate building `dll` file and building `dist/*.js` file.
I can write about building `dist/*.js` files but I think it'll be look like translationese, I think it would be better to be written by native English speaker.
Also, I've written new sentences about timeline and trigger file …
> docs: Korean translation with some old contents update

- .eslintrc.cjs
- eslint/cactbot-locale-order.js
- Sort keys in one-click, even there are multiple invalid orders.
- Add configurable option support. (leave it null or undefined then it would use the default one)
- Use ES6 helper functions, might be a little faster?
- Shorten the notification text.
> lint: A better way to implement locale order eslint rule plugin

- ui/jobs/jobs.js
Due to a too early `return`, mythril tempest can not reset comboTimer to 0.
Fixes #2339
> Jobs: Fix WAR mythril tempest can not reset comboTimer

- resources/user_config.js
- ui/config/config.js
- ui/raidboss/raidboss.js
- ui/raidboss/raidboss_config.js
- ui/raidboss/raidboss_options.js
Fixes #2083.
User triggers now show up in the ui.  Each user-defined js file is shown
in its own section as a peer to each expansion section.  Within that
section, each trigger set is given its own subsection even if multiple
trigger sets apply to the same zone.
Like cactbot triggers, user-defined triggers must use output strings in
order to have configurable output text, but other options like duration
and tts vs text can still be configured as long as the trigger has an
id.
This pr handles deprecated-but-still-supported-in-the-wild user
features like zoneRegex and missing trigger ids.  It's nice that the
code to evaluate trigger text is still there, as it applies to
user triggers without output strings.
Triggers with missing ids can't be configured, because all config
options are …
> config: show user triggers in the ui

- ui/raidboss/data/05-shb/raid/e12s.js
This calls out the direction the kb hourglass spawns at.
The Advanced Relativity hourglass could be called out as well via tethers during Oracle's Speed cast or 4 seconds later by the Quicken buff that they get.
> raidboss: e12s oracle add callouts for "Yellow" Anger's Hourglass and "Yellow" Sorrow's Hourglasses

- ui/raidboss/data/05-shb/raid/e12s.js
After reviewing some OverlayPlugin debug output, I noticed E12S Adv Relativity Hourglass Collect Yellow Tethers errors like TypeError: Cannot read property '...' of undefined (Source: webpack://cactbot/./ui/raidboss/popup-text.js?, Line: 84). This happened to be caused by the tethers appearing in Basic Relativity that I overlooked which activate the trigger.
> raiboss: e12s oracle prevent adv yellow tethers check trigger during basic

- docs/LogGuide.md
What it says on the tin, NARI repo was moved to an org account. The repo itself will auto redirect but GitHub Pages doesn't so here we are.
> Update NARI DirectorUpdate docs URL to new repo location

- ui/fisher/fisher.js
The setTimeout hack causes broken behavior when chaining Chum right after a catch, like when chasing narrow Big Fish windows.
> Handle chum more reliably

- plugin/CactbotEventSource/FFXIVProcessIntl.cs
Re-enables the shield percentage since it seems to be back in patch 5.41. 
It feels a bit messy to copy such a large amount of memory for just one byte so far away from the start but I guess it's fine?
Thanks to @AmenneHolelane in https://github.com/quisquous/cactbot/issues/2107#issuecomment-758983952 (and Pohky on the goat place discord!) for finding the value.
Fixes #2107
> plugin: re-add shield values for 5.41

- ui/oopsyraidsy/oopsy_fields.js
- util/coverage/coverage.css
- util/coverage/coverage.js
- util/gen_coverage_report.js
The main "expansion" table is a little confusing because oopsy is tacked
on at the end, as if it's a separate content type.  We could add a
separate oopsy table, but that's overkill for what most people care
about.
I think it would make sense to defer fixing up the table until the
coverage report handles translations as well, and we can see what that
looks like overall.
> coverage: add oopsy to coverage report

- test/timeline/test_timeline.js
- ui/raidboss/data/05-shb/raid/e9s.js
- ui/raidboss/data/05-shb/raid/e9s.txt
Fixes #2146.
In the future, rather than abbreviating abilities in the timeline
itself, we should keep all abilities as their full names, and
then abbreviate in English via timelineReplace.
> raidboss: support English timelineReplace

- .github/workflows/build-artifact.yml
- .github/workflows/release.yml
After testing gh-pages I found that these workflows only cache dependency of C#, but the one of nodejs is bigger.
Adding this may speed the process of building.
> build: cache nodejs dependencies

- ui/raidboss/data/04-sb/raid/o4s.js
- ui/raidboss/data/04-sb/raid/o4s.txt
In light of BLU updates, quisquous and I thought it would be best to modernize the outstanding Deltascape timelines. Many thanks to Shasta for the initial Very Definitely Good Enough timeline that's only now being replaced.
This timeline is unfortunately not as accurate as I should like. There are a lot of places where timing is off by 0.05-0.15 seconds. This currently is rather difficult to fix because I don't have any logs more recent than mid-2019. (I'd rather not hunt-and-peck replace individual times without having modern logs to compare against.) I think we can let this ride for a week or so and then make adjustments as necessary.
Neither part of the encounter uses an `Engage!` sync, since in two-part encounters that's ambiguous. Fortunately, even though Neo doesn't have autos, the …
> Raidboss: O4S timeline refresh

- .github/workflows/build-artifact.yml
- .github/workflows/release.yml
In #2422 I import `actions/cache` to cache npm, but the path `~/.npm` is for Linux and Mac, not for Windows, so change it like this would capable on any OS.
> build: fix npm cache won't work on win

- ui/raidboss/data/04-sb/raid/o11n.txt
Minor QoL for BLU runners since it makes the re-opener after the intermission more precise.
> Raidboss: O11N targetable/untargetable

- ui/raidboss/data/05-shb/raid/e12s.js
Per discussion on Discord, this PR is to separate out the headmarkers for e12s to individual triggers as a precursor to my next PR to add callouts for statues and hand knockbacks.
> Separate out e12s doorboss headmarker triggers to specific mechanics

- ui/raidboss/data/04-sb/raid/o3s.js
- ui/raidboss/data/04-sb/raid/o3s.txt
Nothing much on this one. It was time-consuming but relatively straightforward. There seems to be some randomness on the Queen's Waltz cast timings in phase 4. Nothing major, but it drifts by about 0.3 seconds sometimes.
I feel like we can do better with the `Spellblade Blizzard/Fire/Thunder` entries by using the English `replaceText` functionality, but I'm not sure how to put it more succinctly without incorrectly including `Spellblade Holy`. ("Random Spellblade" doesn't indicate that.)
> Raidboss: O3S timeline refresh

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
冷却 is ambiguous here saying the jump is "cold". I think the trigger intended to let tank bait jump with some mitigation.
> fix minor CN translation in TEA raidboss

- resources/responses.js
Noted in-line for future us, but particularly for instant cleaves, it's *really* annoying to be told to avoid something we can't.
> Resources: QoL for BLU players on responses.tankCleave

- ui/raidboss/data/04-sb/raid/o8s.js
When Clown Kefka uses Mana charge, he gains the effect of Jester's Antics (fake) or Jester's Truths (real). This sets whether his following mechanic uses the accompanying visuals or not. At the time Kefka was added to the repository, we didn't know or didn't have the log lines to see which was which.
I wrote this PR to drop into the existing triggers with minimal rewriting. Quisquous suggested during some offline discussion that we might combine the initial Mana Charge Fire trigger into one. I thought about this and it's definitely possible, but I think it's easier to follow the logic if we keep things separate. We can always come back and do it that way later!
(This also plays into why the conditions for each Fire trigger are so long horizontally. I figured that clarity here was more …
> Raidboss: O8S callouts added for first fires

- ui/raidboss/data/04-sb/raid/o8n.txt
- ui/raidboss/data/05-shb/raid/e6n.txt
I have been annoyed with my bad timings on the E6N timeline for ages but never annoyed enough to remember to fix it. (It was from before we had a helpful flag to auto-generate these timings, but I still should have done better at the time.) As long as I was doing this, I figured I would also drop in timings for Kefka normal, since I ran that after. I left Kefka as separate commits since that's an older timeline. I don't plan to regenerate it right now, but I might look into it at some point in the future. If it's better to just do all that at once later, I can revert the Kefka changes.
> Raidboss: Targetable timings O8N and E6N

- plugin/CactbotEventSource/FateWatcher.cs
I've also removed the old opcodes from the active code. I had hoped they would be useful for the other regions but it doesn't look like that is going to be the case. I've left a comment with the previous opcodes for reference.
This also fixes #2482
> Eureka: Update Bozja opcodes for v5.45hotfix

- ui/jobs/components/blu.js
- ui/jobs/constants.js
tormentBox will also trace DoT from AetherialSpark and Nightbloom now.
These new DoT cannot be stacked with SongOfTorment.
> Jobs: New DoT support for BLU

- ui/raidboss/popup-text.js
`disabled` now only applies on the final override.
Mentioned in #2503.
> raidboss: fix overriding triggers with disabled in them

- ui/config/config.css
- ui/raidboss/raidboss_config.js
This fixes a previous TODO in an effort to address issues that
were brought up in #2503.
This adjusts CSS because having the warning emoji makes the line
slightly taller and makes the (previously existing, but harder
to spot) misalignment much more obvious.
This also adds translations for things like `(function)` that were
not translated previously (sorry).
> raidboss: improve ui for triggers that can't be configured

- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
大龙卷 -> 旋风：CN server changed translation to '旋风' for Twister.
踩远塔 -> 踩远处的塔：for a more appropriate expression.
不地震 -> 无点名：The official translation for 'Earth Shaker' is '大地摇动', '不地震' is literally 'No shake',  '无点名' means 'No marker(on you)', which is more appropriate imho.
> updating Chinese traslations

- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
Chains (23: 0080) go out 3.111 seconds before Scorching hit, headmarker (1B: 01AC) appears 7.111 earlier than the hits. This is timed to when you should start moving then duration to hit(s) if you are late.
> raidboss: DRS Trinity Seeker add chains

- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
Knockback here occurs if the tank cleave is shared. The tank is able to move during the cleave.
> raidboss: DRS Trinity Seeker change Stillness Tank Cleave => Solo Tank Cleave

- ui/raidboss/popup-text.js
This allows for all trigger types (regex, netRegex, timeline) to be
overridden with a trigger of the same id of any other trigger type.
Fixes #2503.
> raidboss: allow overriding a netRegex trigger with a regex Trigger

- ui/raidboss/data/05-shb/raid/e10s.js
The conversion of resources/util in f46d96 changed the output
type of Util.jobToJobEnum from string to number.  This caused
the === check in the `E10S Shadow Of A Hero` trigger to fail.
This is untested, but seems quite likely.
Fixes #2530 (probably).
> raidboss: fix e10s clone callouts

- ui/raidboss/data/05-shb/raid/e3n.txt
I happened to get E3N in Mentor Roulette tonight, and I noticed that the Rip Current at 77.4 can be skipped. I made a change to account for that.
While I was at it, I added more and wider sync windows to better match modern practice. This should guarantee that the user won't be de-synced for too long. (Previously they would have had to wait until the second Undersea Quake for the timeline to catch up.)
Finally, I added numbers to Spinning Dive and Temporary Current. This better fits with modern expectations of "if it's different and close together, differentiate it a little in the text."
> Raidboss: E3N timeline touch-up

- resources/effect_id.js
- ui/jobs/components/mch.js
- ui/jobs/jobs.css
- ui/jobs/jobs.js
- util/gen_effect_id.py
- Use Wildfire buff `count` from network log instead of counting GCD. This makes Wildfire gauge more accurate.
- Now wildfire gauge will remain displaying for 2.5s after finish Wildfire. It will change to a dimmer color at this time. ( Fixes #2559 )
Co-Authored-By: 迷子 (Maiko Tan) <19927330+MaikoTan@users.noreply.github.com>
> Jobs: MCH Wildfire refactor

- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
This is an unfixed bug with timelines where sometimes
timeline triggers get double callouts if not suppressed.
> raidboss: add suppressSeconds to DRS timeline triggers

- resources/party.ts
As reported by Elestriel on Discord, since https://github.com/quisquous/cactbot/commit/707a44d5124812fc051c70179b43b5a1f65ca77e the party members aren't being cleared properly in PartyTracker when receiving an event.
This commit moves the defaults to the property definitions, removes the spurious call to onPartyChanged from the constructor, and moves the reset logic to its own specific function in case an external piece of code needs to invoke it.
> Fix issue with party tracker's members never clearing

- plugin/CactbotEventSource/FateWatcher.cs
Fixes #2596
I finally found it, but I don't like the way I did.
I waited for CE spawn with watching my PC clock (with seconds), I saw two CE spawn at the same time - this was lucky.
The time was 20:45:54 and I wrote all the opcode logged on that timestamp.
```
0203
02D0
0204
02D0
02F0
02F0
0204
007C
007C
02D0
017A
02D0
017A
030E
02F0
02F0
02F0
02F0
02F0
007C
0204
0203
0204
017A
017A
0351
0204
030E
017A
0347
0347
0268
030E
02F0
...(many same opcode)
02F0
0203
0268
0204
0204
0203
0203
02F0
02F0
02F0
```
copied to spreadsheet and  did `=COUNTIF(S17:S73,0347)` thing.
The opcodes which logged twice were `0347` and `0268`.
I tried `0x0347` and built the project. yes... it worked well.
Is this the right way to find opcode? I guess there should be something better.
> plugin: KR v5.35 CE opcode

- ui/raidboss/data/05-shb/raid/e12s.js
Call out opposite direction of cataclysm, a bit more advanced than "getBehind".
I had tested getBehind early on in the tier, but never made a PR with it as ideally a cardinal would have been nicer to have. I will test this out later this week, I am unsure if delaySeconds 0.5 is enough.
> raidboss: e12s oracle cataclysm callout

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/data/CombatantState.js
- ui/raidboss/emulator/data/CombatantTracker.js
- ui/raidboss/emulator/data/RaidEmulator.js
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.js
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
- Fix event 0x15 not mapping x/y/z for combatant state
- Fix issues with RaidEmulatorOverlayApiHook's getCombatants override vs C# property casing
- Fix RaidEmulatorOverlayApiHook's getCombatants override not having the correct timestamp offset when doing initial encounter analysis
- Fix issue with suppressSeconds in RaidEmulator
- Fix issue with slow PCs causing delay in playback, causing desync vs videos
> raidemulator: Fix issues with getCombatants and issue with NetworkAbility line parsing

- package.json
- util/find_missing_timeline_translations.js
- util/find_missing_translations.js
Convert find_missing_translations from Python to JavaScript.
Example usage:
```sh
node --loader ts-node/esm ./util/find_missing_translations.js --locale fr
```
or
```sh
npm run find-translations -- --locale=fr
```
Fixes https://github.com/quisquous/cactbot/issues/2541
> util: Convert find_missing_translations to JavaScript

- package-lock.json
- package.json
- ui/raidboss/raidemulator.js
- webpack/webpack.config.cjs
This PR fixes #2564 though the fix isn't that great. I added the `worker-loader` loader to npm/webpack and used that to load the worker, which resolves loading over file URI by automatically switching to a blob, but it makes the actual worker import code a bit ugly. Copy/pasting the comment for reference:
```js
// @TODO: For some reason this absolutely has to be imported as `Worker`, no matter what settings
// are specified in webpack.config.cjs
// Using `{ Worker as NetworkLogConverterWorker }` also fails for some reason.
// Using `{}` works for some reason too.
// eslint-disable-next-line import/default
import Worker from './emulator/data/NetworkLogConverterWorker';
```
The `Worker` portion of the import line also shows as an error in vscode and eslint without the ignore rule. …
> Fix web worker for raidemulator loading over file:// URIs

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/data/NetworkLogConverterWorker.js
This PR fixes the bug in #2477 caused by party state not being updated per perspective change in AnalyzedEncounter.
Also fixes a bug that was found during investigating the issue, where import code skipped the first line of the imported log file.
> raidemulator - Fix #2477 related to party events during encounter analysis

- resources/conditions.ts
- resources/netregexes.ts
- resources/regexes.ts
- types/trigger.d.ts
This change makes it easier for us to refactor the Trigger data file later on, we can write
```typescript
{
id: 'General Provoke',
netRegex: NetRegexes.ability({ id: '1D6D' }),
condition: function(data: Data, matches: Matches<typeof NetRegexes.ability>): boolean {
if (matches.source !== data.me && !data.party.inAlliance(matches.source))
return false;
return caresAboutTankStuff(data);
},
},
```
and then TypeScript will automatically derive it as:
```typescript
(parameter) matches: {
sourceId: string;
source: string;
id: string;
ability: string;
targetId: string;
target: string;
timestamp: string;
}
```
As in VSCode, it would be like this:
> Refactor: generic regex/netregex helper function improve

- resources/translations.ts
Sorry that I've not noticed at the last time.
> Fix: LocaleNetRegex should use `this.netRegexes`

- resources/resourcebar.ts
> Fix: typo 'full' in resourcebar

- resources/resourcebar.ts
Reverts quisquous/cactbot#2623
Sorry, this causes the mp bar to say `NaN` in the jobs overlay.  I haven't looked into why this is happening, but just wanted to roll back to a working version.
> Revert "Fix(resourcebar): getter and setter accept string"

- util/find_missing_translations.js
Remove auto-generated files from consideration, and fix a bug where
text blocks including variables were not considered.
Fixes https://github.com/quisquous/cactbot/issues/2608
> Fixup find_missing_translations.js

- util/find_missing_translations.js
Make regex within the JavaScript version of find_missing_translations
more accurately match the Python version.
> Fix find_missing_translations.js Regex

- resources/widgetlist.js
- ui/jobs/jobs.js
Reverts quisquous/cactbot#2532
@Trim21 I'm sorry to revert this, but this patch was causing all of my overlays to run with extreme lag.  Normally I wouldn't revert and would just fix, but I think this is a pretty bad bug.  My jobs overlay would print `BrowserConsole: Element with id child20 is missing? (Source: http://localhost:8080/dist/jobs.bundle.js, Line: 10214)` many times a second.  When I reverted this patch locally it stopped happening, so I feel pretty confident that this is the issue.
> Revert "refactor(resources): migrate WidgetList to TypeScript"

- resources/outputs.ts
I had not seen that it was the adjective and not the conjugate form, this which distorts the indication. I replace by the form conjugate to make the indication correct and understandable.
> output fr minor correction

- resources/overlay_plugin_api.ts
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
After #2611, the raid emulator enters infinite recursion.
```
overlay_plugin_api.ts:97 Uncaught (in promise) RangeError: Maximum call stack size exceeded
at Object.addOverlayListener [as addOverlayListenerOverride] (overlay_plugin_api.ts:97)
at Object.addOverlayListener [as addOverlayListenerOverride] (overlay_plugin_api.ts:98)
at Object.addOverlayListener [as addOverlayListenerOverride] (overlay_plugin_api.ts:98)
at Object.addOverlayListener [as addOverlayListenerOverride] (overlay_plugin_api.ts:98)
```
This is because of this call sequence:
* original addOverlayListener -> checks for override
* calls RaidEmulatorOverlayApiHook version -> calls original function
* original function checks for override again
The root of the issue is that the "original" function needs to not
include the …
> Fix recursion error from overlay_plugin_api.ts

- util/check_translation.py
- util/make_timeline.py
Force UTF-8 encoding for stdout for check_translation.py and
make_timeline.py. A bit of a hack to make things work; but,
hopefully won't cause any issues and hopefully will restore
some functionality.
Closes https://github.com/quisquous/cactbot/issues/2665 and https://github.com/quisquous/cactbot/issues/2510
> util: Force UTF-8 Encoding for Translation Scripts

- ui/raidboss/emulator/data/PopupTextAnalysis.js
- ui/raidboss/emulator/ui/EmulatedPartyInfo.js
- ui/raidboss/raidemulator.css
- ui/raidboss/raidemulator.html
- ui/raidboss/raidemulator.js
This PR reworks the way analyzed triggers are displayed in raidemulator to make it more obvious at a glance what various triggers do.
This PR also adds an additional checkbox to the trigger display to hide "collector" triggers, e.g. triggers that ran but produced no user-visible output.
Here's an example screenshot:
> raidemulator - Rework the way analyzed triggers are displayed

- resources/netregexes.ts
- util/find_missing_timeline_translations.js
This used to work, but when we switched over to netregexes from regexes
this broke and nobody ever noticed.  Unfortunately, there's a lot of
regexes that don't need to be translated, so this adds an
*EXTREMELY* hacky method to detect them.
NetRegexes know what fields that they have on construction, and only
particular fields need translation.  Therefore, if a global flag is
flipped and a NetRegex needs that field, insert a noop character
sequence at the beginning of the NetRegex that we can then detect
in order to know if this NetRegex had such fields when it was
constructed.
> util: fix find_missing_translations to report timelineReplace mismatches

- ui/raidboss/data/03-hw/raid/a1s.js
- I saw this on a11s:
de `'E\\\\.D\\\\.D\\\\.': 'E\\.D\\.D\\.-Mecha',`
fr `'E\\\\.D\\\\.D\\\\.': 'E\\.D\\.D\\.',`
ja `'E\\\\.D\\\\.D\\\\.': 'イーディーディー',`
- a1s:
de `'Oppressor(?! 0)': 'Unterdrücker',`
de `'Oppressor 0\\\\.5': 'Unterdrücker 0,5',`
I thought it should be the same here. If this is not useful, I cancel this request.
> raidboss: a1s replaceSync

- ui/oopsyraidsy/data/05-shb/raid/e7n.js
- ui/oopsyraidsy/data/05-shb/raid/e7s.js
Issues found from converting oopsy to TypeScript manually and
running tsc.
Ignoring issues around unused variables or type assertion, or anything
that applies to TypeScript exclusively.
> oopsy: Logic Error Fixes from TypeScript Compiler

- ui/raidboss/emulator/data/PopupTextAnalysis.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimeline.js
- ui/raidboss/popup-text.js
- ui/raidboss/timeline.js
This PR changes the calls to `new Date` in PopupText and the Timeline classes to instead be emitted from log line events, per various discussions.
> raidboss: Change new Date calls to emit from log events

- .eslintrc.cjs
- eslint/cactbot-timeline-triggers.js
Add rules for checking the timelineTrigger syntax.
Ensure that the `regex` property uses a regular expression literal:
Ensure properties such as `netRegex` or `regexFr` are not present:
> lint: Add timelineTrigger Syntax Checks

- resources/party.ts
- tsconfig.json
When functions have return types, TypeScript already handles the case
where a function cannot have an undefined return type, implicit or
explicit.
I think it noisy to have to add a `return;` at the end of a function
that can return undefined as a type.  This will especially be the
case for triggers, which use implicit return undefined as a way
to not output things in many trigger functions.
Turning this off for now will help make that conversion easier.
If this creates an issue, then once everything has turned into
TypeScript we can revisit and turn it back on.
> typescript: remove tsconfig noImplicitReturns

- package-lock.json
- package.json
- resources/timerbar.ts
- resources/timerbar_test.html
- ui/fisher/fisher-ui.js
- ui/jobs/components/mnk.js
- ui/jobs/jobs.js
- ui/raidboss/timeline.js
- webpack/webpack.config.cjs
Closes #2613.
This is the same as #2613, except for an extra commit to rename `styleFill` to `stylefill`.
Additionally, `toward` appears to be broken, but it was broken before these changes.
I filed #2707 for this.
> Refactor: TypeScript-ize timerbar.js

- ui/raidboss/data/03-hw/raid/a3s.js
- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
- ui/raidboss/data/05-shb/raid/e7s.js
- ui/raidboss/data/05-shb/trial/ruby_weapon-ex.js
Fix incorrect instances of arrays that should be maps, given their usage
throughout the rest of the trigger file. This was not done exhaustively,
searching for instances of arrays within raidboss and ensuring that they
are not accessed in unexpected ways.
> raidboss: Correct Arrays That Should Be Maps

- resources/party.ts
- test/unittests/util_test.js
- ui/oopsyraidsy/data/05-shb/raid/e12s.js
Noticed when running `npm test` that one of the final tests had a typo. Ran a search on the code and corrected all instances of `itt` vs `it`, even though the rest of them were in comments.
> various: Fix typo of 'itt' vs 'it'

- .github/workflows/update-triggers-branch.yml
- docs/CactbotCustomization.md
- docs/ko-KR/CactbotCustomization.md
- docs/zh-CN/CactbotCustomization.md
- docs/zh-TW/CactbotCustomization.md
- package.json
- tsconfig_triggers.json
- util/file_utils.ts
- util/process_triggers_folder.ts
As trigger files are diverging more and more from things that users
can copy and paste into javascript file, create a triggers branch
that can be viewed online that has the most recent version of all
of the triggers.
This will allow us to start converting trigger files and still
have a place that users can look to see a JavaScript transpiled
version that they can more easily copy and paste as needed.
> util: process and generate triggers branch

- types/trigger.d.ts
#2611 @MaikoTan 
```js
// global.d.ts
export type NonEnLang = Exclude<Lang, 'en'>;
// trigger.d.ts
import { Lang, NotEnLang } from './global';
```
> typo in type definition

- ui/config/config.css
- ui/raidboss/raidboss_config.js
Add the ability to view the `triggers` branch from within the config
UI.
Ideally, the link would open in Chrome to take advantage of text
highlighting, but that functionality doesn't exist yet.
> raidboss: Add Trigger Source to Config

- ui/raidboss/timeline.js
As per [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-regexp-exec.md),
RexExp#exec is more performant than String#match while providing the
same results, provided that the global flag is not being used.
> raidboss: Convert Timeline to RegExp#exec Over String#match

- ui/test/test.js
[typescript-eslint prefers to not mix numbers and strings.](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-plus-operands.md)
Small pre-TypeScript conversion step for additional confidence.
> test: Convert Test Strings to Template Literal

- resources/content_list.js
- test/unittests/resources_test.js
Reverts quisquous/cactbot#2787.
ZoneId might be undefined, and ContentList doesn't like that.
> Revert "resources: convert content_list.js to typescript"

- resources/responses.js
(This resolves #2793 )
Briefly, for those not immediately familiar with the internals of `Responses`, some response functions take two parameters, the "primary" severity, and the "secondary". (Usually these functions are assigned different default severity levels.) The user can then choose specific severity levels for the response in the trigger body. If the severity levels are different, the two different output functions are assigned to different severity levels in the trigger response object and it's then returned.
If the severity levels are the same, the response object is supposed to be a function that returns the correct response. However, a missing `return` meant that this function just evaluated `true` and exited. Since it's *incredibly* uncommon to assign non-default severity to …
> Responses: combineFuncs will now combine identical severity levels

- resources/content_list.ts
- test/unittests/resources_test.js
Reland #2787 that was reverted in #2794.
Root fix for the issue in #2795.
This reverts commit bc3d5678c8d90207a697cbd4e7623e8ebd6f8afc.
> resources: convert content_list.js to typescript (reland)

- ui/raidboss/data/04-sb/trial/lakshmi-ex.js
- ui/raidboss/data/04-sb/trial/lakshmi-ex.txt
- ui/raidboss/data/04-sb/trial/lakshmi.js
- ui/raidboss/data/04-sb/trial/lakshmi.txt
- ui/raidboss/data/manifest.txt
I modified the trigger names in EX so as to avoid any possibility of collisions. I didn't *think* this was a problem since it's a necessary disambiguation, but I can revert those changes and submit them separately if necessary.
One of the patterns involving stack markers combined with other markers does technically give people enough time to stack, but it's probably best to keep them away so puddle people don't clip the stack. This is particularly important during Chanchala phases, since the puddles expand significantly.
There are a lot of abilities that have different IDs at different points in the timeline. This is because all her skills are empowered under Chanchala, and Square implements this by just using different skills.
This doesn't attempt to check for whether a non-tank has the …
> Raidboss: Emanation (Lakshmi normal mode) timeline and triggers

- resources/outputs.ts
Better translations.
The addition of the preposition (à) is to give the order to go in the direction.
> outputs fr

- ui/raidboss/popup-text.js
Open promises (i.e. popup text incoming from `delaySeconds` or
`promise`) will be rejected at the end of a fight; the error logging
here is confusing.
> raidboss: Skip Error Logging for Valid Promise Rejections

- resources/regexes.ts
Update Regexes#parseGlobal to additionally take string inputs, matching
Regexes#parse.
> resources: Update Regexes#parseGlobal Parameter Types

- resources/not_reached.ts
- resources/user_config.ts
- ui/raidboss/timeline.js
Unfortunately, even a function that returns `never` is not enough
for TypeScript to trust this in all cases, so convert this to an
Error type instead.
This should remove the need for "convince TypeScript" sort of comments
as well.
> resources: move notReached to common UnreachableCode error

- ui/jobs/components/brd.js
- ui/jobs/jobs.js
It seems like the last PR changed the default value of `toward` property in `resources/timerbar.ts`, so the MPTicker doesn't go right as before.
> Fix(jobs): MPTicker/repertoreTimer bar goes left

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.js
This PR fixes #2504 by supporting `timelineTriggers` during encounter analysis.
This is a first pass. It's functional but causes a lot of DOM updates (due to the timeline events actually firing during analysis) which makes the initial encounter load slightly slower.
I'm not sure if it's worth the effort of fixing this, I can barely tell a difference on my hardware so I'd prefer if someone with slower hardware can test and let me know how much the performance impact is vs the current `main` code.
> raidemulator - Implement timelineTriggers support

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/data/PopupTextAnalysis.js
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js
- ui/raidboss/emulator/ui/EmulatedPartyInfo.js
- ui/raidboss/popup-text.js
This PR fixes the delaySeconds and suppressSeconds implementations for raidemulator, resolving the last two outstanding tasks in #2161.
Also fixes two other issues that have cropped up over time while cleaning up the other tasks in #2161.
Fixing delaySeconds required rewriting a pretty large chunk of code related to how triggers are tracked and processed. I've run this set of changes through the following scenarios:
1. e12s clear
2. e12s partial clear, no delaySeconds got clipped short
3. Several encounters with no triggers
4. Several encounters with only delaySeconds triggers
5. Several encounters with only suppressSeconds triggers
The only scenario I couldn't test is where a trigger with `delaySeconds` never has its delay resolve before the end of the encounter. I don't anticipate there …
> raidemulator: Fix delaySeconds/suppressSeconds implementation

- ui/raidboss/browser_tts_engine.ts
- ui/raidboss/popup-text.js
- ui/raidboss/raidboss_config.js
- ui/raidboss/raidboss_options.ts
Remove the extremely unofficial undocumented API tts path which appears to no longer be working for many users along with the raidboss config option.  The "browser TTS" path now only supports the built-in browser `window.speechSynthesis` path for remote raidboss and that option is enabled implicitly when needed.
If users want to change their cactbot tts voices when using an overlay, they should change their ACT tts voice by going to ACT -> Options -> Sound Settings -> Text to Speech Control Panel Applet and change the Windows tts voice there.
Fixes #2860 {/airquotes}
> raidboss: remove browser tts

- ui/raidboss/data/05-shb/eureka/bozjan_southern_front.js
- ui/raidboss/data/05-shb/raid/e11s.js
- e11s
only that line was translated 'lightning(번개)' into 'fire(화염)'
- bozjan
typo
> raidboss: KR fix

- .eslintrc.cjs
- eslint/cactbot-output-strings.js
- resources/overlay_plugin_api.ts
- resources/resourcebar.ts
- resources/timerbar.ts
- resources/timerbox.ts
- resources/timericon.ts
- resources/translations.ts
- ui/jobs/jobs.js
- ui/jobs/utils.js
- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
- ui/raidboss/emulator/data/CombatantTracker.js
- ui/raidboss/timeline.ts
- util/coinach.ts
As part of a potential series of commits to move to [prettier-eslint](https://github.com/prettier/prettier-eslint), add some rules to enforce desired styles.
For this style, specifically, Prettier will default to putting lines without braces onto a single line if it is able to. The options here would be to either add braces for single line control statements, or to force these one-liners onto two lines. Picking the latter because the changeset is smaller.
> lint: Add Non-Block Body Statement Below

- ui/jobs/components/dnc.js
- ui/jobs/components/mnk.js
- Fix a mistake that `effect` missing when refactoring.
- Use `onYouGainEffect` instead of `onUseAbility` for Twin Snakes, solve the `using at zero` issue.
- Fix Perfect Balance triggers function on each stack consumed.
> jobs: fix mnk, dnc

- ui/raidboss/data/05-shb/dungeon/matoyas_relict.js
The target of the skill `Crash-Smash` is Nixie itself, so change to `HeadMarker` version.
I just write down my opinion on `de`, `fr` and `ko`, might not the correct ones.
> Raidboss: notify as tankbuster from Nixie for tank

- resources/conditions.ts
- resources/responses.ts
- types/data.d.ts
This will let us differentiate OopsyData when that exists,
as well as letting individual trigger files define something
like `Data extends RaidbossData` to have shorter type definitions.
> types: rename Data to RaidbossData

- ui/raidboss/data/04-sb/raid/o4s.js
- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js
These are the three places that are assigning a function() to
data, and then using `this` inside of that function.
In preparation for auto-converting triggers to use arrow functions,
and an eslint rule, convert these to arrow functions.
In the future, this form of function+this will still be ok even with
the eslint rule, but it makes the auto-conversions fully automatic.
I also think it's cleaner.
> raidboss: convert function+this usage in trigger files

- .eslintrc.cjs
- package-lock.json
- package.json
This only applies to raidboss data files at the moment.
> eslint: add prefer-arrow/prefer-arrow-functions rule

- ui/raidboss/emulator/data/network_log_converter/LineEvent0x00.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x19.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
Follow up PR for fixes mentioned in #2879.
Opted to move `LineEvent0x18`'s `effectName` property initialization to the constructor instead of the `convert` method, since it doesn't need to be delayed for repo population like some other properties.
> raidemulator: Follow up fixes for #2879

- .github/workflows/update-gh-pages.yml
- .github/workflows/update-triggers-branch.yml
Use consistent action dependencies across workflows using the checkout
action as well as setup-node in an attempt to fix the most recent build
error: https://github.com/quisquous/cactbot/runs/2661413115
> ci: Use Consistent Action Dependencies

- .eslintrc.cjs
- resources/user_config.ts
- util/process_triggers_folder.ts
This will make sure that trigger files actually are usable as user
files on the triggers branch.
Also, make line length a warning now that we have a limit of
zero warnings.  This will make it less noisy and let us detect
other errors in trigger files.
> util: add eval check to process-triggers

- ui/raidboss/emulator/data/NetworkLogConverter.ts
- ui/raidboss/emulator/data/NetworkLogConverterWorker.js
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x00.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x02.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x04.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x0C.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x17.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x19.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1B.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1C.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1D.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1E.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x22.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x23.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x24.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x25.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x27.ts
After the conversion of LineEvent to use getters, that data was no longer capable of passing the postMessage boundary from the worker to the main window thread. This fixes the issue by iterating the getters on the lines and populating them on the passed generic object.
Note that, even if we were to get rid of the Worker threading, this would still be required as IndexedDB only stores plain objects.
This may make more sense to put directly in the `EmulatorCommon.cloneData` function as base functionality but the performance impact on that is noticeable.
> raidemulator: Fix issue with LineEvent getter data passing postMessage boundary

- resources/matches.ts
- resources/netregexes.ts
- types/trigger.d.ts
- ui/jobs/buff_tracker.ts
- ui/radar/radar.ts
This changes Matches from being `Matches<RegexType<Params>>` to just
`Matches<Params>` for simplicity, as there's no concrete differences
between these types.
It also seems useful to have an indirection between our Match types
and the actual templated type so that we don't have to change
a million trigger files if we ever change how they are implemented.
> resources: add Matches type aliases

- .github/workflows/post-process.yml
These steps sometimes fail for various reasons, so it'd be
nice to make sure that any changes to content don't break
them.
> ci: add "post-process" step for coverage/triggers branch

- .github/workflows/update-gh-pages.yml
After #2924, update-gh-pages stopped working.
Switching back to checkout@v2 as an experiment.
> ci: experimental fix for update-gh-pages

- ui/raidboss/emulator/data/Encounter.js
- ui/raidboss/emulator/data/LogEventHandler.ts
Found two outstanding issues with typescript conversion for raidemulator while testing the parsing plugin update yesterday.
I'll probably revisit the `zoneId` issue once the rest of raidemulator is converted, since it makes more sense to do the `parseInt` conversion when loading and parsing the log data, rather than later when persisting the encounter to DB.
> raidemulator: Clean up some issues with typescript conversion

- ui/raidboss/emulator/data/RaidEmulator.js
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimeline.js
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.js
- ui/raidboss/emulator/ui/EmulatedPartyInfo.js
- ui/raidboss/emulator/ui/ProgressBar.js
This PR fixes a number of minor issues related to using offsets instead of log line timestamps which were left over from #2862, which I incorrectly attributed to the changes in #2942.
Also included in this PR is a fix for a long outstanding issue with seeking during an encounter with a jump (e.g. e12s p2) which these fixes exposed the root cause of.
> raidemulator: Fix various issues related to using relative offsets instead of log line timestamps

- ui/raidboss/popup-text.js
This fixes issues where going into combat would reset which
CE the Zadnor triggers thought you were in.  In particular,
if resetWhenOutOfCombat is set, the triggers themselves
must always specify stopping combat.
> raidboss: fix resetWhenOutOfCombat

- util/translate_timeline.ts
Line number was off by 1 after switching to forEach.
Closes https://github.com/quisquous/cactbot/issues/2965
> util: Fix Translate Timeline

- ui/raidboss/emulator/data/RaidEmulator.js
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
As discussed in #2942, set Options.ParserLanguage to the auto-detected language when analyzing and loading encounters for playback.
This can be done via a single set in `RaidEmulator.setCurrent`.
This PR also fixes an issue with the getCombatants call which was caused by writing the additional non-tracked field code against the old version of LineEvent whereas the new version doesn't store the `parts` array because all relevant parts are extracted to proper fields now.
> raidemulator: Fix loading encounters with a different base language, issue with getCombatants

- .github/workflows/build-artifact.yml
- .github/workflows/css-lint.yml
- .github/workflows/javascript-lint.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/post-process.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update-gh-pages.yml
- .github/workflows/update-triggers-branch.yml
Update `npm install` to instead use `npm ci`.
After looking into an error in the [update-gh-pages](https://github.com/quisquous/cactbot/runs/2707837316?check_suite_focus=true) action, I noticed a
number of workflows are still using `npm install` that should be using
`npm ci`. While looking for best practices, I found [this blog post](https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/), which
I've implemented the "even faster alternative" here.
> ci: Update NPM Cache and Install Commands

- ui/raidboss/raidboss_config.js
generating url in this way: https://github.com/quisquous/cactbot/blob/triggers/04-sb/dungeon/bardams_mettle.js#:~:text=id%3A%20%27Bardam%5C%27s%20Mettle%20Rush%27
it's `id: 'Bardam\'s Mettle Rush'`
previous:
https://github.com/quisquous/cactbot/blob/triggers/04-sb/dungeon/bardams_mettle.js#:~:text=id%3A%20Bardam%5C%27s%20Mettle%20Rush
it's `id: Bardam\'s Mettle Rush`
> fix(config): view source fragment

- ui/raidboss/raidboss_config.js
Reverts quisquous/cactbot#2986.
`replaceAll` is a Chrome M85 feature, which OverlayPlugin does not support.
This patch caused "trig.id.replaceAll is not a function" errors which prevented the config from loading.
> Revert "fix(config): view source fragment"

- ui/raidboss/data/05-shb/raid/e9s.js
Noticed this issue while testing the language fix for raidemulator.
Edit:
Fixes #2995.
> raidboss: Fix e9s callout not being declared properly

- .github/scripts/auto-label.cjs
```js
mocha.setup('bdd');
const assert = chai.assert;
/**
* @param {string} patch
*/
const parseChangedLang = (patch) => {
const set = new Set();
for (const lang of ['cn', 'de', 'ja', 'fr', 'ko']) {
const pattern = new RegExp(String.raw`^\+\s*(?:${lang}|'${lang}'):`);
for (const line of patch.split('\n')) {
if (pattern.test(line)) {
// TODO: it'd be nice to add the file/line number here.
if (!set.has(lang))
console.log(`label: ${lang} [translation]`);
set.add(lang);
}
}
}
return Array.from(set.values());
};
describe('parseChangedLang', () => {
it('should match only single word', () => {
assert.deepEqual(parseChangedLang(`+  de: 'hello',`), ['de']);
});
it('should match quoted', () => {
assert.deepEqual(parseChangedLang(`+  'de': 'hello',`), ['de']);
});
it('should match only single word', …
```
> ci: label script will match key with lang only

- plugin/CactbotEventSource/FateWatcher.cs
Found an amazing plugin to find CE opcode. https://github.com/kshman/DutyContent
I've built the cactbot plugin with this change, and successfully detected CE from v5.4 Korean server.
> eureka: update ko v5.4 CE opcode

- ui/jobs/buff_tracker.ts
- **Auto remove readied raidbuffs that not be used in 3min.** 
If a readied raidbuff not be used in 3min, we can assume that this player has left the battlefield, or that is a DNC who no longer dance with you, or a DRG who no longer consider you as his left eye, or at least his raidbuff is unexpectable and not worth tracing. 
-- This usually happen in Bozjan/Eureka that a lot of NIN cast `Trick Attack` and leave the battlefield, leaving a lot of `Trick Attack ready` on your `buffTracker`, preventing you to read the coming cooldown of other raidbuffs.
> Jobs: Auto remove readied raidbuffs that not be used in 3min

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/data/Encounter.js
- ui/raidboss/emulator/data/NetworkLogConverterWorker.js
- ui/raidboss/emulator/data/Persistor.js
This PR fixes two issues identified in #3021:
- In #2997 code was added to upgrade encounters that were older to a newer format, but this code couldn't trigger due to `Encounter.initialize` being called in the constructor.
- `Encounter.initialize` moved out of the constructor and to downstream locations
- In #2606 when timeline trigger support was added, the code assumed that every loaded fight would have a timeline.
- An `if` check was added to prevent timeline trigger handlers from being added if the encounter has no timeline associated with it
> raidemulator: Fix #3021

- .eslintrc.cjs
find that eslint become extremely slow, try debugging, eslint is trying to lint file in `.venv/` dir.
> eslint: ignore `.venv/` dir

- .eslintrc.cjs
I am not sure what I think about this.  I feel like the eslint file is getting really big and things are added all over the place.  Forcing the keys to be sorted keeps it in a more reasonable order, but also makes it slightly less readable?  I am not sure.
> lint: apply sort-keys to .eslintrc.cjs

- webpack/webpack.config.cjs
Webpack v5 has a native TerserPlugin. Creating a new one led to an
increase in build times by nearly 50%.
> build: Use Webpack v5 Native TerserPlugin

- ui/raidboss/emulator/data/Encounter.ts
- ui/raidboss/emulator/overrides/RaidEmulatorTimeline.js
- ui/raidboss/emulator/ui/ProgressBar.js
- ui/raidboss/raidemulator.js
Found this issue while testing the RaidEmulatorTimelineUI typescript conversion, basically `initialOffset` is, as the name implies, an offset, but in #3029 when I corrected from using `engageAt` I didn't account for the fact that `engageAt` was a timestamp, not an offset.
> raidemulator: Fix issue caused by #3029 with initialOffset

- ui/raidboss/common_replacement.ts
This should, I think, fix #3040.
Please review this one more thoroughly, as I'm not as familiar with exactly how common replacements work through all the components.
The fix looks good in raidemulator using the log attached to the issue, at least.
> raidboss: Fix timeline sync based on area seal message

- ui/raidboss/data/04-sb/dungeon/st_mocianne_hard.js
- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.js
Noticed when testing performance in alliance raids, there were some triggers using `matches.duration` instead of `matches.castTime`. Checked with this regex and found another case:
```
NetRegexes.startsUsing.*?\n(?:      [^ ].*\n)*      delaySeconds.*duration
```
I checked any other cases of `\.duration[^a-zA-Z]` in triggers and it looks like these are the only cases?
> raidboss: Fix some triggers using `matches.duration` instead of `matches.castTime`

- ui/raidboss/emulator/data/AnalyzedEncounter.js
- ui/raidboss/emulator/overrides/RaidEmulatorAnalysisTimelineUI.js
- ui/raidboss/raidemulator.js
This PR fixes a performance issue mentioned and caused by timeline trigger support, as well as an issue with async vs non-async execution when loading encounters, which caused seeking to the start of the encounter to happen before analysis was complete in some cases.
> raidemulator: Performance and fixes

- types/trigger.d.ts
- ui/raidboss/data/00-misc/test.js
While working on converting popup-text.js to typescript, I noticed a typing issue with trigger.d.ts.
Basically, `./ui/raidboss/data/00-misc/test.js` has the following trigger which doesn't use language keys. Either the `Output` type in trigger.d.ts needs adjusted, or this trigger needs adjusted. Either way, to avoid having to redefine types, the typing of OutputStrings was moved to its own type definition and exported.
I opted to allow plain strings in this PR because I don't know if this is the only trigger that's using plain strings here and I don't have a good way to search all the triggers to check.
```js
{
id: 'Test Response',
netRegex: NetRegexes.echo({ line: 'cactbot test response.*?', capture: false }),
netRegexDe: NetRegexes.echo({ line: 'cactbot test antwort.*?', capture: false …
```
> util: Adjust typings in trigger.d.ts

- resources/player_override.ts
- resources/responses.ts
- resources/user_config.ts
- types/data.d.ts
- types/event.d.ts
- types/manifest.d.ts
- types/trigger.d.ts
- ui/raidboss/raidboss_options.ts
- ui/raidboss/timeline.ts
- webpack/webpack.config.cjs
A lot of miscellaneous adjustments I hit while converting popup-text to typescript.
These are fine to push to main before the actual popup-text conversion (which is also done), so I thought I should PR these separately so that the popup-text PR is smaller.
Tested these changes with raidemulator and in-game within overlayplugin overlay via raidboss. Didn't test jobs or the other overlays, since I'm not familiar with them, but they shouldn't have any problems?
> various: Fixes in preparation for popup-text typescript conversion

- types/trigger.d.ts
This will let trigger files have required matches fields but
popup-text will deal with non-required MatchesAny.
It's a bit of a hack, but I think the eslint rule for making
sure that all triggers have the right matches will make this work?
Closes #2994.
> raidboss: make Matches have required fields

- resources/timerbox.ts
- ui/jobs/components/ast.js
- ui/jobs/components/blm.js
- ui/jobs/components/brd.js
- ui/jobs/components/drg.js
- ui/jobs/components/pld.js
- ui/jobs/components/sam.js
- ui/jobs/components/sch.js
- ui/jobs/components/smn.js
- ui/jobs/components/war.js
- ui/jobs/components/whm.js
- ui/jobs/jobs.css
- ui/jobs/jobs.js
- ui/jobs/jobs_config.ts
- ui/jobs/types.d.ts
In case a proc box expires (reaches a duration of 0) and we are still
in combat, continuously flash the box to draw attention to it.
This is intended for proc boxes like dots or self-bufs which should be
always active/running while in combat.
The feature can be turned on in the Jobs settings via the variable
FlashExpiredProcsInCombat.
Proc boxes that should flash should pass
flashWhenExpired: true
to the addProcBox call that creates them.
> Jobs: Flash proc box when expired and in combat

- tsconfig.json
- webpack/webpack.config.cjs
Well in fact, I don't like this solution. But it is not very well to bundle `*.d.ts` and `*.map` in release and ship it to end users. So disable it, and enable in development.
> build: only generate TypeScript declaration in dev

- ui/eureka/eureka.js
This `nm-down` line was removed in #2955 because it was marking every
skirmish, CE, and duel as `nm-down` incorrectly.  However, this was
important for Eureka.  So, just early out for Bozja.
There's probably a better solution here, but I'd like to not leave
this broken.
Fixes #3042.
> eureka: fix Eureka fates not being marked red when on cooldown

- docs/RaidbossGuide.md
- types/trigger.d.ts
- ui/raidboss/popup-text.ts
Closes #3063 
Makes `trigger.tts` completely Partial, adjusts logic for tts to only set `triggerHelper.ttsText` if the value resolves.
If `triggerHelper.ttsText` is undefined, `_onTriggerInternalPlayAudio` will by default fall back to the audio alert.
There might need to be a new `Default alert output` option for `TTS w/ fallback to Sound`, since otherwise this state can't be encountered in normal operation anyways?
> raidboss: Allow partial TTS entries

- package-lock.json
- package.json
- webpack/webpack.config.cjs
to ensure js code would be transpiled,
and recognizable by current version of CEF in OverlayPlugin.
Also allow us to use new ES syntax to simplify code
> build: add babel/preset-env

- ui/eureka/eureka.css
- ui/eureka/eureka.js
- ui/eureka/eureka_config.ts
Following our discussion in [this PR](https://github.com/quisquous/cactbot/pull/3076), here are new features and changes/additions for cactbot-eureka:
1. User Option to allow complete names
2. User Option to allow enriched content
3. Complete names of the Skirmish/CE (english short names moved to "shortname" property)
4. Field Notes informations (data gathered manually, may be off somewhere but I kinda doubt that)
5. Field Notes display if Skirmish/CE has one
These user options are disabled by default and the changes have been made so that they're 100% opt-in. 
Complete names and enriched informations, English
Short names and enriched informations, French
These new features were tested by bruteforcing them in the eureka.bundle.js (sorry) in the 4 parts of Eureka, Bozja and Zadnor. 
The …
> eureka: Complete names & enriched content for Save-The-Queen

- types/event.d.ts
- ui/test/test.ts
This PR reworks the way `PlayerChangedRet` types `job` and `jobDetail` to automatically infer the type of `jobDetail` based on the value of `job`.
This is using some circular infer syntax that I'm not 100% solid on so please give this one a thorough review, and test some of the Jobs overlays.
I tested this against the Cactbot Test overlay and that was picking up changes fine for WHM/WAR/DNC, which are the only three classes I can properly test with.
If `job` is checked against a job that doesn't have a defined JobDetail, it will type `jobDetail` to unknown, as such:
> other: Rework PlayerChangedRet to auto-infer jobDetail type

- ui/raidboss/emulator/data/Combatant.ts
- ui/raidboss/emulator/data/CombatantJobSearch.ts
- ui/raidboss/emulator/data/CombatantTracker.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
I feel like there's a better way to handle CombatantJobSearch but I can't see it?
This is in prep for converting PopupTextAnalysis to typescript. I'll probably visit the JobDetail type next since that's also causing some annoyances with conversion.
> raidemulator: Update job fields to use Job type

- types/trigger.d.ts
`number` should be a current type of the parameter of `output.method()`, as we accept a number as replacement value in popup-text.
```diff
diff --git a/types/trigger.d.ts b/types/trigger.d.ts
index 73c0452a..649663f0 100644
--- a/types/trigger.d.ts
+++ b/types/trigger.d.ts
@@ -34,7 +34,7 @@ export type OutputStrings = { [outputKey: string]: LocaleText };
export type Output = {
responseOutputStrings: OutputStrings;
} & {
-  [key: string]: (params?: { [param: string]: string | undefined }) => string;
+  [key: string]: (params?: { [param: string]: string | number | undefined }) => string;
};
// The output of any non-response raidboss trigger function.
```
> method of `Output` should accpet `number` as param value

- resources/languages.ts
- ui/raidboss/emulator/data/Persistor.js
- ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
- ui/raidboss/raidemulator.html
- ui/raidboss/raidemulator.js
This has been possible for a while, since the switch to webpack for manifest files, I just never got around to making websocket optional.
The change to Persistor is due to an unintentional race condition with event ordering which was only apparent when there was an actual delay to websocket connection.
It might make sense additionally to check for OVERLAY_WS in the URL and skip the attempt to connect entirely?
> raidemulator: Make websocket connection optional

- ui/jobs/components/ast.js
- ui/jobs/components/blm.js
- ui/jobs/components/blu.js
- ui/jobs/components/brd.js
- ui/jobs/components/dnc.js
- ui/jobs/components/drg.js
- ui/jobs/components/drk.ts
- ui/jobs/components/gnb.ts
- ui/jobs/components/mch.js
- ui/jobs/components/mnk.js
- ui/jobs/components/nin.js
- ui/jobs/components/pld.js
- ui/jobs/components/rdm.js
- ui/jobs/components/sam.js
- ui/jobs/components/sch.js
- ui/jobs/components/smn.js
- ui/jobs/components/war.js
- ui/jobs/components/whm.js
In the past it seems it was necessary to set the duration of a
timerbox to 0 before setting the new duration. Most likely in order to
somehow reset the timerbox.
As setting a new duration will always result in calling the reset
function of a timerbox, this shouldn't be necessary anymore.
Removing the unnecessary calls will also prevent that the onReset
callbacks will be called more often than necessary.
> Jobs: Remove obsolete timerbox reset calls

- resources/util.ts
- types/event.d.ts
- ui/raidboss/data/00-misc/test.js
- ui/raidboss/emulator/data/CombatantState.ts
- ui/raidboss/popup-text.ts
This PR adds a `Util.watchCombatants` helper method to monitor combatants, as well as a test trigger showing the usage.
As discussed in #3099
> raidboss: Add helper to watch combatants

- ui/raidboss/timeline.ts
should close #3126, this was introduced in https://github.com/quisquous/cactbot/pull/3079
In old implement, all timeline trigger is executed as `timeline.timebase`, not the current time.
the make all `currentTime` become base time, not real current time.
could be tested with dummy:
```JS
const trigger = {
zoneId: ZoneId.MiddleLaNoscea,
timeline: [
`5 "test"`,
`10 "test"`,
`15 "test"`,
`20 "test"`,
`25 "test"`,
`30 "test"`,
`35 "test"`,
],
timelineTriggers: [
{
id: 'trim21 test refresh',
regex: /Death/,
run() {
// location.reload();
},
},
{
id: 'trim21 test',
regex: /test/,
preRun(data) {
data.times = data.times ?? 0;
data.times++;
},
suppressSeconds: 1,
beforeSeconds: 3,
infoText(data) {return `test message ${data.times}`;},
},
],
};
Options.Triggers.push(trigger);
```
> fix(timeline): execute timeline trigger with current time

- ui/jobs/constants.ts
This has been changed since 4.0. Maybe no one has tested it in leveling dungeon...
> Jobs: Fix Thunder2 ID out of date

- ui/raidboss/emulator/data/PopupTextAnalysis.ts
- ui/raidboss/raidemulator.js
This PR fixes an async issue caused by #3115 (basically, actual cactbot user options weren't being applied).
As well this PR fixes TTS audibly still happening during encounter analysis, which caused my ears to bleed when the entire e12s p2 fight TTS'd for all 8 players at the same time a few minutes ago.
> raidemulator: Fix async issue, fix tts still actually triggering tts during analysis

- ui/raidboss/emulator/data/PopupTextAnalysis.ts
This got broken during the typescript conversion, the previous behavior returned a promise from resolver but that was accidentally left out as part of the resolver refactoring that was done during the conversion.
> raidemulator: Fix promise not evaluating sync during analysis

- resources/user_config.ts
- ui/config/config.js
- ui/raidboss/raidboss_config.js
Requested by @MyTechnoHunter because this link is hard to find.
Also add support for html "inputs".  Maybe this is a case where we need
some other way to add more text at the beginning of a section, but we
can figure that out if we get more examples.
I left this as the raw link text to make it super clear that it was
a link to click on, and what that link was so you could find it outside
of ACT.
It would be really nice if OverlayPlugin supported something like the
`cactbotChooseDirectory` overlay handler for opening links in a browser
outside of ACT.  I would use it for this and view source if it existed.
> config: add link to coverage report

- ui/config/config.css
- ui/raidboss/raidboss_config.js
Sometimes I find a trigger not show long enough, but I turn to config only to find it `(default)`.
What is default value? I have to view source code to know.
So this feature enable user to know actual default value without source code.
> Feature(Raidboss): show default value instead of (default)

- ui/raidboss/data/05-shb/alliance/the_copied_factory.js
- ui/raidboss/data/05-shb/alliance/the_copied_factory.txt
- ui/raidboss/data/05-shb/dungeon/matoyas_relict.txt
Rolled back
~~I think this is better than~~
~~This.~~
And, I wonder why there's `(latest version)` written. That would be obviously latest version if you see on the web. Does this mean that this is later version than the release version? (The code is written before it's been released.)
> Chore: dungeon timelines improvement

- util/find_missing_translations.js
Something that comes up every once in a while is that it can be useful
to update the text of a trigger to be slightly better or slightly
different.  The translations for this trigger are not necessarily wrong
(and using what's there is better than English), but it's the kind of
thing where you want to mark it for somebody to come back and look at
later without deleting it.
This patch supports adding `// FIXME` commments on the lines of
translations you want to leave but mark as needing re-translation.
> util: support FIXME to mark improvable translations

- ui/raidboss/emulator/data/Encounter.ts
Fixes #3163, caused due to the getter not transferring properly through the websocket API
> raidemulator: Switch Encounter.initialTimestamp from getter to property

- .eslintrc.cjs
- resources/overlay_plugin_api.ts
- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/raidboss/emulator/data/Encounter.ts
- ui/raidboss/emulator/data/PopupTextAnalysis.ts
This is Trim21's #3102 with a workaround extended from:
https://stackoverflow.com/questions/59851672/eslint-indent-and-ignorenodes-trouble-getting-ast-selectors-to-work-correctl/59852368#59852368
> eslint: add indent rule for TypeScript

- README.md
Closes #3180
I took this opportunity to update the instructions for raidemulator in general.
> docs: Update raidemulator links and instructions in README

- resources/util.ts
As mentioned on #3186, update the return type of `Util.watchCombatants` to be `Promise<void>`
> util: Fix the return type of watchCombatant helper

- types/trigger.d.ts
- ui/raidboss/popup-text.ts
This PR fixes some issues with the typing of the `timeline` property on trigger sets, which I encountered while converting `00-misc/test.js` to typescript.
> raidboss: Fix typing of timeline property on trigger sets

- ui/raidboss/popup-text.ts
Fixes #3203
The old pre-typescript logic was:
```ts
if (matches.groups)
matches = matches.groups;
```
`matches` was then passed to triggers. When converting to typescript, after hard types were added for these, this exact logic was no longer possible and was erroneously dropped instead of reproduced.
> raidboss: Fix trigger regex with no matching groups not being passed as matches

- ui/raidboss/timeline.ts
```diff
diff --git a/ui/raidboss/timeline.ts b/ui/raidboss/timeline.ts
index 0746284360..809210bd7e 100644
--- a/ui/raidboss/timeline.ts
+++ b/ui/raidboss/timeline.ts
@@ -75,7 +75,7 @@ const activeText = {
};
export type TimelineReplacement = {
-  locale: string;
+  locale: Lang;
missingTranslations?: boolean;
replaceSync?: { [regexString: string]: string };
replaceText?: { [timelineText: string]: string };
```
> set `locale` of TimelineReplacement to `Lang`

- types/trigger.d.ts
~Closes #3188~
~This is an alternative to #3190~
This PR updates the types of the `ResponseOutput` properties to `TriggerField` to match the correct structure, and updates the `extends` clause of the various typings in trigger.d.ts to be more specific.
> util: Update types of trigger.d.ts

- types/trigger.d.ts
This PR changes TriggerSet to require initData if the data type passed in contains non-optional properties that are not part of the RaidbossData type.
Example:
> raidboss: Require initData if data type contains non-optional properties

- ui/raidboss/emulator/EmulatorCommon.ts
- ui/raidboss/emulator/ui/EmulatedPartyInfo.ts
- ui/raidboss/emulator/ui/EncounterTab.ts
- ui/raidboss/emulator/ui/ProgressBar.ts
This PR is a cleanup PR after the last three typescript conversions were merged, to de-duplicate code.
After this PR lands, I'll be converting the main `raidemulator.js` file, then I'll just be waiting on #3173 for the last typescript conversion for raidemulator.
> raidemulator: Move query and clone helper methods to EmulatorCommon to de-duplicate code

- ui/raidboss/popup-text.ts
Unfortunately, it appears that `manifest.d.ts` is not doing anything
and the `RaidbossFileData` type is pretty much bogus.  This PR
doesn't do anything to handle that, just pointing it out.
> raidboss: remove type assertion from popuptext

- ui/raidboss/emulator/data/NetworkLogConverter.ts
Now that the combatant state tracking keys off of the line event type and not just blindly updates states based on if a line has `id/targetId`, we don't need the sort anymore.
> raidemulator: Remove line sorting on convert

- ui/raidboss/emulator/data/Persistor.ts
- ui/raidboss/raidemulator.ts
This PR fixes #3231
This also fixes a pointless double `Encounter.initialize` call when upgrading.
> raidemulator: Fix dexie readonly error, fix double initialize

- ui/raidboss/data/04-sb/dungeon/doma_castle.js
- ui/raidboss/data/04-sb/dungeon/doma_castle.ts
- ui/raidboss/data/04-sb/dungeon/doma_castle.txt
- ui/raidboss/data/raidboss_manifest.txt
Couple things I'm not happy with on Grynewaht:
- The exact ordering on the simultaneous Delay-Action Charge and Clean Cut varies from pull to pull, so I just combined them in the timeline to avoid any missed syncs. The name is a little long, though, and `Cut` gets cut off with default timeline bar width. Any preference on abbreviation here, or even just leaving it as is?
- `make_timeline.py` inserted a fair number of `--sync--` entries for ID 20B0, during testing I couldn't see anything visible corresponding to this, but it was consistent across pulls. Unsure if these should be removed or not.
> raidboss: add Doma Castle timeline

- docs/OopsyraidsyGuide.md
- types/oopsy.d.ts
- ui/oopsyraidsy/data/00-misc/test.js
- ui/oopsyraidsy/data/04-sb/raid/o4s.js
- ui/oopsyraidsy/data/05-shb/eureka/delubrum_reginae_savage.js
- ui/oopsyraidsy/mistake_collector.ts
This is the same as `text` but with no `blame` at this point, so just
remove this extra option.
This is (also) a breaking oopsy user trigger change.  I'm trying to
bunch them all together into a single release and make all the
changes at once.
> oopsy: remove fullText

- ui/raidboss/data/04-sb/alliance/ridorana_lighthouse.ts
While hilarious, this does result in the TTS saying "move to pose-tive" which is confusing.
> Fix spelling error in Yiazmat fight

- resources/timerbar.ts
- resources/timerbox.ts
- resources/timericon.ts
- resources/widget_list.ts
- ui/jobs/components/drk.ts
- ui/jobs/components/gnb.ts
- ui/jobs/components/mnk.js
- ui/jobs/jobs.js
- ui/jobs/utils.ts
- ui/raidboss/timeline.ts
- ui/test/timerbar_test.ts
It is really weird to always `.toString()` before assigning to those properties that are actually numbers inside the component,
so it is better to put the conversion inside the component.
And I change the assigning style of all components to make them consistent.
> Refactor(jobs): consist custom element property type

- .github/workflows/release.yml
Created a fake release on my fork: https://github.com/panicstevenson/cactbot/releases/tag/v0.1.302
Looks the same as the recent release from what I can tell.
Fixes #3308
> ci: Use MSBuild for Plugin Release Artifacts

- ui/jobs/bar.d.ts
- ui/jobs/components/mnk.js
- ui/jobs/jobs.js
- ui/jobs/utils.ts
After patch 5.4 update, MNK's Greased Lightning is not
binding on GCD/Combo anymore.
Nowadays it is traits which only be affected by player's current level,
we can directly compute the corresponding `stacks`, so
move the computing code into `calcGCDFromStat` function.
------
By the way, @quisquous should/can I remove the related code from `FFXIVProcessIntl.cs`, etc?
For example, like this?
```diff
-   [StructLayout(LayoutKind.Explicit)]
-   public struct PugilistJobMemory {
-     [FieldOffset(0x00)]
-     public ushort lightningMilliseconds;
-
-     [FieldOffset(0x02)]
-     public byte lightningStacks;
-   };
-
[StructLayout(LayoutKind.Explicit)]
public struct MonkJobMemory {
-     [FieldOffset(0x00)]
-     public ushort lightningMilliseconds;
- 
-     [FieldOffset(0x02)]
-     public …
```
> refactor(jobs): direct compute MNK lightning stack

- ui/jobs/components/war.js
WAR in ShB don't need to track Storm's Eye dynamically,
not only because the duration of Storm's Eye can be 60s nowadays,
but there are also many skills would extend the duration of Storm's Eye.
So we can just set the threshold to `GCD * 3 + 1`,
which is also consistent with other jobs.
> jobs: remove dynamic threshold of storm's eye

- ui/raidboss/data/03-hw/raid/a8n.ts
- ui/raidboss/data/03-hw/raid/a8n.txt
(This will conflict with and possibly replace #3303.)
As I noted on Valarnin's pull request, this is one of those things I kept meaning to do and kept forgetting. I wasn't able to get a group for this to test, but I did run it through solo, and it didn't *feel* annoying. Short Needle and Hydrothermal Missile correctly called only once for each position on the timeline.
I went ahead and commented out the Hydrothermal syncs that were within 4 seconds of each other. Technically they should have been okay, but I figured it was best to be safe.
No idea what's going on with the end-of-file newline. I would have said it was a Unix-vs-Windows thing, but I'm the only person who's touched this file. Regardless, it shouldn't be a serious issue.
> Raidboss: Reduce annoyance in A8n

- ui/oopsyraidsy/data/04-sb/dungeon/drowned_city_of_skalla.ts
- ui/oopsyraidsy/data/oopsy_manifest.txt
- ui/raidboss/data/04-sb/dungeon/drowned_city_of_skalla.ts
- ui/raidboss/data/04-sb/dungeon/drowned_city_of_skalla.txt
- ui/raidboss/data/raidboss_manifest.txt
Nothing particularly interesting on this one. We could probably eliminate the last block on boss 2, and instead do a forward and back sync against timestamp 1200, but I figured explicit was better to start with.
It's possible we could do a better set of triggers to account for interactions between the boss 3 head markers, but I don't think it's really worth the effort. "You have X" is standard enough anyway.
> Raidboss/Oopsy: Add Drowned City of  Skalla dungeon package

- ui/raidboss/data/03-hw/alliance/dun_scaith.ts
It looks like this was marked as needing work on [June 20](https://github.com/quisquous/cactbot/commit/163304c63e16a3bbafd9818b7fce12b448235540) last year, and I missed that flag's existence when I updated the timeline last [August](https://github.com/quisquous/cactbot/pull/1650). Sorry about that!
> Raidboss: Remove "timeline needs work" flag from Dun Scaith
