quisquous/cactbot

- package-lock.json
- package.json
- tsconfig.base.json
- webpack/webpack.config.ts
- Turn on babel cache
It is helpful to enable babel cache when in rebuilding (e.g. running webpack-dev-server), which would significantly decrease the building time.
- Use babel for TypeScript building
Although `ts-loader` (`tsc` inside) and `babel-loader` (`babel` inside) would basically do the same thing in TypeScript transform, `babel-loader` removes type notations only, and doesn't do the type-checking things, so it would be faster than `ts-loader` (even with `transpileOnly` flag) in most cases. Additionally, we now need `babel-loader` to ensure code available always in Chrome v75 of current CEF, so why not combine them in one loader?
- How is TypeScript type checking now
Nowadays we are using `fork-ts-checker-webpack-plugin` for type checking, which runs `tsc` in a separated process …
> Build: turn on babel cache & use babel for TS building

- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
Level is not an number, its passed as hex instead, confirmed it in game
> Network Event: Added combatant - level fix

- ui/raidboss/data/05-shb/trial/wol-ex.ts
- ui/raidboss/data/05-shb/trial/wol-ex.txt
BLM/WHM is Specter Of Light before to the limit, and DRK/BRD is To The
Limit before Specter Of Light.  Add additional timeline syncs (but leave
the previous as a catch-all) and fix up triggers to reflect this.
Additionally, every limit break can be used in both phases, so fix up
timeline entries for this.
> raidboss: earlier callouts for wolex summon phases

- .github/scripts/lint-pr-title.cjs
This message was really tall, so make it a lot shorter.
Also, fix a bug where the username wasn't being passed to the
message function.
> ci: shorten PR title lint message

- .github/scripts/lint-pr-title.cjs
Various online docs say github will wrap at 72 characters, but
looking at PR 3228, it seems like it will wrap after 69.
Given that there are 8 characters from PR numbers (arguably 9
if we ever wrap to 5 digits), then 60 seems like a round number
to restrict to.
> ci: add length restriction of 60 to PR titles

- .github/workflows/lint-pr-title.yaml
Noticed in #3356 that the bot didn't run the workflow again when I successfully changed the title.
> ci: trigger lint-pr-title when pr edited/reopened

- ui/raidboss/data/04-sb/raid/o10n.txt
What it says on the tin. I have been annoyed by the jump before Exaflare on multiple jobs, but *no more*.
(I also added a count and duration to Protostar since that's moderately helpful to know. Happy to split that out if needed, but I figured a single-line change was small enough to roll up here. Maybe I should add numbers to the Exaflares while I'm at it?)
> raidboss: Add targetability lines to O10n

- resources/netregexes.ts
- types/net_fields.d.ts
I noticed when writing the example UWU trigger in #3338 that when support for the position/heading fields for startsUsing were added in #3355, the underlying type backing NetRegexes weren't updated.
This PR adds the fields to the type, and also adds proper typing of the `fields` parameter for `parseHelper` so that if new field properties are added in the future, they'll need to be added to the underlying type.
> util: Add type checking for NetRegexes parseHelper fields

- .eslintrc.cjs
As we still fail lint if there are warnings, this just makes
VSCode differentiate these a little bit better.
> lint: downgrade some errors to warnings

- resources/content_list.ts
- types/oopsy.d.ts
- types/trigger.d.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/oopsy_options.ts
It's awkward to have ZoneId (the map) and ZoneId (the type) have
the same name.  Some of the issue is that maybe ZoneId (the map,
or all maps really) be capitalized and so they conflict with type
names, but that's a larger issue (whoops).
> resources: fix ZoneId name collision

- resources/netlog_defs.ts
- resources/netregexes.ts
- types/net_fields.d.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x00.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x02.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x0C.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x19.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1B.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x22.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x23.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
As discussed in #3371, this PR refactors `NetRegexes` to use `logDefinitions` entries, and uses a `defaultParams` helper to initiate the default params automatically.
I wasn't able to get the helper to work without the typecasting at some point, I tried 6 different variations but no matter how I arranged and typed things it always required a `... as unknown as ...` typecast at one location or another.
Additionally, I only renamed the `logDefinitions` entries that were currently in use via `NetFields`. Probably the rest should be renamed to match, or the renaming should go in the other direction, but if it were in the other direction it would require updating 3021 lines across 168 files in triggers, plus a few spots here and there that are using current `NetFields` names
> resources: Refactor netregexes to use netlog_defs

- .eslintrc.cjs
- util/gen_coverage_report.js
Coverage report went from 2m to 20m when adding dprint.
An initial attempt to just add an "eslint-disable dprint/dprint"
line to the coverage report made it take 60m to complete (!!!).
For simplicity, just disable lint on this generated file.
> util: disable lint on coverage report

- README.md
- docs/ko-KR/README.md
- docs/zh-CN/README.md
All of the triggers have been updated to not use this setting
any more, and so the recommendation to use it can be removed.
> docs: update README to not mention HP option

- docs/LogGuide.md
- util/gen_log_guide.ts
Remove the "future network data science" section, as this feels like
the wrong place for that information.
> docs: clean up text, outdated hex type mentions

- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/mistake_collector.ts
- ui/oopsyraidsy/mistake_observer.ts
- ui/oopsyraidsy/oopsy_common.ts
- ui/oopsyraidsy/oopsy_live_list.ts
- ui/oopsyraidsy/oopsy_summary.css
- ui/oopsyraidsy/oopsy_summary.html
- ui/oopsyraidsy/oopsy_summary_list.ts
- ui/oopsyraidsy/oopsyraidsy.ts
This is a bunch of refactoring commits with some functional changes at the end.  The end result is that the summary page gets a table that looks something like this:
> oopsy: Add summary table

- ui/oopsyraidsy/oopsy_common.css
- ui/oopsyraidsy/oopsy_summary.html
- ui/oopsyraidsy/oopsyraidsy.html
I wanted to try to get back to the original flavor of (colored) win7 emoji with oopsy icons.  I find it very hard to parse the win10 colored emoji when I glance over sometimes.
Original win7 icons:
Current win10 icons: (death, fail, warn, pull, potion, wipe, good, damage, heal)
Proposed fontawesome icons:
Feel free to counterpropose from https://fontawesome.com/v5.15/icons?d=gallery&p=9&m=free or with some other license compatible svg icon.
> oopsy: change icons to fontawesome

- docs/LogGuide.md
- ui/raidboss/emulator/EmulatorCommon.ts
- ui/raidboss/emulator/data/Encounter.ts
- ui/raidboss/emulator/data/PersistorEncounter.ts
- ui/raidboss/emulator/data/PopupTextAnalysis.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x18.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x19.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1E.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts
- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.ts
- ui/raidboss/emulator/ui/EncounterTab.ts
- util/gen_log_guide.ts
Fixes #3389
I also included the change to remove `properCaseConvertedLine` from `LineEvent` and subclasses, since the non-proper-case version is unused.
Both changes require a bump to encounter version number, so I figured it would be best to include both in the same PR to avoid people having to re-parse encounters twice depending on their timing. As such, I made sure to make these changes in their own commits to make it easier to determine what code change corresponds to which functional change.
> raidemulator/docs: Fix issues with timestamp timezones

- ui/raidboss/popup-text.ts
This will allow a config UI workaround where you just input
a space (or spaces) which will "blank" the entry, vs clearing
it as the default.  Doing this will then disable that particular
entry.
> raidboss: ignore texts with empty spaces

- resources/translations.ts
The brackets around the player name in jp are full-width, same with cn, for example:
```log
00|2021-09-17T17:34:13.0000000+08:00|00b9||戦闘開始まで10秒！ （Maiko Tan）
```
> jobs: fix japanese countdown regex

- ui/oopsyraidsy/damage_tracker.ts
- change massive if-else to switch-case
- stop using hard-coded log type, use logDefinition's instead
- change target name extraction in `WasDefeated` to using logDefinition's field
> oopsy: add logDefinition refactoring

- resources/party.ts
- resources/player_override.ts
- resources/user_config.ts
- resources/util.ts
- test/unittests/util_test.js
- ui/dps/dps_common.js
- ui/jobs/jobs.js
- ui/jobs/utils.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/02-arr/raid/t11.ts
- ui/raidboss/data/02-arr/raid/t5.ts
- ui/raidboss/data/02-arr/raid/t6.ts
- ui/raidboss/data/02-arr/raid/t7.ts
- ui/raidboss/data/02-arr/raid/t9.ts
- ui/raidboss/data/02-arr/trial/levi-ex.ts
- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts
- ui/raidboss/data/05-shb/raid/e10s.ts
- ui/raidboss/data/05-shb/trial/levi-un.ts
- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x03.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
- ui/raidboss/emulator/ui/EmulatedPartyInfo.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.js
as named export
There are two export approaches in an es module:
1. Named export
2. Default export
Currently `resources/util.ts` use the 2. default export,
although the statement `import Util from 'path/to/util.ts'` is clean
and easy to recognize,
to export an object makes webpack cannot `tree-shake` it correctly.
Therefore, I think we should change it to named export style,
perhaps also the `resources/condition.ts` file
BREAKING CHANGES:
`import Util from 'path/to/resources/util'` is not available anymore,
should change to `import * as Util from 'path/to/resources/util'`,
or `import { xxx } from 'path/to/resources/util'`
> resources: change export type of resources/util.ts as named

- tsconfig.triggers.json
This was broken in #3315 when babel was added.  Even though babel is
used with webpack, babel is not used for the triggers branch which is
referenced directly by users who are writing their own triggers.
> build: fix triggers branch target back to ES2019

- plugin/CactbotEventSource/FateWatcher.cs
The recent KR Opcode PR (https://github.com/quisquous/cactbot/commit/287b70ec4aa516260fd5c2dc37044660ba572d34) changed the intl variable by mistake. This PR just reverts that and changes the KR variable as intended.
> plugin: Fix CE Opcode region mix-up

- ui/eureka/eureka.ts
The current implementation only allows lines that have text both before and after the map link to be shown on the map, match[1] and match[4] should be allowed to be empty.
Examples that currently don't show flags: 
```
00:000b:Player NameServer:Eureka Pagos ( 10.3  , 25.4 ) rez plz
00:000b:Player NameServer:pop Eureka Pagos ( 14.5  , 18.5 )
```
> eureka: Fix flagRegex ignoring certain lines

- ui/oopsyraidsy/damage_tracker.ts
This matches the (alone) suffix for soloWarn/soloFail
and should help differentiate whether damage should
not be taken at all, or just not with another person.
> oopsy: add `(share)` suffix on shareWarn/shareFail

- docs/LogGuide.md
- util/gen_log_guide.ts
And run the generate script once.
But there are not only one but two Chinese versions of documents, maybe we should add a key like `tw` to identify `zh-TW` version ?
> docs: LogGuide.md add header localisation

- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts
During the Xun-Zi/Meng-Zi robot fight of the Tower at Paradigm's Rift,
the two robots use some line aoe attacks. These attacks, "Deploy
Armaments" can either be a single big line down the middle of the arena,
or two lines down the sides of the arena.
Add support to trigger an alert on where the safe area is for these
attacks. Use the heading of the skills to determine whether the middle
line attack should be avoided by going north/south or east/west.
TODO:
> raidboss: add triggers for Meng-Zi/Xun-Zi Deploy Armaments

- types/data.d.ts
in line 30 there is a same declaration already
Besides, there is no `scope` for a type only change.
> util: remove duplicate declaration

- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts
Hansel and Gretel use "Tandem Assault: Bloody Sweep" as a combo move
which will either sweep the outsides and mainly the south half of the
arena, or sweep the insides hitting mainly the north half of the arena.
Players need to move south or north depending on the position of Hansel
and Gretel. Sometimes, the two bosses will use "Transference" and switch
places.
Add a trigger which detects the relevant IDs and issues an alert on
whether ot move south or north. We can be clever by using a few facts:
* Hansel is left handed, and Gretel is right handed
* The ID indicates which position Hansel or Gretel will be at start
* The cast time can determine whether or not they switch places
Using this information we can use a single strigger which determines the
side of the arena which is safe. …
> raidboss: add trigger for Bloody Sweep

- ui/oopsyraidsy/death_report.ts
- ui/oopsyraidsy/oopsy_live.css
- ui/oopsyraidsy/oopsy_live_list.ts
- ui/oopsyraidsy/oopsy_summary.css
- ui/oopsyraidsy/oopsy_summary_list.ts
- ui/oopsyraidsy/oopsyraidsy.html
This shows the current hp in the death report on each line prior
to taking damage.  Because current hp is polled from memory, this
value can be incorrect if the player takes a bunch of damage in
a row and so duplicate hp values try to estimate the correct value
by applying damage amounts.  This seems to be ~ok in practice,
but is a bit sketchy.
> oopsy: add current hp to death reports

- resources/zone_info.ts
- util/logtools/encounter_tools.ts
This is the first in a series of changes to our timeline generation/testing ecosystem that will (or at least we hope) unify those utilities with the rest of the project. Rather than using naively re-implemented Python parsing for log lines, we can just drop the existing Typescript definitions in and use those to implement `make/test_timeline`.
I'm still not completely sure what I'm doing with Typescript here, but I did at least manage to clear the lint errors. I was mostly trying to convert the existing `encounter_tools.js` prototype for this particular PR. This isn't in any way intended to be final or polished, simply at a point where I've changed what I can and now need some input for what might need further changes and additions before an actual release.
I'm a little annoyed that we …
> util: Typescriptify encounter_tools

- ui/raidboss/data/02-arr/alliance/the_world_of_darkness.ts
- ui/raidboss/data/raidboss_manifest.txt
Angra Mainyu is the first boss of The World of Darkness alliance raid.
This boss has a few instant-death mechanics, including some basic
mechanics that are very easy to add triggers for.
Add a trigger for the "Mortal Gaze" mechanic. When this is cast, players
should look away. If they fail to look away, they acquire the Doom
debuff and will die in 10 seconds unless they reach a cleansing circle.
Add an alert for the look away, and an alarm for when doom is acquired.
Add a trigger for the "Double Vision" attack. This attack is cast
periodically, and damages players based on their debuff. The whole arena
lights up half red and half white. If the player is hit by the red area
they gain Ireful, and if they are hit by the white area they gain
Sullen. Repeated hits of the same color do …
> raidboss: add basic triggers for Angra Mainyu

- ui/oopsyraidsy/oopsy_summary.css
margin doesn't work well with grid max-content, so instead use
column-gap to add margins around text so that things don't get
squished.
> oopsy: adjust summary death report css

- ui/oopsyraidsy/effect_tracker.ts
This was missing the logic to actually check that it was solo or
shared and was previously marking everything.
This is a fix for #3622.
> oopsy: fixed solo/shared mistakes always showing in report

- util/process_triggers_folder.ts
See:
https://github.com/quisquous/cactbot/runs/4196260990?check_suite_focus=true
This caused #3613 to appear as if it was passing, when it did not.
> build: add failure exit code for tsc in process-triggers

- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts
Found in #3613 that cause `process-triggers` failed.
EDIT:
Looks like this configuration
https://github.com/quisquous/cactbot/blob/e617b03118893f68b875f94968e819c13b06696e/tsconfig.json#L18
that cause this error not report by `npm run tsc-no-emit`,
If I comment this line and run `tsc`, errors in this PR would be reported normally,
But from [the description of this parameter in typescript official website](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess), I didn't found any related information that cause the problem.
> raidboss: fix TEA type error

- util/logtools/encounter_tools.ts
- util/logtools/split_log.js
Sorry this is so extensive! It turns out I didn't do anywhere near enough investigation on how the JS version of the utility actually *worked* before converting it. This restores it to (presumably) exact parity with the pre-Typescript version. Comparing output from this against the JS version, it's exactly the same for all More Than One logs I tried.
One thing that I think we should do in future is extract the various different operation points of `process()` out into helper functions. It's *really* long, and I found myself constantly scrolling up and down to verify what had or hadn't yet happened.
Perhaps the most significant change I made here was mostly eliminating the distinction between the data properties of `Finder` vs `Collector`. Thus, all functions, overridden or not, will refer …
> util: Fix encounter_tools after Typescriptification

- ui/raidboss/data/02-arr/alliance/the_world_of_darkness.ts
The trigger for Angra Mainyu's doom effect accidentally was set to
trigger when the player *lost* the doom effect. This should have been
a gainsEffect trigger. This way, the alert happens and warns the player
to properly cleanse the debuff. Fix this.
Fixes: 09d04fdb3d47 ("raidboss: add basic triggers for Angra Mainyu (#3614)")
Signed-off-by: Jacob Keller <jacob.keller@gmail.com>
> raidboss: trigger on gain doom, not losing doom

- resources/user_config.ts
- types/oopsy.d.ts
- types/trigger.d.ts
- ui/config/config.ts
- ui/oopsyraidsy/oopsyraidsy_config.ts
- ui/raidboss/raidboss_config.ts
Logic changes:
* oopsy config stores triggers as object to match raidboss
* The "Config" types of triggers and triggersets have all of the
optional annotated properties for building the config UI
* trigger.output annotations now trigger.configOutput to avoid collision
> config: convert raidboss_config to ts

- plugin/CactbotEventSource/FateWatcher.cs
This is the cactbot equivalent of:
https://github.com/ngld/OverlayPlugin/pull/225
Without this, if you have a disabled FFXIV_ACT_Plugin.dll listed
before an enabled FFXIV_ACT_Plugin.dll, then it will have a null
pluginObj.  This causes no subscription to exist and fates to
not show up.
> plugin: fix plugin search finding disabled plugins

- webpack/webpack.config.ts
This fixes constant errors on the config page when upgrading to CEF M95:
[11/20/2021 11:14:48 AM] Info: OverlayControl: Invalid Host/Origin header
[11/20/2021 11:14:48 AM] Info: OverlayControl: [WDS] Disconnected!
> build: set disableHostCheck in webpack config

- util/coinach.ts
The original approach that calls
`JSON.stringify(data, Object.keys(data).sort(), 2)` works well
in some situation, but it would
only sort the first dimention of the object,
and the worst thing is that it would drop nested object.
For example, call the function above with a object
like `{ foo: { bar: 1 } }`, the actual output would be
'{"foo":{}}' that lost nested object.
So the ideal way is to recursively sort keys before passing
to `JSON.stringify` function.
> util: coinach add helper function that sorts keys

- types/event.d.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/test/test.ts
The comment says it is a decimal in string, but in my result, it outputs a number. Is it forgotten to change the type after changing the plugin side?
output
```js
{
"id": 270203476, // <- number
"level": 76,
"name": "***",
"job": "SAM",
"currentHP": 63929,
"maxHP": 63929,
"currentMP": 10000,
"maxMP": 10000,
"currentTP": 0,
"maxTP": 1000,
"currentGP": 0,
"maxGP": 0,
"currentCP": 0,
"maxCP": 0,
"debugJob": " 00 00 00 00 00 00 00 00",
"currentShield": 0,
"pos": {
"x": -548.21405,
"y": -740.6234,
"z": 56
},
"rotation": -1.58878767,
"bait": 0,
"jobDetail": {
"kenki": 0,
"meditationStacks": 0,
"setsu": false,
"getsu": false,
"ka": false
}
}
```
> util: fix type of id in PlayerChangedEvent

- test/helper/test_timeline.js
- ui/raidboss/common_replacement.ts
Per <https://github.com/quisquous/cactbot/pull/3673#issuecomment-980494383>, this should permit passing tests for all timeline seal/unseal entries that use the new log line format. Note the error message doesn't include the old format, since we shouldn't be using it for any new work.
> test: Temporarily permit old/new seal formats in timelines

- ui/raidboss/data/02-arr/raid/t10.txt
- ui/raidboss/data/02-arr/raid/t11.txt
- ui/raidboss/data/02-arr/raid/t12.txt
- ui/raidboss/data/02-arr/raid/t13.txt
- ui/raidboss/data/02-arr/raid/t4.txt
- ui/raidboss/data/02-arr/raid/t5.txt
- ui/raidboss/data/02-arr/raid/t6.txt
- ui/raidboss/data/02-arr/raid/t7.txt
- ui/raidboss/data/02-arr/raid/t8.txt
- ui/raidboss/data/02-arr/raid/t9.txt
- ui/raidboss/data/02-arr/trial/cape_westwind.txt
- ui/raidboss/data/02-arr/trial/ifrit-nm.txt
- ui/raidboss/data/02-arr/trial/levi-ex.txt
- ui/raidboss/data/02-arr/trial/shiva-ex.txt
- ui/raidboss/data/02-arr/trial/shiva-hm.txt
- ui/raidboss/data/02-arr/trial/titan-ex.txt
- ui/raidboss/data/02-arr/trial/titan-hm.txt
- ui/raidboss/data/02-arr/trial/titan-nm.txt
Overall I'm fairly happy with this. I'll need to update the script to strip the trailing dot from `addedCombatant` lines, but apart from that it looks relatively clean on a 15-second inspection.
The following errors were encountered and will be fixed manually: 
```
t7: [
'300.0 "--sync--" sync /:Melusine HP at 79%/ window 300,0',
'800.0 "--sync--" sync /:Melusine HP at 59%/ window 800,0'
],
t9: [
'503.3 "Golem Meteors" sync /1B:........:[^:]*:....:....:0007:/ duration 11
window 505,0',
'582.3 "Meteor 1/6" duration 7 sync /1B:........:[^:]*:....:....:000[9A]:/ w
indow 83,0',
'598.3 "Golem Meteors" sync /1B:........:[^:]*:....:....:0007:/ duration 11
window 80,80'
],
cape_westwind: [
'199.0 "--sync--" sync /00:0044:[^:]*:My shields are impregnable/ window 200
,0',
'584.3 "--sync--" sync …
```
> raidboss: Automated alpha conversion of ARR timelines

- resources/resourcebar.ts
- resources/timerbar.ts
- resources/timerbox.ts
- resources/timericon.ts
- resources/widget_list.ts
the function checks parameters with `if (param)`
which didn't work if we assign it as a falsy value
such as `0` or `''`(empty strings)
So change it as `if (typeof param !== 'undefined' && param !== null)`
would fix this.
> jobs: fix create func didn't receive falsy value

- ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt
- ui/raidboss/data/04-sb/eureka/eureka_hydatos.txt
- ui/raidboss/data/05-shb/eureka/bozjan_southern_front.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
- ui/raidboss/data/05-shb/eureka/zadnor.txt
No issues fixing these up. I didn't touch the `21` lines in the Shadowbringers Eureka files since they looked to be correctly formatted already.
I *think* the line ID for "Enemy Gains Buff" is`2AAE`, but I figured it was safer to just make the Gubal Hard lines universal, since that's basically the only place this happens.
> raidboss: remaining alpha timeline conversions

- ui/oopsyraidsy/player_state_tracker.ts
Summoner pets get damage buffs, but have a `0000` sourceId
and a blank `source` field.  Ignore gaining and losing these
effects.
26|2021-11-30T12:08:55.3420000-08:00|511|Embolden|0.00|0000||4001AA2E|Demi-Phoenix|04|119916||36d56cff42be79000154f3eb35b85c64
> oopsy: ignore buffs on pets

- util/encounter_tools.py
- util/make_timeline.py
- util/test_timeline.py
It's all bad, but it seemed to work on the alpha logs I was given. I'm not particularly attached to anything I've implemented here, this was mostly an attempt to get *something* in place for later improvement.
For consistency with converted old logs, I figured it made most sense to format `make_timeline` output the same way, as `1[56]`.
> util: Alpha Python timeline utility updates

- util/make_timeline.py
The alpha plugin no longer proper cases everything, and so
these are lowercase.  Leaving support for both version so that
old log files can be used in make_timeline.
This is a followup to #3697.
> util: support lowercase Unknown_ and Attack

- util/make_timeline.py
The alpha plugin no longer proper cases everything, and so
these are lowercase.  Leaving support for both version so that
old log files can be used in make_timeline.
This is a followup to #3697.
This is a relanding of #3712 on main, as I forgot to pull the
alpha_plugin branch before rebasing.
> util: support lowercase Unknown_ and Attack (#3712)

- eslint/cactbot-response-default-severities.js
Update fixer node argument range to use the first argument's first range
value and the last argument's last range value instead of using start
and end as they don't seem to be returned as part of the node argument
object anymore. Loc is available, but that doesn't give the text
position in characters and instead returns an object of `{ line, col }`.
Fixes #3754.
> lint: Update Fixer Node Argument Range

- ui/eureka/zone_hydatos.ts
Really minor change, but upon testing the bunny fate respawn time is closer to 10:30 than 8min.
The other zones are *probably* the same, but I haven't tested it enough to be confident.
> eureka: update Hydatos bunny respawn time

- ui/jobs/components/war.ts
it's not consistent at all, the actual displayed timer is usually off the ingame buff timer. included as much info as i could about how long it actually lasts but at least it displays now and is mostly accurate
> jobs: WAR surging tempest timer fix

- ui/jobs/bars.ts
- ui/jobs/components/index.ts
There are several fixes here:
* gp alarm should only beep once after it has gone below the threshold
* if the threshold is zero, don't beep at all
* if we go above the threshold (with a potion), don't beep
(this may have been an issue before?)
This is a fix for a bug introduced in #3682.
> jobs: fix gp alarm from constantly beeping

- ui/raidboss/emulator/data/CombatantTracker.ts
If the last event triggered for a given combatant is an 04 line (e.g. a clear) it can cause issues with the pre-flight checks for the getCombatants handler. Found while testing triggers for Endsinger.
> raidemulator: Fix bug with last combatant state tracking

- ui/jobs/constants.ts
Fixes #3788
https://github.com/quisquous/cactbot/blob/54303910154b6ae5847780f1dbac616ce629a381/ui/jobs/utils.ts#L142
[0,0] will cause a 0 division error, so make it 9999 to make unknown gcd about 2.5
382 at lv81 and 400 at lv90 are confirmed, others are assumed.
> jobs: Temporarily fake kLevelMod data to avoid error

- ui/jobs/player.ts
Because the `PlayerStat` log line is always emitted before
the `onPlayerChangedEvent` event, and we have job components
that relies on the stat data when initializing, so we need to
manually emit the stat data here.
> jobs: fix stats not emit when component init

- ui/eureka/eureka.css
- ui/eureka/eureka.ts
A friend pointed out to me that the bozja maps didn't lock the aspect ratio, so could be stretched out depending on the overlay window. Fixing that lead me to realise the weather info panel had been hidden all this time.. Oops!
This PR just adds some aspect ratio correction, adjusts the weather info box to fit neatly and adds the missing weathers for Bozja.
> eureka: Bozja map fixes

- plugin/CactbotEventSource/FFXIVProcess.cs
- plugin/CactbotEventSource/JSEvents.cs
Fixes #3783 where the fisher bait was being read incorrectly as a short when it should be a uint.
> plugin: fix fisher bait is a uint

- plugin/CactbotEventSource/FateWatcher.cs
This got added in fd971b4acc5f2eb6559b7be737f22bc836202247 and I missed it during the merge with 4da4191ce87d2a8c89f3c8b50f26d4beaf4591f5.
> plugin: remove stray variable in fatewatcher

- ui/jobs/bars.ts
- ui/jobs/jobs.css
Per https://github.com/quisquous/cactbot/pull/1856#issuecomment-706589184
So we can abandon to use so many css selectors and calculate the distances.
Add a new div as a container for proc boxes, so now the construction is:
As my test when using caster and healer, it should look the same as before:
BLM:
> jobs: refactor procs boxes in flex layout

- ui/jobs/player.ts
This bug would break something like BuffTracker that
relies on the event, so buffs would not correctly trigger on the event
when the player gains some effect but when the others gains effect
from the player.
This patch fixed this. But I am a bit worrying whether the name is
clear enough for what is it used for.
> jobs: fix effect/gain/you dont trigger self gains buffs

- ui/jobs/components/blm.ts
- ui/jobs/components/mch.ts
- ui/jobs/components/sam.ts
- ui/jobs/components/sge.ts
- ui/jobs/components/whm.ts
- ui/jobs/jobs.css
Consist the structure of stacks to something like `div#blm-stacks.stacks > div#blm-stacks-hearts > div` even there is only one type of stacks like MCH or SAM does:
------
Also, I found that many combo timer bar is slightly shorter than others, so change its width to 202px, too.
(Samurai as the example)
Before:
After:
------
What @Echoring said in #1856 is caused by the `margin-right: 2px;` CSS property, so I add a `:last-child` pseudo-selector to clear the margin, then all elements can use the same CSS.
So Echoring can you test other jobs to make sure that behaves properly? You can download this ZIP package and replace your files in `cactbot/ui/jobs/`.
[cactbot-jobs.zip](https://github.com/quisquous/cactbot/files/7701853/cactbot-jobs.zip)
> jobs: refactor stacks boxes in flex layout

- ui/jobs/bars.ts
- ui/jobs/jobs.css
- ui/jobs/jobs_config.ts
- ui/jobs/jobs_options.ts
This is for someone that they dont like to "wrap" the target bar
in the jobs module UI, but just want to monitor their buffs or something.
i18n: add cn/ja translations for new option
------
BLM Preview:
> jobs: add compact view option

- ui/jobs/components/drk.ts
Delirium have been changed from 10s to 3 stacks with 15s, no longer need active time trace.
Cooldown also changed to 60s, same as blood Weapon.
Maybe this can be replaced by Salted Earth later.
> jobs: DRK: update Delirium trace

- ui/jobs/components/ast.ts
Draw is chargeable now.
In EW you can no longer ensure that you can gain 3 different seals due to change of redraw and minor arcana.
So change this box to show seal amount instead of kinds, any 3 seals will make this box green.
> jobs: AST: Draw and Sealbox change

- plugin/CactbotEventSource/CactbotEventSource.cs
Apparently this was confusing to some users who thought the
"Cactbot" tab in OverlayPlugin meant that they had cactbot already
and didn't need to add an overlay.
cc @MyTechnoHunter
> plugin: change tab text to Cactbot Config

- ui/raidboss/data/06-ew/trial/zodiark-ex.txt
Not sure if astral eclipse timings vary or not, but I was seeing ~12.7 and ~13.7 in fflogs.
> raidboss: add 1st ex trial targetable lines to timeline

- ui/raidboss/data/06-ew/dungeon/stigma_dreamscape.ts
Per a report on the XIV plugin Discord server, this trigger seems to call only West, regardless of the dragon's actual spawn location. I'm not having much luck tracking down the issue, so for now we'll just tell the user to get behind the dragon the moment it spawns.
> raidboss: Correct Dreamscape dragon direction trigger

- ui/jobs/components/war.ts
- ui/jobs/constants.ts
Fixes #3778 
Some hypothesis to the question in #3778:
> Initial application of Storm's Eye is not exactly 30s (instead is ~31.1):
Storm's Eye will apply Surging Tempest at once with a log says you gain Surging Tempest for 30s,
but this buff duration will not go down until Storm's Eyes' damage is dealed.
(if you use other ability to cancel its animation, duration will still be locked to designed time, this make things very complex when use Inner Release in this case)
When refreshing, this duration lock will not apply.
Mythril Tempest do not have buff lock time. 
> I found that the timer and box were consistent, but if I refreshed then they got offset by like ~0.5s?
There is a log line delay of 0.5s for most buff.
> jobs: WAR: fix Surging Tempest timer

- .editorconfig
This takes the editorconfig from Trim21's #3677, with a slight
modification to also apply quote_type=single to js/ts/json files.
> build: add more vscode editorconfig settings

- ui/jobs/components/index.ts
- ui/jobs/jobs.ts
- ui/jobs/player.ts
This patch fill up incompled events('action/party', 'action/other'),
and add an event 'action' for any action using.
Change BuffTracker.onUseAction bind to action,
Fixes https://github.com/quisquous/cactbot/issues/3909
Co-authored-by: Echoring <68432572+Echoring@users.noreply.github.com>
> jobs: fix party action tracking

- ui/raidboss/data/06-ew/raid/p1n.ts
- ui/raidboss/data/06-ew/raid/p1n.txt
- ui/raidboss/data/06-ew/raid/p2n.ts
- ui/raidboss/data/06-ew/raid/p2n.txt
- ui/raidboss/data/raidboss_manifest.txt
I didn't realize renaming the branch would remove the pr.
Originally just had p2n, but decided to work out p1n as it wasn't up yet.
Some comments for P1N:
- ~~Hot Spell/Cold Spell shortened to Hot/Cold as it is similar to DRS Hot/Cold.~~ **EDIT:** Updated
- ~~Not to sure if we want to do something with 'unknown_6d15', a lot of parties don't know they can stack to prevent the knockback, but in normal arms length/surecast is up every cast...~~ **EDIT:** Updated
- I favored the visible cast name over the Gaoler's Flail cast for the later Aetherflail cast.
- I think the third gaoler's flail does not have a pair and that the last atherflail is paired with a gaoler's flail. The other pairs are their own sets?
> raidboss: add p1n and p2n timeline

- plugin/CactbotEventSource/FFXIVProcessIntl.cs
- types/event.d.ts
- ui/jobs/components/ast.ts
- ui/jobs/components/index.ts
- ui/jobs/jobs.css
- ui/test/test.ts
- Fix a mixture of Arcana and Minor Arcana in `Plugin`. This will fix `cardBox` error when you held a minor arcana. 
- Support Minor Arcana analysis in memory.
- Split EW AST from 5.x component.
- Change charactor to symbol `○` `×`, for `O` is too similar to `0`. (I'm not sure how it looks like in other language's PC?)
- Change Sign count box to show Minor Arcana. `↑` refers to Lord, and `＋` refers to Lady. (Is there any better symbols like sword and wings?)
- Add a stack-like gauge to show Sign. (When filling from left to right, users are more likely to feel full, but in-game gauge is from right to left)
> jobs: AST: Minor Arcana support and Sign improve

- ui/oopsyraidsy/oopsyraidsy_config.ts
This allows the debug console output to print the full filename
when user files are loaded for a particular zone.  This matches
what raidboss does.
> oopsy: annotate user triggersets with filenames

- ui/dps/rdmty/dps.css
- ui/dps/rdmty/dps.js
Allows up to 49 bars to be shown in Rdmty along with scrolling of overflow. This is helpful to see your rank in large events such as alliance raids, bojan front, etc. It also allows for smaller windows sizes as now bars not fitting can be seen by scrolling the window.
Fixes #3455
> dps: increase max rdmty bars and allow scrolling

- ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
- ui/raidboss/data/06-ew/trial/hydaelyn.ts
I still think calling it as early as possible here just feels
subjectively bad, but this is what I get for trying to adjust times
to fit closer in time to visuals.
Addresses half of #3880.
> raidboss: adjust lvl89 trial/EX2 timings

- ui/raidboss/data/06-ew/hunts/ultima_thule.ts
Fixes #3994 incorrect zone id for Ultima Thule hunts.
> raidboss: fix EW hunts wrong ZoneId

- resources/resourcebar.ts
- resources/timerbar.ts
Convert simple text values from using innerHTML to innerText as it has a
significant impact on performance; the values being updated should only
be numbers or percentages and shouldn't need HTML values, even for
potentially custom content.
> resources: Convert Simple HTML Text to InnerText

- resources/timerbar.ts
- resources/timerbox.ts
- resources/timericon.ts
Convert new Date instances that are trying to get current time to
instead use Date.now(). As proposed in #3824.
> resources: Convert New Date to Date.now()

- ui/jobs/components/index.ts
- ui/jobs/components/rdm.ts
- ui/jobs/constants.ts
- ui/jobs/jobs.css
- Adjust black and white mana related code
mana bar adjust to 25 per incs, and bright threshold change to 50
- Add fleche and contre sixte timer, also remove lucid dream.
white and black proc color are adjusted, for the black one cannot be distinguish from contre sixte.
- Adjust proc timer
it set to 30 - 1 gcd before, but cast time is 0.8 gcd, and proc will be comsumed 0.5s earlier before cast complete.
- Add mana stack guage
only shown when you have any.
> jobs: RDM: EW changes

- ui/raidboss/data/06-ew/raid/p4s.ts
* differentiates between cape (safer) and cleave (unsafe)
* spread/stack always alert (because important)
* removes delay on well pinax (incorrect for double knockback)
* lightning super important and forgettable so make it loud
> raidboss: slight p4s trigger adjustments

- ui/raidboss/data/06-ew/dungeon/smileton.ts
The knockback call during the first boss is called out more than once simultaneously.
This is caused by the trigger checking for two spellids that go off simultaneously.
673E targets Face
6C5E targets players
suppressSeconds is one fix... an alternative would be to remove one of spellids? Looks like they both are always cast.
> raidboss: smileton fix duplicate knockback call

- ui/raidboss/data/06-ew/dungeon/smileton.ts
Violent Discharge, used by The Big Cheese in Smileton, is a room-wide AoE. This was probably a copy/paste error from Right Disassembler.
> raidboss: Fix incorrect response for Violent Discharge

- ui/raidboss/data/06-ew/raid/p1s.ts
The current Shackles of Time callout is based on a previously used safe spot from a spell that is not relevant. I believe the nature of this debuff is such that wherever the player stands is what is going to do damage to the other players should they stand on it, so the call could be wrong if the party were to choose a color to always have the player be that is not matching whatever spell the boss had used previously.
EDIT: Not sure what to name the PR.
> raidboss: p1s shackles of time call opposite party/player

- ui/raidboss/data/06-ew/raid/p3s.ts
This is an alternate approach to #4050, combining amki and valarnin's
work from that patch with some extra tweaks.
In particular, this uses AddedCombatant over getCombatants to make it
easier to debug and differentiates bird tethers from player tethers.
Co-authored-by: valarnin <valarnin@gmail.com>
Co-authored-by: amki <amki@amki.eu>
> raidboss: p3s sunbird tether callouts

- ui/raidboss/data/06-ew/raid/p1s.ts
Shackles of Time Target and Shackles of Time call roughly the same thing
at the same time.  Remove one of them.
> raidboss: remove Shackles of Time duplicate call

- plugin/CactbotEventSource/FFXIVProcessIntl.cs
This is a following up fixing for #4090 
Opps, untestment makes bug.
If someone have lv90 DRG can you have a check?
> plugin: Fix NonSerialized for drg job data

- ui/eureka/eureka.ts
It's possible for the tracker id to be generated with an underscore.
Example: https://ffxiv-eureka.com/v3y_9B
> eureka: detect _ in the trackerRegex

- ui/oopsyraidsy/mistake_collector.ts
The `RequestSync` message should only be printed if the Debug option is
enabled.
Mentioned in #4096.
> oopsy: clean up debug log messages

- ui/raidboss/common_replacement.ts
- ui/raidboss/timeline_parser.ts
The international version of the ffxiv act plugin has changes to
log lines in the 2.6.x.x branch.  However, these changes have not
been merged back into the Korean plugin yet.  As timelines are
the only place that cactbot still uses parsed log lines, add
this additional edge case translation for Korean regexes.
This changes them back to the pre-6.x forms.  It doesn't cover
everything, but should cover enough that it's worth merging.
Tested by running `npm run util`, and looking at a few timelines
translated into Korean.
Maybe addresses #3949.
Fixes #4109 (in a better way).
Partially addresses #4102.
> raidboss: translate Korean logs into pre-6.x forms

- ui/raidboss/popup-text.ts
The first trigger registered by the system (usually "General Provoke") gets index `0`. When attempting to override this trigger from a user file, the index would be looked up and checked for existence via an implicit conversion to `boolean`. However `0` converts to `false`, so a new trigger would always be created, making it impossible to override this trigger.
This fix explicitly checks both the trigger id and index against `undefined`, instead of using an implicit conversion.
> raidboss: fix overriding trigger index 0 from user file

- ui/raidboss/data/06-ew/trial/hydaelyn-ex.ts
Per discord discussion.
Probably the underlying typescript mechanisms for this should be examined to prevent this issue in the future? Either:
a. `NetRegexes.ability` should return a partial type conforming to its valid matching fields
b. `NetRegexes.ability` should match every field, losing that performance gain
> raidboss: Fix EW Ex2 north/south trigger

- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.ts
Hansel and Gretel use "Tandem Assault: Bloody Sweep" as a combo move in
which the two bosses stand on the edge of the arena and each swipe
a large angled chunk of the platform simultaneously.
Hansel and Gretel will teleport to the side of the platform and will
sweep with their spears. Hansel is left handed and will hit the left
half while Gretel will hit the right half. Depending on which side of
the arena each is on, the safe spot to avoid getting hit will either be
between the two bosses or on the opposite side of the platform.
This can be detected using the relevant IDs, as determining whether the
spears are on the outside or inside of the arena is based on which of
the two IDs that Hansel and Gretel open the attack with.
To further complicate this, sometimes Hansel and Gretel will use …
> raidboss: add trigger for Bloody Sweep (#3605)

- resources/netregexes.ts
- resources/regexes.ts
Per discussion on #4142, this matches "option B".
Should probably be a follow up PR to make linting check for `@deprecated` and error out, along with related cleanup?
> raidboss: Refactor ability vs abilityFull

- resources/timerbar.ts
- resources/timerbox.ts
Timer objects can continue to advance in the background, even after
removed from the DOM if their duration is set to extremely high values.
This is most noticeable with the debug timer within raidboss, as it has
an extremely high duration upon creation. This issue exists in a smaller
capacity with other timerbar objects, but they will still leak beyond
their expected lifecycle until their duration ends. For instance, at the
end of the fight using raidboss, all of the active timerbars will
continue to advance until they reach their duration, even after the
fight has ended.
This can lead to memory issues as debug timers begin to accumulate with
multiple attempts of fights, each one continuing to be referenced until
they reach their duration (~31.5 years).
Fixes #3824
> resources: Stop TimerBar Advance on Disconnect

- test/unittests/netregex_test.ts
- test/unittests/regex_test.ts
This clarifies the testing for ability vs abilityFull after #4143.
> test: fix up regex tests after abilityFull change

- ui/oopsyraidsy/player_state_tracker.ts
It seems like this used to be '0' and now can be '0000'.
This should avoid buff tracking errors and console errors.
> oopsy: treat combatants with 0000 owners as not pets

- ui/raidboss/data/06-ew/dungeon/the_tower_of_zot.ts
During The Tower of Zot's first boss, Minduruva, cactbot has some tells
for the Transmute Fire III and Transmute Bio III delayed aoe attacks.
These trigger immediately when the Transmute begins casting, and warn
the player to run behind or under the orb that will have the Fire or Bio
attacks.
The boss will perform 2 transmutation of the elements before then using
a third element directly. If the boss uses Bio or Fire, the players must
first stack appropriately on the boss before running to the first or
second orb.
Since there is no tell for this, the tell for the orb mechanic can lead
players to run to the spot early, making it difficult to reach the
correct safe spot.
To correct this, we want to tell the player to first handle the mechanic
for the boss before handling the orb mechanic. …
> raidboss: improve Manusya/Transmute alerts

- docs/LogGuide.md
- ui/raidboss/data/03-hw/trial/sephirot.ts
- ui/raidboss/data/raidboss_manifest.txt
The sephirot normal mode boss does not have any triggers or data. This
boss has many mechanics without cast bars, and low visual tells.
Add some basic triggers to alert the player of the major mechanics like
the stack marker, earth shaker, spreading, etc. Also add a trigger to
warn about where knockbacks will land during Pillar of Mercy and to kill
the add that pops up before the three-arm wave (as failing to kill it in
time will be a wipe).
Signed-off-by: Jacob Keller <jacob.keller@gmail.com>
> raidboss: add basic triggers for Sephirot Normal mode

- ui/jobs/components/index.ts
Crafter's CP drinks also tracked as potion.
Gatherer may find someone use Chain Stratage or TA nearby.
Hide raidbuff tracker for unnecessary notice.
> jobs: hide raidbuff for crafter&gatherer

- ui/oopsyraidsy/data/06-ew/raid/p1n.ts
- ui/oopsyraidsy/data/06-ew/raid/p1s.ts
The hot/cold spell value carried over from the first set of
intemperate and could throw a mistake on the first hot/cold
of the second set of intemperate.  Stop being clever and
just track lose/gain.  Lose always happens prior to gaining
the new one, so this will not clobber the value.
> oopsy: fix p1 hot cold spell bugs

- ui/raidboss/data/02-arr/alliance/the_world_of_darkness.ts
During the Angra Mainyu encounter of the World of Darkness, the boss
will cast Level 100 Flare and Level 150 Death. These attacks put a head
marker on a target, and tether a few nearby players. After a few
seconds, the flare or death will trigger. For flare, if the number of
tethered players is still in the circle, everyone in the circle takes
massive damage. For death, if the number of players is a multiple of
3 then all players in the circle die.
The simplest way to avoid this is to have every player except the bound
target leave the circle.
Add an alarm that warns players to move away from the target. For
simplicity, just alert all players even if they aren't tethered. We
could possibly determine the tethers and alert only those players, but
its much simpler to just alert all players …
> raidboss: add triggers Angra Mainyu Flare and Death

- webpack/constants.ts
- webpack/webpack.config.ts
Fixes #3895.
If the static dir is dist/, then any emitted file into the dist/
directory causes a reload.  This causes the build process to
cause continuous reloads, making a slow process much slower.
> build: don't mix webpack static dir and output dir

- ui/config/config.css
- ui/config/config.ts
- ui/raidboss/data/00-misc/test.txt
- ui/raidboss/emulator/overrides/RaidEmulatorTimeline.ts
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
- ui/raidboss/raidboss_options.ts
- ui/raidboss/timeline.ts
- ui/raidboss/timeline_parser.ts
This adds a new "Edit Timeline" section to the config ui for any trigger set that has a timeline.  On a per text-basis, it allows for hiding all instances of a particular text or renaming it.  The primary use cases are to for folks who think the timeline is too messy or who want to rename things on the timeline (e.g. `Elegant Evisceration` to `Tank Buster`) or some such.
> raidboss/config: add ui for timeline text enable/renaming

- ui/oopsyraidsy/data/06-ew/raid/p4s.ts
6A16 is Hemitheos's Dark IV, which is the untelegraphed raid aoe when a
purple tether breaks.
> oopsy: fix p4s Dark IV mistake

- ui/raidboss/data/04-sb/trial/shinryu-ex.ts
- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts
These were broken due to extra precision from the 6.x ffxiv
act plugin changes.  Changed to look at all numbers and round
them, which should be more robust going forward.
Huge thanks to @valarnin for debugging!
Fixes #4212.
> raidboss: fix TEA trines / shinryu icicles

- ui/raidboss/data/05-shb/trial/diamond_weapon-ex.ts
When the Diamond Weapon is going to swipe a platform, an info message is
presented to inform the user of which side to move to and what attack
will follow this.
The default 5 second duration causes the info message to be gone well
before the attacks happen. Extend this duration to 15 seconds, lining up
better with the overall mechanic. This is ok because no other alerts
happen during this time.
The longer duration allows users to see what is happening more easily,
giving time to notice it and response without needing to memorize it for
10 seconds while focusing on other aspects of the fight.
Signed-off-by: Jacob Keller <jacob.keller@gmail.com>
> raidboss: extend duration for diamond ex platform switch

- ui/raidboss/emulator/data/PopupTextAnalysis.ts
Fixes #4214.
Logic error occurred only when multiple triggers were matched the same line and those triggers depended on each other's output.
Since resolved status is being checked per-line, the call to `this.checkResolved` between the two loops was no longer needed, instead it only needs to run at the end of the outer `for` loop to resolve older triggers.
> raidemulator: Fix error in PopupTextAnalysis

- ui/raidboss/data/02-arr/trial/ultima-ex.ts
- ui/raidboss/data/02-arr/trial/ultima-ex.txt
- ui/raidboss/data/raidboss_manifest.txt
Ultima is a mostly-typical ARR-style encounter. It consists of four phases each with its own rotation, with each activating in turn at HP thresholds. Phases 1/2/4 are reasonably well-behaved and presented basically no problems working out. Phase 3 appears to be incredibly convoluted almost beyond belief.
Triggers first though. As is normal for ARR-era encounters, the vast majority of Ultima's abilities have no cast times. This means most of our triggers will have to be timeline-driven. This is mostly not an issue, but we will discuss the exceptions later. For now, the major important triggers are in place. (Raidwide, tank swap, and off-tank cleave.)
The major issue experienced with generating this timeline was in phase 3. At 64.9% HP, Ultima enters its Ifrit phase, where it (mostly) …
> raidboss: Ultima EX timeline and minimal triggers

- docs/LogGuide.md
NARI recently merged the `event-rewrite` branch which heavily restructured all our events. This PR updates the URL for Cactbot docs. There's technically also the `instance` data in `nari.types.event.instance` but that's more for specific director commands.
I noticed a few of the event names no longer match ACT/NARI too, prob something to address.
> docs: Update DirectorUpdate link to NARI docs

- ui/raidboss/data/02-arr/trial/ultima-ex.ts
- ui/raidboss/data/02-arr/trial/ultima-ex.txt
Live testing and some video watching shook out a couple of mistakes.
Homing Lasers seems to be similar to Liquid Hell, although there's some dispute over whether it's on the farthest target or "if 1+ targets are out of melee, target one at random, else target random in melee". I'm not sure whether maybe we should just have a "Homing Lasers!" warning and leave it at that?
Diffractive Laser's addition and Homing Aetheroplasm's fix should be self-explanatory.
Should we maybe offset the callouts for the Boom orbs vs the Boom knockback? They are different severity levels, so there's no overlap in that sense, but they do come up at the same time.
The timeline desync in phase 3 that I noted in a previous conversation was simply from a sometimes-present Viscous Aetheroplasm. I don't exactly like …
> raidboss: Ultima EX updates

- .npmrc
This will throw errors when trying to run `npm` commands
like `npm install`, e.g.:
```
npm ERR! notsup Unsupported engine for @typescript-eslint/parser@5.16.0: wanted: {"no de":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.1","npm":"6.14.8"})
```
Fixes #2719.
> build: add engine-strict to require node version

- ui/config/config.css
- ui/raidboss/raidboss_config.ts
- ui/raidboss/timeline_parser.ts
- util/translate_timeline.ts
- webpack/loaders/timeline-loader.ts
The follow-up step to this is to add some ui that will allow for adding
custom timeline entries, but to have that make any sense, I think it's
useful for the timeline itself to be visible (and translated), so that
the times for custom timeline entries can have context.
A simpler alternative to this is to make a link to the triggers branch
timeline, but I thought this was nicer, and easy enough to translate
in place like we do for the tools.
This doesn't (and won't) let the user edit the timeline at all.
Perhaps there's some way to make this more obvious?  However,
I didn't want to disallow selection as copy and paste of times
seemed useful.  Not sure how else to indicate that this is a display
and not an editable text field.
Additionally, this doesn't respect the renaming or hiding …
> config: show timeline in edit timeline section

- ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.ts
- ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.txt
- ui/raidboss/data/raidboss_manifest.txt
Not much to say here. There's been no live testing of the triggers. The timeline is immensely accurate against the More Than One logs I ran it against. (I did have the timeline in place when I ran the dungeon once, and it mostly worked. What's in this PR is the updated version.)
No TODOs inline, but we have some calculations to try for such as the tentacle locations on boss 1, the bit positions on boss 2, and the curtain spots on boss 3. I'll have a look at that maybe tomorrow when I'm not in a time crunch.
> raidboss: Alzadaal's Legacy initial timeline and triggers

- ui/raidboss/data/06-ew/trial/endsinger-ex.ts
- ui/raidboss/data/06-ew/trial/endsinger-ex.txt
- ui/raidboss/data/raidboss_manifest.txt
```
447.2 "Elenchos" sync / 1[56]:[^:]*:The Endsinger:702[02]:/ window 5,5
```
For some reason this timeline entry required the `window` parameter to pass `test_timeline.py` but generating the timeline for every single pull shows the same `447.2`-ish timestamp.
Starting on basic triggers next, I'll base that branch off this one and rebase when this is merged.
> raidboss: Add Endsinger Ex timeline

- plugin/CactbotEventSource/FFXIVProcess.cs
- plugin/CactbotEventSource/FFXIVProcessIntl.cs
The previous one is zero when dying in combat and also during some
cutscenes and transitions.  This is an attempt to use one similar
to the previous 6.0 version.  However, rather than using the writer
which is the "mov [rax+rcx],bl" line which is complicated to
untangled, use a reader instead.
Unfortunately, this reader is on a "cmp byte" line where the pointer
is not at the end of the instruction.  This requires modifying
the SigScan line to handle adjusting for this case, as the scanner
otherwise doesn't know anything about instruction boundaries.
Notes for the future:
```
Combat is a byte, 0x01 when on, 0x00 when out
Start in combat, search for 0x1, hit next scan a bunch
out of combat, search for 0x0, hit next scan a bunch
In combat but untargeted as 0x1
Find green static address, …
```
> plugin: use another in combat signature

- ui/raidboss/data/06-ew/trial/endsinger-ex.ts
Due to a raidemulator bug:
5head triggers won't work in raidemulator for second set in a given pull.
6 head triggers won't work in raidemulator at all.
The super quick and dirty "fix" to test these triggers is:
```diff
diff --git a/ui/raidboss/emulator/data/Combatant.ts b/ui/raidboss/emulator/data/Combatant.ts
index 2b27074e7..c8adb9040 100644
--- a/ui/raidboss/emulator/data/Combatant.ts
+++ b/ui/raidboss/emulator/data/Combatant.ts
@@ -97,7 +97,10 @@ export default class Combatant {
const oldStateJSON = JSON.stringify(this.states[lastSignificantStateTimestamp]);
const newStateJSON = JSON.stringify(this.states[timestamp]);
-    if (lastSignificantStateTimestamp !== timestamp && newStateJSON !== oldStateJSON)
+    if (
+      (lastSignificantStateTimestamp !== timestamp && newStateJSON !== …
```
> raidboss: Endsinger Ex advanced triggers

- ui/raidboss/data/06-ew/trial/ultima-unreal.ts
- ui/raidboss/data/06-ew/trial/ultima-unreal.txt
- ui/raidboss/data/raidboss_manifest.txt
Looks like it was a simple enough find/replace job. I had to expand the window at 332.4 for the Radiant Plume opening sync, since it *looks* like the Ceruleum Vent there might be skipped? Or maybe it's HP-based and our EX testing didn't show it up? In any case, this version passed `test_timeline` nicely, so I think we're good to release it and let the bug reports flow in.
Oopsy will be forthcoming tonight or tomorrow.
> raidboss: Add Ultima Unreal

- ui/raidboss/data/06-ew/trial/endsinger-ex.ts
I mentioned these changes in a reply to #4270
Basically, remove the star name requirement entirely (change 1) and remove the need for calls to `getCombatants` (change 2).
> raidboss: Endsinger Ex star trigger tweaks

- util/DEPS.json5
Update to build against 0.18.2 which uses Newtonsoft.Json 13.x.
Since cactbot builds against OverlayPlugin's version directly,
use this DLL to make sure it depends on 13.x and not 12.x.
See:
https://github.com/ngld/OverlayPlugin/commit/061c11cdb24bcbddf653c8d54ad2070a76cdef77
> build: update OverlayPlugin dependency to 0.18.2

- ui/raidboss/emulator/data/CombatantTracker.ts
Fixes #3349
Might also fix the second issue mentioned, at least it's not returning `???` anymore, but I've never done this fight and have no idea if the callouts are correct.
I had to add multiple line events to the 'force significant states' mapping, the `20` event only fixed the original `4000478C` combatant. I included logic for target line events though I'm not sure of any specific cases where they would apply yet.
> raidemulator: Force combatant sig states for line events

- resources/util.ts
- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/raidboss/emulator/data/PopupTextAnalysis.ts
- ui/raidboss/emulator/data/RaidEmulator.ts
- ui/raidboss/emulator/overrides/RaidEmulatorWatchCombatantsOverride.ts
- ui/raidboss/raidemulator.ts
This one ended up being significantly more complicated than I was hoping.
This PR:
- Adds an override for watchCombatant for raidemulator to use
- Modifies the way PopupTextAnalysis tracks trigger promise resolution to not block waiting for a promise to resolve
- Refactors the way RaidEmulatorOverlayApiHook handles getCombatants to let other classes call it
- Adds a new class to override watchCombatant
Technically these 4 could be separate sequential PRs but considering how small 1/2/3 would be, I didn't think it was really worth splitting them up.
~~There's some sort of bug with resolved timestamp display, e.g. this trigger actually resolved at 1:05 into the pull:~~
~~So this isn't quite ready to merge yet (or that bug can be fixed in a later PR), I just wanted to get it open for …
> raidemulator: Add support for watchCombatant

- ui/raidboss/emulator/data/Combatant.ts
- ui/raidboss/emulator/data/CombatantState.ts
- ui/raidboss/emulator/data/CombatantTracker.ts
I mentioned changing the way state comparisons work in #3360. This is that change.
This is part one of breaking that old PR up into separate PRs instead.
The logic here is to only have to stringify the state once on creation, and then use that cached value until the combatant tracker state has been fully created.
Also shifted the logic added in #3359 to sit in the Combatant class since it makes more sense to live there alongside the new logic.
> raidemulator: Refactor state tracking for better performance

- ui/raidboss/emulator/data/NetworkLogConverter.ts
- ui/raidboss/emulator/data/NetworkLogConverter.worker.ts
This is part two of breaking #3360 up into smaller PRs. Update the indexing logic to be encounter-relative instead of file-relative.
I specifically avoided using `lines.forEach` or any other direct iteration method like that as even a 9-minute fight is 42k lines long which adds a noticeable overhead when having to recreate arrays. Calling `Object.entries` as used elsewhere is even slower.
> raidemulator: Update LineEvent indexing

- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/raidboss/emulator/data/PopupTextAnalysis.ts
Penultimate PR for splitting up #3360.
This PR decreases the time to load a Trinity Avowed encounter from 325s to 254s.
> raidemulator: Implement regex result caching for analysis

- ui/raidboss/emulator/data/Combatant.ts
- ui/raidboss/emulator/data/CombatantTracker.ts
- ui/raidboss/emulator/data/Encounter.ts
- ui/raidboss/emulator/data/Persistor.ts
- ui/raidboss/emulator/data/PopupTextAnalysis.ts
Last PR followup for #3360.
The Regex Caching change improves performance more for analysis per combatant (all performance gain was in `AnalyzedEncounter.analyzeFor`), so that change will see a bigger improvement for 24-man content than 8-man content, whereas these changes benefit more from a lines-per-encounter perspective.
Performance improvement statistics copy/pasted from other PR:
```
p3s: 9m52s encounter duration, 35923 lines
No changes: 15222, 14951, 14959, average 15044
Regex Caching: 14320, 13812, 13873, average 14002, 7% improvement from baseline
Loop Changes: 11543, 10951, 10717, average 11070, 26% improvement from baseline
drs: 27m37s encounter duration, 93598 lines
No changes: 341555, 325064, 326215, average 330945
Regex Caching: 279454, 279426, 276079, average 278320, 16% …
```
> raidemulator: Adjust loops to be more efficient

- resources/netlog_defs.ts
- resources/netregexes.ts
- resources/regexes.ts
As discussed in #4165 and elsewhere, this is an attempt at addressing the issue of log format drift between versions (international, cn, ko).
This is still very much a WIP, and should function exactly as the current release as far as logic. The goal ultimately for this PR is to remove all of the default types (`lang extends Lang = 'en'` => `lang extends Lang`, remove default export for `netlog_defs.ts`).
This PR doesn't tackle extracting the version from log files for raidemulator or handling old log files in raidemulator, and in fact raidemulator still treats all log files as `en`.
For now, I'm looking mostly for feedback on the changes in `netlog_defs.ts` as that drives the changes elsewhere. Changes elsewhere are still extremely WIP.
> raidboss: Refactor log defs to support multiple versions

- ui/raidboss/data/03-hw/trial/sephirot-ex.ts
- ui/raidboss/data/03-hw/trial/sephirot-ex.txt
Updated the timeline and added new triggers.
The timeline had some issues with sync timings after the first rotation. I fixed the initial Yesod cast and added windows elsewhere to mitigate any other possible jumps. Everything else timeline-related should be self-explanatory.
The positions for the Ein Sof puddles in phase 1 can technically be detected so that we can call an actual direction for moving the boss on Fiendish Rage and Ain + Ratzon. It's a good bit of work to do so because the puddles constantly cast as they expand, and it's just a lot of work to make that functional. Maybe in a later update, but it's good enough as it is here.
Some triggers have full translations because I copied them from the normal mode version.
Earth shakers do proximity falloff damage in this encounter. …
> raidboss: Sephirot EX updates

- ui/raidboss/raidboss_config.ts
Duration got added later and wasn't added to the remove button
logic, and so clicking "remove" causes layout issues.
Fixes #4332.
> config: fix removing timeline entry

- plugin/CactbotEventSource/VersionChecker.cs
Hello, if you want get the ```Machina.FFXIV.Headers.Opcodes.OpcodeManager.Instance```, just try opcode_manager_type.GetProperty("Instance").GetValue(***null***) instead of create a new instance of the singleton.
> plugin: fix broken singleton mode in Machina.FFXIV

- test/helper/test_trigger.ts
- util/gen_coverage_report.ts
Fixes #3922
- Fix coverage report skipping file if the timelineFile is missing
- Add test for missing timelineFile
I don't really work with mocha very often but this seems correct and worked for the test setup I did.
> test: Tweaks for missing timelineFile

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
This PR adjusts the Adelphel KB direction to key off of name toggle, and to call out the direction the player should move.
Additionally, this adds a trigger for left/right movement depending on boss movement (the logic on this could use a double-check).
> raidboss: Fix Adelphel KB direction, add move callout

- ui/raidboss/emulator/data/CombatantTracker.ts
Noticed some NaNs while debugging DSR triggers. When I was verifying those were fixed, also noticed extra states caused by the optimization PR.
> raidemulator: Fix NaNs and extra states

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
The non-p1 knockback was broken in #4376.
> raidboss: fix Thordan knockback call

- resources/netlog_defs.ts
- resources/netregexes.ts
- resources/regexes.ts
Fixes #3713.
Also managed to clean up an `x as y` cast in both files as part of this.
Examples with this change:
```js
// NetRegexes.statusEffectExplicit({ data4: '00', capture: true });
/^(?<type>(?:38))\|(?<timestamp>(?:[^|]*))\|(?<targetId>(?:[^|]*))\|(?<target>(?:[^|]*))\|(?<jobLevelData>(?:[^|]*))\|(?<hp>(?:[^|]*))\|(?<maxHp>(?:[^|]*))\|(?<mp>(?:[^|]*))\|(?<maxMp>(?:[^|]*))\|(?:[^|]*\|){2}(?<x>(?:[^|]*))\|(?<y>(?:[^|]*))\|(?<z>(?:[^|]*))\|(?<heading>(?:[^|]*))\|(?<data0>(?:[^|]*))\|(?<data1>(?:[^|]*))\|(?<data2>(?:[^|]*))\|(?<data3>(?:[^|]*))\|(?<data4>(?:00))\|/i;
// NetRegexes.statusEffectExplicit({ data1: '00', capture: true });
/^(?<type>(?:38))\|(?<timestamp>(?:[^|]*))\|(?<targetId>(?:[^|]*))\|(?<target>(?:[^|]*))\|(?<jobLevelData>(?:[^|]*))\|(?<hp>(?:[^|]*))\|(?<maxHp>(?:[^|]*)) …
```
> raidboss: Add support for optional netlog fields

- util/logtools/arg_parser.ts
- util/logtools/split_log.js
This is a cleaned-up (I hope) version of the mess in #3658.
~~It appears that when we create an instance of `LogUtilArgParse` after exporting + importing it, the various values for any unused args are set to `null` rather than their default values. This means we have to shift how we validate the various flags. (That is, if we `invoke split_log -f logfile.log -lf`, all arguments apart from `-f` and `-lf` will be `null` rather than their defined constant values.`-lf` will be -1.) It's very possible I'm missing a better way to handle all this, but as it stands this all seems to *work*.~~
~~`--force` is special-cased to be true if present, since if we don't define it as constant, it will instead have a value of `force[]` rather than `true`.~~
Disregard this because I'm bad at Argparse  and …
> util: Argparse separation updates

- requirements.txt
- util/coinach.py
- util/encounter_tools.py
- util/gen_fisher_data.py
- util/make_timeline.py
- util/test_timeline.py
- util/translate_fight.py
fix #4321
bump black 19.10b0 to 22.3.0
reformatted python files with option `black **/*.py --line-length 100`
bump pylint 2.5.3 to 2.13.7
The only new errors that appear are:
```python
>>> pylint **/*.py --errors-only
************* Module make_timeline
util\make_timeline.py:512:8: E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
util\make_timeline.py:514:8: E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
util\make_timeline.py:516:8: E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
************* Module test_timeline
util\test_timeline.py:610:8: E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
util\test_timeline.py:613:8: E0702: Raising …
```
> build: update python formatter and linter

- package-lock.json
- package.json
- test/helper/test_trigger.ts
Closes #4230 as well.
Sorry for stealing your change, @MaikoTan.
I elected to go with a typeguard rather than an `as` cast as I outlined in the mentioned issue. Still not sure what caused this breakage in the typescript update to begin with 🤷‍♂️
> build: Update typescript to latest version (4.6.4)

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt
This is an opinionated addition to #4381. It's not practical for melee jobs, but it's useful for anyone on a ranged job. It's kind of difficult to maintain uptime through the dashes, but it's doable.
(There's a good deal of self-interest here, since with the current opener, Bard has to refresh Iron Jaws very soon after Adelphel returns during the knockback. But again, this is opinionated, so I have no problem just keeping this as a personal addition.)
> raidboss: DSR--Phase 1 targetable window addition

- util/logtools/encounter_tools.ts
- util/logtools/split_log.js
When working with `EncounterCollectors` during imports, it's a real pain to deal with properties that may or may not be present on a `FightEncInfo` object vs a `ZoneEncInfo` object. Going forward, there should be no more ambiguity.
(This is a stepping-stone change that came up while I was doing some other work with `encounter_tools`, and I figured it would be best to consider it entirely separately.)
> util: Make encounter info property categories explicit

- ui/config/config.ts
> config: Fix display for user triggers with ZoneId.MatchAll

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
An attempt to address #4389 by adding some more time to account
for lag.
> raidboss: delay Spiral Thrust callout by 0.5s

- util/logtools/encounter_tools.ts
- util/logtools/split_log.js
This is another stepping-stone for continued changes to our log utilities. I'm not really attached to having these functions live in `encounter_tools`, I mostly placed them here to get them *out* of `split_log`. I'm not really attached to much here in general, really. In large part the changes made here are "satisfy the compiler but otherwise maintain most of the logic".
> util: Move utility functions to Encounter Tools

- util/find_missing_timeline_translations.js
This makes it easier to differentiate output when concatenating
the missing results of all languages together.
> util: add localeReg to find missing output

- test/helper/test_trigger.ts
- ui/raidboss/data/04-sb/eureka/eureka_hydatos.ts
- ui/raidboss/data/05-shb/etc/the_diadem.ts
test_trigger.ts had a bunch of older tests that were no longer valid (testing game log lines instead of network log lines).
Instead, this PR removes those tests and adds new tests as follows:
1. Make sure that built-in triggers don't use the `regex: Regexes` format
2. Make sure that built-in triggers don't use `regex` or a lang-keyed version
It also:
1. Fixes a performance issue with calling `getParamNames` twice
2. Fixes a broken trigger for unnecessary group regex (and fixes the two triggers that had this issue)
> test: Update test_trigger.ts

- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
- ui/raidboss/popup-text.ts
Fixes #4425.
While testing the fix I noticed an issue with initData being called multiple times instead. Turns out it wasn't ever being cleared which I'm sure lead to some memory leakage slowly over time, as the initData functions built up and populated the data object with more and more zones' worth of initial state.
> raidboss/raidemulator: Fix issues with initData handling

- test/helper/test_trigger.ts
The NetRegexes flag needs to be set prior to import when it is
used for evaluation.  This was broken due to a final change to #4433
without being properly retested.
Also, some small cleanups while here.
This is working towards #1306 as well.
> test: fix test for missing regex translations

- resources/translations.ts
- test/helper/test_timeline.ts
- test/helper/test_trigger.ts
- ui/raidboss/timeline_parser.ts
To avoid writing this code a third time for translating regexes in
popup-text.ts, move translation functions into translations.ts.
This allows the runtime timeline/regex and test code to share the
same functionality, which makes it more likely that the test code
is testing the correct thing and the same translations are
happening at runtime as they are in tests.
This is working towards #1306.
The final steps are:
* auto-translation netRegex fields when netRegexDe (etc) is unspecified
* deprecate and remove netRegexDe (etc)
> resources/test: consolidate translation functions

- ui/config/config.ts
As a followup to #4449 and #4454, there were two conditionals in config.ts which followed the same general pattern but due to the combined boolean expression (`a && b || c`), didn't turn up with the new eslint rule's most permissive settings.
I figured it's better to submit these as a separate PR.
> config: Adjust typechecks in config.ts

- util/find_missing_timeline_translations.ts
- util/find_missing_translations.ts
- util/translate_timeline.ts
Working on the new test_timeline.ts file, I wanted to move the building of argparse and handling of args for each util out of `index.ts` and to their own file so that the `index.ts` file doesn't bloat as more tools are added.
While trying to move said code responsibility out of `index.ts`, I ran into issues because these files weren't typescript, so I converted them.
Also there were some bugs that I fixed along the way.
> util: Convert `find_missing_*_translations` to typescript

- .eslintrc.cjs
This is the beginning of a series of follow up PRs for #4447. This PR adds the lint rule `@typescript-eslint/strict-boolean-expressions` with its most permissive settings.
This PR can't be merged until the downstream PRs are merged to clean up errors:
- #4449
- #4450
- #4451
- #4452
- #4454
> lint: Enable basic strict-boolean-expressions lint rule

- ui/raidboss/popup-text.ts
This was broken in #4449 because I didn't realize that the empty
string check was important behavior, whoops.
If a user edits something in the config ui and then clears it,
then it will leave an empty string in the config json and
output strings overrides.  This needs to be skipped (and could
be cleaned up elsewhere, but this is a small bugfix for now).
> raidboss: fix edited-but-empty strings from being skipped

- ui/raidboss/popup-text.ts
This is a follow-up to #4458, and is for #1306.
It seemed weirdly asymmetrical to not auto-translate regex as well,
even though these are deprecated.
> raidboss: auto-translate regex as well

- ui/config/config.css
If you expanded and then collapsed Edit Timeline under a
Config > Raidboss section, then the Add More Rows button would
still be visible incorrectly before this patch.
> config: hide Add More Rows button when collapsing timeline

- docs/RaidbossGuide.md
- docs/zh-CN/RaidbossGuide.md
- test/helper/test_trigger.ts
- types/trigger.d.ts
- ui/raidboss/raidboss_config.ts
This fully deprecates the locale netRegex/regex equivalents,
removing them from the trigger.d.ts type definition and from
documentation.
These are now auto-translated from the timelineReplace section.
Fixes #1306.
> raidboss: deprecate netRegexDe / regexDe etc

- util/find_missing_translations.ts
- util/generate_data_files.ts
- util/index.ts
- util/translate_timeline.ts
Followup to #4466, precursor to #4444.
I tested that `findTranslations` and `translateTimeline` work as expected, and that `findTranslations` output the same as before the change, and that `translateTimeline`'s output made sense/wasn't broken somehow.
`generate` does not work in either `main` or this PR, due to the ESLint update. I'll open an issue for that in general for better tracking.
> util: Move responsibility for arg parsing out of index

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
The second Wyrmsbreath in phase 6 utilizes Boiling and Freezing debuffs. I am not sure if it's possible to get these debuffs by failing the first Wyrmsbreath, but the debuffs do not appear in a kill log at that time that I looked at and so I did not think to add a check for that.
This also brings back Deep Freeze and Pyretic debuffs from old. Deep Freeze looks to be unavoidable, but Pyretic will require an advance notice such that the player is not moving when Boiling expires as there is a brief period of time between Cauterize hit and Boiling expiration where Pyretic is on the player.
I am not certain on the exact timing of when the dragons are in position, but it looks like it's at least random left/right which dragon is where and I am not sure if the cardinal they choose is also …
> raidboss: DSR Wyrmsbreath 2 Boiling and Freezing

- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/mistake_collector.ts
- ui/oopsyraidsy/oopsy_viewer.css
- ui/oopsyraidsy/oopsy_viewer.html
- ui/oopsyraidsy/oopsy_viewer.ts
- ui/oopsyraidsy/oopsyraidsy.ts
- webpack/constants.ts
- webpack/webpack.config.ts
This allows you to drag and drop a network log file onto
an html page and get a list of all mistakes.
This is still a bit of a work in progress, especially party buffs
which need to figure out who is in the party and is currently
depending on events that don't exist.
There's also a lot of TODOs here to improve the UI.  The summary
page could probably use a lot of work as well, in terms of being
able to select certain zones/encounters, and also to have a
summary of mistakes by type.
Fixes #3429.
> oopsy: add file viewer

- util/logtools/arg_parser.ts
- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
- util/logtools/split_log.js
Lots and lots of nonsense, but at a bare minimum, it can produce a basic timeline. We have duplicated (for the most part) the logic of our Python version with some small improvements here and there. Speed is comparable between the two versions. (We should be able to get more speed in future with some improvements to `EncounterCollector`.)
All `ignore` flags should work, as should `-it` and `-oc`.  
A *lot* of the weird-looking declarations are to satisfy the compiler. Most of them are "the heck with it, *now* it's guaranteed defined". This is particularly true in interactions with `args`, since we can't guarantee any specific one is populated from Typescript's point of view. (Also there are very possibly remnants from VSCode's debugger, since it sometimes has subtle behavior differences …
> util: Typescriptify make_timeline

- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/data/06-ew/raid/p2s.ts
Sometimes abilities are marked as AOEActionEffect but they only
have one target.  This was fixed in player_state_tracker.ts
but needed to be fixed in damage_tracker.ts as well.
This is most obvious on Ser Adelphel's Execution (62D5) ability.
This is a follow-up to #4161.
> oopsy: fix single target damage looking like a share

- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/player_state_tracker.ts
In order for the log file-based oopsy_viewer to know who is in the
party, the PartyList log lines need to be used instead of the
PartyChanged events.  For simplicity, don't support both and
switch even the live version over to the log-based tracking
so there's only one code path.
> oopsy: use log lines instead of events for party tracking

- ui/raidboss/data/04-sb/dungeon/drowned_city_of_skalla.ts
As far as I can see this is pretty much a clean cut, boss turns to player and does frontal type mechanic. When I first saw the message I was trying to figure out what an eye laser was and where I should be looking.
Only concern I have is that the boss does it multiple times so the previous custom message had 'avoid eye laser**s**' whereas it would now just say 'Away From Front' 🤷‍♂️.
> raidboss: changed DCoS final boss custom text to preset

- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
This is mostly just a proof-of-concept. I'm not really attached to it and I didn't benchmark it, but I did feel like seeing whether it would *work*.
> util: Add single-pass file parsing in timeline tools

- util/logtools/encounter_tools.ts
```
2022-04-25
2022-04-24
1)  16:56:11.436 |  2m | Thavnair                             [Zone Change]
2)  17:25:55.837 |  1m | Eden's Gate: Descent                 [Wipe]
3)  17:51:32.543 |  6m | Eden's Gate: Descent                 [Win]
4)  18:25:11.796 |  7m | Alexander - The Soul of the Creator  [Win]
5)  18:43:18.817 | 83m | Radz-at-Han                          [Zone Change]
2022-04-25
6)  20:12:08.257 |  6m | Thavnair                             [Zone Change]
~The Temple of the Fist~
2022-04-25
7)  20:21:50.000 |  1m | Tourmaline Pond                      [Unseal]
8)  20:27:17.000 |  2m | Harmony                              [Unseal]
9)  20:32:32.000 |  3m | Guidance                             [Unseal]
10)  20:42:06.077 | 62m | Radz-at-Han                          [Zone Change] …
```
> util: Fix encounter_tools encounter listing

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Cast is an instant cast. Also the resentment from p6 would need more condition work as it is currently used as a means to detect that the DPS check has been met, so I have specified the phase condition for now.
> raidboss: DSR Resentment AoE + DoT Callout

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
`DSR Spiral Thrust Safe Spots` made three synchronous calls to `getCombatants`, which can add a lot of overhead on execution time if using remote raidboss/fetching over websocket in general.
`DSR Sanctity of the Ward Direction` error text states it's expecting at least one, but the check is for at least two. Adjust the check down to match the text (in practicality IIRC there's two combatants with the name `Ser Janlenoux` usually, but it's irrelevant due to the sort applied afterwards, this was more of a "correctness" change and could have gone the other way instead of updating the error text).
> raidboss: Cleanup some DSRU getCombatants calls

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
This is a series of opinionated commits to add some minor improvements to #4435.
In particular:
* merges the "dive" callout into the In+Out (or In+Out followup) calls
* uses alert in more places
* more specialized logic for two baiters/placers
* simplifies the position sorting logic
without this PR side 1:
with this PR side 1:
without this PR 2:
with this PR 2:
(One other thought is maybe the "1 (all circles)" call should be combined with "Dive (circles) => Out" a second later? Or is it worth having the 1-2 second warning there but a duplicate call? Should there be another out/in reminder after the stack or a dive, e.g. dive => out, out, in vs just dive => out, in (10 seconds later)? Also, the `Dir Group` call is a personal trigger, in case there's confusion.)
> raidboss: DSR DFG minor improvements

- ui/raidboss/popup-text.ts
This was changed in #4449, but the incorrect typing obscured
that this was possible.  Type assertions hiding bugs.  :C
> raidboss: fix error if TriggerParams are undefined

- resources/datetime.ts
- resources/stringhandlers.ts
- ui/raidboss/emulator/EmulatorCommon.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x01.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
- ui/raidboss/emulator/ui/EmulatedPartyInfo.ts
- ui/raidboss/emulator/ui/EncounterTab.ts
- ui/raidboss/emulator/ui/ProgressBar.ts
- ui/raidboss/raidemulator.ts
- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
(*Ping @valarnin, since you probably have the best idea of whether anything I've touched here breaks things.*)
Mostly self-explanatory. I changed a couple of date/time function names to make What They Do slightly easier to follow, but apart from that it's largely simple movement. I'm not strongly attached to the choices I made here, so please offer all the criticisms. In particular, I'm not really sure about all the names I assigned here. (Should I have/have not have aliased the imports? Are some of the function names too long? etc)
(It's noted in-line, but I absolutely do not intend `getTZOffsetFromLogLine` to permanently use naive string parsing to extract a timestamp. Once we get the line parser disentangled from the emulator I'll gladly swap over to using that, but I don't know the …
> util: Move + centralize core date/string handling 

- ui/raidboss/data/00-misc/general.ts
Fixes #4560.
This file had the same issue as #4536, where it didn't have
any timeline and thus was missed by the scripts.
Worse, it also appears that the translation replacement happens
*after* the \y{Name} replacement, so ready check is a little
awkward to replace.  If we get more \y{Name} or \y{Float} replacement
issues we can add a better way to handle this.
To make replacement easier (for French), I reordered the ready
check regular expression and removed some unnecessary periods.
Also, I removed the translations for "commands" like
"cactbot lang" and left them untranslated.
With this patch, the regexes for each language are:
netRegex: `^(?:00)\|(?:[^|]*)\|(?:0039|0139|0239)\|(?:[^|]*)\|(?:(?:You have commenced a ready check|(?:[^\s:|]+(?: [^\s:|]+)?|) has initiated a ready …
> raidboss: fix general.ts translations (e.g. ready check)

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Looking at fflogs replays and the log from #4564,
it appears that the "left wing" and "right wing" comments
are backwards.
We could consider saying "north" and "south" here to be
absolute, but I think most folks will be looking at Hraesvelgr
to see the wing and head, so left/right is pretty natural.
> raidboss: DSR reverse p6 hallowed wings left/right

- util/logtools/anonymizer.js
Hashes are 16 characters and because the log splitter has not been
updated to typescript, the change to `firstOptionalField` was
missed.
> util: fix some anonymizer bugs

- util/logtools/encounter_tools.ts
This resolves bugs I introduced when moving functions around in #4522. I'm not sure how I missed seeing the Glaringly Obvious Misformatting, but after removing the unnecessary replacements from `printZone/Fight`, all seems to be back to normal. 
This also fixes a bug with getting milliseconds where the logic was exactly backward from what it should have been, and therefore we were getting nonsense offsets. This somehow didn't show up obviously anywhere.
(Thanks quisquous for the bug report!)
> util: Restore correct date formatting in encounter_tools

- util/logtools/encounter_printer.ts
- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
- util/logtools/split_log.ts
This makes it easier to include encounter_tools in a web page.
> util: move node-only encounter printing to its own file

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Self-explanatory; extend duration of Sanctity of the Ward CW/CCW direction callout to 13secs so it stays up for the duration of the mechanic.
> raidboss: Extend duration of Sanctity direction callout

- ui/raidboss/popup-text.ts
There's currently no way to disable sound for a trigger.
This makes `sound: ''` to mean don't play any sound.
It's possible but unlikely this will fix #4588 due to the
`DSR Wrath Thunderstruck Targets` trigger having `sound: ''` and
`tts: 'null'`, but I was unable to repro this situation.
This also intersects with the https://github.com/quisquous/cactbot/pull/4523 changes.
> raidboss: make empty string sound mean no sound

- util/logtools/arg_parser.ts
- util/logtools/fflogs.ts
- util/logtools/make_timeline.ts
- util/logtools/split_log.ts
It works for the More Than One reports I tried it on. Usage is (or should be) identical to the original Python implementation. I haven't tested all the combinations of arguments, so it's entirely possible I left in some invalid combinations.
On the error codes, I tried to keep it to "a missing or invalid encounter is -2, actual script errors are -1". If we should make that more granular, I'm happy to make those changes.
Testing On My Machine seems to be not costly at all, with a solid half-hour debugging session not even reaching 100 V1 API points.
> util: Add basic FFLogs support to make_timeline.ts

- util/logtools/make_timeline.ts
Very basic and very naive. It doesn't work if there are interleaved abilities, but it catches most of them.
```
120.0 "Weight of the Land" sync / 1[56]:[^:]*:The Ultima Weapon:6F01:/
121.0 "Ceruleum Vent" sync / 1[56]:[^:]*:The Ultima Weapon:6EEF:/
134.1 "Eruption" sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
134.2 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
136.0 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
136.1 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
138.1 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
138.1 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
140.0 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
140.0 "Eruption" #sync / 1[56]:[^:]*:The Ultima Weapon:6F03:/
141.8 "Eruption" #sync / 1[56]:[^:]*:The Ultima …
```
> util: Auto-comment some repeated abilities in make_timeline

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt
This adds the initial hit to the timeline for the one and two sword marker groups during sanctity. This helps with landing a heal between the swords before movement is required to dodge orbs in daylight strategy.
> raidboss: DSR Individual Sacred Sever hits in timeline

- ui/fisher/fisher.js
may fix #3998?
change `place` regex to `.+` for sure, and added `αβγ` for uncertain.
fix `fish` regex for `'36519': 'E.B.E-9318',` and `'33243': '隆卡的大水蛇？', 'Grand Serpent marin de Ronka?' ...`
> fisher: fix place and fish regex

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
When Spreading/Entangled debuffs are applied, the player who has no debuff
should stack with other player who has 'Entangled Flame' debuff.
Combined 'DSR Spreading Flame' and 'DSR Entangled Flame' to one trigger
and added support to 'no debuff' callout.
> raidboss: update DSR Spreading/Entangled Flame

- ui/raidboss/data/06-ew/trial/zodiark-ex.ts
The previous id was self-casted, which prevented the response from working properly.
> raidboss: fix zodiark ex tankbuster id

- ui/raidboss/data/05-shb/eureka/bozjan_southern_front.ts
It seems the mistake was inherited from the Japanese version as the messages in other languages are correct. One can easily tell, even without understanding Japanese, that if '白玉へ' means 'go to the white orb', then '赤玉へ' definitely doesn't mean what it's supposed to mean. In fact '赤玉へ' means 'go to the red orb', but my japanese is too poor to fix it, sorry.
> i18n: fix a mistake in cn

- ui/raidboss/emulator/data/AnalyzedEncounter.ts
- ui/raidboss/emulator/translations.ts
- ui/raidboss/emulator/ui/EmulatedPartyInfo.ts
- ui/raidboss/emulator/ui/EncounterTab.ts
- ui/raidboss/emulator/ui/ProgressBar.ts
- ui/raidboss/raidemulator.html
Assuming I understood the issue correctly, this should fix #4548
Could use some additional testing by another pair of eyes, as stated elsewhere this is a bit of a complicated mess to adjust.
Also this PR fixes a bug I noticed where triggers with a delaySeconds parameter were getting additional time added to their resolvedOffset due to leftover code from a previous way of calculating the resolvedOffset value.
> raidemulator: Change emulator display to hide pre-pull time

- ui/oopsyraidsy/data/03-hw/trial/sephirot-ex.ts
- ui/oopsyraidsy/data/oopsy_manifest.txt
Largely self-explanatory. I could use criticism on the Force Against mistake text, since even after I cut it down to what it is now, it's still really long.
I'm not sure what we want to do with the non-tank + no-debuff tower trigger, since #4530 is still floating around. I would be okay removing it, but it's going to be moderately important once this is released for Unreal.
> oopsy: Sephirot EX

- ui/raidboss/data/06-ew/hunts/thavnair.ts
- ui/raidboss/data/06-ew/hunts/ultima_thule.ts
[yilan 2022-07-30 11-24-21.webm](https://user-images.githubusercontent.com/37621276/181867570-f30920a8-fb59-453c-aa1f-718fcb0d1054.webm)
Not all players gain directional march effect. so I think it would be better if there was an alarm to go outside
[Fan Ail 2022-07-30 11-17-32.webm](https://user-images.githubusercontent.com/37621276/181867682-0a712161-68f8-4e4a-b4af-9a63c93951a9.webm)
In fact, the direction of Fan Ail is fixed when the divebomb marker appears, so you only need to avoid front of that.
> raidboss: fix some ew hunts triggers

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt
Adds targetable and untargetable lines for p6 and p7.
Made with make_timeline using my own network log and combined outputs of three timelines each with:
```
-p 71E4:4000 -it 'Dragon-king Thordan'
-p 6667:3500 -it 'Nidhogg'
-p 6667:3500 -it 'Hraesvelgr
```
Adds replacetext with shortened names for Nidhogg and Hraesvelgr: nid and hrae.
> raidboss: DSR p6 and p7 targetable/untargetable lines

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Adds a callout ~~5~~ **3.7** seconds before Mortal Vow occurs.
Will call out Soon (Spread), who has it when it is time to pass, and if it is on you when it is time to pass.
I think 5 seconds is enough time, perhaps it could be shorter. I find it helpful to have a callout even if healer as it helps as a reminder to avoid whoever has it when the time is coming since it can be hectic learning this part of the fight so late.
**EDIT:** Changed to 3.7 as last call should happen after touchdown to avoid triggering early movement into bosses.
> raidboss: DSR add Mortal Vow callout

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
fixes #4664
Removes the P6 and P7 regex captures from DSR Phase Tracker as they are not casted abilities.
Adds DSR Phase Tracker P6/P7 to capture network abilities for the p6/p7 ids.
Changes regex to match Shockwave as indicator for p7.
> raidboss: DSR fix#4664 track p6/p7 by ability trigger

- .github/workflows/release.yml
[actions/create-release](https://github.com/actions/create-release) is no longer maintained.
Switch to one of the listed alternatives and use it to create the release with
autogenerated notes. Removes the need to use a separate step for uploading
assets.
> ci: Autogenerate Release Notes

- resources/user_config.ts
- ui/raidboss/raidboss_config.ts
The config interface is loading everything from the raidboss overlay,
including raidboss.css if defined in the user's user directory. This can
cause some interesting interactions that overwrite style options.
Fixes #4554
> config: Don't Load Raidboss CSS Within Config UI

- ui/jobs/components/drk.ts
- ui/jobs/components/gnb.ts
- GNB: Bloodfest cooldown changes to 120s.
- DRK: Living Shadow duration is reduced. 
And I think it's not necessary to trace its duration, for there is no action to make the Shadow attack quicker.
The duration-cooldown structure is lengthy, I'm thinking about use a util func to instead them like
```
export const showDuration = (o: {
tid: number;
timerbox: TimerBox;
duration: number;
cooldown: number;
threshold: number;
activecolor: string;
deactivecolor: string;
}): number => {
o.timerbox.duration = o.duration;
o.timerbox.threshold = o.duration;
o.timerbox.fg = computeBackgroundColorFrom(o.timerbox, o.activecolor);
o.tid = window.setTimeout(() => {
o.timerbox.duration = o.cooldown - o.duration;
o.timerbox.threshold = o.threshold;
o.timerbox.fg = computeBackgroundColorFrom(o.timerbox, …
```
> jobs: 6.2 changes

- ui/raidboss/data/06-ew/trial/barbariccia-ex.ts
Workaround for a possible timeline trigger issue with tracking Impact. This uses different spell that is also related to the knockback and has a cast time. Using the "standard" 5s timing, although the spell cast is almost the same as the knockback immunity duration.
> raidboss: ex4 switch impact trigger

- util/logtools/fflogs.ts
It's messy, but it does seem to work. Previously, if event data were paginated, the subsequent `callFFLogs()` was being called with the wrong parameter, leading to corrupted + incomplete data being returned.
Separate from that, `Object.assign` was *overwriting* the `events` property on `mergedData`, not concatenating it. This wasn't visible previously due to the pagination bug, but it meant that after fixing that, if data *was* paginated, we would get only the last page of events.
Please do criticize, this is me tossing it in quickly so we can actually use it for the new content.
> util: Fix fflogs.ts pagination handling

- ui/raidboss/data/06-ew/trial/barbariccia-ex.txt
Remove overlapping syncs (e.g. Brutal Rush).
Remove extra syncs that caused extra desyncs.
Remove duplicate names (Boulder Break -> Boulder Break 5s later).
Add names (e.g. Savage Barbery, Secret Breeze for clarity)
Rename some abilities to --sync-- (e.g. Savage barbery, for clarity).
This now passes test_timeline.py.
> raidboss: EX4 timeline improvements

- ui/oopsyraidsy/data/06-ew/raid/p7n.ts
- ui/raidboss/data/06-ew/raid/p7n.ts
- ui/raidboss/data/06-ew/raid/p7n.txt
Nothing much to say on this one. Once I figured out which abilities to ignore the loops weren't too hard to identify.
The proximity marker on Immortals' Obol kills people a lot because it's logarithmic falloff damage, but because it always damages players it's tough to make anything from it.
> raidboss: Pandaemonium 7 normal package

- ui/oopsyraidsy/data/06-ew/trial/sephirot-un.ts
- ui/raidboss/data/06-ew/trial/sephirot-un.ts
- ui/raidboss/data/06-ew/trial/sephirot-un.txt
Largely a matter of find/replace. I finished up the timeline and triggers prior to an attempt at running it, and everything seemed to work okay. The "change to Earth Shakers" that was mentioned in one of the live letters is simply that the targets are now *also* clearly marked with stretchy tethers that turn purple when extended far enough.
Oopsy is untested, but the IDs all match, so I'm comfortable releasing it as it stands.
> raidboss: Add Sephirot Unreal

- package-lock.json
- package.json
Fixes the following error on continuous integration builds with the latest LTS of Node:
> Error [ERR_LOADER_CHAIN_INCOMPLETE]: "ts-node/esm 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
> util: Upgrade ts-node Version

- ui/oopsyraidsy/data/06-ew/raid/p6n.ts
- ui/raidboss/data/06-ew/raid/p6n.ts
The timeline for this encounter has ended up being significantly more obstinate than I would like, so quisquous graciously agreed to take over on that.
I couldn't find *anything* in the network log relating to how Polyominous Dark works. (The radiating AoEs from the totems.) All of the totems have identical NPC models, and the cast ID is the same for all of them. There are no status effects on any of them. All of them have a facing of 0.0 from beginning to end of the cast, whether or not they hit a target.
> raidboss: P6N Initial triggers/oopsy

- ui/raidboss/data/06-ew/raid/p5s.ts
I had used the wrong spellid previously. 7710 is the one to count.
> raidboss: p5s raging claw move use 7710

- ui/raidboss/data/06-ew/raid/p6s.ts
First headmarker (the healer stackmarkers) appears to be 013E. This value will have the numbers be treated with their previous 004F starting point.
Would need to do more research to determine the other headmarkers:
First Exchange of Agonies Markers:
These seem to be dependent on tethers too, but not sure if we need to know the tether information as it looks like there are unique headMarker ids for each:
Pattern 1
0163 x1 Targetted by 786D (Unholy Darkness) Stack
0164 x1 Targetted by 7870 (Dark Burst)
016A x3 Targetted by 7872 (Dark Burst)
0168 x3 Donut
Pattern 2
016A x2 Targetted by 7872 (Dark Burst)
0164 x1 Targetted by 7870 (Dark Burst)
0165 x1 Targetted by 7871 (Dark Burst)
0167 x1 Targetted by 786E (Unholy Darkness) Stack
0168 x2 Donut
016E x1 Donut
Other Markers:
0065 Spread Marker …
> raidboss: p6s Pathogenic Cells headmarkers

- ui/raidboss/data/06-ew/raid/p5s.ts
- ui/raidboss/data/06-ew/raid/p5s.txt
Should fix a missed sync if Searing Ray is cast instead of Raging Claw
> raidboss: p5s add searing ray to timeline

- ui/raidboss/data/06-ew/raid/p5s.ts
- ui/raidboss/data/06-ew/raid/p5s.txt
The targetable line seems to be +- .1s depending on if relative to 7708 or relative to first 7A03, I chose to make it relative to the first 7A03.
Untargetable is relative to the last 7A03.
I retrieved the lines from make_timeline.py.
> raidboss: p5s add targetable/untargetable lines

- ui/raidboss/data/06-ew/raid/p5s.ts
Captures both spellids similar to the normal mode trigger.
> raidboss: p5s add Ruby Glow aoe callout

- ui/raidboss/data/06-ew/raid/p6s.ts
Adds callout for the Exocleaver mechanic and the healer group headmarkers (013E).
Notes:
- ~~Unholy Darkness stack headmarkers are 3.8s before first Exocleavers~~ EDIT: Unholy Darkness stack headmarkers come out same time as first Exocleavers
- Exchange of Agonies headmarkers are ~~7~~3s before second Exocleavers
> raidboss: p6s Exocleaver Move + Healer Groups

- ui/raidboss/data/06-ew/raid/p6s.ts
Small comment for clarity of the trigger, and enumerated marker ids if they ever come up again. My logs did not have donut exchanged to stack or stack exchanged to donut, so I took an (easy) educated guess for which was which given that I had the other 7.
> raidboss: Add P6S Exchange Comments

- ui/raidboss/data/06-ew/raid/p7s.ts
Since the Close and Far ones are static, they may be better done with a timeline trigger for pre-positioning.
> raidboss: p7s Bough of Attis (arrows) callout

- ui/raidboss/data/06-ew/raid/p7s.ts
Adds code for getting headmarkers in this encounter and a trigger for healer groups. It appears it is using the same 013E marker from p6s.
Spread markers that I have seen in this fight are using 008B.
5s Timer marker appears to be 00A6.
> raidboss: p7s Hemitheos's Holy III Healer Groups

- ui/raidboss/data/06-ew/raid/p7s.ts
The cast on this one is strange, fflogs showing it is canceled, castTime appears to be ~5s, and the ability goes off 26s after start of cast. This adds a ~5s notice for the aoe.
Also to note, strats may vary, but arguably it could be earlier call out such as get middle, big aoe because as far as I am aware, all strats require changing platform between purgations. **EDIT:** Updated to reflect such.
> raidboss: p7s add Light of Life bigAoe

- ui/raidboss/data/06-ew/raid/p7s.ts
Adds a headmarker-based callout for the Inviolate Bonds and Inviolate Purgation mechanics utilizing previous triggers. **EDIT:** This effectively gives a 6s notice, which by then the player should already be headed to or on the platform.
Note: Previous triggers are relying on 4/4 support/dps party and purgation relies on 8-player party, so these may not function properly in non-standard party...
> raidboss: p7s Inviolate Bonds/Purgation Reminders

- ui/raidboss/data/06-ew/raid/p6s.txt
```
334.6 "Aetheronecrosis 3" sync / 1[56]:[^:]*:Hegemone:7877:/
334.8 "Dual Predation" sync / 1[56]:[^:]*:Hegemone:7878:/
335.8 "Predation 1" sync / 1[56]:[^:]*:Hegemone:(787A|787B):/
338.7 "Aetheronecrosis 4" sync / 1[56]:[^:]*:Hegemone:7877:/
```
When I initially wrote this, I assumed that since every ability was more than 2.5s apart, everything was fine. However, Aetheronecrosis 3 looks ahead enough to sync with an early fourth usage immediately after Predation 1. Because of this, it's possible to be behind by about 3-4 seconds during the rest of the Predation usages. It's not always going to happen, but when it does, it looks like this:
```
334.568: Matched entry: 334.6 Aetheronecrosis 3 (+0.032s)
334.865: Matched entry: 334.8 Dual Predation (-0.065s)
335.737: Matched entry: 335.8 …
```
> raidboss: Fix P6s Cachexia 1 timeline

- ui/raidboss/data/06-ew/raid/p8s.ts
Just to avoid incorrect directions, temporarily call out just away/follow.
See: #4835
> raidboss: p8s temporarily disable crush/impact direction

- ui/raidboss/data/06-ew/raid/p8s.ts
Originally needed delay to get correct data even after OverlayPlugin update, however it turns out this mechanic only has results of 0 or 1 and since the boss starts at 0, we can safely assume non-0 is south.
Fixes #4835
> raidboss: p8s fix initial impact/crush

- resources/timerbar.ts
- ui/raidboss/skins/jwidea/jwidea.css
- ui/raidboss/skins/lippe/lippe.css
Using [parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), you can override parts of custom elements. Hopefully this will alleviate some of the necessary touching of TypeScript components and allow users to completely override via CSS in their user raidboss.css file instead.
> raidboss: Allow Skins to Override Timerbar Elements

- resources/netlog_defs.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
Also, clean up some comments while I'm here.
The raidemulator will currently generate all non-ffxiv plugin lines with "Unknown" prefix which should not match anything.  A followup fix could prevent it from generating these lines at all (making converted line optional or skipping it later), but it shouldn't cause any problems to have it here.
> resources: add source to netlog_defs.ts

- ui/raidboss/data/06-ew/raid/p8s.ts
The bird/snake casts should always happen first by a second or two, but sometimes their names are incorrect.
Fixes #4828.
> raidboss: fix p8s flameviper/tetraflare combo trigger

- resources/netregexes.ts
This will make it possible to have the log guide have regexes for things that don't have built-in cactbot regexes automatically by using this helper.
This also changes the default "error name" for NetRegexes to match the NetMatches type in most cases, and at least be capitalized in others.  This is cosmetic and only shows up in errors.
> resources: build NetRegexes from helper in most cases

- ui/raidboss/data/06-ew/raid/p7s.ts
Sometimes roles don't work and so this can cause bugs. This only considers individual debuffs.
Borrowed/modified from valarnin's comment here:
https://github.com/OverlayPlugin/OverlayPlugin/issues/60#issuecomment-1250426209
> raidboss: make P7S inviolate purgation not use roles

- ui/raidboss/data/06-ew/raid/p8s.ts
Adds three callouts:
- A silent counter
- An audible Bait and Tower number
- Soak Tower when safe to move
The Counter is based on Tyrant's Fire III (75F0). The Soak Tower is based on Tyrant's Flare II (7A88) puddles, it could have been just a delayed trigger from the Tyrant's Fire III, but possibly this is a cleaner solution for timings?
> raidboss: p8s Limitless Desolation Callouts

- ui/raidboss/data/06-ew/raid/p8s.ts
Adds a callout for all and a reminder.
It looked like the targetX and targetY data of the 793D and 793C spells could be used to resolve this without OverlayPlugin.
> raidboss: p8s Blazing Footfalls directions

- resources/outputs.ts
- resources/responses.ts
- ui/raidboss/data/06-ew/hunts/elpis.ts
- ui/raidboss/data/06-ew/hunts/mare_lamentorum.ts
- ui/raidboss/data/06-ew/hunts/ss_rank.ts
- ui/raidboss/data/06-ew/hunts/thavnair.ts
- ui/raidboss/data/06-ew/hunts/ultima_thule.ts
- ui/raidboss/data/raidboss_manifest.txt
- ui/raidboss/popup-text.ts
This also includes a few fixes to make these triggers work better:
* target-less tankbusters (b/c there's too many people around) are now handled
* `resetWhenOutOfCombat: false` now properly sets `inCombat` rather than just ignoring changes to combat
* to avoid clearing any stored `data` fields when engaging a mob, set `resetWhenOutOfCombat: false` in a few places
> raidboss: add s-rank hunts

- ui/raidboss/skins/jwidea/jwidea.css
- ui/raidboss/skins/lippe/lippe.css
`rgba(r g b / a%)` needs a slash in it.
Closes #4859.
Fixes #4857.
> raidboss: fix skin colors not working properly

- resources/timerbar.ts
- ui/raidboss/raidboss.css
- ui/raidboss/timeline.ts
Change timerbar CSS from `background-color` to `background` shorthand to allow for more options within a skin.
> raidboss: Allow Skins to Use CSS Background

- resources/user_config.ts
For users using the `OVERLAY_WS` query parameter, the value could contain forward slashes, which causes a failure to load skin CSS. This wasn't an issue when the CSS was directly in timerbar.ts.
Fixes https://github.com/quisquous/cactbot/issues/4868
> raidboss: Fix Skins CSS for OVERLAY_WS

- ui/raidboss/raidemulator.ts
close https://github.com/quisquous/cactbot/issues/3247
currently the final file of emulator's service worker script is named by chunk name `[id].bundle.js`, and its id is curretnly 378, so webpack will generate a service worker file with meanless filename `378.bundle.js` in `dist/` .
set `webpackEntryOptions: { filename: "ui/raidboss/raidemulator.worker.js" }` so it will be generated to `dist/ui/raidboss/raidemulator.worker.js`
> build: stabilize emulator service worker's output filename

- package-lock.json
- package.json
- webpack/loaders/timeline-loader.ts
- webpack/webpack.config.ts
timeline is now parsed at runtime and currently `timeline-loader` do nothing, so no need to keep `timeline-loader`, just use `raw-loader`
also, `raw-loader` is deprecated in webpack5.
> build: remove timeline loader

- package-lock.json
- package.json
Recent versions (>9.3.0) of `ts-loader` implicitly disable the compiler options for declaration and declarationMap when the Fork TS Checker Webpack Plugin is being used (non-CI environments).
This improves my local build times from ~40 seconds to ~15 seconds. There are faster options overall (esbuild-loader was one potential option), but this seemed fairly low-risk.
> build: Upgrade ts-loader Package

- webpack/webpack.config.ts
As OverlayPlugin was upgrade to CEF v95 for a long time, we can increase the target version to 95 for some newer javascript syntax as they might shorter cause a smaller bundle.
> build: increase target version in webpack build

- ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.txt
- ui/raidboss/data/06-ew/raid/p5n.txt
- ui/raidboss/data/06-ew/raid/p7n.txt
- ui/raidboss/data/06-ew/trial/barbariccia.txt
From https://github.com/xpdota/event-trigger/issues/130
The problem is that if a user enables "Hide chatlog for privacy" in the parsing plugin OR is simply chainpulling with no countdown, and a timeline doesn't have any valid initial sync other than that (i.e. sync with a large enough window to be valid for 0.0), then the timeline will just never start.
I looked at also just using OP's combat start to start the timeline, but this doesn't necessarily work for timelines where the actual contents don't start at 0.
> raidboss: Ensuring timelines have a non-chatlog initial sync

- .github/workflows/build-artifact.yml
- .github/workflows/css-lint.yml
- .github/workflows/javascript-lint.yml
- .github/workflows/labels.yaml
- .github/workflows/lint-pr-title.yaml
- .github/workflows/markdown-lint.yml
- .github/workflows/post-process.yml
- .github/workflows/python-lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update-gh-pages.yml
- .github/workflows/update-triggers-branch.yml
bug of `actions/checkout@v2` is fixed in v3 I think, using v3 for a while, didn't get wrong commit checkout.
And it only fetch depth=1 by default to avoid fetching all commits https://github.com/quisquous/cactbot/issues/4865 , take 2m to 2s.
> ci: upgrade actions checkout to v3

- package-lock.json
- package.json
- tsconfig.json
- types/event.d.ts
Enabling the lib check has two errors, one in event.d.ts which is easily fixed.  The other is in globby, due to import node:url.
Error:
```
node_modules/copy-webpack-plugin/node_modules/globby/index.d.ts:1:19 - error TS2307: Cannot find module 'node:url' or its corresponding type declarations.
```
This is fixed by upgrading @types/node.  Upgraded to the latest version, not to a specific version.
Closes #4882.
Closes #4885.
Closes #4880.
> build: enable lib check, upgrade @types/node

- .github/workflows/release.yml
Error: Unable to resolve action `microsoft/setup-msbuild@v1.1.1`, unable to find version `v1.1.1`
This was broken by the version change in #4892.
> build: revert setup-msbuild version change

- docs/LogGuide.md
- resources/netlog_defs.ts
- resources/netregexes.ts
- resources/regexes.ts
- util/gen_log_guide.ts
Added support in netlogs_defs and regexes/netregexes for new MapEffect (257) lines, along with some updates to LogGuide.  
There are dependencies both on the ACT FFXIV Plugin being updated to v2.6.6.7 (which adds processing support for these lines), and on an update to OverlayPlugin to  re-add support for these lines that was disabled in v0.19.6.  Marking this as draft for now until these dependencies are resolved.
> resources: support for mapeffects

- ui/raidboss/popup-text.ts
Calling `getDataObject` returns a `RaidbossData` that does not have `initData` called on it.  Prior to this patch, when entering combat, `data` would be set to a new `data` object but without `initData` called on it.
This isn't a larger issue because if `resetWhenOutOfCombat` is true, then `this.Reset()` is called again in `SetInCombat`, fixing the issues.  This only is an issue for the s-rank hunts in Thav and Mare that have this flag set.
To avoid this problem in the future, always have `getDataObject` return a properly initialized object.  To fix the short-term issue, update `this.data.inCombat` directly without calling `getDataObject` (oops).
> raidboss: fix entering combat resetting `data`

- ui/raidboss/data/06-ew/raid/p8s.ts
- ui/raidboss/popup-text.ts
Utilizes new MapEffects regex to determine the color of the tower and then existing debuff trigger to determine who to merge with. Will merge Long Debuffs together and Short Debuffs + Stack Players together.
This is a draft for now. Still need to fixup  HC2's non-debuff players and the two color towers.
> raidboss: p8s HC1/HC2 Tower Colors + Merge Targets

- .eslintrc.cjs
- resources/player_override.ts
- types/global.d.ts
- types/trigger.d.ts
- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.ts
this rule force to import shortest path, like `types/trigger.d.ts` should import  `./net_matches` not `../types/net_matches`
autofix available
> lint: add eslint rule `import/no-useless-path-segments`

- resources/netregexes.ts
- ui/pullcounter/pullcounter.ts
- ui/raidboss/emulator/EmulatorCommon.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/timeline.ts
- util/logtools/encounter_tools.ts
Bug report: go to <https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html>
```
Uncaught ReferenceError: Cannot access 'NetRegexes' before initialization
at buildRegex (netregexes.ts:163:56)
at NetRegexes.network6d (netregexes.ts:379:12)
at <static_initializer> (netregexes.ts:414:22)
at 622 (netregexes.ts:159:27)
at __webpack_require__ (bootstrap:19:1)
at 456 (responses.ts:584:1)
at __webpack_require__ (bootstrap:19:1)
at 266 (player_override.ts:66:8)
at __webpack_require__ (bootstrap:19:1)
at startup:4:1
```
Reverts quisquous/cactbot#4946
> resources: Revert: use a shared wipe net regex

- ui/raidboss/raidboss_config.ts
This was causing errors on triggers that had both `type` and a regular expression `netRegex` (which is most of them).
> config: fix raidboss config not listing zones

- .github/scripts/npm-package.cjs
- .github/workflows/release.yml
- .npmrc
`.github/scripts/npm-package.cjs` will create a `.npmrc ` in `npm-package/.npmrc` so release script will work.
> ci: fix for yarn user

- test/helper/test_timeline.ts
- ui/raidboss/common_replacement.ts
This would break on the eureka_hydatos version:
`netRegex: { line: '.* will be sealed off.*?', capture: false },`
This patch allows this to be translated properly.  However, this patch doesn't change the trigger itself because more work needs to be done on message vs gamelog etc before using the parameter version.
> raidboss: Fix seal common translation for param netRegex

- resources/netregexes.ts
- test/helper/test_trigger.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
`NetRegexes.ability` match NetworkAbility and NetworkAOEAbility, but `buildRegex('Ability', ...) ` only match NetworkAbility 
Add a function `buildNetRegexForTrigger` to dispatch ability trigger to use `NetRegexes.ability` to build regex
should fix https://github.com/quisquous/cactbot/issues/4984
> raidboss: fix `NetRegexes.ability` is alias

- tsconfig.json
I think [you are right](https://github.com/quisquous/cactbot/pull/4938#issuecomment-1287938337) here about source map and source file, I forget to enable `inlineSources` in tsconfig so source file is not included in source map, so it's actually broken.
> build: include source in sourcemap

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Calls out the player's brand number which quadrant to start at during Infern Brand 2 and. This is done by checking where the player's Brand debuffs match the orange and blue flame's brand numbers.
First player will receive call to cut based on receipt of First Flame debuff. Once an Infern Brand has lost its brand number (a player cut the flame), the next player in line gets the call to cut their flame number.
Utilizes timestamp of Cryptic Flame hit that applies Magic Vulnerability Up to compare with timestamp of the flame that was cut before player's turn to cut to ensure there is delay added if necessary for a safe quick cut.
> raidboss: ASS add Infern Brand 2 triggers

- package-lock.json
3.4.2 has the required changes.  Updating to 3.4.8 just as that's the latest and it seems to work locally in testing.
See: #5009
> build: update memfs dependency for node 18

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
The call is correct when it's flipped like such.
There was also an issue with handling of First Flame's second cut which this now fixes the timing. The trigger basically checks that the color being cut is the same color that was last cut, which is only true for players 2-4.
Fixes #5002
> raidboss: ASS Infern Brand 2 fixes

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
During the final boss, Banishment is the mechanic that happens between Infern Brand 3 and Infern Ward 4. I have seen multiple strategies for this mechanic, some simpler than others.
It looked to me like there was an invisible debuff, B9A, that has its count field that correlates to the portal animation that the player has, so this can be used to make triggers for where to position to solve the mechanic. I compared raid_emulator with positioning I have in a log and created the mapping.
I also added two additional triggers for baiting the wards. I was not sure they are both necessary, I know the first one can be a bit more trickier as it has extra time before the bait and at least two players are likely to have been teleported in such a way that they need to move to not trigger an Infern …
> raidboss: ASS add Banishment triggers

- package.json
close https://github.com/quisquous/cactbot/issues/5021
> lint: add missing ts file extention to husky dprint

- dprint.json
- package-lock.json
- package.json
`@dprint/json` just released a new version, dprint now can use plugin downloaded by npm
> lint: use dprint json plugin from npm

- .eslintrc.cjs
- package-lock.json
- package.json
- resources/datetime.ts
- resources/languages.ts
- resources/responses.ts
- resources/stringhandlers.ts
- resources/user_config.ts
- test/helper/test_manifest.ts
- test/helper/test_trigger.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/data/04-sb/dungeon/bardams_mettle.ts
- ui/oopsyraidsy/data/05-shb/eureka/delubrum_reginae.ts
- ui/oopsyraidsy/data/05-shb/eureka/delubrum_reginae_savage.ts
- ui/oopsyraidsy/death_report.ts
- ui/oopsyraidsy/oopsy_common.ts
- ui/pullcounter/pullcounter.ts
- ui/raidboss/data/03-hw/dungeon/gubal_library_hard.ts
- ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.ts
- ui/raidboss/emulator/data/LogEventHandler.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1F.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x26.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
- util/logtools/anonymizer.ts
- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
`String.substr` is not a standard API, replace them with `String.slice`.
add `@typescript-eslint/prefer-string-starts-ends-with` and `unicorn/prefer-string-slice`
both autofix available
> lint: add rule for string substr

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Hells' Nebula is an ability done by trash mobs between the first and second boss in ASS and ASS(S) that reduces all players' HP to 1.  There is no follow-up Doom debuff or other such mechanic that requires immediately topping up players' health, other than the next source of raidwide damage which is approximately 10s later.  This trigger provides a heads-up callout for the HP reduction.
There was a question if a trigger for this ability was useful when merging the initial ASS triggers, so this pull request is made in isolation so it can be rejected if undesired.
> raidboss: ASS/S add Hells' Nebula trigger

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
King's Will is an ability done by trash mobs between the first and second boss in ASS and ASS(S) that gives the mob a 100% physical damage increase for the next 12s.  In Savage, this causes the mob's auto-attacks to increase from ~33k per hit to ~66k per hit, effectively becoming mini-tankbusters.  This trigger provides a heads-up callout to the tank or healer for the incoming damage.
There was a question if a trigger for this ability was useful when merging the initial ASS triggers, so this pull request is made in isolation so it can be rejected if undesired.
> raidboss: ASS/S add King's Will trigger

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Had a few instances where the Silken Puff would cast Squeaky Clean instead of Silkie.
[18:09:51.371] StartsCasting 14:4001B920:Silkie:7752:Squeaky Clean:4001B920:Silkie:4.200:-335.01:-170.00:471.00:3.14 [18:09:51.371] StartsCasting 14:4001B92D:Silken Puff:7756:Squeaky Clean:4001B92D:Silken Puff:8.900:-331.00:-159.00:471.00:0.00 [18:09:51.371] StartsCasting 14:4001B92E:Silken Puff:7754:Squeaky Clean:4001B92E:Silken Puff:7.400:-347.00:-159.00:471.00:0.00 [18:09:51.371] StartsCasting 14:4001B92F:Silkie:7753:Squeaky Clean:4001B92F:Silkie:5.700:-341.51:-165.65:471.00:2.50
> raidboss: ASS Squeaky Clean cast

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Not sure why, but it seems like even though the mob name is Aqueduct Armor in-game it shows up as Sil'dihn Armor in logs (at least over multiple pulls i've noticed.)
[20:40:22.000] ChatLog 00:282B::The Sil'dihn armor readies Hells' Nebula. [20:40:22.743] StartsCasting 14:40014A89:Sil'dihn Armor:796C:Hells' Nebula:40014A89:Sil'dihn Armor:3.700:-53.12:-213.06:517.50:-1.56
[20:40:33.781] StartsCasting 14:40014A89:Sil'dihn Armor:796B:Infernal Weight:40014A89:Sil'dihn Armor:4.700:-63.80:-207.57:517.50:-0.77 [20:40:33.000] ChatLog 00:282B::The Sil'dihn armor readies Infernal Weight.
[20:40:39.908] StartsCasting 14:40014A89:Sil'dihn Armor:796A:Dominion Slash:40014A89:Sil'dihn Armor:3.200:-63.80:-207.57:517.50:-0.77 [20:40:39.000] ChatLog 00:282B::The Sil'dihn armor readies Dominion Slash.
> raidboss: ASS 2nd trash fix

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
re: #5051 Mob name changed from Aqueduct Armor in 6.25 to Sil'dihn Armor in 6.28.
Translated names may need adjusting too?
> raidboss: ASS(S) mob name change

- resources/util.ts
- test/unittests/util_test.ts
As of Endwalker (6.0), Sleep is now a role action for all magical ranged dps jobs.
> resources: update Sleep to role action

- util/logtools/make_timeline.ts
It seems that entirely unused params are `undefined`, and params without a value (e.g. `-f` on its own) are `null`.
I'm not sure when this changed, but the types are wrong in this file now in multiple places.
Fixes #5073.
> util: handle undefined params in make_timeline.ts

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
Reverts changes to this trigger in #5036 and removes `source` from netRegex to account for the fact that this ability can be used sometimes by an invisible actor.  
Closes #5064
> raidboss: fix abilityid for ASS/S Slippery Soap

- package.json
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.ts
- ui/raidboss/html_timeline_ui.ts
- ui/raidboss/raidboss.ts
- ui/raidboss/timeline.ts
- util/test_timeline.ts
Refactor TimelineUI into HTMLTimelineUI and base class TimelineUI.  This puts HTMLTimelineUI in its own file so it's possible to run test_timeline without including dom.
> raidboss: refactor TimelineUI to not include HTML elements

- util/test_timeline.ts
The drift is from the time value itself, not the window. Additionally, changing the colors to green/yellow/red.
> util: adjust test_timeline drift time/colors

- util/index.ts
- util/test_timeline.ts
There's many things that make sense to run from `npm run util` but make and test timeline both have a lot of parameters and are more suited for command-line repeated iteration with the same / edited parameters.
Rather than supporting two paths for all of the parameters, only support command line args, removing a bunch of code.
This makes it possible to run `ts-node util/test_timeline.ts` directly now.
> util: remove index.ts path from test_timeline

- util/logtools/fflogs.ts
- util/logtools/make_timeline.ts
There's a bunch of logic that goes into stitching together data from fflogs.  Move this to a shared place and use a data structure that's less tied to make_timeline to return data.
> util: refactor fflogs parseReport for sharing

- util/logtools/make_timeline.ts
I broke this with some last minutue "cleanup" in #5075 and neglected to test these final few changes enough.  Oops, sorry.
> util: fix make_timeline ignoring all entries

- util/logtools/fflogs.ts
- util/test_timeline.ts
This also fixes a bug in test_timeline's `testLineEvents` where it was not setting the time before processing a log line. Normally, time advances linearly with a timer and ticks periodically, and this causes the set of active syncs to be updated.  For test timelines, there's no such timer, so the current time needs to be set prior to processing the log line or the set of active syncs will be stale.
This is not an issue for `-f` style logs, as there's usually enough log lines to update the time appropriately.  However, for fflogs that only include boss abilities, this causes many incorrect stale syncs.
Additionally, it seems unnecessary to sync after every long line, which might create incorrect timings.  If the sync occurs because a regex matches, then the time will be updated as needed.
> util: add fflogs support to test_timeline

- docs/OopsyraidsyGuide.md
- docs/RaidbossGuide.md
- types/oopsy.d.ts
- types/trigger.d.ts
- ui/config/config.ts
- ui/raidboss/data/00-misc/the_masked_carnivale.ts
Implements an optional `zoneLabel` property for trigger sets.  Allows for providing a custom zone name for use in the configuration UI.
Supports translated strings.
re: https://github.com/quisquous/cactbot/issues/5083#issuecomment-1313122130_
> config: implement zoneLabel property

- util/test_timeline.ts
This only logged timeline triggers, which isn't particularly useful to track.  Instead, make this tool only about whether the timeline conforms to a log file or not.
> util: remove test_timeline logging of triggers

- util/logtools/test_timeline.ts
It uses encounter_tools/encounter_printer/fflogs/arg_parser and moving it there matches make_timeline.
> util: move test_timeline into util/logtools

- ui/config/config.ts
- ui/raidboss/data/03-hw/deepdungeon/the_palace_of_the_dead_general.ts
- ui/raidboss/data/raidboss_manifest.txt
Adds general triggers for the Palace of the Dead deep dungeon.
Includes general triggers that are applicable to all PotD floor sets.
Continuation of #5083
> raidboss: initial triggers for the Palace of the Dead

- resources/party.ts
For some reason, `healerNames` getter was already defined but not used.  This updates `otherHealer` to be consistent with `otherTank`.
> resources: use healerNames getter

- ui/raidboss/common_replacement.ts
Not sure when this broken, but it does wrong replace in current version for the translation having the text before the arena name ($1), like (cn lang for example):
- `^^00\|[^|]*\|0839\|[^|]*\|Something will be sealed off.*?\|` -> `^^00\|[^|]*\|0839\|[^|]*\|距Something被封锁还有.*?\|` (✔)
- ` 00:0839::Something will be sealed off` -> `距 00:0839::Something被封锁还有` (✘)
- `Something will be sealed off` -> `距Something被封锁还有` (✔)
- `00|2022-11-27T21:27:47.4638235+08:00|0839||Something will be sealed off` -> `00|2022-11-27T21:27:47.4638235+08:00|0839||距Something被封锁还有` (✔)
This PR add `:` in the regex for matching the area name in parsed log line to fix this issue, it should affect the triggers/timelines which using parsed log line to sync.
> raidboss: fix broken sync key translation replace

- ui/raidboss/data/05-shb/raid/e2n.txt
- ui/raidboss/data/05-shb/raid/e7n.txt
- ui/raidboss/data/05-shb/raid/e8n.txt
Eden 7's change isn't that important, but it's an improvement, so I threw it in.
Eden 2 and 8 have had sync issues since before the start of Endwalker. Voidwalker's update should be self-explanatory. I'm still not sure where the Shiva sync issues come from, but on multiple occasions things have desynced by 3-5 seconds during the first phase. When I originally put this timeline together, player DPS was *far* too low to even think of breaking the timeline, so I never bothered to add safety sync windows.
> raidboss: Eden Normal timeline improvements

- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
- ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
This is subjective, but I find this style of instructions much easier to read and understand.
I asked a few people about this, and nobody is thinking about absolute north during this mechanic, and so "go east" when everybody is looking at the gladiators requires a lot more thinking.
I also understand that there is some ambiguity in "go left 1, right 2" (is it saying you need to go 2 the left or is the left one blinking 2 so you go 2 to the right, but hopefully the word "go" there makes it more obvious?)
> raidboss: ASS/S simplify Rush of Might 1

- ui/raidboss/data/03-hw/raid/a7s.txt
The current text of the zone seal seems to be `[12:34:56.789] ChatLog 00:0839::The electrocution gallery will be sealed off in 15 seconds!`. This PR updates the timeline file accordingly.
> raidboss: Fix zone seal message for a7s timeline

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Something I've noticed during reclears is that the healers do not get a buster callout for the RNG busters that occur during Wyrmsbreath 1 and 2, even though it would benefit healers to know where to quickly use their single target mitigation so they have more time to get to the right spot. I did not include healers in the callout for tanks apart, since obviously the healers will have their own positions during those mechanics.
> raidboss: include healers in DSR p6 rng buster callouts

- ui/oopsyraidsy/buff_map.ts
6.3: BRD Nature's Minne changed from single target to party-wide buff.
> oopsy: 6.3 buff updates

- ui/raidboss/data/03-hw/trial/sophia-ex.txt
- ui/raidboss/data/06-ew/trial/sophia-un.ts
- ui/raidboss/data/06-ew/trial/sophia-un.txt
- util/sync_files.ts
This should resolve the issues I noticed when clearing Unreal last night. I changed over the sync window for the fixed Thunder II at 328,, since it overlapped with the random one at 291. The end of the rotation block has had the jump point changed because Execute is a better anchor point than Quasar. (Multiple times last night I saw the jump sync fail, so this should resolve that.)
> raidboss: Sophia EX/Unreal fixes

- ui/raidboss/data/06-ew/alliance/euphrosyne.ts
Nophica's Matron's Harvest raidwide has a second ID that is used second and sometimes third in the fight.
> raidboss: Euphrosyne Matron's Harvest additional ID

- util/sync_files.ts
This makes it so running sync_files is a no-op and doesn't require lintfix.
> util: split on CRLF and not just LF in sync_files

- ui/raidboss/data/06-ew/alliance/euphrosyne.ts
The condition for the Rondel trigger can potentially run before `haloneIceDartTargets` is fully populated, leading to a situation where a player is simultaneously instructed to spread and stack. Because `condition` evaluates prior to `delaySeconds`, we have to move the condition in-line and return if it's met.
> raidboss: Fix Euphrosyne boss 3 stack + spread call

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
Using fflogs logs from Kindred and a few other public logs that have enrage spells and timings to generate an initial timeline for p4-p6.
Patch timings likely need to be updated. Targetable/untargetable were manually added from first hit in logs, so will need to be adjusted.
There are multiple spells with names Wave Cannon, Cosmo Meteor, and Cosmo Arrow spells in p6. I clarified some of the spells in the timeline. Ignoring a spell that's named Inhale (7E51) and the propagating Wave Cannon Exaflares (7BAE).
I was not able to test this.
> raidboss: add p4-p6 initial timeline

- ui/oopsyraidsy/data/06-ew/ultimate/the_omega_protocol.ts
- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
Some adjustments to #5258
* clean up self-targeted / damage lines to only include self-targeted
* use letters for wave cannon to avoid two things with numbers
I thought about numbering the three stacks as well? But that seems like too many numbered things.
> raidboss/oopsy: adjust TOP p4 timeline

- ui/raidboss/data/06-ew/raid/p6s.ts
In some "full uptime strats" like https://youtu.be/03kPYiaWBV8?t=109, players are required to do pre-position according to the buff they gain. It would be useful if Cactbot can remind players instantly whether their buff is forwardCleave or backwardCleave.
> raidboss: Add instant reminder for P6S Transmission

- ui/oopsyraidsy/data/06-ew/ultimate/the_omega_protocol.ts
oopsy doesn't support `initData` and so all of `Data` should be optional.  We should probably treat it as Partial<> internally.
> oopsy: mark TOP data members as optional

- ui/oopsyraidsy/data/06-ew/ultimate/the_omega_protocol.ts
- ui/raidboss/data/05-shb/raid/e1s.ts
- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
- e1s
to avoid being captured by `find-translations`.
> i18n: add ko translations

- ui/raidboss/browser_tts_engine.ts
A followup to #5273, which wouldn't have worked.
Move the event handling external to the initialize function.
Current suspicion is that maybe the onvoiceschanged event only is thrown once but the voices aren't ready yet.
> raidboss: try to fix brower tts take two

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
- Adds a break tether callout for when the magic vulnerability up from the Patch spell expires and duration has <4s remaining.
- Adds callout for tether players for which tower to go to
~~Potential for this to be expanded to call the tower to run to with merging of my other PR #5264.~~
I don't really see it necessary to call the first break here since it happens naturally. For the last set I am not too sure on, I only know that the regression that breaks there changes order. ~~Not sure how these triggers impact P5, might need to condition these to only run in P3?~~ **EDIT:** P5 Uses different effectIds for its Local and Remote Regressions, but the same Magic Vulnerability debuff is used with Patch.
> raidboss: p3 add some tether triggers

- .gitattributes
Due to file-ending handling, the original font **distributed** incorrectly and was unusable. This *should* correct the problem in future releases.
> raidboss: fixed corrupt font file in dorgrin's skin

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
I adjusted the p5 timeline from a log offered on discord.
Some of my notes:
Delta:
- Add 7AFA - Fists' Explosion spell
- Add 7B94 - Swivel Cannon (There is probably another one missing, but of the 5 logged encounters on discord they each had 7B94)
Sigma:
- Missing Solar Ray casts
- Adjusted Targetable/untargetable
- Add 7B98 Program Loop
- Unsure on 7B14 and 7B16...
- Add 7B73 Wave Cannon
- Add 7B8F Rear Lasers x14 (ignore 7B90)
Omega:
- Adjust Targetable/untargetable
- Sync to first melee attack and ignore rest of melee attacks from omega-m (7C02)
- Add additional spells 7B2D, 7B2A, retimed
- Ignore blasters 7E76 and 7B99
- Didn't see 7B43
> raidboss: p5 timeline adjustments

- ui/pullcounter/pullcounter.ts
Currently `/echo pullcounter reset` does not work for this I guess?
Use case: When I do A or S-rank hunts with full-party, seems the counter increases, which is useless for me. To reset this, I need to edit the JSON file directly.
> pullcounter: make able to reset zone counters

- ui/oopsyraidsy/oopsy_live.css
The width of the list can be fixed according to the size of the window, instead of its content.
> oopsy: specify flex props of flex childs

- util/logtools/encounter_tools.ts
Closes #5246.
This is an alternative to #5246 based on the comment from valarin.
> util: fix when the log time is 00

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
The effects are unique for delta, so there wasn't a need to use phase filter.
I think maybe in the future it would say something more for the blue tether players like blue tether with some description about the world they may be with. For certain strats, players are using near world or distant world as a method to say which blue tether pair goes where.
> raidboss: TOP P5 delta tether + beyond defense filter

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
I managed to get a second log of this with different directions, this is what I have found:
7B9B Diffuse Wave Cannon (Attacking North/South), is followed up with 7B78
7B9C Diffuse Wave Cannon (Attacking East/West), is followed up with 7B77
7B79 is always the damage in all 4 cases.
Duration is not needed because the 7B79 happens when the cast of 7B9B, 7B9C, 7B78, or 7B77 end.
> raidboss: TOP P5 Omega adjust Diffuse Wave Cannon

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
The logs seem a bit strange on this one. Omega-M which casts Discharge, is seen as casting the spell but Omega-F is what readies it. Unsure if this is capturing the correct npc model.
> raidboss: TOP P5 Sigma Staff/Feet Call

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Adds callout for the card/intercard Omega-M jumps to.
Fflogs seems to show that the same npc that casts Omega-M moves to the card/intercard, so assuming that is correct this may just need its delaySeconds tested to see how early the data is available.
> raidboss: TOP P5 Sigma Omega-M location

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
This is mostly just to make the timeline a little more brief so that it's much more obvious when mit needs to be hit for important abilities during the phase.
> raidboss: TOP remove some abilities from p6 timeline

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
There is an AddCombatants that occurs either before or shortly after the 8015 Run Dynamis: Omega Version cast starts. This utilizes OverlayPlugin, which the other two triggers still pull data from.
Previous PR did not have delay and so did not fire if the combatants were added late per the log line. Alternatively, this trigger can fire off a collection of AddCombatants that match the BNPCIds, but some care would need to be accounted for if they happened to be added before the Omega Version cast starts since that is also what triggers the 'omega' phase. Basing on AddCombatants (if this line varies) could also make a durationSeconds more varied. So I have stuck with the 8015 cast for now and may test different delays.
> raidboss: TOP P5 Omega Earlier Safe Spot Call

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
This changes the generic `safeSpot` output into `legsShield`, `legsSword`, and `staffShield` as a feature request for people who want to make their output say "In (by M)" or call out the full pair "legs shield".
Additionally, this does a little cleanup:
* make more variables const where possible
* add a helper function for duplicated staffSwordMid helper
* clean up combo text generation for step 1
* rearrange code to match comments better
> raidboss: TOP adjustments and cleanup for omega dodges

- ui/config/config.ts
This will make it easier to store options per trigger set and reuse the same ConfigEntry ui builder code.
> config: refactor ui building to support option paths

- resources/user_config.ts
- ui/config/general_config.ts
- ui/eureka/eureka_config.ts
- ui/oopsyraidsy/oopsyraidsy_config.ts
- ui/raidboss/raidboss_config.ts
Most of the time a setterFunc wants to set its own value, so don't make it repeat its own id.  Rearrange the arg order so options is optional.
> config: refactor setterFunc for configs

- resources/outputs.ts
This is a translation mistake. (misunderstood as maximum melee range)
<del>JP is also mistranslated. I can read but cannot write, @MaikoTan </del> Done.
> raidboss: correct translation

- eslint/cactbot-triggerset-property-order.js
- resources/user_config.ts
- test/helper/test_trigger.ts
- types/data.d.ts
- types/trigger.d.ts
- ui/config/config.ts
- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/05-shb/raid/e8s.ts
- ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
- ui/raidboss/raidboss_options.ts
This adds a new `config` entry to trigger sets that can add field entries to the top of the trigger set under the raidboss section in the config ui. Trigger sets must have an id to have any config loaded, saved, or displayed.
Triggers can use `data.triggerSetConfig['optionId']` here to access anything listed in the `config` section by id. The `Data` type for a trigger set can be extended in a way that will type check ids and add field names.
To avoid naming collisions, not all trigger set config values are loaded. Trigger sets get their own config's values loaded implicitly, but if they need to load some other trigger set's values, they can use `loadConfigs` and specify other trigger sets by id.
For backwards compat, `data.triggerSetConfig` contains all saved values (even ones that no …
> config: add config ui for trigger set options

- util/sync_files.ts
There's no script that verifies this was run (oops) and so it was not updated after #5350.
> util: update sync_files to handle trigger set ids

- ui/oopsyraidsy/player_state_tracker.ts
This was broken in #4499. Apparently I had implemented it, but forgot that job was in hex and so the id -> job -> role mapping was incorrect.  Oops.
Fixes #4530.
> oopsy: fix role-based mistake tracking

- .github/workflows/test-sync-files.yml
- package.json
- ui/raidboss/data/03-hw/trial/sophia-ex.ts
> ci: add test for sync_files

- resources/netregexes.ts
- resources/regexes.ts
To quote Discord DMs:
> valarnin: ... is it just me, or is the `ParseHelperType` in `netregexes.ts` just flat out incorrectly defined? I just have no clue how typescript allows it in its current state.
> Consider:
```ts
type ParseHelperType<T extends LogDefinitionTypes> =
& {
[field in Extract<keyof NetFieldsReverse[T], string>]?: string;
}
& { capture?: boolean };
type EmptyType = ParseHelperType<'Ability'>;
type ParseHelperTypeFixed<T extends LogDefinitionTypes> =
& {
[field in keyof NetFields[T]]?: string | string[];
}
& { capture?: boolean };
type CorrectType = ParseHelperTypeFixed<'Ability'>;
```
> valarnin: (in fact, `Extract<keyof NetFieldsReverse[T], string>` evaluates to `never` because all keys of a given `NetFieldsReverse` type entry are numerical and therefore can never be …
> raidboss: Fix ParseHelperType definitions

- ui/eureka/eureka_config.ts
- ui/oopsyraidsy/oopsyraidsy_config.ts
Some setterFuncs were using different variable names. Since `Options` isn't typed very well here, this wasn't obvious. This undoes some of those changes. One thing this would cause is the death report showing up even if it was set to zero.
(Thanks, @g0shu)
> config/oopsy: fix setterFunc changes from #5353

- resources/user_config.ts
For trigger set config ui that has a select box, the default was not being set.  This would only have broken #5367 at this point.
Huge thanks to @Legends0 for a ton of help tracking this down.
> config: fix select type defaults after #5357

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Because the rotation direction depends on which side you have dodged to, it's impossible to write this PR without having the user pick which dodge they are doing.
This promotes the dodge direction to a new option (defaulting to far, since that seems to be the PF approach) and adds in the rotation direction as well.
Because there's an option, there's no longer any combo output strings for staff sword, and the correct one is picked.
> raidboss: TOP add config option + rotation to omega dodge

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
Switching the output strings and increasing the delay makes this consistent.
Fixes #5335.
> raidboss: re-enable TOP Sigma Superliminal/Blizzard

- types/trigger.d.ts
- ui/config/config.ts
- ui/raidboss/popup-text.ts
There was an oversight that configs from user files were not being added to the set of triggersets by id, and so could never be looked up. This meant that only built-in trigger sets could use configs.
This should address that issue.
Fixes #5380.
> raidboss: fix user triggerset configs not loading

- ui/raidboss/popup-text.ts
Some trials (e.g. Hydaelyn, Zodiark) have a set piece staging zone with the same name but a different zone id, e.g.
```
01|2023-05-04T08:04:28.4810000-07:00|404|The Dark Inside|fdb658b6504e7637
01|2023-05-04T08:09:52.4630000-07:00|3E0|The Dark Inside|f9ffe2b0702f8aa1
```
Raidboss was only detecting zone *name* changes and not zone *id* changes, and so it would try to load zone 0x404 (not found, pun not intended) and never switch to 0x3E0 (the real zone).
Fixes #4509.
> raidboss: fix triggers on "first time" trials

- ui/jobs/buff_tracker.ts
- ui/jobs/combo_tracker.ts
- ui/jobs/components/base.ts
- ui/jobs/components/index.ts
- ui/jobs/components/mch.ts
- ui/jobs/components/pld.ts
- ui/jobs/components/sge.ts
- ui/jobs/components/whm.ts
- ui/jobs/constants.ts
- ui/jobs/jobs.ts
- ui/jobs/player.ts
Based on #5389 
This allows us to change the behavior by just edit the version in jobs.ts, instead of changing all the conditions in each jobs module.
> jobs: use ffxivVersion instead of ffxivRegion

- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
There are NPCs that are added at the first Cosmo Arrow that then cast 7BA3 Cosmo Arrow. The position that these NPCs spawn in at or where they start casting at can be used to determine if it is in or out exasquare first.
There are 4 NPCs used for the outer exasquare and two NPCs for the inner exasquare.
The second Cosmo Arrow will use these same NPCs.
This calls initial in/out before any visible aoes. The rest are timed with the ability.
> raidboss: TOP P6 Add Cosmo Arrow Exa Calls

- ui/oopsyraidsy/buff_map.ts
Ability id added in #5416 but should have been effect id.
Fixes #5418.
> oopsy: update veil id again

- ui/raidboss/data/06-ew/trial/golbez-ex.ts
- ui/raidboss/data/06-ew/trial/golbez-ex.txt
A small belated fixup to #5411 to use ability names in the timeline instead of abbreviations to make
it easier for other languages to translate.
> raidboss: translation refactoring for extreme

- ui/raidboss/data/06-ew/trial/golbez-ex.ts
Adjust the timing from castbar-based to when the invisible clones start casting, fixes move callout being a second early.
> raidboss: ex6 fix spark move trigger timing

- util/logtools/test_timeline.ts
This avoids having test_timeline report events as being missed when intentionally jumping over them.
I'm not 100% sure about this implementation, my understanding of this code is still pretty surface level, but it seems to work for me on a few logs I tested it against (mostly my new p9n stuff).
Also not sure if I should do `>=` or `>`. The latter still reports a missed entry for the line you're jumping to, e.g. this:
```
100.0 "foo" jump 200.0
150.0 "bar"
200.0 "foo"
201.0 "baz"
```
would output something like this with `>`:
```
0.000 |    1 | 100.0 "foo" jump 200.0
Missed |    3 | 200.0 "foo"
0.000 |    4 | 201.0 "baz"
```
But with `>=` it outputs:
```
0.000 |    1 | 100.0 "foo" jump 200.0
0.000 |    4 | 201.0 "baz"
```
I'm not sure exactly what the behaviour should be like if you have …
> util: support jumps in test_timeline

- ui/raidboss/data/06-ew/raid/p10n.ts
Small mistake I didn't catch during testing, but changing the Pandaemoniac Meltdown trigger ability id and output means it should look for a 21-line, not the previous 20-line.  Fixed and tested.
> raidboss: fix P10N Pandaemoniac Meldown

- ui/raidboss/data/03-hw/trial/zurvan-ex.ts
- ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts
- ui/raidboss/data/06-ew/raid/p10n.ts
- ui/raidboss/data/06-ew/raid/p12n.ts
- ui/raidboss/data/06-ew/trial/zurvan-un.ts
@quisquous I am not 100% sure for p10n if the translated names will work as they are.
When running through the `translate-timeline`, they will return as "Pandæmonium" with the special "æ" or if this has to be escaped as well 
But i cant avoid errors, its either the translate timeline script does not show correct value but `npm run test` will pass OR (as it is right now) `run test` wont pass (`AssertionError: P10N Pandaemonic Pillars:locale de:missing timelineReplace replaceSync for source 'Pandæmonium': expected false to be true`) and translate timeline will display the correct value.
> i18n: 6.4 translations (continued)

- ui/oopsyraidsy/data/06-ew/raid/p9n.ts
- ui/raidboss/data/06-ew/raid/p9n.ts
- ui/raidboss/data/06-ew/raid/p9n.txt
This is my first attempt at a timeline, so there's probably some issues here.
I've run this with `test_timeline.ts` against 17 different runs that I did and didn't see anything particularly concerning, there's a few abilities that are sometimes about 0.2 seconds off, but for the majority of the logs it's more or less spot on.
I might've gone a little bit overboard with the forking/merging of timelines in the timeline, since the actual casts are about the same either side of the fork, but I decided to leave it in for the first review since I already did the work of splitting it up. Happy to merge it back together, though, if that's preferred, the timeline of this fight is actually quite linear if you ignore the fire vs ice parts.
I did a test run as well with this, and didn't notice …
> raidboss/oopsy: add P9N

- ui/oopsyraidsy/data/06-ew/raid/p11n.ts
- ui/raidboss/data/06-ew/raid/p11n.ts
- ui/raidboss/data/06-ew/raid/p11n.txt
It's done, a little later than everyone else. It's still missing the safespot calls for the illusory adds, since I haven't yet been able to figure out what's going on with those. Overall I'm not terribly happy with the textual choices I made here, but the nature of the mechanics here requires a little more than we normally might want.
> raidboss/oopsy: P11N Initial Package

- ui/raidboss/emulator/data/network_log_converter/LineEvent0x14.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x15.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x17.ts
- ui/raidboss/emulator/data/network_log_converter/LineEvent0x1A.ts
- ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
Just fixing some minor bugs.
1. Emulator didn't reset properly when changing encounters within the same zone, so now it does so explicitly
2. Various lines were `parseInt`-ing hex values without specifying base 16, this wasn't causing any bugs but did make it more annoying to debug and analyze the encounter manually via devtools
> raidemulator: Fix some minor bugs

- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/06-ew/raid/p10s.ts
- ui/raidboss/data/06-ew/raid/p11s.ts
- ui/raidboss/data/06-ew/raid/p9s.ts
P9S will error with `AssertionError: ui/raidboss/data/06-ew/raid/p9s.ts:locale de:no translation for replaceSync ' 104:[^:]*:1($|:)': expected false to be true` if i remove the `'missingTranslations': true,` element
For P10S i am currently missing deobfuscated content for following skills:
```
'Daemonic Bonds'
'Pandaemoniac Turrets'
'Pandaemoniac Web'
'Steel Web'
```
Also for P10S shouldn't it be `Daemoniac Bonds` instead of `Daemonic Bonds`?
> i18n: more 6.4 translations

- ui/raidboss/data/06-ew/raid/p12s.txt
Merging in my own half-finished timeline into #5518.
* adds notes about abilities
* removes some windows that aren't needed
* numbers a few more abilities to make it easier to keep track
* adds in a few missing abilities (e.g. Sample)
* switches a few ids from damage to the self-targeted snapshot ability
> raidboss: some p12s timeline adjustments, notes

- resources/translations.ts
- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/04-sb/eureka/eureka_hydatos.ts
- ui/raidboss/data/06-ew/trial/golbez-ex.ts
This is part of #4986.  Similar to #5452.
`Test Combatant Cast Enable` was manually tested.
> raidboss: convert NetRegexes functions to params

- ui/oopsyraidsy/data/06-ew/trial/golbez.ts
- ui/raidboss/data/06-ew/trial/golbez.ts
- ui/raidboss/data/06-ew/trial/golbez.txt
Tested in raidemulator and a couple of pulls in-game.
Per my comment in #5405 I'll do another PR tomorrow with some basic oopsy stuff as well.
Edit:  Closes #5497
> raidboss: timeline & initial triggers for Golbez (normal)

- resources/netlog_defs.ts
This ensures that split logs will have the correct minimap image, even if the split log does not include the first pull after changing areas.
> util: Set lastInclude: true for ChangeMap

- ui/raidboss/data/06-ew/raid/p11s.txt
All Styx casts hit one more time than was listed.
> raidboss: Adjust p11s timeline to fix miscounted Styx hits

- ui/raidboss/data/06-ew/raid/p10s.ts
Some of the bonds messages (especially bonds1 and bonds4) could use a much earlier warning, so add a custom delay/duration for each of the four different bonds mechanics.
There's also a lot of info that lines up with bonds warnings so bump some priorities around so there's less info overload.
> raidboss: adjust p10s bonds timing, message severity

- ui/raidboss/data/06-ew/raid/p10s.ts
add basic p10s Jade Passage trigger
It would be nice if the position of the laser could be displayed like 'stand on lines' or 'stand in box' refer to the pattern of the floor. but I can't find a way to do it.
> raidboss: add p10s Jade Passage trigger

- ui/raidboss/data/06-ew/raid/p10s.ts
In attempting to clean up messages that don't make sense, e.g. "Partners => Role Stack" I removed the condition check that prevented it from being double called out.
Also, move the counter to the reset location.  This is not a logic change, but it makes sense to have the counter on the cast.
> raidboss: p10s fixups after #5562

- ui/raidboss/data/06-ew/raid/p9s.ts
Adds a one-second delay to the 2nd through 4th 'soak tower' calls during p9s limit cut.
Closes #5566
> raidboss: add delay to p9s limit cut 'soak tower' alerts

- ui/raidboss/data/06-ew/raid/p10s.ts
This uses the AddCombatant log lines instead of cast since it comes sooner.
Just based on the y values and not having tested in game, largest y value I assume is the lines, so using a map to quickly determine from one of the Arcane Spheres where it is located.
Boxes:
88.00
92.00
96.00
100.00
104.00
108.00
112.00
Lines:
86.00
90.00
94.00
98.00
102.00
106.00
110.00
114.00
This is also assuming the data in the log line is accurate, otherwise OverlayPlugin would be needed. It seems accurate to me and they get spawned in and removed between parts so no need to check for updated location.
> raidboss: p10s Jade Passage trigger box/line

- ui/raidboss/data/06-ew/raid/p11s.ts
The lasers are not always in sorted order, apparently? From the one (1) example of them not being sorted, it appears that sorting by actor id puts them in the correct order.
Fixes #5584.
> raidboss: fix P11S lightstream safespot

- ui/raidboss/data/06-ew/raid/p11s.ts
Fixes a bug from #5585, which itself was fixing #5584.
I don't know why I thought this worked in the emulator. Sorry for the hassle.
Fixes #5588.
> raidboss: re-fix P11S lightstream safespot

- ui/raidboss/data/06-ew/raid/p10s.ts
Just played p10s in games, and it seems the result is opposite, still need someone to take further testing.
> raidboss: fix p10s jade passage wrong output

- resources/outputs.ts
- ui/raidboss/data/06-ew/raid/p12s.ts
- ui/raidboss/data/06-ew/raid/p12s.txt
- ui/raidboss/data/06-ew/trial/rubicante-ex.ts
Adds triggers for:
- Clones north/south during Paradeigma 1
- Clone line cleaves (e.g. inside east/outside west) during Paradeigma 2
- Glaukopis tank cleaves/swap
- Parthenos line cleave (during Superchain IIB)
> raidboss: additional p12s p1 triggers

- ui/raidboss/data/04-sb/dungeon/bardams_mettle.ts
- ui/raidboss/data/04-sb/dungeon/doma_castle.ts
- ui/raidboss/data/04-sb/dungeon/doma_castle.txt
- util/logtools/make_timeline.ts
Triggers were ok for this one, but there were changes to the boss timelines and a non-targetable actor name change.
Bosses will now walk center when using certain actions, making it very easy to induce timeline drift by dragging the boss off-center.  The first boss is particularly prone to timeline de-sync; however, most groups will likely not see it if they are not intentionally moving the boss more than necessary.
> raidboss: update Doma Castle for 6.4 duty Support

- ui/raidboss/data/06-ew/raid/p12s.ts
Has been tested in game and in emulator, but could use some additional validation and feedback, particularly on alert timings and collisions.
One odd thing is that for the Sample Tiles combatants/triggers, the trigger works fine in game, but the emulator never  return position data (via getCombatants) for the tiles.
> raidboss: add p12s superchain2b

- ui/raidboss/data/06-ew/raid/p12s.ts
Tested extensively against logs & vod, but could use some additional testing in game and validation on the timings.
Right now, for classical2, it will display the initial position for 7 seconds as an infoText, and right about as that expires, it will then display the inverted (actual) position as an alertText.  I left those as static values, but I'm undecided whether it would make more sense to add a config option to allow the user to specify when the alert should 'transition' from initial to actual.
Admittedly, I made a stylistic choice to do a single output trigger that covers the output for classical1 as well as the initial and actual calls for classical2.  It adds some trivial complexity around delay/duration, but the primary benefit I saw in this approach was a single set of …
> raidboss: improvements to p12sp2 classical concepts

- ui/raidboss/data/06-ew/raid/p12s.ts
Closes #5630 .
Added three config options:  1+2 (current), 0+2 (newly added), and 'agnostic' (which will not call stays or swaps associated with any particular strat, and will only call a swap if the last tower color is now the same as the player's debuff color (meaning they will die and wipe if they don't swap).  Set agnostic as the config default since it will correctly function regardless of strat.
(Also, small note re: the comments on #5630 - in the 0+2 strat, the players who take the first towers _always_ both swap to take the second (opposite color) towers.
> raidboss: improvements to p12s pangenesis

- ui/raidboss/data/06-ew/raid/p12s.ts
Sorry for the piecemeal PRs today - I keep ending up with more time on my hands than I thought.
This adds a preposition 'stack for tethers' call before both of the player-chain-break mechs during uav phases.  It also adds directional safe calls for the ultima ray (clone) dives, and combines the 'break tethers' call with the geocentrism call during uav2.
> raidboss: p12sp2 uav phase improvements

- resources/outputs.ts
- ui/raidboss/data/06-ew/raid/p12s.ts
- ui/raidboss/data/06-ew/trial/endsinger-ex.ts
Reasons for strategy translations, for other translators.
```ts
{
id: 'classicalConceptsPairOrder',
name: {
en: 'Classical Concepts: Pairs Order (Left->Right)',
ko: 'Classical Concepts: 도형 순서 (왼 -> 오)',
},
type: 'select',
options: {
en: {
'X□○Δ (BPOG)': 'xsct',
'○XΔ□ (Lines)': 'cxts',
'○Δ□X (Rocketship)': 'ctsx',
},
ko: {
'X□○Δ (파보빨초)': 'xsct',
'○XΔ□ (1234)': 'cxts',
'○Δ□X (동세네엑)': 'ctsx',
},
},
default: 'xsct',
},
```
`BPOG` -> Blue, Purple, Orange, Green -> **파**랑, **보**라, **빨**강, **초**록 -> `파보빨초`
`Lines` -> 1 line with ○, 2 lines with X, 3 lines with Δ, 4 lines with □ -> `1234`.
`Rocketship` -> Just the initials of the Circle(동그라미), Triangle(세모), Square(네모), and X(엑스).
```ts
{
id: 'pangenesisFirstTower',
name: {
en: 'Pangenesis: First Towers',
ko: 'Pangenesis: 첫번째 기둥',
},
type: …
```
> i18n: p12s, endsinger ko translations

- util/find_missing_translations.ts
- util/find_missing_translations_action.ts
- util/index.ts
One file is the wrapper for `index.ts` aka `npm run util` and the other file is the implementation for that code.
> util: split up find missing translation code

- ui/raidboss/data/06-ew/raid/p12s.ts
Add +0.3 second delay to `P12S Classical Concepts` trigger to address issue of network/combatant data lag
> raidboss: add delay to fix p12s classical concepts

- resources/user_config.ts
This partially addresses #5648. Handling the appearance of these cleared options differently is more involved.
> config: treat cleared options as defaults

- ui/raidboss/data/06-ew/raid/p10s.ts
The translation of the boss name did not work properly and so no trigger with a `source` property was firing.
Fixes #5643.
> raidboss: fix P10S bond and other triggers for non-English

- docs/RaidbossGuide.md
- ui/raidboss/data/06-ew/raid/p10s.ts
Sorry, this is more complicated than it should be. Maybe we can avoid unnecessary escaping in the future.
Caused by #5662 (sorry).
Fixes #5664.
> raidboss: take two on P10S translations

- resources/translations.ts
- test/helper/test_trigger.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
- util/find_missing_timeline_translations.ts
This adds extra functionality to the existing netRegex param translation to indicate missing translations.
This allows test_trigger and find_missing_timeline_translations to both re-use the actual path at runtime that translates. This removes bespoke logic in test_trigger to do this same work and adds this logic to find_missing_timeline_translations to report missing netRegex translations (that it previously did not do).
Previously also, doing the translation of netRegex params overwrote the params in place with the new translation. This wasn't technically an issue because of the post-collision checks, which mean that you can apply translations any number of times and still get the same result as applying it once. However, this is very confusing and subtle behavior and so now it makes a …
> util/test: add missing netRegex params to find translations

- resources/translations.ts
PR #5667 accidentally dropped all parameters that were not translated, which caused triggers to match nearly everything.
Sorry, oops.  Maybe we need some better testing for triggers.
> raidboss/resources: fix all triggers

- docs/TimelineGuide.md
- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/00-misc/test.txt
- ui/raidboss/timeline.ts
- ui/raidboss/timeline_parser.ts
Rather than adding a `loop`, add a variant of `jump` called `forcejump` to the timeline language.  If the sync does not occur, the jump will always happen when the time passes. This allows the timeline controller to automatically add loop lookahead rather than manually specifing it.
There's some manual testing of this in the Frankenstein manual `test.txt` test case.
To track this, `nextEvent` now has a whole bunch more state to track where it is in the lookahead so that when adding additional events as timer bars, it doesn't duplicate its efforts.
Additionally, since the same event could be added twice (or more) times on the screen, they need to have different ids (now strings instead of numbers, that include the "jump count" of the number of times we've gone through a lookahead jump to …
> raidboss: add `forcejump` timeline command

- util/find_missing_translations.ts
The "code" missing translations finder wasn't properly async and so would continue to accumulate missing translations as the rest of the coverage report continued.
The find missing translations script (standalone) handles this by not ending automatically, but the coverage report would (for example) list 4 entries but then say 21 errors as the the counting of the errors came after the entries were written.
> util: fix async bugs with find missing translations

- resources/netlog_defs.ts
- util/logtools/splitter.ts
Addresses the original scope of #5486 .  Updating make_timeline/test_timeline to use RSV lines (or, for that matter, to use a substitution table) would take some additional work.
Because 262 lines are zone-specific, I unset `globalInclude` and added logic to the log splitter to collect and push only those zone-specific RSV lines for each split log.  (From what I can tell, `globalInclude` is only used by the splitter, but if that's incorrect and we need to make adjustments elsewhere, let me know.)
> util: apply rsvs to abilities/effects in log splitter

- resources/zone_info.ts
I just ran the `util/gen_zone_id_and_info.py` file, and there's differences with #5686.
> resources: ko 6.31

- util/logtools/make_timeline.ts
This aims to simplify the recent "soft standard" of listing out all ignored abilities in detail, as well as the full list of abilities used by enemies in the encounter, ignored or not. Sample output:
```
make_timeline.ts -lf 10 -it Nidhogg -ii 179D 179F
###Loads more elided for space
hideall "--Reset--"
hideall "--sync--"
```
(Those random "--sync--" entries are because the entry processing step prior to this one automatically replaces Unknown abilities. I don't think it's too big a deal, but we can probably add a rule to convert those back to Unknown_XXXX.)
This same technique can probably be applied to auto-listing ignored combatants, but unfortunately that's not quite as simple. The input `-ic MonsterOne "Two-Word Monster" "Three Word Monster"` is rendered in the …
> util: Auto-generate header data in make_timeline

- types/trigger.d.ts
- ui/raidboss/popup-text.ts
- ui/raidboss/raidboss_config.ts
- ui/raidboss/raidboss_options.ts
Every once in a while people ask for ways to override or disable a particular trigger set, so here you go.
If a trigger gets overridden from another trigger set, the overriding trigger set's options get used instead. This is probably not what people want, but it's consistent.
> raidboss/config: add per triggerset default output options

- ui/raidboss/data/06-ew/dungeon/mount_rokkon.txt
This syncs for the Yozakura on other paths, so is incorrect.
> raidboss: fix Mount Rokkon timeline sync

- ui/raidboss/data/06-ew/raid/p12s.ts
Also adjust durations to reflect this.
From @valarnin's comment here: https://github.com/quisquous/cactbot/pull/5682#issuecomment-1631198471
A follow-up to this would be to adjust the calls about baiting to say "quick" or "delayed" or "very delayed" or something depending on how long the wait is.
> raidboss: add durations for p12s white flame

- ui/raidboss/raidboss_config.ts
This changes was proposed in #5733 but it is not correct.
@lsl1225 此選項意在指示 TriggerSet 即觸發器集合之整體的輸出形式，但似乎您理解爲使用者自定義觸發器的相關設定。事實上使用者自定義的觸發器與 cactbot 內建的觸發器在設定介面是沒有區別的。
Please review and give an approve if you agree the change in this fixup PR.
> i18n: fix cn translation for trigger set config output

- docs/TimelineGuide.md
This is (probably) not a complete modernization, but it should be a good first pass. I tried to structure the commits to be sensibly distinct for review and rollback purposes.
For readers' convenience, the formatted revision can be viewed at https://github.com/JLGarber/cactbot/blob/update-timeline-guide-new-table-key/docs/TimelineGuide.md.
> docs: Update timeline guide

- docs/zh-CN/README.md
> docs: update raidboss emulator guide cn translation

- ui/raidboss/raidemulator.ts
Currently, the DOM element's classList operations were happening before the applyTranslation method, causing the DOM to be completely overwritten by the new HTML string. This resulted in non-English language users always seeing 'Not Connected' in the prompt interface. This issue has been resolved by adjusting the code sequence.
> raidemulator: Fixed class operations for non-English users.

- types/data.d.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/player_state_tracker.ts
I'll look at actually making this work in p12s tomorrow. maybe.
> oopsy: add isImmune to OopsyData

- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.ts
Japanese translations for `directions`, `backLeft`, `backRight`, and `front`.
Arrow symbol `→` at `directions` can be `=>` for consistency, though `→` is more common in Japanese context.
> raidboss: Add JA translations for DSR Gigaflare

- ui/raidboss/data/06-ew/raid/p12s.ts
Followup to #5689.
This also fixes a bug where the delays were incorrect because ongoing add updates caused the trigger to re-fire.
> raidboss: add P12S delay info to white flame baits

- .gitattributes
- ui/raidboss/data/06-ew/raid/p12s.ts
Closes #5752 -- adds a config checkbox so that the 'Actual' (final) correct position during classical2 will be called out on the classical2 cast, and no follow up alert during Panta Rhei.
> raidboss: p12s classic2 option to call actual w/no flip

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
Tested with a fresh environment on node 18.17.1. As was mentioned in #5764 , I also added version numbers to the recommended global packages in CONTRIBUTING (the same ones as in package.json), and version numbers to the README for nodejs and npm (current LTS).  
Apologies if I used the wrong label for this PR.
> build/docs: Updated ttypescript version

- plugin/CactbotEventSource/CactbotEventSource.cs
- util/DEPS.json5
After updateing DEPS.json5, i got following compilation error: 'CactbotEventSource.cs(46,13): error CS0104: "GameRegion" ist ein mehrdeutiger Verweis zwischen "Cactbot.VersionChecker.GameRegion" und "RainbowMage.OverlayPlugin.GameRegion"' thats why i touched CactbotEventSource.cs
> plugin: update DEPS.json5

- plugin/CactbotEventSource/FFXIVProcessIntl.cs
After the change of #5413 , ScholarJobMemory has been AGAIN left shifted one bit.
Fixes #5773
> plugin: ScholarJobMemory change again

- ui/oopsyraidsy/data/06-ew/raid/p12n.ts
`82C3` is Trinity of Souls (line 14)
> oopsy: fix P12N palladion spread id

- docs/TimelineGuide.md
- ui/raidboss/data/00-misc/test.txt
- ui/raidboss/timeline_parser.ts
> raidboss: add named timeline jump labels

- ui/raidboss/data/06-ew/raid/p11s.ts
The current translations are lacking the meaning of "other."
> raidboss: update cn translation

- ui/raidboss/popup-text.ts
> raidboss: text in alerts lang, not display lang

- plugin/CactbotEventSource/CactbotEventSource.csproj
CN players use a modified FFXIV_ACT_Plugin to parse the game. (https://github.com/TundraWork/FFXIV_ACT_Plugin_CN)
This modified plugin do not have strong name, so cactbot report an error like this:
```
[2023/9/23 15:22:11] Error: LoadAddons: CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50' ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
at Cactbot.FFXIVPlugin.RegisterProcessChangedHandler(Action`1 …
```
> plugin: disable strong name req for FFXIV_ACT_Plugin.Common

- ui/raidboss/data/06-ew/raid/p12s.ts
Added Paradeigma 2 Tower Strategy tetherbase, which is commonly used by Chinese players.
- [【【菓子】FF14万魔殿天狱篇零式4层 P12S超详解攻略】 ](https://www.bilibili.com/video/BV1vF411S7oL)
Solution idea:
1. First look at the type of Anthropos generated on the sidelines, and the corresponding position of the Tether player
2. Determine the debuff type that you have
3. drop the tower according to the priority TH: A->B->C DPS: D->C->B
This solution avoids seeing the wrong type because the Tether player is not in place in time
> raidboss: p12s Paradeigma 2 Tower Strategy add 'tetherbase'

- ui/oopsyraidsy/data/06-ew/trial/golbez-ex.ts
- ui/raidboss/data/06-ew/trial/golbez-ex.ts
- ui/raidboss/data/06-ew/trial/golbez-ex.txt
Based on #5425 (thank you!)
Closes #5425.
Changes:
* forcejump in timelines
* fixes Arctic Assault (east/west seemed reversed)
* combines Arctic Assault with Terrastorm / Gale Sphere
* combines partner/healer stack with Gale Sphere calls
* calls out Gale Sphere incrementally
* Azdaja tells so you know what's coming
* headmarker triggers (knockback, flare, towers)
* followup calls during front/back "phases of the X" mechanic
* changed `--jump--` to `--middle--` and `--north--` for clarity
* updated front/back timeline entries to reflect damage snapshots
* removed `(record)` entries from timeline as they seemed noisy
> raidboss/oopsy: ex6 improvements

- ui/oopsyraidsy/data/03-hw/trial/thordan-ex.ts
- ui/raidboss/data/03-hw/trial/thordan-ex.ts
- ui/raidboss/data/03-hw/trial/thordan-ex.txt
(This will close #5742 )
This should largely be self-explanatory. We are fortunate that this content is old enough that positions and headings are accurate without having to do any work for them.
I've tested this live both solo and with others (thanks quisquous!) but it will definitely need some polish here and there. In particular, some complex mechanics feel very noisy. It would be nice to figure out what alerts can be downgraded to info.
Note that currently there's no support for keeping Defamation and Pierce players out of the stack during the meteor trio. This can be done without too much effort but I have no brain left for today.
> raidboss/oopsy: Thordan EX

- ui/raidboss/data/06-ew/trial/zeromus-ex.ts
- ui/raidboss/data/06-ew/trial/zeromus-ex.txt
Just timeline for now. Haven't tested in-game yet, only against pulls from last night and against FFLogs reports.
P2 enrage I'm still not sure how to indicate.
I'll poke at some initial triggers as well but might not have time to actually add any until tomorrow, so if this timeline looks good feel free to merge it now and I'll do the triggers as a separate PR.
Also left my notes in the timeline file instead of deleting them like I normally do, figured they might be useful in the future if the timeline needs cleaned up by someone else.
> raidboss: ex7 initial timeline

- resources/netlog_defs.ts
See https://github.com/quisquous/cactbot/issues/5842
While field 20 is technically the first field that could contain a player ID, truncating right there results in an incomplete triplet. Better to just delete the entirety of the first triplet instead of having a malformed line.
> resources: Statuseffectlist first unknown field fix

- ui/raidboss/data/06-ew/trial/zeromus-ex.ts
- ui/raidboss/data/06-ew/trial/zeromus-ex.txt
- ui/raidboss/data/06-ew/trial/zeromus.txt
* condense notes into `-la` table at the bottom
* add 0.3 to castbars for real ability timing
* number Abyssal Echoes
* durations on Sable Thread / Dark Matter
* remove mistake damage (Burst, The Dark Binds)
* rename first branding/sparking to --towers--
* add in --spread-- damage for Big Bang/Crunch
* add multiple ids for Visceral Whirl / Eventide
> raidboss: ex7 timeline tweaks

- util/coverage/coverage.css
- util/coverage/coverage.d.ts
- util/coverage/coverage.ts
- util/coverage/coverage_report.ts
- util/find_missing_timeline_translations.ts
- util/find_missing_translations.ts
- util/gen_coverage_report.ts
Currently the "missing translations" lists hundreds of errors for each timeline entry that can't be translated because this content doesn't exist yet.
To make it easier to find issues with content that can be fixed, create a new category of error for missing 'replaceSection' and separate out those errors into their own column on the sheet.
This also makes it possible to show better "how many fights are translated" numbers for other languages by not including fights that don't exist yet in that region.
> util: improve coverage report for Chinese/Korean

- plugin/CactbotEventSource/CactbotEventSource.cs
- plugin/CactbotEventSource/CactbotEventSource.csproj
- plugin/CactbotEventSource/CactbotPathWarning.cs
- plugin/CactbotEventSource/loc/Strings.Designer.cs
- plugin/CactbotEventSource/loc/Strings.resx
Adds an ACT warning when there's an old path.
Wrong path: `cactbot/cactbot-version/ui/raidboss/etc`
Right path: `cactbot/cactbot/ui/raidboss/etc`
...where "version" is some cactbot version number.
This can happen if somebody adds and removes the cactbot plugin but doesn't add and remove their overlays *and* they were on an old version of cactbot that still had version numbers in the path.
Closes https://github.com/OverlayPlugin/OverlayPlugin/pull/227/
> plugin: add warning for misconfigured cactbot paths

- types/event.d.ts
- ui/test/test.ts
It looks like this was removed in:
https://github.com/OverlayPlugin/OverlayPlugin/pull/165
> test: remove non-existent FileChanged event

- docs/LogGuide.md
- resources/netlog_defs.ts
Per the .cs that Ravahn shared.
Probably there's other updates that can be made, but this was the main driver.
Also `37` lines should probably have actual examples and such instead of having hardcoded values, but that's not really in the scope of this PR.
> docs: Update defs to add currentShield

- ui/raidboss/data/06-ew/dungeon/aloalo.ts
- ui/raidboss/data/06-ew/dungeon/aloalo.txt
Sorry no timeline and no i18n. 😭
Simple triggers only.
> raidboss: Simple Aloalo triggers

- docs/LogGuide.md
- resources/netlog_defs.ts
- resources/netregexes.ts
- resources/regexes.ts
- util/gen_log_guide.ts
Add the new line types, and their corresponding documentation.
I don't think I missed anything here but please double check as the info included in LogGuide.md may be excessive or not 100% accurate for all cases.
> raidboss: Add 263/264 line types

- resources/party.ts
- types/trigger.d.ts
- ui/raidboss/popup-text.ts
Followup to #5861 and discussions on #5891.
As the comment in the code specifies, if a trigger passes in `players: [player1, player2, player3]`, and a user specifies `${players.job}`, then return: `${players[0].job}, ${players[1].job}, ${players[2].job}`.
In general, this means that all array elements must either be simple strings/numbers or all share the same prop, or there will be errors below about non-existent properties. In practice, this likely will never happen.
This will also handle simpler cases like: `output.safeSpots!({ dirs: [output.front!(), output.back!(), output.left!()] })`
This also allows for `data.party.member(undefined)` to return '???', just to reduce boilerplate.
> raidboss: handle player object arrays in output params

- resources/responses.ts
- ui/raidboss/data/00-misc/general.ts
- ui/raidboss/data/02-arr/dungeon/brayfloxs_longstop.ts
- ui/raidboss/data/02-arr/dungeon/pharos_sirius.ts
- ui/raidboss/data/02-arr/dungeon/sastasha_hard.ts
- ui/raidboss/data/02-arr/dungeon/the_wanderers_palace_hard.ts
- ui/raidboss/data/02-arr/raid/t10.ts
- ui/raidboss/data/02-arr/raid/t11.ts
- ui/raidboss/data/02-arr/raid/t12.ts
- ui/raidboss/data/02-arr/raid/t13.ts
- ui/raidboss/data/02-arr/raid/t2.ts
- ui/raidboss/data/02-arr/raid/t5.ts
- ui/raidboss/data/02-arr/raid/t6.ts
- ui/raidboss/data/02-arr/raid/t7.ts
- ui/raidboss/data/02-arr/raid/t8.ts
- ui/raidboss/data/02-arr/raid/t9.ts
- ui/raidboss/data/02-arr/trial/shiva-ex.ts
- ui/raidboss/data/02-arr/trial/shiva-hm.ts
- ui/raidboss/data/02-arr/trial/titan-hm.ts
- ui/raidboss/data/02-arr/trial/titan-nm.ts
> raidboss: update arr and responses to use player objects

- docs/LogGuide.md
Clarify how 263/264-lines work with regards to abilities that have a cast direction/angle but do not target a specific location.
> docs: Clarify 263/264 in LogGuide.md

- ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts
Add trigger for initial Ifrit position pre-dash, as well as safe spot away from dashes and radiant plumes.
There might be a better way to detect Ifrit's initial positioning but I can't think of it. Maybe our next custom log line should be `ActorSetPos` or something, if that gets sent here?
> raidboss: UWU - Add ifrit phase change triggers

- types/data.d.ts
- ui/oopsyraidsy/damage_tracker.ts
- ui/oopsyraidsy/data/00-misc/general.ts
- ui/oopsyraidsy/data/05-shb/raid/e12s.ts
- ui/oopsyraidsy/oopsy_live_list.ts
- ui/oopsyraidsy/oopsy_summary_list.ts
- ui/oopsyraidsy/oopsy_viewer.ts
- ui/oopsyraidsy/oopsyraidsy.ts
- ui/oopsyraidsy/player_state_tracker.ts
- ui/raidboss/popup-text.ts
Followup to #5861.
There's no "output strings" in oopsy, but it does use ShortName in a few places. Move this over to data.party.member(x).toString() in order to potentially support an oopsy option for how to display names.
This also changes some logic for mit tracking and raise tracking to use full names instead of short names when storing and comparing, only using the shortened version for output.
This also creates the party tracker earlier so that it can be passed to all the things that want to use it, and so all of oopsy can indirect through `PartyTracker` to find out short names.
> oopsy: update oopsy code to use player objects

- ui/oopsyraidsy/oopsyraidsy_config.ts
- ui/raidboss/raidboss_config.ts
You can now also write `${player.job}`, `${player.role}`, `${player.nick}`, or `${player.name}` in triggers now as well if you want to override output strings individually.
If the property isn't there (somebody not in your party, bugs, typos), it will default to nickname.
Fixes #3000.
> raidboss/oopsy: support jobs instead of names in triggers

- ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.ts
The in-line comments should largely cover everything. It's maybe more complex than other possibilities for how we can handle the situation, but it does work.
> raidboss: Lunar Subterrane -- Add Forsaken Fount triggers

- ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.ts
This would probably be a lot simpler with matrix math, but I don't know matrices enough to implement them here, so this is what we get instead. It should be largely self-explanatory with the in-line comments, but please criticize away, since this isn't necessarily the nicest implementation.
> raidboss: Lunar Subterrane--Add Ruinous Hex calls

- ui/raidboss/data/00-misc/test.ts
- ui/raidboss/data/00-misc/test.txt
- ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.ts
- ui/raidboss/raidboss.ts
- ui/raidboss/timeline.ts
- ui/raidboss/timeline_parser.ts
- util/logtools/test_timeline.ts
Closes #5145
Obviously needs plenty of testing etc.
Example added to `test.txt` timeline, can be triggered with `/e testNetRegexTimeline`.
Took the opportunity to refactor the `TimelineParser.parse` function to extract out some of the line matching, so there wasn't a need for a 30+-space-indented set of lines, and to allow reusing some of the logic for the rest of the line matching after the regex.
> raidboss: Add support for netregexes in timelines

- .github/workflows/release.yml
There's no reason to do another setup step here to get git for a one-liner.
More fixes for #5953.
> ci: move create tag into create release step for release

- util/logtools/encounter_tools.ts
- util/logtools/make_timeline.ts
This wasn't as simple as I had hoped, but it does seem to work as it is. There's still a bit of fragility in `make_timeline` with this implementation, since it still relies on the seal name being present in game log form. We could change this to make "name from game log" optional in the `assembleTimelineStrings()` function, but that would involve some complex conditions to allow for use of either the network seal or the game log seal.
Alternatively, we could simply not care about game log seals at all, except to check "if there's a game log seal here, use the name it contains". Maybe something like this for the end of `assembleTimelineStrings()`?
```javascript
if (fight !== undefined && fight.sealId !== undefined) {
if (fight.sealName !== undefined) {
const sealMessage = …
```
> util: Add basic network log seal support in timeline tools

- ui/raidboss/timeline_parser.ts
- util/find_missing_timeline_translations.ts
Follow-up to #5939.
This translates each parameter (only if needed) rather than the entire sync. It also prints out only the untranslated parameters in the find missing translations script / coverage report. This also improves the output of the translated timeline utility to use translated parameters and fixes a bug where it wouldn't have output any translated sync lines at all for netregex lines.
> raidboss: improve translation of timeline netregex

- ui/raidboss/data/00-misc/test.txt
- ui/raidboss/timeline_parser.ts
Rather than eval (which is probably TOO lenient)
switch to using json5 instead of json parsing.
This is a followup to a TODO from #5939.
> raidboss: support bareword keys in timeline netregex

- ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts
An off by one error meant that if awoken Ifrit was the 4th dash, it would not print out any dash instructions. Oops.
> raidboss: fix UWU Ifrit 4th dash

- .github/workflows/release.yml
It doesn't seem to pick up the tag from earlier in the job and just says `refs/head/main` which is not helpful. Hopefully being explicit will fix this.
> ci: change release.yml to use tag explicitly

- ui/raidboss/data/00-misc/test.txt
`test sync` would match with everything, so add a number to disambiguate.
> raidboss: fix test timeline `test sync`

- dprint.json
It was excluded before, but lint-staged considers *.json as something to lint, and so modifying it would cause lint-staged to complain.
> lint: include package-lock.json for linting

- ui/raidboss/data/06-ew/dungeon/another_aloalo_island-savage.ts
- ui/raidboss/data/06-ew/dungeon/another_aloalo_island.ts
Depending on your strategy, you may have bubbles go to 1 or 2 which may change where people go. Regardless, bubbles always are in a static location relative to crystals so list both.
Also, the limit cut number to go to is just noise so remove it.
> raidboss: clarify bubble on Aloalo Spring Crystals 1/6

- ui/raidboss/data/02-arr/trial/levi-ex.txt
- ui/raidboss/data/03-hw/alliance/dun_scaith.txt
- ui/raidboss/data/03-hw/dungeon/the_lost_city_of_amdapor_hard.txt
- ui/raidboss/data/03-hw/dungeon/xelphatol.txt
- ui/raidboss/data/03-hw/raid/a10n.txt
- ui/raidboss/data/03-hw/raid/a10s.txt
- ui/raidboss/data/03-hw/raid/a12n.txt
- ui/raidboss/data/03-hw/raid/a12s.txt
- ui/raidboss/data/03-hw/raid/a4s.txt
- ui/raidboss/data/03-hw/raid/a6s.txt
- ui/raidboss/data/03-hw/raid/a8n.txt
- ui/raidboss/data/03-hw/raid/a8s.txt
- ui/raidboss/data/03-hw/trial/sephirot-ex.txt
- ui/raidboss/data/04-sb/dungeon/bardams_mettle.txt
- ui/raidboss/data/05-shb/alliance/the_copied_factory.txt
- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt
- ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
- ui/raidboss/data/05-shb/trial/hades-ex.txt
- ui/raidboss/data/05-shb/trial/levi-un.txt
- ui/raidboss/data/06-ew/trial/sephirot-un.txt
/sync\s*\/ ?22:(?:\.{8}|\[\^:\]\*):(?<name1>[^:]*):(?:\.{8}|\[\^:\]\*):(?<name2>[^:]*):(?<toggle>[^:]*)\//
> raidboss: timeline netregex for nameToggle

- ui/raidboss/data/02-arr/trial/ifrit-nm.txt
- ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.txt
- ui/raidboss/data/04-sb/raid/o11n.ts
- ui/raidboss/data/04-sb/raid/o11n.txt
- ui/raidboss/data/04-sb/raid/o12n.ts
- ui/raidboss/data/04-sb/raid/o12n.txt
- ui/raidboss/data/04-sb/raid/o9n.ts
- ui/raidboss/data/04-sb/raid/o9n.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
- ui/raidboss/data/05-shb/trial/hades-ex.ts
- ui/raidboss/data/05-shb/trial/hades-ex.txt
- ui/raidboss/data/06-ew/dungeon/lapis_manalis.txt
`/sync\s*\/ 00:(?<code>[^:]*):(?<name>[^:]*):(?<line>[^:]*)\//`
Because parameters are now translated individually vs the sync as a whole, there are now missing translations (that were missing before, but not seen by the script).
> raidboss: timeline netregex for gameLogWithName

- ui/raidboss/data/06-ew/dungeon/the_sildihn_subterrane.txt
- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
`/sync\s*\/ 257 101:(?<instance>[^:]*):(?<flags>[^:]*):(?<location>[^:]*):\//`
The instance here was dropped deliberately as it's always the same for a given zone, so is not useful in a regex.
> raidboss: timeline netregex for mapEffect

- ui/raidboss/data/04-sb/eureka/eureka_hydatos.txt
- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt
`/sync\s*\/ 17:\[\^:\]\*:(?<source>[^:]*):(?<id>[^:]*):\//`
> raidboss: timeline netregex for interrupt

- ui/raidboss/data/04-sb/eureka/eureka_hydatos.txt
These are only for Art and Owain, see comments in trigger file. This is untested and probably the most likely thing to break out of all the conversion.
`/sync\s*\/ 1\[56\]:\[\^:\]\*:(?<source>[^:]*):(?<id>[^:]*):\[\^:\]\*:\[\^:\]\*:\[\^:\]\+:\//`
> raidboss: timeline netregex for abilityWithNonEmptyTarget

- ui/raidboss/data/06-ew/raid/p12s.txt
`/sync\s*\/ 03:(?:\.{8}|\[\^:\]\*):(?<name>[^:]*):(?<job>[^:]*):(?<level>[^:]*):(?<ownerId>[^:]*):(?<worldId>[^:]*)::(?<npcNameId>[^:]*):\//`
There is probably a more compact way to write this by dropping parameters, but it seemed safer to convert directly.
> raidboss: timeline netregex for addedCombatantOneOff

- ui/raidboss/data/02-arr/raid/t9.txt
- ui/raidboss/data/03-hw/alliance/dun_scaith.ts
- ui/raidboss/data/03-hw/alliance/dun_scaith.txt
- ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt
- ui/raidboss/data/03-hw/raid/a10n.txt
- ui/raidboss/data/03-hw/raid/a3s.txt
- ui/raidboss/data/03-hw/trial/thordan-ex.txt
- ui/raidboss/data/04-sb/dungeon/temple_of_the_fist.txt
- ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt
- ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae.txt
- ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt
- ui/raidboss/data/05-shb/trial/wol-ex.txt
- ui/raidboss/data/06-ew/alliance/aglaia.txt
- ui/raidboss/data/06-ew/raid/p7n.txt
- ui/raidboss/data/06-ew/trial/endsinger-ex.txt
- ui/raidboss/data/06-ew/trial/thordan-un.txt
- ui/raidboss/data/06-ew/trial/zodiark.txt
- ui/raidboss/data/06-ew/ultimate/dragonsongs_reprise_ultimate.txt
- ui/raidboss/data/06-ew/ultimate/the_omega_protocol.txt
`/(?<=\w* {[^}]*source: )"\((?<source>[^)]*)\)"/`
Splits source groups into their own parameters.
This reveals some translation collision, so fix that too.
Related to #5977.
> raidboss: timeline netregex for sourceGroups

- util/logtools/encounter_tools.ts
Without this code, it only finds one fight with `-lf`
> util: fix make_timeline support for split logs
